### ISSUE TITLE
Regression with games now showing distance based (mip mapping?) issues

### ISSUE THREAD

**Issue by 7oxicshadow** [xemu-project/xemu#1002]
### Bug Description

The following games have started exhibiting possible distance based graphics corruption (mip mapping?).

Outrun / Forza / Crimson Skies / Blazing Aces

Steps to reproduce:

1. Launch one of the games above
2. Go in game
3. Observe the following issues

![forza](https://user-images.githubusercontent.com/10350138/171286106-34f05434-da02-4f15-a9f0-31b27aab763d.png)
![image](https://user-images.githubusercontent.com/10350138/171286317-e19b6d0a-1721-4e5f-802f-41123fffcd49.png)
![image](https://user-images.githubusercontent.com/10350138/171286418-f2270387-84d2-4e8c-b69f-d6b608510817.png)

theboy181 did a search to find the problem version in master and confirmed that 7.17 is fine and 7.18 is broken.

7.18 is a change that incorporated pull request 962 ( https://github.com/mborgerson/xemu/pull/962 )

We have confirmed that if you revert this pull request it seems to resolve the issue.

Links:
https://xemu.app/titles/55530057/#Blazing-Angels-Squadrons-of-WWII
https://xemu.app/titles/53450036/#OutRun-2
https://xemu.app/titles/53450088/#OutRun-2006-Coast-2-Coast
https://xemu.app/titles/4d53006e/#Forza-Motorsport
https://xemu.app/titles/4d530021/#Crimson-Skies-High-Road-to-Revenge
https://xemu.app/titles/41430007/#Aggressive-Inline

### Expected Behavior

No graphics corruption

### xemu Version

Works in release 7.17
Broken in 7.18

**Comment by theboy181** [comment]
https://cdn.discordapp.com/attachments/818645238377611275/981306858902020116/0.7.17.mp4
https://cdn.discordapp.com/attachments/818645238377611275/981306860445528104/0.7.18.mp4

Videos if needed

**Comment by 7oxicshadow** [comment]
Note: Forza is only for reference as it doesn't officially work in master yet

**Comment by AdadG** [comment]
The same with Grand Theft Auto III:

![xemu exe Screenshot 2022 05 31 - 16 58 58 96](https://user-images.githubusercontent.com/81838886/171291801-7c1b3293-0ab0-4ebb-afb9-c004ac637708.png)
![xemu exe Screenshot 2022 05 31 - 17 03 45 12](https://user-images.githubusercontent.com/81838886/171291802-e73b22e8-4bae-477d-9b3c-c03dc1306cbe.png)

**Comment by cazzhmir** [comment]
A similar issue also began presenting in Splinter Cell, coinciding with 0.7.17 and 0.7.18 in the same way. These artifacts now show with the rain seen in some levels:

0.7.17:
https://user-images.githubusercontent.com/104662859/171293730-119d8236-7f9a-4de2-a9f5-1215642e24dc.mp4

0.7.18:
https://user-images.githubusercontent.com/104662859/171293750-450e78a3-b93d-4b4e-bb82-71d5324fd61a.mp4

**Comment by abaire** [comment]
@7oxicshadow can you add the compatibility links for the titles so they're properly linked?

https://xemu.app/titles/4d53006e/#Forza-Motorsport
https://xemu.app/titles/4d530021/#Crimson-Skies-High-Road-to-Revenge

Not sure if Blazing Aces is the same as Blazing Angels, and not sure if Outrun is Outrun 2

**Comment by theboy181** [comment]
https://xemu.app/titles/55530057/#Blazing-Angels-Squadrons-of-WWII
https://xemu.app/titles/53450036/#OutRun-2
https://xemu.app/titles/53450088/#OutRun-2006-Coast-2-Coast

**Comment by Triticum0** [comment]
https://xemu.app/titles/41430007/#Aggressive-Inline
https://xemu.app/titles/4d530007/#Azurik-Rise-of-Perathia
https://xemu.app/titles/5454007e/#Gotcha
https://xemu.app/titles/56550048/#Bass-Pro-Shops-Trophy-Hunter-2007

**Comment by AdadG** [comment]
@theboy181 please add the links of the games mentioned here to your original request, so the issues will appear on their respective pages and it will be easier to see them.

**Comment by Triticum0** [comment]
Azurik Rise of Perathia
Gotcha!

**Comment by theboy181** [comment]
> @theboy181 please add the links of the games mentioned here to your original request, so the issues will appear on their respective pages and it will be easier to see them.

Not sure what your asking? I shared the games that toxic mentioned. But have no other request open.

**Comment by abaire** [comment]
> > @theboy181 please add the links of the games mentioned here to your original request, so the issues will appear on their respective pages and it will be easier to see them.
> 
> Not sure what your asking? I shared the games that toxic mentioned. But have no other request open.

Presumably that was meant for @7oxicshadow since the links need to be added to the bug description in this issue so they get associated in the compatibility page.

**Comment by 7oxicshadow** [comment]
Original post updated

**Comment by AdadG** [comment]
Sorry @theboy181, I messed up the tag, could you please add GTA III, @7oxicshadow? Thanks.

**Comment by abaire** [comment]
I expanded the pgraph test suite to check mipmaps

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_format_dxt_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_DXT)

xemu departs from hardware when the mipmap image has an axis drop below 4 (e.g., 2x8 in both my 64_256_bands_dxt1.dds test and in a Forza renderdoc grab)

**Comment by ChaseDerick** [comment]
Confirmed fixed for [Crimson Skies: High Road to Revenge](https://xemu.app/titles/4d530021#Crimson-Skies-High-Road-to-Revenge) no issues in 0.8.96.

Note: I'm not too sure what this looked like prior in this game, might need to see if I can grab a screenshot to add.

Edit: Downloaded the older version where this does happen. Comparison screenshots below.

Broken 0.7.18:
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/7ebece11-0bb4-4c12-807e-e9311f4ab317" />
Fixed 0.8.96:
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/4679a37b-d003-43d5-96cf-9333fd6f29ba" />
