### ISSUE TITLE
PSH register combiner V1R0_SUM flags are ignored

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1039]
https://github.com/mborgerson/xemu/blob/176b574403e0f4a08bfb1f8ab58e0f819a45cf81/hw/xbox/nv2a/psh.c#L1168-L1171

These 3 variables are currently not used.

I've [prototyped something in the past](https://github.com/JayFoxRox/xqemu/pull/21/files#diff-51ba751a7088fda65dcc10c3a6103995R276) (from https://github.com/JayFoxRox/xqemu/pull/21), but it needs some other changes to our PSH code first, and has not been confirmed to be correct yet (and the code quality isn't good enough).

### Additional Context

This was ripped directly from https://github.com/xqemu/xqemu/issues/207 So big thanks to JayFoxRox for the information.

**Comment by abaire** [comment]
No, they're not ignored, I fixed this months ago: https://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837

**Comment by Triticum0** [comment]
Cool thanks, I'm porting over some issues from qxemu some of them I don't know if there have been fixed so Id you fix just comment and I will close the issue.

**Comment by PatrickvL** [comment]
Should that implementing commit also do a `add_var_ref(ps, 'v1')` or is that handled earlier already? (Or are v registers not required to be referenced like that?)
