### ISSUE TITLE
Assertion for non-dword aligned inline array offset (Conker L&R)

### ISSUE THREAD

**Issue by Djipi71** [xemu-project/xemu#104]
When you try to catch the key , you must have weapon. After conker having a Frying Pan , the emu crash.

Here's the scene:

![000](https://user-images.githubusercontent.com/35375131/102776291-c5548600-438e-11eb-881c-59dcc134419b.png)

And here's the error:

![001](https://user-images.githubusercontent.com/35375131/102776311-cf768480-438e-11eb-99f3-4e007c25e34c.png)

Titles: 4d530051, 4d57001a

**Comment by drjerk1** [comment]
You can just comment those asserts in the source code, the game doesn't crash itself, those asserts just cause some graphical glitches, i have tested the first charapter of conker just now, it works with all asserts commented.

**Comment by Djipi71** [comment]
How i Can Do that?

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by drjerk1** [comment]
you need to compile emulator from source to do this

**Comment by drjerk1** [comment]
I did patching with simple script and dummyassert.h header file, and a bit of manual patching, as it failed to compile one file
```
#!/bin/sh

ack -l '#include <assert.h>' | xargs -i@ sed -i 's/#include <assert\.h>/#include <dummyassert\.h>/g' @
```
```
/*
 * dummyassert.h
 * Copyright (C) 2020 terminal <terminal@localhost>
 *
 * Distributed under terms of the MIT license.
 */

#ifndef DUMMYASSERT_H
#define DUMMYASSERT_H
#include <stdio.h>

#define assert(condition) { if(!(condition)){ fprintf(stderr, "dummyassert in %s, line %d, cond %s\n", __FILE__,  __LINE__, #condition); fflush(stderr); } }

#endif /* !DUMMYASSERT_H */
```

**Comment by Djipi71** [comment]
Have you hot a build with thisfix?

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Djipi71** [comment]
IS it possible to have xemu.exe with the fix
?
Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by drjerk1** [comment]
for now, it doesnt exists, maybe someone will do this later

**Comment by Djipi71** [comment]
Ok Hope :)

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by mborgerson** [comment]
Thanks for reporting, the issue will be fixed shortly.  Downloading builds from other people is not supported, and highly(!) discouraged as those builds might potentially include malware. I also do not recommend blanket removal of all `assert`s in this way. If you want to help fix the underlying issue, you are welcome to join us in the chat and/or file a PR.

**Comment by Djipi71** [comment]
ok so i will wait no problem :)

**Comment by peksomess** [comment]
Hello exactly the same thing is happening to me and I am using the Latest Version of XEMU-0.5.0-2 For Windows

**Comment by Djipi71** [comment]
Yeah assertion seems like to take time to merged do or merged on MAster :(
