### ISSUE TITLE
007: Everything or Nothing 

### ISSUE THREAD

**Issue by Ahju713** [xemu-project/xemu#1062]
### Title

https://xemu.app/titles/45410042/#007-Everything-or-Nothing

### Bug Description

![Screenshot (445)](https://user-images.githubusercontent.com/107522901/173723128-9e2071c4-cff9-421e-b08f-227c3dba1026.png)
![Screenshot (446)](https://user-images.githubusercontent.com/107522901/173723132-da9fbdfe-3d67-4746-b760-d5cbf59af0fa.png)
![Screenshot (447)](https://user-images.githubusercontent.com/107522901/173723140-faa344d1-f0ac-4409-8e71-25f188d4e5f3.png)
![Screenshot (448)](https://user-images.githubusercontent.com/107522901/173723144-95911594-3875-4cc5-8b9e-dbf40f70548c.png)
![Screenshot (449)](https://user-images.githubusercontent.com/107522901/173723156-58872162-94d3-4a8b-8309-99cf8156d0d9.png)

### Expected Behavior

The game has very terrible framerate issues can dip from 22 all the way to 1 or even 0 barely making it playable also has incredible amounts of delay because of the inconsistent frame drops

### xemu Version

0.7.36

**Comment by mborgerson** [comment]
dup #1003
