### ISSUE TITLE
Iron Phoenix

### ISSUE THREAD

**Issue by fuhuan416** [xemu-project/xemu#107]
Issues:
Black screen

All CMD window gives me:

> xemu_settings_get_path: config path: C:\Users\Big_Milk\AppData\Roaming\xemu\xemu\xemu.ini
config_parse_callback: [system] flash_path = C:\Game\xemu-win-release\files\complex_4627debug.bin
config_parse_callback: [system] bootrom_path = C:\Game\xemu-win-release\files\mcpx_1.0.bin
config_parse_callback: [system] hdd_path = C:\Game\xemu-win-release\files\xbox_hdd.qcow2
config_parse_callback: [system] eeprom_path = C:\Game\xemu-win-release\files\eeprom.bin
config_parse_callback: [system] dvd_path = C:\Game\Iron Phoenix[XBOX].iso
config_parse_callback: [system] memory = 128
config_parse_callback: [system] shortanim = true
config_parse_callback: [audio] use_dsp = false
config_parse_callback: [display] scale = scale
config_parse_callback: [display] ui_scale = 2
config_parse_callback: [input] controller_1_guid = keyboard
config_parse_callback: [input] controller_2_guid =
config_parse_callback: [input] controller_3_guid =
config_parse_callback: [input] controller_4_guid =
config_parse_callback: [network] enabled = false
config_parse_callback: [network] backend = user
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [misc] user_token =
Created QEMU launch parameters: C:\Game\xemu-win-release\xemu.exe -cpu pentium3 -machine xbox,bootrom=C:\Game\xemu-win-release\files\mcpx_1.0.bin,short-animation,kernel-irqchip=off -device smbus-storage,file=C:\Game\xemu-win-release\files\eeprom.bin -bios C:\Game\xemu-win-release\files\complex_4627debug.bin -m 128 -drive index=0,media=disk,file=C:\Game\xemu-win-release\files\xbox_hdd.qcow2,locked -drive index=1,media=cdrom,file=C:\Game\Iron Phoenix[XBOX].iso -display xemu -audiodev none,id=snd0
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
Resetting rate control (182393 samples)

I've used extract xiso to repackage the game before running the emulator
The emulator version is: 0.4.0-38-gc820256ac0

**Comment by mborgerson** [comment]
Hi, thanks for the report! Unfortunately this isn't really enough information to warrant a GitHub issue at this time. Stay tuned for compatibility updates at https://xemu.app, and come join the Discord server for updates
