### ISSUE TITLE
nv2a: 0x1e80 - 0x1e90 are unhandled (NV097_SET_TRANSFORM_DATA and NV097_LAUNCH_TRANSFORM_PROGRAM)

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#1074]
### Bug Description

Thanks to @jackchentwkh for [the information](https://github.com/mborgerson/xemu/issues/1072#issuecomment-1159311417) in #1072: 

```
0x1e8x NV097_SET_TRANSFORM_DATA is supposed to be an array of four float values
that are assigned to the V0 register used in vertex shader.

0x1e90 NV097_LAUNCH_TRANSFORM_PROGRAM shall launch the vertex shader inside 
GPU, and the argument comes with it is the starting point (slot) of the vertex shader, which
shall be sitting within 0 to 135.
```

This is used in Spy vs Spy during the main menu rendering and may or may not be a contributing factor to #1072, so I'm splitting it into a new bug in case it turns out to be unrelated. 

### Expected Behavior

Handling of these commands should be implemented. More research will need to be done to determine if the target vertex shader can use any other inputs as well as to understand what is done with the outputs (it may just rely on the standard nv2a behavior of persisting register values until they are explicitly changed).

### xemu Version

Affects all xemu versions through 0.7.39

### System Information

n/a, this is not system specific

**Comment by jackchentwkh** [comment]
I repeat some info here:
The usages of these methods are vertex state shaders. These info are collected by reversing Xbox d3d RunVertexStateShader()

**Comment by abaire** [comment]
We can probably just emulate these on the CPU if they only ever set the c registers. It'd mean some ugly duplication of the vsh wrappers but would bypass the need to emulate writable uniforms (through transform feedback or some other mechanism) which so far has only come up in one game, as far as I'm aware.
