### ISSUE TITLE
Instant crash with latest release on MacOS Ventura 

### ISSUE THREAD

**Issue by zoeyronain** [xemu-project/xemu#1077]
### Bug Description

Opening the latest build from the releases page on Ventura (macOS 13) bounces once and closes. 0.7.28 Works as expected

### Expected Behavior

App opens

### xemu Version

0.70.40
0.7.28 Works

### System Information

OS: macOS 13 (Ventura) Dev beta 1
CPU: 8 core M1 pro
GPU: 14 core GPU
(it's a base 14" Macbook Pro with M1 Pro CPU)

### Additional Context

Crashlog from console: 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               xemu [44410]
Path:                  /Users/USER/Downloads/*/xemu.app/Contents/MacOS/xemu
Identifier:            xemu.app.0
Version:               1 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-06-18 22:05:02.5026 -0500
OS Version:            macOS 13.0 (22A5266r)
Report Version:        12
Anonymous UUID:        84FC501A-4A9D-5FB2-4FD5-B392C93A1993

Sleep/Wake UUID:       C95BB86E-DA70-4FCD-B1DF-95B064F410C2

Time Awake Since Boot: 360000 seconds
Time Since Wake:       38931 seconds

System Integrity Protection: enabled

Crashed Thread:        6

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1913b2664 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1913ee85c _pthread_cond_wait + 1232
2   xemu                          	       0x10093a7fc main + 3372
3   dyld                          	       0x21d7a7c10 start + 2368

Thread 1:
0   libsystem_pthread.dylib       	       0x1913e9068 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1913e9068 start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	       0x1913b2664 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1913ee85c _pthread_cond_wait + 1232
2   xemu                          	       0x100d95e9c qemu_event_wait + 128
3   xemu                          	       0x100d93500 call_rcu_thread + 344
4   xemu                          	       0x100d9607c qemu_thread_start + 128
5   libsystem_pthread.dylib       	       0x1913ee290 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1913e907c thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1913e9068 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1913e9068 start_wqthread + 0

Thread 6 Crashed:
0   libsystem_kernel.dylib        	       0x1913b72a4 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1913edf10 pthread_kill + 288
2   libsystem_c.dylib             	       0x1913272d8 abort + 180
3   libsystem_c.dylib             	       0x1913266e0 __assert_rtn + 272
4   xemu                          	       0x1009a6220 Shader(unsigned int, char const*) + 332
5   xemu                          	       0x1009a5d4c NewDecalShader(ShaderType) + 116
6   xemu                          	       0x100933940 sdl2_display_early_init + 692
7   xemu                          	       0x100c09180 qemu_init + 35724
8   xemu                          	       0x1008676a4 qemu_main + 52
9   xemu                          	       0x10093b870 call_qemu_main + 28
10  xemu                          	       0x100d9607c qemu_thread_start + 128
11  libsystem_pthread.dylib       	       0x1913ee290 _pthread_start + 148
12  libsystem_pthread.dylib       	       0x1913e907c thread_start + 8

Thread 7:
0   libsystem_kernel.dylib        	       0x1913ba43c __sigwait + 8
1   libsystem_pthread.dylib       	       0x1913eea64 sigwait + 40
2   xemu                          	       0x100d9853c sigwait_compat + 80
3   xemu                          	       0x100d9607c qemu_thread_start + 128
4   libsystem_pthread.dylib       	       0x1913ee290 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1913e907c thread_start + 8

Thread 6 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000008   x6: 0x000000000000000a   x7: 0x0000000000000000
    x8: 0x58e37557b0e06e4c   x9: 0x58e37556df6e5e4c  x10: 0xcccccccccccccccd  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000001f77f3738  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000016f8e3000  x21: 0x0000000000007113  x22: 0x000000016f8e30e0  x23: 0x000000010100f793
   x24: 0x00000001ec85e000  x25: 0x0000000101ac5888  x26: 0x0000000101ac51c0  x27: 0x0000000101ac8ff8
   x28: 0x0000000101ac5990   fp: 0x000000016f8dfec0   lr: 0x00000001913edf10
    sp: 0x000000016f8dfea0   pc: 0x00000001913b72a4 cpsr: 0x40001000
   far: 0x000000010d4a8000  esr: 0x56000080  Address size fault

Binary Images:
       0x1913ae000 -        0x1913e6fe7 libsystem_kernel.dylib (*) <e113a1b5-ca82-3627-8f50-2eff1f63d2c4> /usr/lib/system/libsystem_kernel.dylib
       0x1913e7000 -        0x1913f3ff3 libsystem_pthread.dylib (*) <de39e254-2433-3a79-80ca-623fe473d3df> /usr/lib/system/libsystem_pthread.dylib
       0x100860000 -        0x10108ffff xemu.app.0 (1) <8190cf3d-5770-3f98-a8d9-68dd3022bfde> /Users/USER/Downloads/*/xemu.app/Contents/MacOS/xemu
       0x21d7a2000 -        0x21d82a89f dyld (*) <d238d2ee-ddec-3f3f-8d6c-c291f4562cea> /usr/lib/dyld
       0x1912ae000 -        0x19132effb libsystem_c.dylib (*) <4448148e-acd1-36ae-8815-3da83dacf996> /usr/lib/system/libsystem_c.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 12
    thread_create: 0
    thread_set_state: 192

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 4992K        8 
CG image                           112K        1 
ColorSync                          528K       25 
CoreAnimation                       48K        3 
CoreGraphics                        32K        2 
CoreServices                        48K        1 
CoreUI image data                  240K        2 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           251.4M       43 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                       1616K       33 
__AUTH                             653K      165 
__AUTH_CONST                      11.3M      329 
__CTF                               756        1 
__DATA                            5904K      329 
__DATA_CONST                      16.1M      344 
__DATA_DIRTY                       722K      115 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__LINKEDIT                       782.4M       16 
__OBJC_CONST                      1365K      144 
__OBJC_RO                         64.0M        1 
__OBJC_RW                         1963K        1 
__TEXT                           246.5M      360 
dyld private memory                512K        2 
mapped file                      172.6M       22 
shared memory                      896K       15 
===========                     =======  ======= 
TOTAL                              2.6G     2003 
TOTAL, minus reserved VM space     1.6G     2003 

-----------
Full Report
-----------

{"app_name":"xemu","timestamp":"2022-06-18 22:05:03.00 -0500","app_version":"1","slice_uuid":"8190cf3d-5770-3f98-a8d9-68dd3022bfde","build_version":"1","platform":1,"bundleID":"xemu.app.0","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A5266r)","roots_installed":0,"name":"xemu","incident_id":"5C547B3A-80DD-4E49-9D39-CC0349C753DC"}
{
  "uptime" : 360000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 70999,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A5266r",
    "releaseType" : "User"
  },
  "captureTime" : "2022-06-18 22:05:02.5026 -0500",
  "incident" : "5C547B3A-80DD-4E49-9D39-CC0349C753DC",
  "pid" : 44410,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-06-18 22:05:02.0791 -0500",
  "procStartAbsTime" : 8768466245054,
  "procExitAbsTime" : 8768476206291,
  "procName" : "xemu",
  "procPath" : "\/Users\/USER\/Downloads\/*\/xemu.app\/Contents\/MacOS\/xemu",
  "bundleInfo" : {"CFBundleShortVersionString":"1","CFBundleVersion":"1","CFBundleIdentifier":"xemu.app.0"},
  "storeInfo" : {"deviceIdentifierForVendor":"7A7542E8-9AF6-5356-B7A6-86D8ED212182","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "xemu.app.0",
  "crashReporterKey" : "84FC501A-4A9D-5FB2-4FD5-B392C93A1993",
  "wakeTime" : 38931,
  "sleepWakeUUID" : "C95BB86E-DA70-4FCD-B1DF-95B064F410C2",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":192,"task_for_pid":12},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 6,
  "threads" : [{"id":3974455,"queue":"com.apple.main-thread","frames":[{"imageOffset":18020,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":30812,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":894972,"symbol":"main","symbolLocation":3372,"imageIndex":2},{"imageOffset":23568,"symbol":"start","symbolLocation":2368,"imageIndex":3}]},{"id":3974488,"frames":[{"imageOffset":8296,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":3974489,"frames":[{"imageOffset":8296,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":3974490,"frames":[{"imageOffset":18020,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":30812,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":5463708,"symbol":"qemu_event_wait","symbolLocation":128,"imageIndex":2},{"imageOffset":5453056,"symbol":"call_rcu_thread","symbolLocation":344,"imageIndex":2},{"imageOffset":5464188,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":2},{"imageOffset":29328,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8316,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":3974494,"frames":[{"imageOffset":8296,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":3974499,"frames":[{"imageOffset":8296,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"triggered":true,"id":3974509,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":8},{"value":10},{"value":0},{"value":6405092114541080140},{"value":6405092111027166796},{"value":14757395258967641293},{"value":10},{"value":0},{"value":49},{"value":0},{"value":0},{"value":328},{"value":8447276856},{"value":0},{"value":6},{"value":6166556672},{"value":28947},{"value":6166556896},{"value":4311807891,"symbolLocation":68920,"symbol":"WC_FULL_CONFIG_STRING"},{"value":8263163904,"symbolLocation":4888,"symbol":"read_memory"},{"value":4323039368,"symbolLocation":0,"symbol":"epoxy_glFramebufferTexture2D"},{"value":4323037632,"symbolLocation":0,"symbol":"epoxy_glDrawBuffers"},{"value":4323053560,"symbolLocation":0,"symbol":"epoxy_glTexImage2D"},{"value":4323039632,"symbolLocation":0,"symbol":"epoxy_glGenFramebuffers"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6731783952},"cpsr":{"value":1073745920},"fp":{"value":6166544064},"sp":{"value":6166544032},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6731559588,"matchesCrashFrame":1},"far":{"value":4517953536}},"frames":[{"imageOffset":37540,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":28432,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":1},{"imageOffset":496344,"symbol":"abort","symbolLocation":180,"imageIndex":4},{"imageOffset":493280,"symbol":"__assert_rtn","symbolLocation":272,"imageIndex":4},{"imageOffset":1335840,"symbol":"Shader(unsigned int, char const*)","symbolLocation":332,"imageIndex":2},{"imageOffset":1334604,"symbol":"NewDecalShader(ShaderType)","symbolLocation":116,"imageIndex":2},{"imageOffset":866624,"symbol":"sdl2_display_early_init","symbolLocation":692,"imageIndex":2},{"imageOffset":3838336,"symbol":"qemu_init","symbolLocation":35724,"imageIndex":2},{"imageOffset":30372,"symbol":"qemu_main","symbolLocation":52,"imageIndex":2},{"imageOffset":899184,"symbol":"call_qemu_main","symbolLocation":28,"imageIndex":2},{"imageOffset":5464188,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":2},{"imageOffset":29328,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8316,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":3974510,"frames":[{"imageOffset":50236,"symbol":"__sigwait","symbolLocation":8,"imageIndex":0},{"imageOffset":31332,"symbol":"sigwait","symbolLocation":40,"imageIndex":1},{"imageOffset":5473596,"symbol":"sigwait_compat","symbolLocation":80,"imageIndex":2},{"imageOffset":5464188,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":2},{"imageOffset":29328,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8316,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6731522048,
    "size" : 233448,
    "uuid" : "e113a1b5-ca82-3627-8f50-2eff1f63d2c4",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6731755520,
    "size" : 53236,
    "uuid" : "de39e254-2433-3a79-80ca-623fe473d3df",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4303749120,
    "CFBundleShortVersionString" : "1",
    "CFBundleIdentifier" : "xemu.app.0",
    "size" : 8585216,
    "uuid" : "8190cf3d-5770-3f98-a8d9-68dd3022bfde",
    "path" : "\/Users\/USER\/Downloads\/*\/xemu.app\/Contents\/MacOS\/xemu",
    "name" : "xemu",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9084477440,
    "size" : 559264,
    "uuid" : "d238d2ee-ddec-3f3f-8d6c-c291f4562cea",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6730473472,
    "size" : 528380,
    "uuid" : "4448148e-acd1-36ae-8815-3da83dacf996",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  }
],
  "sharedCache" : {
  "base" : 6728384512,
  "size" : 3602022400,
  "uuid" : "eeec21cb-3fcb-3c84-b9ab-efd839ae773b"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG backing stores                 4992K        8 \nCG image                           112K        1 \nColorSync                          528K       25 \nCoreAnimation                       48K        3 \nCoreGraphics                        32K        2 \nCoreServices                        48K        1 \nCoreUI image data                  240K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           251.4M       43 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                       1616K       33 \n__AUTH                             653K      165 \n__AUTH_CONST                      11.3M      329 \n__CTF                               756        1 \n__DATA                            5904K      329 \n__DATA_CONST                      16.1M      344 \n__DATA_DIRTY                       722K      115 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__LINKEDIT                       782.4M       16 \n__OBJC_CONST                      1365K      144 \n__OBJC_RO                         64.0M        1 \n__OBJC_RW                         1963K        1 \n__TEXT                           246.5M      360 \ndyld private memory                512K        2 \nmapped file                      172.6M       22 \nshared memory                      896K       15 \n===========                     =======  ======= \nTOTAL                              2.6G     2003 \nTOTAL, minus reserved VM space     1.6G     2003 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 250000044
    },
    {
      "rolloutId" : "6112e3d2fc54bc3389840661",
      "factorPackIds" : {

      },
      "deploymentId" : 250000067
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by eks28** [comment]
Same here but for me I am on latest BigSur MACOS please fix

**Comment by kjharcombe** [comment]
> Same here but for me I am on latest BigSur MACOS please fix

@eks28, Not sure if this helps but release v0.7.30 works fine for me on macOS Big Sur.
