### ISSUE TITLE
[Feature Request] Add Vulkan support

### ISSUE THREAD

**Issue by Spidy123222** [xemu-project/xemu#109]
![image](https://user-images.githubusercontent.com/64176728/103061747-2cc22f80-4561-11eb-9c3b-d31c999bbcef.png)

_Hello, I am Spidy123222_

### **Explanation:**

I believe adding Vulkan to Xemu will benefit in some way. GPU makers start to support Vulkan better and Vulkan has ran better on almost all emulators I've seen that implemented it like dolphin, ppsspp, etc. 

OpenGL might not go away but Vulkan is made by people from Opengl and performs better with same results on graphics. Some Os's for example like MacOS have OpenGL depreciated and have an old version of OpenGL (some say lower quality than intel by now) on it still. Using something like Vulkan can allow you to use their Metal API Via using MoltenVK which converts Vulcan to Metal which is currently being updated constantly.

![image](https://user-images.githubusercontent.com/64176728/103062092-15377680-4562-11eb-8784-6b0f56a591b2.jpeg)

### **Problems:**

- Vulkan uses a lot more boiler code to get a similar result visually because of the Low-Level Api nature of it that also benefits the backend.

- Doesn't support every OS below windows 7 or older Linux distros which I don't think is too big of an issue. But is still relatively very portable.

- Can be hard to read because of more code. (Depends on the organization of it I guess)

- Types of shaders can be limiting depending on how portable you want it. Vertex shaders and compute shaders are found to be most portable of the types of shaders for Vulkan rather than tessellated shaders and Geometry shaders.

- Not all gpu hardware supports Vulkan. Depending on needs of program that has if implemented it might not matter.

### **Benefits:**

Some benefits I've said in the explanation but I will list them here and maybe extras.

- Supports computers that depreciate on devies (might remove the api) OpenGL like Apple Devices and other platforms if they do it.

- GPU manufacturers focus on DirectX and Vulkan more than OpenGL because Vulkan is technically the replacement from the OpenGL devs themselves.

- Balances GPU and CPU load (free CPU time) better which can help emulation a good amount (especially when graphics options come with more intense workloads).

- Spreads CPU load across multiple CPU cores via backend multithreading to lower overhead on single cores

- Mobile platforms support Vulkan as a desktop featured level backend like android and ios using MoltenVK from Vulkan creators. Current backends other than Vulkan on mobile platforms are OpenGLES (worst on ios with version 3.0 compared to android) which doesn't have every feature Desktop Opengl has.

- Could fix driver behavior issues from the boilerplate code for some GPUs that have bad drivers in general like intel or AMD ones. For emulators it can be easier to implement behavior of a gpu without driver conflict which could lead to more controlled behavior which can also lead to optimization for the program if wanted. (dolphin prefers Vulkan for this so they don't have to workaround often).

- Removal of legacy requirements simplifies API design, simplifies usage guidance, reduces specification size.

- if needed SPIR-V can be used to make it more High level api user friendly. SPIR-V also has a GLSL to SPIR-V translator

- Vulkan validation layers and compatibility layers to verify the integrity and problems of a implementation.

- Asynchronous rendering

- Asynchronous computing

- Asynchronous shaders

- Less api bloat compared to latest OpenGL

![image](https://user-images.githubusercontent.com/64176728/103062023-d9041600-4561-11eb-95ed-a2a8b8c55c9c.jpeg)

### **Conclusion:**

It would take time to implement Vulkan on Xemu but I think that posting a Feature Request here can at least maybe give ideas and maybe info or people wanting to help out.

There is ways to make developing Vulkan on Xemu likely easier for example using things like using [VK Bootstrap](https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp) to start out with the boilerplate code fast.

There is detailed article (a bit dated to beginnings of it) on what Vulkan does and benifits it can ad and disadvantages. Explains how Vulkan is faster via how they have the drivers be setup and how tile based rendering helped a lot of performance and more. https://www.toptal.com/api-developers/a-brief-overview-of-vulkan-api

There is also other things like memory allocators like [VMA from GpuOpen](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator).

There's tutorials that help for example [VKGuide](https://www.vkguide.dev/) and [Vulkan-Tutorial](https://vulkan-tutorial.com/)  

### **Videos:**

This video Compares a benchmark between OpenGLes and Vulkan with smooth gnome and choppy gnome video.

https://youtu.be/P_I8an8jXuM

This video explains a bit about what a API is and what's going on in DirectX12 and Vulkan. 

https://youtu.be/r0fgEVEgK_k

This video is about OpenGL on Arm Devices comparing OpenGLES to Vulkan on the cpu utilization.

https://youtu.be/rvCD9FaTKCA

For some reason when I try to search Vulkan vs OpenGL on YouTube I get a lot of arm device ones.

This one is a comparison in performance on ppsspp on arm OpenGLES VS Vulkan

https://youtu.be/JtKXKJfTqxs

Vulkan VS OpenGL on PlayStation 3 emulator. 

https://youtu.be/3TUfZA-I9HM

I'm searching for more other platform stuff so it's not OpenGLES which is another factor on Vulkan and OpenGL is faster than OpenGLES.

### *Other*

https://github.com/mborgerson/xemu/issues/322#issuecomment-1002812624

**Comment by mborgerson** [comment]
Thanks for the feature request! Vulkan support will be considered for xemu at a later time, but only after xemu is more stable overall. There is still a great deal of research/work to do, and GL works fine for the time being and is not currently a gating factor to xemu progress.

Regarding performance: Vulkan does offer a lot of flexibility but, based on my experimental work, GL is more than capable of reaching xemu performance targets.

Regarding platform support: GL enables xemu to run across a very large range of platforms dating back more than a full decade, and without any necessary compatibility layers at this time. I do expect that compatibility layers will be maintained for GL into the future for backwards-compatibility with the large library of code written for OpenGL. Even if OpenGL is deprecated on some platforms, this does not mean its unsupported.

For these reasons, I'm going to close this issue for now, and we can revisit at a later time.

**Comment by Spidy123222** [comment]
> Thanks for the feature request! Vulkan support will be considered for xemu at a later time, but only after xemu is more stable overall. There is still a great deal of research/work to do, and GL works fine for the time being.

I thank you for reading this and in off-topic on discord I sent something similar to this before I made this. I know I didn't expect it to happen now but was kind of wanting to at least make an issue so that people who stumble into it could maybe add it for you possibly. 

> For these reasons, I'm going to close this issue for now, and we can revisit at a later time.

I'm unsure if it's necessary to close it but I do have a question about support part of what you said.

> Regarding platform support: GL enables xemu to run across a very large range of platforms dating back more than a full decade, and without any necessary compatibility layers at this time. I do expect that compatibility layers will be maintained for GL into the future for backwards-compatibility with the large library of code written for OpenGL. Even if OpenGL is deprecated on some platforms, this does not mean it's unsupported.

I do get that there's going to support still on all of these platforms. But a thing is that IIRC that Apple uses an old version of OpenGL (lower than intel quality at times) which is slower than the latest version of it to transition to metal.


> Regarding performance: Vulkan does offer a lot of flexibility but, based on my experimental work, GL is more than capable of reaching xemu performance targets.

Yeah, it practically does the same things just faster depending how it's implemented didn't say it wouldn't be capable of getting up to speed but I do think Vulcan would be faster in general because of the flexibility and how it frees up CPU time which could help the emulation speed because of more headroom for CPU usage.

**Comment by awsms** [comment]
>Thanks for the feature request! Vulkan support will be considered for xemu at a later time, but only after xemu is more stable overall.

Any news since? :eyes:
