### ISSUE TITLE
Build AppImage releases

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#1103]
### Feature Request

It would be nice if xemu released AppImage versions for Linux. It's something we can easily do in the CI pipeline to provide consistent/reproducible/portable releases to people running different distributions.

**Comment by ADHDefy** [comment]
I am seconding this request, as I am used to running Xemu in portable mode from a HDD for a Windows host, and there is currently no way to do this with a Linux host. An AppImage release would make this possible. Thanks for the consideration! :smile:
