### ISSUE TITLE
Fuzion Frenzy menu text is overlapping

### ISSUE THREAD

**Issue by tinkerer-red** [xemu-project/xemu#111]
![b8435ab25512668b34ca4585d3029a39](https://user-images.githubusercontent.com/8210/103705745-d4c7f780-4f68-11eb-8cbc-8ead1715b697.png)

Titles: 4d530002

**Comment by dekay** [comment]
Attached is the Vertex shader grabbed from Renderdoc where the overlapping character names are being drawn.  My guess to what is happening is that there is a missing offset calculation within the shader.  Such a calculation shows up in CXBR-R's [old VertexShader.cpp code](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/e1d87339769a5b3f2a8c2e5c13315289dcdd5053/src/CxbxKrnl/EmuD3D8/VertexShader.cpp#L1351) via c59.  Unfortunately, I don't know enough about GLSL to take it to the next step and figure out the appropriate fix, so happy if someone is able to take it from here.

[FusionFrenzyVertexShader.txt](https://github.com/mborgerson/xemu/files/5754877/FusionVertexShader.txt)

**Comment by dekay** [comment]
This looks to be working now in master as of 0.5.4-25-ged7cbef.  Nice!

![image](https://user-images.githubusercontent.com/59916/125166888-02ca0680-e15b-11eb-8858-3b63c7b9142e.png)
