### ISSUE TITLE
Blinx 2: Bomb in sweepers tutorial

### ISSUE THREAD

**Issue by SilasLock** [xemu-project/xemu#1117]
### Title

https://xemu.app/titles/4d530065/#Blinx-2-Battle-of-Time-Space-Blinx-2-Masters-of-Time-Space

### Bug Description

During the opening Sweepers tutorial, there are two segments where the player observes a bomb exploding on screen:
1. The player is asked to acquire a bomb from a crate, and then shoot it at a monster to kill it.
2. The player is asked to acquire a Retry, and then a bomb is dropped on them from above, temporarily killing them and demonstrating the Retry mechanic.

In these two segments, the explosion causes Xemu to either freeze (necessitating a restart of the application), or to shudder for half a second. I encountered the first of these two outcomes when testing on one computer, and the second outcome on a separate computer with different specs.

I suspect the issue is triggered by *viewing* the explosion--if the in-game camera is not trained on the bomb when it explodes, I didn't experience a shudder or a total freeze.

Steps to reproduce the first explosion, in the shoot-a-monster-with-a-bomb part of the tutorial:
1. Start a new game in single-player mode.
2. After the opening cutscene and character creation, the Sweepers tutorial should start.
3. Follow the tutorial until you are asked to break a crate, sweep up a bomb, and shoot it at a monster.
4. When firing the bomb at the monster, keep the in-game camera trained on the ensuing explosion. The game should freeze, or shudder heavily.

Steps to reproduce the second explosion, in the Retry tutorial:
1. Start a new game in single-player mode.
2. After the opening cutscene and character creation, the Sweepers tutorial should start.
3. Follow the tutorial until you are asked to break a crate, sweep up a bomb, and shoot it at a monster.
4. After firing the bomb at the monster, quickly rotate the in-game camera to look away from the upcoming explosion. The game should continue normally.
5. The tutorial will then proceed to a segment explaining the Retry mechanic. After acquiring 3 Retry hearts, a bomb is dropped on the player's head (and here, it is not possible to rotate the camera away). When the bomb explodes, the game should freeze, or shudder heavily.

### Expected Behavior

The game should not freeze, or even experience slowdown. To my eye, the explosion animation doesn't look very graphically intensive, and I don't remember it causing the game to lag (much less freeze) even on the Xbox 360, which runs Blinx 2 with far worse performance than the original Xbox.

### xemu Version

Tested in Xemu versions 0.7.52, 0.7.49, and 0.6.5. The bug exists in all three.

### System Information

I tested for this bug on two separate computers. On the first computer, viewing the explosion causes a total freeze of the game. On the second computer, the game shuddered for a brief moment and then resumed. I tested this multiple times on each computer to ensure the behavior was consistent.

First computer specs (caused Xemu to freeze)
OS: Windows 10
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80 GHz
GPU Model: GeForce GTX 1650/PCIe/SSE2
Driver: 4.0.0 NVIDIA 417.88
Shader: 4.00 NVIDIA via Cg compiler

Second computer specs (caused Xemu to shudder)
OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
GPU Model: Intel(R) Iris(R) Xe Graphics
Driver: 4.0.0 - Build 27.20.100.8853
Shader: 4.00 - Build 27.20.100.8853

**Comment by ehw** [comment]
This is not on an issue for me as of 0.7.85. I can't replicate it. The bomb explodes and everything seems fine, even the Retry tutorial.

Version:      0.7.85
Branch:       master
Commit:       065c74a00fe402f65147e9b0d1a1eeac1b4b609f
Date:         Mon Mar  6 21:06:28 UTC 2023

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 531.26
Shader:       4.00 NVIDIA via Cg compiler

**Comment by arandomguysomewhere** [comment]
Should this issue be closed if no one can reproduce it?

**Comment by mborgerson** [comment]
> Should this issue be closed if no one can reproduce it?

Yep. Since it is quite an old issue, closed unless it can be reproduced again.
