### ISSUE TITLE
[Feature Request] Fps Counter

### ISSUE THREAD

**Issue by Spidy123222** [xemu-project/xemu#112]
Title speaks for itself but by having a way to have a internal fps and or milliseconds per frame counter it can help judge performance gains or not if there's settings to change. 

Also if Someone adds code to improve performance and wants to see how much gains it gets which means people can benchmark their hardware if it runs games they want at full speed all the time or if something takes performance.

**Comment by dracc** [comment]
Fps counter would need to be running guest side.
There's [this](https://github.com/JayFoxRox/xbox-fps-overlay), but getting it running requires you to have a devkit.

**Comment by dracc** [comment]
Fixed in #184
