### ISSUE TITLE
Change console / system language or region

### ISSUE THREAD

**Issue by sm4rty89** [xemu-project/xemu#113]
How to change the region or language of the xemu emulator?

Trying to play Conker Live & Reloaded in German but cant get the language switched.
How can I achieve to switch Console Language / Systemlanguage to "German"?

Audio is working very well except a little stutter but I think its because of my slow hardware

**Comment by dracc** [comment]
Same way you'd do it on your physical Xbox; Set system language in your dashboard.

**Comment by sm4rty89** [comment]
ahh thx, didn't know that I have to install the dashboard first. I used it without an installed dashboard.
tank you very much!

**Comment by B4rabbas** [comment]
Sorry if it's obvious for the other but I've foundt nothing for launching the dashboard on xemu, how did you did this ?

**Comment by Ryzee119** [comment]
You need to copy the original dashboard files to the xboxes c partition.
The bios normally looks for xboxdash.xbe in this folder and will load it. Just like a real xbox.
If you require any further advise please consider joining the discord
