### ISSUE TITLE
Same color & zeta surface offset is not supported

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1138]
### Bug Description

The following games are known to be affected by the following assert block:

https://github.com/mborgerson/xemu/blob/aa7acc8f64e64bb517a0bd0e5e41672671e61df1/hw/xbox/nv2a/pgraph.c#L5421

https://github.com/mborgerson/xemu/blob/aa7acc8f64e64bb517a0bd0e5e41672671e61df1/hw/xbox/nv2a/pgraph.c#L5415-L5416

Games Affected:
[Power Drone](https://xemu.app/titles/4253000b/#Power-Drome)

### Expected Behavior

Should be Implemented

### xemu Version

Version: 0.7.55
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/db389b15086753cb7b72e05b24af205baa742bc3
Date: Sun Jun 26 05:58:57 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

**Comment by Fabxx** [comment]
Dup of #775
