### ISSUE TITLE
xemu won't play anything anymore

### ISSUE THREAD

**Issue by Snaoke** [xemu-project/xemu#115]
I've been gone a while and just downloaded the latest xemu, but now it won't play anything. I use to play Sarges War no problem, and Conker when it would freeze at Scarecrow encounter. Now, it just refuses to load any game.

Here's the log if needed:

**xemu_settings_get_path: config path: C:\Users\manof\AppData\Roaming\xemu\xemu\xemu.ini
config_parse_callback: [system] flash_path = C:\Users\manof\Desktop\emulators\xemu-win-release\data\xbox-4627_debug.bin
config_parse_callback: [system] bootrom_path = C:\Users\manof\Desktop\emulators\xemu-win-release\data\mcpx_1.0.bin
config_parse_callback: [system] hdd_path = C:\Users\manof\Desktop\emulators\xemu-win-release\data\xbox_hdd.qcow2
config_parse_callback: [system] eeprom_path = C:\Users\manof\AppData\Roaming\xemu\xemu\eeprom.bin
config_parse_callback: [system] dvd_path = D:\Games\Xbox Games\Conker Live and Reloaded DVD5.iso
config_parse_callback: [system] memory = 64
config_parse_callback: [system] shortanim = true
config_parse_callback: [display] scale = scale
config_parse_callback: [display] ui_scale = 1
config_parse_callback: [input] controller_1_guid =
config_parse_callback: [input] controller_2_guid =
config_parse_callback: [input] controller_3_guid =
config_parse_callback: [input] controller_4_guid =
config_parse_callback: [network] enabled = false
config_parse_callback: [network] backend = user
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [misc] user_token =
Created QEMU launch parameters: C:\Users\manof\Desktop\emulators\xemu-win-release\xemu.exe -cpu pentium3 -machine xbox,bootrom=C:\Users\manof\Desktop\emulators\xemu-win-release\data\mcpx_1.0.bin,short-animation,kernel-irqchip=off -device smbus-storage,file=C:\Users\manof\AppData\Roaming\xemu\xemu\eeprom.bin -bios C:\Users\manof\Desktop\emulators\xemu-win-release\data\xbox-4627_debug.bin -m 64 -drive index=0,media=disk,file=C:\Users\manof\Desktop\emulators\xemu-win-release\data\xbox_hdd.qcow2,locked -drive index=1,media=cdrom,file=D:\Games\Xbox Games\Conker Live and Reloaded DVD5.iso -display xemu -audiodev none,id=snd0
dsp_init
dsp_init
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active**

**Comment by mborgerson** [comment]
You need a fully initialized EEPROM image. You can do this with the official Microsoft dashboard, or you can use an alternative open-source dashboard like NevolutionX to do this. Come chat in the Discord server for help.
