### ISSUE TITLE
Handle color/zeta overlap

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#116]

**Comment by Triticum0** [comment]
Other title affected:
https://xemu.app/titles/4156003b/#DreamWorks-Madagascar
https://xemu.app/titles/5655000a/#Metal-Arms-Glitch-in-the-System
https://xemu.app/titles/41480002/#Playboy-The-Mansion
https://xemu.app/titles/4d53002e/#Maximum-Chase
https://xemu.app/titles/4b4e001a/#Silent-Scope-Complete (2)

**Comment by Triticum0** [comment]
Can This Be closed?

**Comment by mborgerson** [comment]
Yes
