### ISSUE TITLE
Tenchu Return from Darkness - Wireframes Everywhere.

### ISSUE THREAD

**Issue by Machina74** [xemu-project/xemu#1162]
### Title

https://xemu.app/titles/41560026/#Tenchu-Return-from-Darkness

### Bug Description

Wireframe appears on characters and scenery while in-game. You notice it once you get to the character select screen. The wireframes are not textures seams and they stay solid regardless of the camera angle.

Higher-resolution scaling decreases the size of the wireframe lines. 

![unknown](https://user-images.githubusercontent.com/106844154/177064282-c43bc98d-3f97-4968-9063-1ac4b200b523.png)

### Expected Behavior

Wireframes shouldn't appear at all.

### xemu Version

Version:      0.7.57
Branch:       master
Commit:       6a8a967438572656e95d12b881eb01f0f1873aaa
Date:         Sat Jul  2 17:42:25 UTC 2022

### System Information

CPU:          AMD Ryzen 9 5900X 12-Core Processor            
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 516.59
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

I noticed this issue at least over a year ago.

**Comment by abaire** [comment]
Note: you can also see this on the moon when going into the tutorial menu
![Screenshot_20220715_213233](https://user-images.githubusercontent.com/448413/179339512-49fcedf3-afc5-4fc0-af55-e99cf3f5c311.png)

**Comment by abaire** [comment]
The moon is rendered in the second BEGIN_END, which is a `NV097_SET_BEGIN_END_OP_TRIANGLE_STRIP`.

The input texture is a bit unusual in that it seems to contain both the moon and a fog/plasma image, but there is no visible artifact across the moon. The artifact itself appears to be a partial line between the two triangles in the strip where alpha is set to 0, allowing the clear color (black) to show through.

Combiner:
```
// Stage 0
mux_sum.rgb = clamp(vec3(((max(t0.rgb, 0.0) * max(v0.rgb, 0.0)) + (max(vec4(0.0).rgb, 0.0) * max(vec4(0.0).rgb, 0.0)))), -1.0, 1.0);
mux_sum.a = clamp(((((max(t0.a, 0.0) * max(v0.a, 0.0)) + (max(vec4(0.0).b, 0.0) * max(vec4(0.0).b, 0.0))) * 4.0)), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
r0.a = mux_sum.a;
// Final Combiner
fragColor.rgb = max(clamp(vec4(v1.rgb + r0.rgb, 0.0), 0.0, 1.0).rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(r0.a, 0.0);
if (!(fragColor.a >= alphaRef)) discard;
```

Forcing `fragColor.a` to 1.0 does not fix the problem, which may indicate that there's a gap in the geometry itself (removing the `alphaRef` check and using a lower alpha results in the gap being lowered as well, but it is always something less than the full triangle alpha)

**Comment by abaire** [comment]
Looking at the pgraph log, I see that `NV097_SET_LINE_SMOOTH_ENABLE` and `NV097_SET_POLY_SMOOTH_ENABLE` are both enabled. If I disable the glEnable call in xemu that backs enabling these options, the artifacts disappear.


As far as I can see these don't appear to actually affect anything on HW:
[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/three_d_primitive_tests.cpp)
[HW Results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-3D_primitive)


UPDATE: There must be some additional trigger, as the polygon smoothing definitely has an effect on the MS Dashboard (and was implemented as part of fixing jagged edges around the memory/music/etc... options in the menu)

The dashboard reners to a non-AA surface but the surface size is doubled in each direction and is later manually drawn to the normal sized screen via a single triangle that is itself doubled in each direction wrt. the already doubled texture. So the screen is 640x480, the texture is 1280x960, and the triangle is 2560x1920 using texcoords `0.5,0.5` - `5120.5,3840.5`

**Comment by abaire** [comment]
#1187 is a temporary workaround. It ignores the smoothing flag altogether, which may or may not result in "jaggies" instead of the current wireframe artifacting, so it may or may not be an improvement, depending on your point of view.

**Comment by abaire** [comment]
On further investigation, I found that 0x1D7C is acts as a disable switch for the smoothing flags, Tenchu uses this to turn off smoothing on the complex poly draws.

**Comment by Reonu** [comment]
Any fix for this on the horizon?

**Comment by TenchuNinja** [comment]
Vemu continues to disappoint me. I’ve been trying to play Tenchu: Return of Darkness. Wireframes are all over the game at a fast speed, and when you reach higher than 4x, the wireframes are reduced the game ran extremely slow.

**Comment by TenchuNinja** [comment]
Vemu continues to disappoint me. I’ve been trying to play Tenchu: Return of Darkness. Wireframes are all over the game at a fast speed, and when you reach higher than 4x, the wireframes are reduced the game ran extremely slower than a turtle.

But in the menu, Tesshu is the only one covered in wireframes. 

When will this problem ever get fixed? They updated the Xemu last March and yet they still didn't fix this bug for the graphic and speed. 

![IMG_4524](https://user-images.githubusercontent.com/130874085/232258044-ad9ad537-0b81-45ce-ac0e-05cf8b419103.jpeg)
![IMG_4525](https://user-images.githubusercontent.com/130874085/232258045-4ece368e-b9e0-418e-9b5b-d15a61d2330f.jpeg)


![IMG_4526](https://user-images.githubusercontent.com/130874085/232258046-b9207dd6-a162-4c88-8c23-dbb64181ea74.jpeg)
![IMG_4533](https://user-images.githubusercontent.com/130874085/232258048-2525a476-e81d-487a-bf5f-5f5762215edc.png)
![IMG_4534](https://user-images.githubusercontent.com/130874085/232258050-8ad3b083-6b6b-416a-b114-c5b17fa78283.jpeg)

![IMG_4517](https://user-images.githubusercontent.com/130874085/232258040-f21f693f-1603-427b-a25f-6941f991f113.png)

**Comment by TenchuNinja** [comment]
Vemu continues to disappoint me. I’ve been trying to play Tenchu: Return of Darkness. Wireframes are all over the game at a fast speed, and when you reach higher than 4x, the wireframes are reduced the game ran extremely slower than a turtle.

But in the menu, Tesshu is the only one covered in wireframes.

When will this problem ever get fixed? They updated the Xemu last March and yet they still didn't fix this bug for the graphic and speed.
![IMG_4524](https://user-images.githubusercontent.com/130874085/232258145-e4837f38-59f5-40aa-8c76-bd8e33a1e2f8.jpeg)
![IMG_4525](https://user-images.githubusercontent.com/130874085/232258149-b1825418-1a68-428f-999e-d77f8312bfe0.jpeg)
![IMG_4526](https://user-images.githubusercontent.com/130874085/232258151-ea283d9e-9014-41b7-81e9-47703ec6e1d0.jpeg)
![IMG_4533](https://user-images.githubusercontent.com/130874085/232258152-0b99f4e8-742e-4c25-b19e-4c43dd2b3549.png)
![IMG_4534](https://user-images.githubusercontent.com/130874085/232258153-137fdce7-a086-4b9c-b474-1ccd3b22251c.jpeg)
![IMG_4535](https://user-images.githubusercontent.com/130874085/232258154-83629125-456e-4c43-ac5b-7bb9b07ca283.png)

**Comment by ghost** [comment]
Vemu continues to disappoint me. I’ve been trying to play Tenchu: Return of Darkness. Wireframes are all over the game at a fast speed, and when you reach higher than 4x, the wireframes are reduced the game ran extremely slower than a turtle.

But in the menu, Tesshu is the only one covered in wireframes.

When will this problem ever get fixed? They updated the Xemu emulator last March 2023 and yet they still didn't fix this bug for the graphic and speed. Unbelievable...

![IMG_4524](https://user-images.githubusercontent.com/130874085/232258219-95b07231-fed1-42c6-b960-b2979d821427.jpeg)
![IMG_4525](https://user-images.githubusercontent.com/130874085/232258221-6786d88e-7c3f-402e-ba3c-4aae6d76b4d0.jpeg)
![IMG_4526](https://user-images.githubusercontent.com/130874085/232258222-fcd06d22-8d08-45ca-ad7c-d9ef6a6c0a4b.jpeg)
![IMG_4533](https://user-images.githubusercontent.com/130874085/232258223-eeb3830f-ad2b-4f13-b46f-be752e97d85b.png)
![IMG_4534](https://user-images.githubusercontent.com/130874085/232258224-1f474547-c20d-4ef7-9f73-929a6012de32.jpeg)
![IMG_4536](https://user-images.githubusercontent.com/130874085/232258225-5c636007-6603-40b9-8fd9-695f3d095ced.jpeg)
![IMG_4535](https://user-images.githubusercontent.com/130874085/232258227-b5f64cc6-033f-4fc5-84de-19ef97c8e031.png)
