### ISSUE TITLE
MagiDeathFight! Nivida rendering issue

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1176]
### Title

https://xemu.app/titles/544b0001/#Magi-Death-Fight

### Bug Description

When using a Nivida GPU to test this game, all menu screens have a diagonal line going across the whole screen from corner to corner. This didn't affect me when using an AMD GPU but think it is an Ampere issue only.
![xemu-2022-07-08-14-53-58](https://user-images.githubusercontent.com/71127352/178009422-38aac3a5-b527-4d69-8efb-15442129189a.png)

### Expected Behavior

The line should'nt be present

### xemu Version

Version: 0.7.58
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/6f878ede01ad1992392dde22b506a3c00fab87c4
Date: Wed Jul 6 02:14:58 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processor
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

**Comment by abaire** [comment]
Note for whoever investigates this: sounds potentially similar to #1162 which was also tested on a RTX3... card. 

UPDATE: @Triticum0 tested #1187 which has a hackaround for #1162 and it didn't fix the problem, so it seems like it's unique

**Comment by abaire** [comment]
@Triticum0 can you get a pgraph trace of this problem?

```
trace-event nv2a_pgraph_method* on
```

I probably just need one or two frames of the screen you posted above to start theorizing about the cause.

**Comment by Triticum0** [comment]
[MagiDeathFight!.txt](https://github.com/mborgerson/xemu/files/9126072/MagiDeathFight.txt)

Here

**Comment by abaire** [comment]
Can you double check with the latest state of #1187? 

Looking at that pgraph log I see exactly the pattern that would cause the problem in #1162 that my PR addresses (draws using `NV097_SET_BEGIN_END_OP_TRIANGLE_STRIP` with `NV097_SET_POLY_SMOOTH_ENABLE` true).


That said, I don't see any 0x1D7C commands in the log, so maybe there is some additional mechanism that causes that flag to be ignored in HW or causes it to blend more correctly? Someone may need to do a renderdoc capture to dig into exactly what is causing the line. It is very suspicious that smoothing is enabled w/ complex primitives, as it should cause something like ![this](https://raw.githubusercontent.com/abaire/nxdk_pgraph_tests_golden_results/main/3D_primitive%2fTriStrip-inlinearrays-ps.png)
