### ISSUE TITLE
XEMU for Xbox Dev Mode

### ISSUE THREAD

**Issue by BrandiBlitz** [xemu-project/xemu#1206]
### Feature Request

Is it possible for the Xbox Series X|S Dev Mode to utilize XEMU? It would be ‪really interesting and awesome to play my OG xbox games on Next Gen Hardware.

**Comment by mborgerson** [comment]
There are no plans to get xemu running on Xbox Series X. If you want to try though you are welcome to. You can also play some of your games with the official back compat

**Comment by BrandiBlitz** [comment]
> There are no plans to get xemu running on Xbox Series X. If you want to try though you are welcome to. You can also play some of your games with the official back compat

That's alright~ I hope this inspires someone to give it a try. I don't know how to code though.
