### ISSUE TITLE
XEMU "Load Disc..." state can be broken, requires emulator restart

### ISSUE THREAD

**Issue by ParadoxGBB** [xemu-project/xemu#1218]
### Bug Description

There's a set of steps that makes Xemu stuck on "Please insert an Xbox disc...", no matter what file you select. I can only get out of this state by restarting XEMU, which isn't a huge problem, but it could confuse a user into believing ISO files are corrupt when they are not.

1) Start XEMU, select an ISO, load it.
2) Play a bit, close XEMU
3) Rename or move the file selected in 1)
4) Re-launch XEMU
5) See and dismiss popup complaining that it couldn't find the file in 1) with "Ok"
6) Select "Machine" --> "Load Disc..." and attempt to load any other ISO file.

### Expected Behavior

Expected: File loads, game starts.

Actual: Screen stuck on "Please insert an Xbox disc..." screen.

### xemu Version

0.7.66

### System Information

OS: Windows 11 10.0.22622
CPU: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3301 Mhz
GPU: Nvidia GeForce GTX 750 Ti
GPU Driver Version: 516.59

### Additional Context

I looked briefly at the open issues and didn't see this specific issue. If there already is one, please accept my apologies and dupe.

Side comment: great job with this emulator!

**Comment by dracc** [comment]
This is not a xemu problem, but of the [xemu-hdd-image](https://github.com/mborgerson/xemu-hdd-image) repository.
Please close this issue and take a look there instead.
