### ISSUE TITLE
Insert Xbox disc after loading iso

### ISSUE THREAD

**Issue by polishprodigy93** [xemu-project/xemu#123]
My emulator won’t launch a game after loading iso and is just stuck with “insert Xbox disc” after animation.  I have tried many different bios and nothing is launching....

**Comment by mborgerson** [comment]
You need a fully initialized EEPROM image. You can do this with the official Microsoft dashboard, or you can use an alternative open-source dashboard like NevolutionX to do this. Come chat in the Discord server for help.

**Comment by 4oo4** [comment]
Since this is seems to be a common issue, I think that should be added to the README and docs. All the other required files are documented super well except for this one, so it gives false expectations about the included EEPROM image.

**Comment by mborgerson** [comment]
This is out of date. See here https://xemu.app/docs/faq/#q-why-am-i-getting-please-insert-an-xbox-disc-i-already-loaded-an-iso @4oo4

**Comment by 4oo4** [comment]
Thanks, I didn't see that. So to understand that I did it right, I grab the NevolutionX ISO, boot from that to initialize the EEPROM, then after that I can load my game ISO? That seems to read my game ISO OK then, but then I only get audio output and no video, but that's probably a separate issue with my graphics.

Cheers
