### ISSUE TITLE
XEMU can't enable Bridged Adapter on Arch linux

### ISSUE THREAD

**Issue by Abro61209** [xemu-project/xemu#1233]
### Bug Description

1. Launch XEMU
2. Go to Machine -> network -> change attached to 'Bridged Adapter', select my network interface -> enabled.

I get the error code "failed to open interface 'xxx' for capture: enp34s0: socket: Address family not supported by protocol."

Do I need some kind of package on Linux to allow this? The Linux equivalent of Npcap probably? Although I have no idea what that is. Tried installing libpcap.

### Expected Behavior

Should just bridge my interface and work.

### xemu Version

Version:      0.7.67

**Comment by HadetTheUndying** [comment]
Just out of curiosity did you run:
```
sudo setcap cap_net_raw,cap_net_admin=eip `which xemu`
```
It is outlined in the documentation here: https://xemu.app/docs/networking/#linux

**Comment by Fabxx** [comment]
Also an additional note, to do that command, you either have to put the binary in the home directory, or a system directory, usually i use /usr/bin, then i do the command and it works

**Comment by Abro61209** [comment]
@HadetTheUndying -  Ran that command and it says xemu doesn't exist.
@Fabxx - I downloaded the flatpak version. Don't flatpaks put the apps in /usr/bin by default?

**Comment by Fabxx** [comment]
No, you have tu use the source code and compile the binary. The website has a guide for each distro

**Comment by Abro61209** [comment]
Ok, guess flatpaks really are hit or miss. I'll just compile it myself and try that way.

**Comment by Abro61209** [comment]
@Fabxx 
Compiled it, it stored it in my /home/user/xemu, tried running that command. says xemu doesn't exist again. Moved the entire directory to /usr/bin through the command line, STILL says xemu doesn't exist. Running Arch Linux btw.

**Comment by Fabxx** [comment]
when you type `xemu` in terminal does it start the emulator? It should since now it's in /usr/bin

**Comment by dracc** [comment]
> @Fabxx
> Compiled it, it stored it in my /home/user/xemu, tried running that command. says xemu doesn't exist again. Moved the entire directory to /usr/bin through the command line, STILL says xemu doesn't exist. Running Arch Linux btw.

This really isn't the place for Computer 101.
The program is, after you've run `./build.sh`, located in a new folder named `dist`.

**Comment by Abro61209** [comment]
@Fabxx 
Nope, command not found, even when in /usr/bin. I followed their guide here for Arch Linux:

https://xemu.app/docs/dev/building-from-source/#linux

Seems like I can only run it with that full ./dist/xemu command, just xemu doesn't work. Here is the error output I get when trying to run that setcap command.

which: no xemu in (/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

The emulator works flawlessly otherwise.

**Comment by Abro61209** [comment]
@Fabxx 

Ah okay I see now. I moved just the binary to /usr/bin just like you said, now the command @HadetTheUndying said from xemu's documentation works. I was moving the WHOLE xemu folder over as I was thinking the xemu binary wouldn't launch unless its dependencies were in the same directory as the binary. Thanks much all, going to close this now.
