### ISSUE TITLE
SSX Tricky (PAL) - Freeze at EA Sports BIG logo

### ISSUE THREAD

**Issue by RibShark** [xemu-project/xemu#1245]
### Title

https://xemu.app/titles/45410004/#SSX-Tricky

PAL EA-004 v1.03

### Bug Description

When booting the game, the game will freeze at the end of the EA Sports BIG logo, after the "Checking hard disk..." message and loading screen show. The EA Sports BIG logo will also not have any audio (I believe the game actually is programmed to continue to the next cutscene after the audio has finished, so this is relevant). The NTSC-U and NTSC-J versions of this game work fine.

### Expected Behavior

The EA Sports BIG logo will have its audio, and will continue on to the game's opening cutscene after it has finished playing.

### xemu Version

v0.7.67

### System Information

OS: Windows 11
CPU: AMD Ryzen 5900x
GPU: NVIDIA GeForce GTX 970
GPU Driver Version: 473.33

### Additional Context

The PAL version has a slightly different character roster to the NTSC one (Mac was replaced with Marty), so it would be nice to get this version working. Replacing the video file on the PAL disc with the NTSC one still causes the game to freeze.

**Comment by RibShark** [comment]
As of now, the game boots and works, however audio is bugged: only the left channel is active and some sound effects do not play.

**Comment by mborgerson** [comment]
@RibShark thanks for the update. Can you file a new issue about the audio problem? I'll close this one now that its playable.
