### ISSUE TITLE
Multiple games marked as "playable" doesn't boot

### ISSUE THREAD

**Issue by VladimirVSC** [xemu-project/xemu#1252]
### Title

https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2

MS-075 [4d53004b]

https://xemu.app/titles/55530018/#Beyond-Good-Evil

US-024 [55530018]

https://xemu.app/titles/4541003c/#SSX-3

EA-060 [4541003c]

https://xemu.app/titles/4c410003/#Star-Wars-Knights-of-the-Old-Republic

LA-003 [4c410003]

https://xemu.app/titles/5454000e/#Grand-Theft-Auto-III

TT-014 [5454000e]

https://xemu.app/titles/5454000f/#Grand-Theft-Auto-Vice-City

TT-015 [5454000f]

### Bug Description

Some games tested (Beyond Good & Evil, Knights of the Old Republic, GTA III, GTA - Vice City, SSX 3, Project Gotham Racing 2) (marked as "playable") don't start at all. Instead the Xbox dashboard appears somehow, as if the emulator doesn't see the disk inserted. Original "Redump" NTSC isos, trimmed with "dd" command were used. The dashboard version is 5960 (if it has any importance).

### Expected Behavior

The game should start after Xbox logo, not the dashboard.

### xemu Version

Xemu 0.7.67

### System Information

OS: Linux Mint Debian Edition 5
CPU: Core-I5 4430 (3.00 GHz) (4 cores)
GPU: GeForce GTX 760
Driver: NVIDIA 470.129.06

**Comment by dracc** [comment]
The `dd` method isn't fool proof, some titles have issues with it. Recommended procedure is to use `extract-xiso` instead.
