### ISSUE TITLE
Halo 2 Multiplayer Map Pack crashes to desktop after initial videos

### ISSUE THREAD

**Issue by VladimirVSC** [xemu-project/xemu#1253]
### Title

https://xemu.app/titles/4d5300cd/#Halo-2-Multiplayer-Map-Pack

MS-205 [4d5300cd]

### Bug Description

After two initial videos the progress stops, showing a black screen for several seconds, and then the emulator crashes to desktop. Trying to interrupt this videos has the same result - screen picture freezing and then crashing.

### Expected Behavior

The content of the disc working properly, not being stuck and crash at the very beginning.

### xemu Version

Xemu 0.7.67

### System Information

OS: Linux Mint Debian Edition 5
CPU: Core-I5 4430 (3 GHz) (4 cores)
GPU: GeForce GTX 760
Driver: 470.129.06

**Comment by dracc** [comment]
Tricky title - this behavior has been observed when a non-32 bit build of extract-xiso has been used to create the disc image.

**Comment by VladimirVSC** [comment]
> Tricky title - this behavior has been observed when a non-32 bit build of extract-xiso has been used to create the disc image.

Strange... The download link of the program says "win32" release.

**Comment by mborgerson** [comment]
Enable 128MiB memory to work around the issue

Dup #34
