### ISSUE TITLE
Bridged network adapter not working?

### ISSUE THREAD

**Issue by hdfsyu** [xemu-project/xemu#1254]
### Bug Description

Bridged network type/adapter does not work inside of the emulator (either is not recognized, or i'm just configuring something wrong)
Some images of the error:
![Screenshot from 2022-09-02 13-08-19](https://user-images.githubusercontent.com/83127463/188204109-a9a6d631-2c1f-4475-a084-a05d9032e5c3.png)
![Screenshot from 2022-09-02 13-08-35](https://user-images.githubusercontent.com/83127463/188204111-0d2f114c-beb9-412b-b475-f3c3b563ba43.png)

### Expected Behavior

Bridged network adapter should be recognized and should be able to connect to emulator

### xemu Version

Version:      0.7.67
Branch:       master
Commit:       940bee452cc34127ecf3f364c3c5f52e4e6a80a4
Date:         Fri Aug  5 20:51:02 UTC 2022

### System Information

CPU:          Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
OS Platform:  Linux
OS Version:   Zorin OS 16.1
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.85.02
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

I tried this in windows, still didn't work
Also, in the Xbox dashboard when I try to connect it fails to find the IP address, sometimes it finds it but then it can't find the DNS
I'm using a Realtek Wi-Fi card to bridge to the emulator

**Comment by HadetTheUndying** [comment]
Did you make sure to set network capabilities on the `xemu` binary? It's working fine for me.

https://xemu.app/docs/networking/#linux

**Comment by hdfsyu** [comment]
@HadetTheUndying I already did that, still not working

**Comment by HadetTheUndying** [comment]
Can you run xemu from a terminal and paste the output after you try to enable the bridge? Where did you install xemu from? PPA? flathub? 

Also bear in mind you are not going to be able to connect to Xbox Live regardless so this isn't a good test scenario. Xbox Live 1.0 has been offline for over a decade.

**Comment by hdfsyu** [comment]
> Can you run xemu from a terminal and paste the output after you try to enable the bridge? Where did you install xemu from? PPA? flathub?
> 
> Also bear in mind you are not going to be able to connect to Xbox Live regardless so this isn't a good test scenario. Xbox Live 1.0 has been offline for over a decade.

no im trying to use XLink Kai

**Comment by hdfsyu** [comment]
and I need to reboot into linux so gimme a sec to reboot

**Comment by hdfsyu** [comment]
I installed it from the PPA, and when I try to connect it doesn't do anything

**Comment by hdfsyu** [comment]
The only output I got:
`xemu_version: 0.7.67
xemu_branch: master
xemu_commit: 940bee452cc34127ecf3f364c3c5f52e4e6a80a4
xemu_date: Fri Aug  5 20:51:02 UTC 2022
xemu_settings_get_path: config path: /home/hdfsyu/.local/share/xemu/xemu/xemu.toml
CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
OS_Version: Zorin OS 16.1
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 510.85.02
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
Created QEMU launch parameters: xemu -machine xbox,bootrom=/home/hdfsyu/Desktop/originalxboxemu/mcpx_1.0.bin,kernel-irqchip=off,avpack=hdtv -device smbus-storage,file=/home/hdfsyu/.local/share/xemu/xemu/eeprom.bin -bios /home/hdfsyu/Desktop/originalxboxemu/Complex_4627v1.03.bin -m 128 -drive index=0,media=disk,file=/home/hdfsyu/Desktop/originalxboxemu/xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file= -display xemu `

**Comment by mborgerson** [comment]
> I'm using a Realtek Wi-Fi card to bridge to the emulator

Generally your wi-fi adapter should not let you inject packets with multiple MAC addresses (e.g. Xbox and host), and using the same MAC address as your host will cause issues. I recommend only bridging with Ethernet devices.

If you want to give Internet connectivity to Xbox software, or if you want to test XBL connectivity (which will fail unless you're connecting to some infrastructure like [Xombie](https://github.com/XombieOnline/xombie/)), you can simply use NAT mode.

If you want to play with another person using xemu, you can use the UDP tunnel mode and connect to the servers listed on the Discord #multiplayer channel.

More info about networking [on xemu.app](https://xemu.app/docs/networking/)
