### ISSUE TITLE
Half-Life 2 : Graphic glitch

### ISSUE THREAD

**Issue by LuLu89LT** [xemu-project/xemu#1255]
### Title

https://xemu.app/titles/45410091/#Half-Life-2

EA-145

### Bug Description

The game start but the menu is not displayed correctly 

![xemu-2022-09-02-19-33-32](https://user-images.githubusercontent.com/112720915/188207809-9a433af5-7baa-40e8-8250-0cf45f3ba6d4.png)

1) Press strart

![xemu-2022-09-02-18-48-00](https://user-images.githubusercontent.com/112720915/188207845-448113e4-1f7f-475d-940a-6f4dd51cd9ce.png)

2) Start a new game 
3) Press "A" button 3 time

The game crash on loading

![xemu-2022-09-02-19-34-01](https://user-images.githubusercontent.com/112720915/188207727-c2489d9e-46a8-47d3-b6f4-1036d0a3a5a7.png)

### Expected Behavior

the texture of menu should do display correctly

### xemu Version

Version:      0.7.67
Branch:       master
Commit:       940bee452cc34127ecf3f364c3c5f52e4e6a80a4
Date:         Fri Aug  5 18:17:20 UTC 2022

### System Information

CPU:          Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1060/PCIe/SSE2
Driver:       4.0.0 NVIDIA 516.94
Shader:       4.00 NVIDIA via Cg compiler

**Comment by HunterAhlquist** [comment]
I don't have this issue on my device.
Intel i7-11370H
RTX 3050 Ti mobile
Diver: 517.48
Shader: 6.6 

Perhaps a driver update fixed it unintentionally?

**Comment by Triticum0** [comment]
Probably fixed with https://github.com/mborgerson/xemu/pull/1187

**Comment by FluffyPuppyKasey** [comment]
M1 MacBook Air here, menu is fine, game itself has severe artifacting

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/58578837/194182652-99ccfaf7-d25e-4cdd-98d0-4c0f47620e26.png">

**Comment by HunterAhlquist** [comment]
@KaseyTheJackal I recommend creating a different issue for this.

@Triticum0 Any way to update the compatibility page? If the issue is fixed maybe it should be closed.

**Comment by LuLu89LT** [comment]
I resolved this issue, I reset my computer and reinstall windows and the game is running very well

![xemu-2022-10-11-18-04-44](https://user-images.githubusercontent.com/112720915/195149541-b3e4e497-2306-44b2-9631-9acc804e49d7.png)

![xemu-2022-10-11-15-41-25](https://user-images.githubusercontent.com/112720915/195149571-7fe39fef-98c9-4a34-9192-3ab9c1768810.png)

![xemu-2022-10-11-14-51-58](https://user-images.githubusercontent.com/112720915/195149609-60fe81ca-721d-4ce0-884a-b0499c66f243.png)

![xemu-2022-10-11-14-56-37](https://user-images.githubusercontent.com/112720915/195149904-7077ff5f-c685-467a-93d3-7c53a734469b.png)
