### ISSUE TITLE
Linux Guest has not initialized the display yet

### ISSUE THREAD

**Issue by Blad3forc3** [xemu-project/xemu#126]
Version: 0.4.0-42-ga72cc138f4
Branch:  master
Commit:  a72cc138f4fca618b8e919b4db378ce64e7fbda3
Date:    Thu Dec 31 23:09:32 UTC 2020

KDE Neon

Menu opens but displays this
Guest has not initialized the display yet
Loading ISO resetting doesnt help

**Comment by mborgerson** [comment]
Check your boot ROM hash and verify you have a compatible BIOS image.

https://github.com/mborgerson/xemu/wiki/FAQ#q-why-am-i-getting-the-guest-has-not-initialized-the-display
