### ISSUE TITLE
Compatibility for the other BIOS files

### ISSUE THREAD

**Issue by John-Enigma** [xemu-project/xemu#1269]
### Feature Request

I don't know if this has been requested before, nor do I know if it's in development, but I would love if Xemu had compatibility with the following Flash BIOS versions: 3944, 4034, 4132, 4134, 4817, 5101, 5530, 5713, and 5838. 

Same goes for the MCPX boot ROM, that does not support the 1.1 version of it.

I've tried to look for information on why this emulator doesn't support the other versions, but I never found an explanation.

**Comment by dracc** [comment]
They already work, have you even tried it?

**Comment by MattPonton** [comment]
My XEMU instance is running my OG Xbox's bins: MCPX 1.1 and Flash 5838...

![image](https://user-images.githubusercontent.com/45347806/192858873-c186ab06-4b91-41aa-a33a-89209cd58799.png)

**Comment by mborgerson** [comment]
xemu is compatible with various BIOS images, as evident by @MattPonton's screenshot. You'll need to make sure your ROM dumps are correct/paired properly

**Comment by John-Enigma** [comment]
Sorry for the late response. Thank you. I'll try to see if I can make them work. 

If not, then I don't know.
