### ISSUE TITLE
After updating to latest release, the "Port Forwarding" section of the FTP guide no longer works

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [xemu-project/xemu#1275]
### Bug Description

After updating to the latest release, the guide on the Xemu website for setting up an FTP connection to the emulated HDD no longer works, the emulator claiming the options cannot be set:
https://xemu.app/docs/ftp/

Following the guide:

"1. In xemu, open the Network window by navigating to Machine --> Network. If networking is currently enabled, click Enable toggle to disable it. From the "Attached to" combo box, select "NAT".

2. We must now configure xemu to forward FTP traffic on the host machine to the internal network. In the Port Forwarding section, enter 2121 in the Host Port field, 21 in the Guest Port field, select TCP as the Protocol and click the Add button.

Finally, then click Enable to connect the virtual network."

However, starting latest release, this no longer works, instead failing with an error box that says "Could not set host forwarding rule 2121 -> 21 (tcp)".
![image](https://user-images.githubusercontent.com/58268914/195397386-96b40e24-78db-422d-83d0-e0363086dd20.png)

### Expected Behavior

The emulator should be successful in port forwarding, allowing FTP connections to the system.

### xemu Version

Issue appeared in:  v0.7.71

Last working in:  v0.7.70

### System Information

OS: Windows 10 Pro x64 build 19041
CPU: Intel Core i9-10900K
GPU: NVIDIA RTX 2080 SUPER
RAM: 64 GB DDR4

**Comment by Aerocatia** [comment]
I have seen this before, this seems to be related to restarting the process after updating. It will usually work again after restarting it again.

**Comment by SlyCooperReloadCoded** [comment]
Huh you're right, that did fix it.  Had to restart the whole computer but yeah.

**Comment by Aerocatia** [comment]
You might want to leave this open as ideally this should still be handled some way.
