### ISSUE TITLE
Please add a version for Android Users

### ISSUE THREAD

**Issue by joelos1111** [xemu-project/xemu#1281]
### Feature Request

Please try to compile a version for Android users like me, right now the Emulator looks amazing but i'd love to try it on my phone or Tablet. I hope you are able to make it work on the vast majority of Android Devices whether they are ARMV7 or ARMV8 and that you can compile an official version of your wonderful Emulator in the upcoming days or months, if you offer some support for this then we all mobile/tablet users would highly appreciate it

**Comment by parkerlreed** [comment]
Performance wise this has a slim chance of ever working. It is using qemu to translate x86 calls on native x86 hardware. Doing that translation across architectures has a major performance impact. 

See box86 and box64 for examples

**Comment by mborgerson** [comment]
It will happen one day, but it is not a priority today. Today PC and PC-like platforms are the main priority. That said, if someone is very motivated to work on Android support, they are welcome to.

**Comment by dracc** [comment]
https://xemu.app/docs/faq/#q-are-there-any-plans-for-a-mobile-port-of-xemu
#501
#719
#857
