### ISSUE TITLE
Title Name: Dead or Alive Xtreme Beach Volleyball hanging issue if you take a rest on poolside

### ISSUE THREAD

**Issue by AkihitoZero5454** [xemu-project/xemu#1285]
### Title

Dead or Alive Xtreme Beach Volleyball
TC-007 [54430007]

### Bug Description

Game will hang and emulator will not respond if you take a rest on poolside
### Expected Behavior

Poolside should function properly

### xemu Version

v0.7.71
Unknown

### System Information

Windows 10
AMD Ryzen 7 3700X 8 Core Processor
Nividia Geforce GTX 1070 TI
4.0.0 Nividia 522. 25

**Comment by MattPonton** [comment]
I was unable to reproduce this. I started a new game as Ayane and pool hopped to Day 7 Morning. 

```
Version:      0.7.71
Branch:       master
Commit:       22db3304a454b2d289a9d5ea488fa3c3dec836f4
Date:         Tue Oct 11 18:38:37 UTC 2022
```

```
CPU:          Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
Driver:       4.0.0 NVIDIA 522.25
Shader:       4.00 NVIDIA via Cg compiler
```

```
MCPX Boot ROM MD5 Hash:        2870d58a459c745d7cc4c6122ceb3dcb
Flash ROM (BIOS) MD5 Hash:     36d12651df613489953382480d267170
```

**Comment by AkihitoZero5454** [comment]
> I was unable to reproduce this. I started a new game as Ayane and pool hopped to Day 7 Morning.
> 
> ```
> Version:      0.7.71
> Branch:       master
> Commit:       22db3304a454b2d289a9d5ea488fa3c3dec836f4
> Date:         Tue Oct 11 18:38:37 UTC 2022
> ```
> 
> ```
> CPU:          Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
> OS Platform:  Windows
> OS Version:   Windows
> Manufacturer: NVIDIA Corporation
> GPU Model:    NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
> Driver:       4.0.0 NVIDIA 522.25
> Shader:       4.00 NVIDIA via Cg compiler
> ```
> 
> ```
> MCPX Boot ROM MD5 Hash:        2870d58a459c745d7cc4c6122ceb3dcb
> Flash ROM (BIOS) MD5 Hash:     36d12651df613489953382480d267170
> ```

I think I found the real issue. Taking a rest on poolside causes it and I only tested Kasumi and Ayane and the game hangs and Emulator doesn't respond

**Comment by MattPonton** [comment]
Is it related at all to this existing issue?

https://github.com/mborgerson/xemu/issues/563

**Comment by AkihitoZero5454** [comment]
> Is it related at all to this existing issue?
> 
> #563

Well yes If you try to rest in the poolside it'll do the issue and then your save will have the issue even worse by not just resting in poolside but now the whole game have the issue trying to prevent you from exceeding the days. I hope I'm true and sorry this issue has been confusing for me.

**Comment by MattPonton** [comment]
I still am not able to reproduce this issue. This time I started a vacation as Kasumi and rested at the pool every time available. I was able to complete a whole 14 day vacation doing nothing but resting at the pool.

**Comment by dracc** [comment]
Sounds like a bad dump to me. :shrug:
