### ISSUE TITLE
[Feature Request] CHD support

### ISSUE THREAD

**Issue by RinMaru** [xemu-project/xemu#129]
CHDs are a Compressed format and can shrink down ISOs to varying sizes so its a good format for saving space and can be used on XISOs aswell would be nice to support at some point

https://github.com/rtissera/libchdr

**Comment by Shoegzer** [comment]
Agreed, this would be great to see especially if support for redump-style ISOs can be added as discussed [here](https://github.com/mborgerson/xemu/issues/62).  CHD support can then allow use of a compressed full preservation-quality game without needing to store an additional extract-xiso style dump.

**Comment by Anuskuss** [comment]
Big fan of CHD, but I don't think it's a good format for Xbox. If you aren't aware, there's a bunch of random (aka uncompressible) data of the disk and CHD can't (and won't) deal with that:
```
Counter-Strike (PAL)
      ISO: 7463 MiB
      CHD: 6548 MiB
Extracted: 1598 MiB
```

The best approach would be a custom format and to figure out how that padding gets generated, like has happend in the past for GameCube / Wii (in the form of [NKit](https://wiki.gbatemp.net/wiki/NKit)), but we're yet to crack that.

**Comment by RinMaru** [comment]
I think it would be good for extracted games put into Iso because it ends up trimming a good chunk off but yea redump style games have diminishing returns

**Comment by Anuskuss** [comment]
Well technically yes, but that isn't really the spirit of CHD. Obviously it would still be smaller than extracted (and zipped), but adding the libchdr dependency just for some megabytes sounds like avoidable extra work for the devs.

**Comment by RinMaru** [comment]
Not even 7zip can compress the junk data. I'm all for a custom format but that will probably be a ways off.

**Comment by psyalemao** [comment]
I wonder if Zarchive could be an alternative, Xenia supports it already, it compress using zstd
