### ISSUE TITLE
Timesplitters Future Perfect - Mapmaker levels very slow on Steam Deck

### ISSUE THREAD

**Issue by t1op** [xemu-project/xemu#1299]
### Bug Description

On Steam Deck the framerate drops to 1 FPS after beginning a map maker level.

To Reproduce:
Find and fownload a mapmaker level from internet, then FTP it to the Xbox UDATA folder.
Start Xemu. Load game disc, reset.
Select 1 player,  select/ create profile. 
Select Xbox Live / System Link, then system link. 
Select Start Match. 
Press Y for Options. Press up on Dpad, then select Mapmaker, then Xbox HDD.
Select a map and start game. 

### Expected Behavior

The game should run at a regular framerate. 

### xemu Version

7.71

### System Information

Steam Deck. Native OS.

**Comment by mysteria25** [comment]
looks like this emulator is now abandoned.  no new builds for almost 6 months.  such a shame,  it was just starting to become a solid emulator for xbox :/

**Comment by t1op** [comment]
Maybe they are just slowing down for an infinite number of reasons.?
In any case, I discovered that when I increased the Steam Deck's swap file size and swappiness using cryoutilities the problem went away. 
THANK YOU developers! This emulator is amazing and a dream come true!!!

**Comment by prism2001** [comment]
> looks like this emulator is now abandoned. no new builds for almost 6 months. such a shame, it was just starting to become a solid emulator for xbox :/

i think your perception of time is messed up. it has not been 6 months since the last release of this emulator lol.

**Comment by t1op** [comment]
Issue is resolved by increasing swap size
