### ISSUE TITLE
ftp is not working

### ISSUE THREAD

**Issue by cornflakes6374** [xemu-project/xemu#1300]
### Bug Description

cannot ftp to the emulator with filezilla as it says this in the filezilla log:
`Status:	Connecting to 127.0.0.1:2121...
Status:	Connection established, waiting for welcome message...
Error:	Connection timed out after 20 seconds of inactivity
Error:	Could not connect to server
Status:	Waiting to retry...
Status:	Connecting to 127.0.0.1:2121...
Status:	Connection established, waiting for welcome message...
Error:	Connection timed out after 20 seconds of inactivity
Error:	Could not connect to server`
Steps to reporduce this problem:
follow the instructions at [https://xemu.app/docs/ftp/](url), start the server, and connect it with filezilla.

### Expected Behavior

Should show the file list in filezilla

### xemu Version

0.7.71

### System Information

CPU:          Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
OS Platform:  Linux
OS Version:   Debian GNU/Linux 10 (buster)
Manufacturer: Intel Open Source Technology Center
GPU Model:    Mesa DRI Intel(R) UHD Graphics 600 (Geminilake 2x6) 
Driver:       4.5 (Core Profile) Mesa 18.3.6
Shader:       4.50

**Comment by mborgerson** [comment]
Double check the FTP server. You can try LithiumX dashboard

**Comment by dante3732** [comment]
> Double check the FTP server. You can try LithiumX dashboard

Yep, LithiumX pretty good, need replace it in the instructions.
https://xemu.app/docs/ftp/

I spent half an hour on NevolutionX and I didn't have a connection.

**Comment by dbedrenko** [comment]
There is definitely some issue with xemu/qemu here. I have tried the FTP servers offered from these ISOs:
* True Hexen 2021 
* True Hexen 2024
* Rocky5's Soft Modding Tool Extras Disc
* LithiumX
* NevolutionX

The connection is established and the user credentials are authenticated, but the request to list files gets no response and times out.

I have tried all sorts of clients:
* FileZilla
* `ftp` utility in linux
* `lftp`

Here is output from LithiumX as an example:
```
Status:	Connecting to 127.0.0.1:33321...
Status:	Connection established, waiting for welcome message...
Response:	220 -> CMS FTP Server, FTP Version 2020-08-20
Command:	AUTH TLS
Response:	504 Not available
Command:	AUTH SSL
Response:	504 Not available
Status:	Insecure server, it does not support FTP over TLS.
Command:	USER xbox
Response:	331 OK. Password required
Command:	PASS ****
Response:	230 OK, logged in as user
Command:	SYST
Response:	215 FTP Server, V1.0
Command:	FEAT
Response:	211 Extensions supported:
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Retrieving directory listing...
```

These are my network settings:
![image](https://github.com/user-attachments/assets/14d8870d-691d-4245-9b39-3c1a2ec892a7)

This is Xemu v0.7.131 on ArchLinux.
I've spent 4 hours trying to figure it out using all sorts of settings like Passive, Active mode, setting specific charsets, etc. Trying to set up forwarding for the FTP data port for an active connection (failed at this too).

**Comment by dbedrenko** [comment]
Oh my God! Nevermind. I skipped over [this entire section](https://xemu.app/docs/ftp/#step-4-connect-using-your-ftp-client), thinking it's some elementary info on how to connect to an FTP server.
Halleluja! It finally works!
