### ISSUE TITLE
Gunvalkyrie:  Unable to Save

### ISSUE THREAD

**Issue by gridmortis** [xemu-project/xemu#1311]
### Title

https://xemu.app/titles/49470017/#Gunvalkyrie

IG-023 [49470017]

### Bug Description

Cannot save game progress.  Game states upon launch, "Unable to save GUNVALKYRIE game data.  Press A to continue."  Also in options screen, you cannot save.  Otherwise, game runs fine.  Other games save as normal.

To reproduce issue:
1)  Launch game.

### Expected Behavior

Game should allow saving.

### xemu Version

Version: 0.7.71

### System Information

OS: Windows 10 Home
Processor:  i9-11900KB @ 3.30GHz
Graphics:  Nvidia 3060ti
Ram: 32gb

### Additional Context

I added Xemu to Windows security exclusions, and it didn't help the issue.

**Comment by ehw** [comment]
Can't reproduce, I was able to save just fine. Do you have a HDD image associated?

![image](https://user-images.githubusercontent.com/885618/226200786-e0bf6550-839b-4831-b862-16eef2dacdc3.png)

Version:      0.7.85
Branch:       master
Commit:       065c74a00fe402f65147e9b0d1a1eeac1b4b609f
Date:         Mon Mar  6 21:06:28 UTC 2023

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 531.29
Shader:       4.00 NVIDIA via Cg compiler

**Comment by gridmortis** [comment]
PROBLEM SOLVED!  I'm not sure where I got my original HDD image from, but I replaced it with a fresh one from https://github.com/xemu-project/xemu-hdd-image, and the game saves without issue.  Case closed.  ^_^
