### ISSUE TITLE
Xemu does not open in mac

### ISSUE THREAD

**Issue by Triple592** [xemu-project/xemu#1317]
### Bug Description

1. Open Xemu
2. Xemu does not open (Latest release) 

### Expected Behavior

The app should open

### xemu Version

Newest in 1/5/23

### System Information

OS: MacOS

**Comment by mborgerson** [comment]
Can you help provide some basic info, like
* What version of macOS are you on? What hardware/platform?
* Can you clarify what 'does not open' means? How are you opening it? What happens? Do you see any error messages?
* Did xemu work previously for you? If so when?
* Did you download xemu from xemu.app or somewhere else?

**Comment by mborgerson** [comment]
I've tested 0.7.72 (latest release at time of writing) on an M1 Mac Mini and it works fine. Without more info to go on, I'll consider this issue invalid. If you can provide more info about the problem, feel free to re-open a more detailed issue.
