### ISSUE TITLE
Corrupted hard drive/save files if xemu crashes during gameplay

### ISSUE THREAD

**Issue by darreldearth** [xemu-project/xemu#1327]
### bug description 

If xemu crashes during gameplay the save files on the hard disk become corrupted, and you end up needing to create a new hard disk, thus losing all saves for all games. Just wondering if maybe there should be a falesafe of some kind preventing corruption in this instance. 

I was overclocking my ram which led to the crashes, but it still shouldn't corrupt the hard drives save files making the hard drive useless, because even when deleting the save file im still prevented from creating a new one in game. 

### Expected Behavior

Hard drive shouldn't become corrupted

### xemu Version

All versions

### System Information

OS windows 11
CPU 12900k
Gfx card rtx 2060

**Comment by mborgerson** [comment]
Unfortunately, there little that can be done if xemu closes while Xbox software is writing to the disk--like a real Xbox losing power while it is saving. Indeed if you were overclocking your RAM, all bets are off about the state of the application and potential corruption.

To prevent data loss, make a copy of your .qcow2 somewhere, or copy the saves out via FTP, or attach an XMU image (see docs) and copy the saves out via dashboard.

**Comment by jlnhlfan** [comment]
I only lost files for the game that was playing while it crashed.

**Comment by pedroyzkrak** [comment]
This is bullshit. The whole HDD shouldn't be corrupted if it's not writing a save. Again, if it crashes during gameplay the HDD should not be corrupted.

**Comment by BiatuAutMiahn** [comment]
> This is bullshit. The whole HDD shouldn't be corrupted if it's not writing a save. Again, if it crashes during gameplay the HDD should not be corrupted.

https://github.com/xemu-project/xemu/issues/1327#issuecomment-1379377257
