### ISSUE TITLE
Rasperry Pi4 issue

### ISSUE THREAD

**Issue by tlosm** [xemu-project/xemu#133]
Hi i dont know if devs are interested in a rasperry pi compatibility. this is my log after try to build xemu on pi 4 debian buster 32
___
CC      i386-softmmu/hw/xbox/nv2a/debug.o
In file included from /home/pi/src/xemu/include/qemu/osdep.h:37,
                 from /home/pi/src/xemu/hw/xbox/mcpx/apu.c:22:
/home/pi/src/xemu/hw/xbox/mcpx/apu.c: In function ‘is_voice_locked’:
/home/pi/src/xemu/include/qemu/compiler.h:96:36: error: static assertion failed: "not expecting: sizeof(*&d->vp.voice_locked[v / 64]) > ATOMIC_REG_SIZE"
 #define QEMU_BUILD_BUG_MSG(x, msg) _Static_assert(!(x), msg)
                                    ^~~~~~~~~~~~~~
/home/pi/src/xemu/include/qemu/compiler.h:105:30: note: in expansion of macro ‘QEMU_BUILD_BUG_MSG’
 #define QEMU_BUILD_BUG_ON(x) QEMU_BUILD_BUG_MSG(x, "not expecting: " #x)
                              ^~~~~~~~~~~~~~~~~~
/home/pi/src/xemu/include/qemu/atomic.h:133:5: note: in expansion of macro ‘QEMU_BUILD_BUG_ON’
     QEMU_BUILD_BUG_ON(sizeof(*ptr) > ATOMIC_REG_SIZE); \
     ^~~~~~~~~~~~~~~~~
/home/pi/src/xemu/hw/xbox/mcpx/apu.c:451:13: note: in expansion of macro ‘atomic_read’
     return (atomic_read(&d->vp.voice_locked[v / 64]) & mask) != 0;
             ^~~~~~~~~~~
  CC      i386-softmmu/hw/xbox/nv2a/pbus.o
  CC      i386-softmmu/hw/xbox/nv2a/pcrtc.o
make[1]: *** [/home/pi/src/xemu/rules.mak:69: hw/xbox/mcpx/apu.o] Error 1
make[1]: *** Attesa per i processi non terminati....
make: *** [Makefile:569: i386-softmmu/all] Error 2

real	5m17,539s
user	15m26,318s
sys	2m46,839s
___

Ciao 
Luigi

**Comment by mborgerson** [comment]
Thanks for reporting! This and #159 appear to be the same. I'll close this one as the other is tagged now.
