### ISSUE TITLE
Assertion issue.

### ISSUE THREAD

**Issue by RageXbox** [xemu-project/xemu#134]
Figure that out.

**Comment by dracc** [comment]
The assertions are there to assert (surprise surprise!) that the emulator keeps out of trouble by not executing after doing stuff that isn't properly supported yet. It's not an issue, it's a design decision.

**Comment by mborgerson** [comment]
Thanks. These issues can and will be resolved. GitHub issues are typically used to capture more specific information about the problem, closing for lack of info.
