### ISSUE TITLE
https://xemu.app/titles/4d530064/#Halo-2 bugs from main menu to cutscene & gameplay!

### ISSUE THREAD

**Issue by Gareth17andMinnie14** [xemu-project/xemu#1340]
### Title

https://xemu.app/titles/4d530064/#Halo-2

MS-100 [4d530064]

### Bug Description

![Proof of issue 1](https://user-images.githubusercontent.com/122693175/212491582-c5172a23-30de-4d73-8712-11b265c54a95.PNG)
![Proof of issue 2](https://user-images.githubusercontent.com/122693175/212491587-b198f8e9-855f-4fb1-9401-fe70ce740d4b.PNG)
![Proof of issue 3](https://user-images.githubusercontent.com/122693175/212491588-01b4fd46-2bbf-4c6d-91e5-24c1d3172281.PNG)

Found these issues in Halo 2 seems like there is a graphic flicker scrolling down on the scene where we enter high charity & I even notice it on the main menu on the covenant cruiser too which is really irretating, but however its not just that I even notice there is some sort of bug for the gameplay which could effect the entire missions including cutscenes too.

### Expected Behavior

Graphics seem to be flickering on main menu & in the first cutscene until you start to play the game which is already covered, but there is a bug where it is showing the stairs and door when you are doing the tutorial in the first area on cario station when the cutscene is finished for the heratic and moves you into doing your first mission.

### xemu Version

Version:      0.7.76
Branch:       master
Commit:       92b62d942f02362c5ad53039018aba3dd781f54f
Date:         Sat Jan 14 00:09:51 UTC 2023

### System Information

CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
OS Platform: Windows
OS Version: Windows
Manufacturer: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver: 4.0.0 NVIDIA 528.02
Shader: 4.00 NVIDIA via Cg compiler

**Comment by mborgerson** [comment]
Sounds like a duplicate of #740. Hard to know what is meant by flickering from screenshots. I'll close the issue for now. If the issue is truly unique from other reported issues we can re-open.

BTW, no need to include the compat page URL in the issue title, just in the 'Title' section of the issue body.

**Comment by bryc** [comment]
@mborgerson 

I believe this issue is distinct. There is no flickering or black geometry like #740.  It's very apparent in the first two levels. What's happening is that it shows incorrect geometry on top of other geometry, as if geometry bleed through or holes spontaneously appear.

**Comment by callephi** [comment]
Would like to bring attention to this as this seems to be still apparent in the latest xemu `v0.8.11`. I checked on this issue in 2024 as well and the issue existed then. Could be related to NVIDIA cards or drivers or Intel processors, as I myself am also running a 14700k/RTX4080 setup and still facing this.

Seems easier to spot on multiplayer maps, and may be somehow related to z-axis/z-depth rendering in which it incorrectly determines what geometry is visible to the player and gives us this issue.

**Comment by bryc** [comment]
@callephi This is not related to hardware or drivers, happens on AMD too: https://youtu.be/tw9AE28c44Q?t=49

**Comment by Gareth17andMinnie14** [comment]
> [@callephi](https://github.com/callephi) This is not related to hardware or drivers, happens on AMD too: https://youtu.be/tw9AE28c44Q?t=49

You are right about that bryc but a new patch just came out and has fixed the bugs for Halo 2 so now you cannot see through objects and can finally play it without any tech issues, but still the first halo game does have some audio issues really and it's kinda annoying to be honest that it's quiet then goes loud

**Comment by bryc** [comment]
Yeah there's some audio distortion in Halo 2 now that wasn't there before I think? When you get into firefights, the sound clips horribly. Nice to see the geometry fixed though!
