### ISSUE TITLE
AppImage file doesn't start

### ISSUE THREAD

**Issue by VladimirVSC** [xemu-project/xemu#1365]
### Bug Description

1. Make a file executable
2. Start with double-clicking
3. Nothing happens...

### Expected Behavior

Starting file properly.

### xemu Version

xemu 0.7.83

### System Information

OS: LMDE 5
CPU: Core-I5 4430
RAM: 8 Bb
Video: Geforce GTX 760

### Additional Context

It says something about "GLIBC_2.3x" not found when trying to start from the terminal. How to install it and shouldn't it be included into the appimage file by default?

**Comment by VladimirVSC** [comment]
[Appimage glibc bug.txt](https://github.com/xemu-project/xemu/files/10478839/Appimage.glibc.bug.txt)

**Comment by mborgerson** [comment]
Related #1353

**Comment by casasfernando** [comment]
Same issue on Debian 11.
