### ISSUE TITLE
[RalliSport Challenge 2] Performance tanking on a specific time schedule

### ISSUE THREAD

**Issue by Valtekken** [xemu-project/xemu#1367]
### Title

https://xemu.app/titles/4d530039/#RalliSport-Challenge-2

MS-057

### Bug Description

The game's performance operates on a 5 minute time schedule, which means that every 5 minutes the performance tanks for 5 minutes (roughly, it's slightly less than that, let's say 4 minutes and 55 seconds), and after those 5 minutes have elapsed the game's performance returns to playable levels. For reference, the game's FPS counter goes anywhere from 22 to 40+fps when it's in the 5 minutes of playable performance and goes anywhere from 5 to 15+fps when it's in the 5 minutes of tanked performance.

Any CPU or GPU throttling due to thermal issues can be safely excluded, since temperatures hover around the 60°C mark for the CPU and around the 50°C mark for the GPU during gameplay, both in the 5 "playable" minutes and in the 5 "unplayable" minutes.

This is also not track-dependent or vehicle-dependent, seeing as it happens systematically with any car and any track under any time of day/weather condition.

Xemu's priority has been set to "real time" in the Windows scheduler, and the multithread optimizations for the GPU have been disabled in the NVidia Control Panel (as per troubleshooting instructions).

### Expected Behavior

Performance should at least be at a consistent level regardless of any time schedule. If any drops in performance occur I'd expect them to be random, but the fact that they happen on a specific schedule makes me think this is fixable by looking at the right parameters. Maybe it's clock-dependent.

### xemu Version

0.7.83

### System Information

OS: Windows 11 22H2
CPU: AMD Ryzen 5 5600X
GPU: NVidia GTX 970
GPU Driver: 528.02

**Comment by LeRutY** [comment]
I´ve never encountered an issue like this and I´ve played much of it

**Comment by Valtekken** [comment]
> I´ve never encountered an issue like this and I´ve played much of it

Uh, I don't know what to tell you. Want me to provide video proof?

**Comment by Valtekken** [comment]
Okay, I got absolutely nothing. Apparently the new NVidia driver and a reboot fixed the issue. Weird issue in the first place, but I'll take it.
