### ISSUE TITLE
Severe application instability with Intel Iris Xe Graphics

### ISSUE THREAD

**Issue by DukeZilla** [xemu-project/xemu#137]
I'm running xemu on a brand new:

- HP laptop
- Windows 10 x64
- Intel core i7
- 16 GB RAM
- Intel Iris Xe Graphics

The xemu application itself works fine before settings configuration...
Even had the same bios settings as listed. Implemented them, booted xemu back up, and then ran into some problems such as:

- xemu application running very very slow (even after logo boots up.) 
- Receiving black screen when games load up (only hear sounds but no display output.)
- Even ram usage is unusually high. (builds up until application boots up.)

No error messages come up either when these things occur.

I've even tried to install an graphics drivers updater, still didn't fix it.
Tested my laptop with XQemu, and it worked just fine, games are playable too.
I assume this is a problem within the xemu itself being incompatible with my graphics card / drivers, or something else that's
over my head.

Just another error report. 

Thanks.

**Comment by mborgerson** [comment]
Thanks for reporting, there does appear to be an issue with Intel Iris Xe graphics specifically causing severe application instability. Another user has reported this as well. This will need investigation.

**Comment by nex86** [comment]
Its the Windows driver, it just outputs garbage on the screen on boot while the menus become unresponsive. 
It works just fine on Iris Plus under Linux.
Same behavior with Intel HD graphics on 6th or 7th gen CPUs.

**Comment by DukeZilla** [comment]
> 
> 
> Its the Windows driver, it just outputs garbage on the screen on boot while the menus become unresponsive.
> It works just fine on Iris Plus under Linux.
> Same behavior with Intel HD graphics on 6th or 7th gen CPUs.

What do you mean by Windows driver?

**Comment by DukeZilla** [comment]
@mborgerson 

Hey. back with another report...

Been doing some digging through the older builds of xemu, realized that the older builds worked normally.
Managed to track the exact build of when the problems of instability first started occurring, which was:

    build-202010230430 (d6e52a0)

The build before that worked completely fine on my pc and I was able to boot into games, use the application, etc.
This build was named:

    build-202010222020 (f8a6326)

Hope this info helps on tracking down the true source of the problem.

Thanks in advance.

**Comment by nex86** [comment]
> > Its the Windows driver, it just outputs garbage on the screen on boot while the menus become unresponsive.
> > It works just fine on Iris Plus under Linux.
> > Same behavior with Intel HD graphics on 6th or 7th gen CPUs.
> 
> What do you mean by Windows driver?

The issue only occurs on Windows. Its fine on Linux.
I tested it on my GPD Win Max.

So its something they changed in the code that the Intel driver on Windows does not like.

**Comment by mborgerson** [comment]
Hi @DukeZilla,

Have you tried updating your driver recently? Looks like a new version was released last Monday.

https://www.intel.com/content/www/us/en/support/products/205778/graphics/graphics-for-11th-generation-intel-processors/intel-iris-xe-graphics.html

Thanks for your help debugging this.

**Comment by DukeZilla** [comment]
I appreciate your response @mborgerson 

Just updated my drives, still no luck, I believe it has something to do with the change of code from the two previous builds stated.

I don't know how to truly pin point it. But it's between those two builds.

I believe it may have something to do with the memory RAM. When I check task manager the RAM usage goes up exponentially, Though I'm not sure if we're seeing the result of a memory leak...

**Comment by mborgerson** [comment]
Thanks for bisecting and providing info. It does look like some leak, but will require some more investigation.

**Comment by DukeZilla** [comment]
@mborgerson 

Did a bit of research, found out that the memory leak isn't the problem, the memory leak is caused by the initial slowness / freezing of xemu when the emulated xbox is booting, it's a partial leak at first but ends when it unfreezes. Sometimes xemu freezes indefinitely resulting in an endless leak until it's closed.

So memory leak isn't the problem, something is causing my xemu to freeze resulting in a leak.

https://www.youtube.com/watch?v=eu_kTGv61WQ

This video should help understand.

**Comment by mborgerson** [comment]
Hi @DukeZilla @nex86, could you please try running the latest version of xemu on your Windows setup with Iris Plus / Xe? The issue may be resolved now after I fixed some issues affecting other Intel integrated gfx models/drivers.

**Comment by DukeZilla** [comment]
@mborgerson Just downloaded and tested your latest version of xemu as you requested with Halo CE & Smashing Drive, and the emulator performed excellently! Smooth graphics / frame rate, audio is working, & no startup freezes!

What ever you did just did the trick, thanks for the fix!

**Comment by mborgerson** [comment]
Very glad to hear it. Thanks!
