### ISSUE TITLE
Implement portable mode

### ISSUE THREAD

**Issue by ElektroStudios** [xemu-project/xemu#138]
This is a (basic and must-have) feature request:

Please consider to implement portable mode, that is the **xemu.ini** and any other files must be read/written in root directory of **xemu.exe**. 

One easy way for all users to set portable mode probably would be to let them create a "portable.txt" file in the root folder of **xemu.exe**, and then **xemu** should do the magic to recognize the installation as a portable mode. Or through an option in the emulator UI.

I cannot think of a good emulator that is not portable itself or does not provide the user a functionality to make it portable, like PCSX2, RPCS3, Dolphin, Cemu, Citra and of course Cxbx-R just to mention some of them.

I'm in love with **Xemu**'s UI and its functionality but this is a thing that stops me from using it as my main choice instead of others (well, the only other working xbox emulator) because I need emulators to be portable, not to save settings in the user roaming folder like **xemu** does :(

Just please consider this feature request. Thanks in advance.

**Comment by mborgerson** [comment]
Thanks, it is planned.

**Comment by ElektroStudios** [comment]
Thanks to you for your quick reply! and for accepting the request. It would be great if you could provide any ETA for this, although I do not ask for it to be an official time estimation.

Thanks for all your work on this emulator guys.

**Comment by theboy181** [comment]
Instead of making a portable.txt just have it understand it’s portable if the xemu.ini is in the root with the exe.

**Comment by mborgerson** [comment]
@theboy181 Sounds good. Do you want to help do this?

**Comment by ElektroStudios** [comment]
Any E.T.A for this?

**Comment by dracc** [comment]
> Any E.T.A for this?

I haven't heard of anyone actively working on it. A dirty prototype shouldn't take much longer than 20 minutes to throw together if someone has the time and necessary skills.

**Comment by rrrcabral** [comment]
i want that feature too.  just have it understand it’s portable if the xemu.ini is in the root with the exe. 
a lot of people uses emulators in external hdd or other partitions.

**Comment by mborgerson** [comment]
It already exists

Note to future reader: Create a xemu.toml file next to your xemu.exe

**Comment by abaire** [comment]
Note for macOS:

If you put your xemu.toml file within the Contents/Resources directory within the bundle it should work in portable mode. I'm guessing when xemu is signed in the future this would require a re-sign.

You should also be able to open the bundle using open and pass [command line arguments](https://xemu.app/docs/cli/) with the --args param: open xemu.app --args -config_path xemu.toml
