### ISSUE TITLE
SpongeBob SquarePants: BFBB: pgraph_render_surface_to_texture assertion

### ISSUE THREAD

**Issue by irllzrd** [xemu-project/xemu#140]
In Spongebob: Battle for Bikini Bottom, assertion error in pgraph.c occurs in function pgraph_render_surface_to_texture when you use the X/Y button bubble-bash and bubble-stomp moves. Removing assert(glGetError() == GL_NO_ERROR) from pgraph_render_surface_to_texture and rebuilding shows the specific error is GL_INVALID_FRAMEBUFFER_OPERATION. It occurs multiple times during the moves, and ends when the bubble models disappear. The game continues to be very playable.

The bubble foot/helmet model generated may use a framebuffer as a texture to show a 'reflection' of the world around it. I tried moving the assert around to pinpoint where the errors begin, but it seems to start right on function call. 

Titles: 5451001a

**Comment by medievil1** [comment]
```GL_INVALID_FRAMEBUFFER_OPERATION is generated if the specified read and draw framebuffers are not framebuffer complete. ```

**Comment by Triticum0** [comment]
It seems that Batman: Rise Of Sin Tzu(https://xemu.app/titles/5553001c/#Batman-Rise-of-Sin-Tzu) also hit the same assertion even though it gives the assertion: Bail out! ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:3671:pgraph_gl_sync: assertion failed: (epoxy_glGetError() == 0)  looking at the assertion on github commit it give this: https://github.com/mborgerson/xemu/blob/b9df39749346d83ebd3be8884ead5c75fdb8261f/hw/xbox/nv2a/pgraph.c#L3668-L3671 So I think it should go hear but feel free to correct me if I'm wrong.

**Comment by antangelo** [comment]
Seems this assertion failure is different in newer versions. #635 tracks the current assertion failure message.

**Comment by abaire** [comment]
If this is no longer valid and #635 tracks the new issue, can we close this bug?
