### ISSUE TITLE
Can't load games with apostrophes in filenames from xemu.toml

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#1401]
### Bug Description

When parameters are read from xemu.toml that includes filenames with apostrophes an error is generated.
Example:  
dvd_path = 'C:\roms\xbox\Oddworld - Stranger's Wrath (USA).xiso.iso'

![Screenshot 2023-02-23 225719](https://user-images.githubusercontent.com/26314088/221039790-0116d3da-6eaf-4741-b9ae-ada1605ed15c.png)

### Expected Behavior

Xemu should load games with any filename accepted by the OS.

### xemu Version

0.7.84, commit d8fa50e524c22f85ecb2e43108fd6a5501744351

### System Information

CPU:          Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
Driver:       4.0.0 NVIDIA 528.49
Shader:       4.00 NVIDIA via Cg compiler

**Comment by mborgerson** [comment]
You must escape the apostrophe properly. See [toml spec](https://toml.io/).
