### ISSUE TITLE
Crazy Taxi 3: High Roller - Assertion failed shaders.c line 509 (v0.7.85) during post title screen sequence

### ISSUE THREAD

**Issue by ehw** [xemu-project/xemu#1404]
### Title

https://xemu.app/titles/53450004/#Crazy-Taxi-3-High-Roller
Crazy Taxi 3 - High Roller (USA)
SE-004 [53450004]

### Bug Description

Xemu hangs with an "Assertion failed!" message at a specific spot during the post title screen movie. A screenshot of the error and the specific scene can be found below.

To reproduce:
1.) Start the game
2.) When the title screen appears, do not press START.
3.) Let the intro movie play, it will get to a certain part sometime after Gus' intro and spawn an "Assertion failed" with shaders.c

### Expected Behavior

The expected behavior can be seen in the following part of this long play:
https://youtu.be/ScoVqj5GOuo?t=91

### xemu Version

Version:      0.7.85
Branch:       master
Commit:       065c74a00fe402f65147e9b0d1a1eeac1b4b609f
Date:         Mon Mar  6 21:06:28 UTC 2023

Last working: Unknown

### System Information

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 531.26
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

![image](https://user-images.githubusercontent.com/885618/224508292-bffc5814-17ab-4f93-8002-f2521d1db6c4.png)
![image](https://user-images.githubusercontent.com/885618/224508297-f284e702-e906-43df-a8d5-97240d436e74.png)
3

**Comment by Triticum0** [comment]
dupe of  #379

**Comment by ehw** [comment]
This is fixed as of v0.7.101.
