### ISSUE TITLE
Xemu Discord problem.

### ISSUE THREAD

**Issue by DimMan88** [xemu-project/xemu#1406]
### Bug Description

Hello

I opened a ticket because I wasn't able to communicate with you in other way.

I am banned from discord server a long time ago (1 year +) without any warning or reason explained. 

My discord username is "DimMan88".

Please can you take a look and if you can to lift the ban? I don't know what I did wrong. 

Maybe unintentionally broke a rule. **It won't happen again.**

**Thank you very much.** 

### Expected Behavior

-

### xemu Version

-

**Comment by mborgerson** [comment]
Ban for Rule 1 violation. I'll lift the ban, but please read and follow the rules.

**Comment by DimMan88** [comment]
Thank you!
