### ISSUE TITLE
ESPN NHL 2K5: Assertion Failed!

### ISSUE THREAD

**Issue by jlnhlfan** [xemu-project/xemu#1413]
### Title

https://xemu.app/titles/53450032/#ESPN-NHL-2K5

Game version unknown

### Bug Description

While the game is loading, this error message involving the Microsoft Visual C++ Runtime Library opens in front of the game window:

Assertion failed!

Program: G:\6\xemu-win-release\xemu.exe
file: ../hw/xbox/mcpx/dsp/dsp_emu.inl
Line: 40

Expression: false

For more information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

Pressing Retry actually crashes the entire emulator, and I am not sure why this only started happening now. It didn't happen earlier today (or yesterday, depending on when this gets read). What is there I can do to try and fix the issue, or is an update needed to fix the problem?

![Screenshot_March_26_2023_10_56_55_PM](https://user-images.githubusercontent.com/31529087/227855432-9c61ec5a-0c74-45c0-bd18-3afe75ec88f0.png)

### Expected Behavior

The game is supposed to load without the error in front of it, as shown here.
![xemu-2023-03-26-10-54-03](https://user-images.githubusercontent.com/31529087/227856567-f3b09396-663d-4d22-a25d-ff31b850d956.png)

### xemu Version

Version:      0.7.86
Branch:       master
Commit:       4a99fd0f1855fc52e15885812abd3ee4bb2b3847
Date:         Mon Mar 27 05:23:17 UTC 2023

The last version the game worked in was the version before this one.

### System Information

CPU:          Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
OS Platform:  Windows
OS Version:   Windows 10
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1650/PCIe/SSE2
Driver:       4.0.0 NVIDIA 527.56
Shader:       4.00 NVIDIA via Cg compiler

**Comment by antangelo** [comment]
Disable surround sound, or delete your EEPROM and have xemu generate a new one

**Comment by jlnhlfan** [comment]
Deleting the EEPROM worked. Thank you for the fix. :)
