### ISSUE TITLE
Wrong version number in macOS download 0.7.86

### ISSUE THREAD

**Issue by suschizu** [xemu-project/xemu#1414]
### Bug Description

The `info.plist` s version notation doesn't contain the displayed version number (https://github.com/xemu-project/xemu/releases/latest/download/xemu-macos-universal-release.zip):

```
 <key>CFBundleShortVersionString</key>
  <string>1</string>
  <key>CFBundleSignature</key>
  <string>xemu</string>
  <key>CFBundleVersion</key>
  <string>1</string>
```
 

### Expected Behavior

shortVersionString should be 0.7.86 not 1

### xemu Version

0.7.86

### System Information

macOS
download: https://github.com/xemu-project/xemu/releases/latest/download/xemu-macos-universal-release.zip

**Comment by Florin9doi** [comment]
Dup #1344

**Comment by suschizu** [comment]
yes I know … nothing has changed unfortunately :/

**Comment by mborgerson** [comment]
@suschizu No need to keep filing issues until whatever it is gets fixed... If the issue is open then it's likely not fixed yet. Feel free to send a PR to fix the issue
