### ISSUE TITLE
PPA needs to be updated for Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by StianOby** [xemu-project/xemu#1425]
### Bug Description

After upgrading to Ubuntu 23.04 (Lunar Lobster) I get the following output when running sudo apt update:
`Err:11 http://ppa.launchpad.net/mborgerson/xemu/ubuntu lunar Release                                                   
  404  Not Found [IP: 185.125.190.52 80]`

It appears that the PPA simply hasn't been updated to include a build for 23.04 (Lunar Lobster).

### Expected Behavior

Running `sudo apt update` should not throw a 404 error.

### xemu Version

N/A

**Comment by mborgerson** [comment]
Added Lunar to the PPA. Build is pending. Thanks
