### ISSUE TITLE
counter strike: menu does not render on linux

### ISSUE THREAD

**Issue by sylveonsylvia** [xemu-project/xemu#1427]
### Title

https://xemu.app/titles/4d530036/#Counter-Strike

version 1.0

### Bug Description

the main menu does not render at all

![image](https://user-images.githubusercontent.com/78629289/236074706-023ab424-fca7-485c-8ef1-a840137d0046.png)

however the intro videos and attract mode video do render 
![image](https://user-images.githubusercontent.com/78629289/236074871-a9e08f05-e26c-4637-9503-266bcb99517c.png)

### Expected Behavior

the menu to render 

### xemu Version

Version:      0.7.86

does not happen in the windows version of xemu 

### System Information

 OS: Arch Linux x86_64
 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD Radeon RX 6600XT 
Mesa version: Mesa 23.0.3

**Comment by jyetcv** [comment]
This bug was fixed at some point, for me at least.

**Comment by mborgerson** [comment]
@sylveonsylvia can you confirm this is not longer an issue for you?

**Comment by sylveonsylvia** [comment]
yea seems to be fixed for me aswell
