### ISSUE TITLE
Small lines/bars on the Left + Top sides of the window in all games

### ISSUE THREAD

**Issue by xXRaptorSc0pezXx** [xemu-project/xemu#1436]
### Bug Description

On every game I've tested Xemu with I always get these annoying small bars on the left and usually also the top of the window (see attached screenshots. You may have to view them in fullscreen). This bug occurs in both windowed and fullscreen mode and it occurs regardless of what the internal resolution scale is set to. When I asked on the Discord, someone linked this Pull Request: https://github.com/xemu-project/xemu/pull/1362 which may or may not be related.
![Screenshot 2023-05-16 095328](https://github.com/xemu-project/xemu/assets/123332042/5f4626ac-4074-4412-89cb-f450686e32c4)
![Screenshot 2023-05-16 095311](https://github.com/xemu-project/xemu/assets/123332042/2c907048-4f06-4e4b-aa2b-7c105452e40d)

### Expected Behavior

Expected behavior would be for Xemu to just run games properly without the small lines/bars at the side.

### xemu Version

Latest version at time of posting which is Version: 0.7.89

### System Information

OS: Windows 11
GPU: NVIDIA RTX 3080 12GB
CPU: Intel i7-12700k

**Comment by antangelo** [comment]
Duplicate of #1256
