### ISSUE TITLE
Unable to start with raw disk image.

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1444]
### Bug Description

Xemu wont start with raw disk image.
It's only displayed BIOS splash screen and then freezed.

Disk image was created using dd:
`sudo dd if=/dev/zero of=ogxhdd.img bs=1 count=0 seek=8G`

Here's the terminal log:
```
WARNING: Image format was not specified for '/home/iza/Documents/XEMU FILES/ogxhdd.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```

So, I've added `raw` parameter to `qemu`:
`xemu-v0.7.90-x86_64.AppImage -drive format=raw,file='/home/iza/Documents/XEMU FILES/ogxhdd.img'`

But, still failed but with new error:
```
WARNING: Image format was not specified for '/home/iza/Documents/XEMU FILES/ogxhdd.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
xemu-v0.7.90-x86_64.AppImage: Failed to get "write" lock
Is another process using the image [/home/iza/Documents/XEMU FILES/ogxhdd.img]?
```

Understandable, as multiple process accessing that `ogxhdd.img` file.

So, what am I suppossed to do to use raw disk image on `xemu`?
I'm thinking about passing external config (toml?) but can't found a docs about it.

Thanx.

### Expected Behavior

Xemu boot raw disk image normally.

### xemu Version

0.7.90

### System Information

```
iza@5060:~$ uname -a
Linux 5060 6.3.2-1-default #1 SMP PREEMPT_DYNAMIC Mon May 15 15:59:38 UTC 2023 (70ea6f6) x86_64 x86_64 x86_64 GNU/Linux
iza@5060:~$ inxi -CG
CPU:
  Info: 6-core model: Intel Core i5-8400 bits: 64 type: MCP cache: L2: 1.5 MiB
  Speed (MHz): avg: 1466 min/max: 800/4000 cores: 1: 2800 2: 800 3: 2800
    4: 800 5: 800 6: 800
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Navi 24 [Radeon RX 6400/6500 XT/6500M] driver: amdgpu
    v: kernel
  Device-3: Sunplus Innovation Full HD webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: x11 server: X.org v: 1.21.1.8 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: radeonsi,iris gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 6400 (navi24 LLVM
    16.0.2 DRM 3.52 6.3.2-1-default)
```

### Additional Context

I'm trying to use raw disk image as currently using btrfs on openSUSE. 
It's known that CoW image performance is poor in btrfs as it's also a CoW filesystem.

**Comment by antangelo** [comment]
FWIW I have not had any issues with qcow2 on btrfs myself (without disabling CoW). If you are concerned you can use `chattr +C <harddisk.qcow2>` to disable btrfs' CoW on that file.

I am not in a position to say that raw images are strictly unsupported, but know that the warning exists for good reason, and you are still better off using qcow2.

Also note that the `raw` option that you have supplied (by passing an additional `-drive` parameter) is conflicting with the arguments that xemu itself is setting up, which is why you are seeing write lock errors. Without changing how xemu sets up this argument (e.g. by detecting that a drive was specified manually and omitting its own), this will not work.

**Comment by GXTX** [comment]
Don't worry about the warning. I only use raw images and have never had an issue with it.

```
 xemu-v0.7.90-x86_64.AppImage -drive format=raw,file='/home/iza/Documents/XEMU FILES/ogxhdd.img'
[...]
xemu-v0.7.90-x86_64.AppImage: Failed to get "write" lock
Is another process using the image [/home/iza/Documents/XEMU FILES/ogxhdd.img]?
```

Don't manually attach the drive, use the GUI for it.
