### ISSUE TITLE
Play splitted xiso

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1449]
### Feature Request

It would be nice if xemu can play splitted xiso by selecting the first image.
As for now, I'll get "It may be dirty or damage" error when doing that.

Thank you.

### Alternatives

Rejoin the splitted xiso.

### Additional Context

Booting xiso directly from ogxbox's disk is now preferred methods to boot a game.
If the xiso is bigger than 4+ GB it's need to be splitted to obey FATX limitation.

I mostly keep that splitted (along with another) image on my computer so I don't have to redo conversion/extraction from redump when I need it.

**Comment by GXTX** [comment]
This sounds like a feature of a kernel you're using rather than the Xbox itself. You can do this already by transferring the game to the virtual drive and launching it as you would normally on your Xbox.

**Comment by rizaumami** [comment]
It is a kernel's feature, and probably with supported BIOS (Cerbios or patched M8+) it's doable to do that.
But, transfering the game to the virtual disk requires more steps compared to just clicking `Machine -> Load Disc (CTRL+O)`

**Comment by GXTX** [comment]
`Load Disc` is loading "disc" into the DVD drive and presenting it to the Xbox, if your kernel supports split games via the DVD drive then it should work similarly.

**Comment by mborgerson** [comment]
Sorry, I don't plan to support this use case. If you really want it and are willing to submit a patch I'll consider it. But really, I recommend just splitting the images when you deploy them to your Xbox and leaving them whole otherwise
