### ISSUE TITLE
xemu can't boot fatxfs formatted disk image

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1450]
### Bug Description

Getting `Service required. Call Customer support.` error when using [`fatxfs`](https://github.com/mborgerson/fatx) formatted disk.

Steps to reproduce this issue:
1. Create a raw disk image
   ```sh
   sudo dd if=/dev/zero of=ogxhdd.img bs=1 count=0 seek=8GB
   sudo chown $USER:$USER ogxhdd.img
   ```
2. Format it using `fatxfs`
   ```sh
   sudo losetup loop0 ogxhdd.img
   sudo fatxfs /dev/loop0 --format=retail --destroy-all-existing-data
   sudo losetup -d /dev/loop0
   ```
3. Boot as `xemu` disk image

### Expected Behavior

`xemu` booting disc normally even with empty disk image. 

### xemu Version

`xemu_version: 0.7.92`

### System Information

```
iza@5060:~$ inxi -CG
CPU:
  Info: 6-core model: Intel Core i5-8400 bits: 64 type: MCP cache: L2: 1.5 MiB
  Speed (MHz): avg: 3800 min/max: 800/4000 cores: 1: 3800 2: 3800 3: 3800
    4: 3800 5: 3800 6: 3800
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: AMD Navi 24 [Radeon RX 6400/6500 XT/6500M] driver: amdgpu
    v: kernel
  Device-3: Sunplus Innovation Full HD webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: x11 server: X.org v: 1.21.1.8 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: radeonsi,iris gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 6400 (navi24 LLVM
    16.0.4 DRM 3.52 6.3.4-1-default)
```

### Additional Context

Using [`fatxfs`](https://github.com/mborgerson/fatx) I can now conveniently format (?), mount, read, and write to FATX disk.
I've never tried to format ogxbox real disk, but raw disk image above can't be booted by xemu.
I can mount its C and E partition, copy some dashboard's file, but still get the error. 

`xemu` can play game from the disc after I "prepare" the raw disk image using [`xboxdumper`](https://github.com/ldotsfan/xboxdumper):
```
xboxdumper' prepare xhdd.img 0
```

**Comment by GXTX** [comment]
Once you format your drive, you'll need to add the required dashboard files. If you attempt to boot an Xbox with an empty HDD you'll get the same error on hardware.

**Comment by rizaumami** [comment]
It seems that `xemu` doesn't need any file at all. Yes, I can't boot to the disk.
The `xboxdumper`'s prepared disk also empty, and `xemu` can boot the disc (iso games) just fine.

Is it "table partition" thing?

**Comment by GXTX** [comment]
> Is it "table partition" thing?

This is a scene created thing for extended partitions, unneeded for your use case.

Your problem is you don't have the dashboard files, some games check for this with the dashboard updater, and others require the Xbox Live files to be present. So the fix for you is to use fatxfs to put the required dashboard files in `C:\`.

**Comment by rizaumami** [comment]
I think have found the culprit.
Probably because I've formatted the loop device (where disk is mounted).
[Seems like `fatxfs` can directly format (flat) raw disk image](https://github.com/mborgerson/fatx/issues/39).

Quick test shows that `xemu` can boot the game disc just fine if I format the disk directly.

```
sudo dd if=/dev/zero of=xhdd.img bs=1 count=0 seek=8G
sudo chown $USER:$USER xhdd.img
sudo .local/bin/fatxfs xhdd.img --format=retail --destroy-all-existing-data
```

I'll close this issue as resolved.
Thanx for your time.
