### ISSUE TITLE
libc.so.6: version `GLIBC_2.XX' not found

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1451]
### Bug Description

Getting error when running `xemu` on Linux Mint Debian Edition 5 (based on Debian 11).

```
iza@lmde:~$ ./xemu-v0.7.92-x86_64.AppImage
./xemu-v0.7.92-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./xemu-v0.7.92-x86_64.AppImage)
./xemu-v0.7.92-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./xemu-v0.7.92-x86_64.AppImage)
./xemu-v0.7.92-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./xemu-v0.7.92-x86_64.AppImage)
./xemu-v0.7.92-x86_64.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./xemu-v0.7.92-x86_64.AppImage)
...
```

Seems like `xemu` was build on newer `libc` than what's on Debian 11.

```
iza@lmde:~$ ldd --version
ldd (Debian GLIBC 2.31-13+deb11u6) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

If possible, please compile `xemu` against previous Debian or oldest supported Ubuntu LTS.

### Expected Behavior

`xemu` run normally.

### xemu Version

`xemu_version: 0.7.92`

### System Information

```
iza@lmde~$: inxi -xxS
System:    Host: lmde Kernel: 6.0.0-0.deb11.2-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: Cinnamon 5.6.8 
           tk: GTK 3.24.24 wm: muffin dm: LightDM Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 
```

### Additional Context

Some distros (Debian, Ubuntu LTS, etc) has a long release life. If possible, please support these kind of distros. We can manually copy the latest `mesa` binary and rebuild `xemu.AppImage`, but can't do that with `libc` as it's probably statically linking hundreds of libs at its compile time.

**Comment by dracc** [comment]
There's been five point releases to Debian since your installation (11.2 -> 11.7), please consider updating.

**Comment by rizaumami** [comment]
This is LMDE, A Linux Mint take on Debian distribution. As of now, it's based on Debian 11.2.
According to [this](https://packages.debian.org/bullseye-updates/libc6), Debian 11.7 `libc` version is still at 2.31.

**Comment by antangelo** [comment]
To my knowledge we support Ubuntu LTS versions under standard support (as per https://ubuntu.com/about/release-cycle, this is currently Ubuntu 20.04). You can build from source as an alternative.

**Comment by mborgerson** [comment]
Duplicate #1365 cause #1353
