### ISSUE TITLE
So... any sign of making xemu work on a Chromebook (which uses linux)?

### ISSUE THREAD

**Issue by MesaBlack** [xemu-project/xemu#1464]
### Feature Request

![Screenshot 2023-06-20 6 03 12 PM](https://github.com/xemu-project/xemu/assets/132141735/f5ac1b54-3e2e-463a-b392-5f5d09528cc0)

### Alternatives

N/A at the moment

### Additional Context

I tried putting the starting installing code in "penguin" and it doesn't work...

**Comment by mborgerson** [comment]
It does work, according to a user on Discord who shared this: https://www.youtube.com/watch?v=Mm2jI9w2j80

**Comment by MesaBlack** [comment]
But I started by putting in the add apt repo line
and it doesn't work...

**Comment by dracc** [comment]
Not all Linux distributions are created equal. What you're trying to run looks like a Ubuntu thingy.
Consider compiling xemu from source instead.

**Comment by HadetTheUndying** [comment]
You can install Flatpak on ChromeOS. That's what I would recommend

**Comment by MesaBlack** [comment]
aight

**Comment by HadetTheUndying** [comment]
> aight

In case you're not sure where to get started

https://flatpak.org/setup/Chrome%20OS

**Comment by MesaBlack** [comment]
Uh I think I loaded the hdi and xemu can't open...

**Comment by MesaBlack** [comment]
nvm
