### ISSUE TITLE
How to use keyboard as a keyboard?

### ISSUE THREAD

**Issue by rizaumami** [xemu-project/xemu#1469]
### Bug Description

On real hardware, when I'm plugging-in a keyboard then it's act as a keyboard.
But on `xemu`, keyboard is mapped as a gamepad.

I'm using real ogxbox controller (with adapter) as gamepad and want to use keyboard as a keyboard to input text. How can I do that?

Thanx.

### Expected Behavior

When selecting keyboard as an input I can use it as a keyboard to input text.

### xemu Version

v0.7.96

**Comment by BiatuAutMiahn** [comment]
Looks like this would be a pull request to implement a keyboard option as an input selection, and make the current profile 'Emulated X-Pad' or something

**Comment by mborgerson** [comment]
Currently the UI only lets you select input devices that control an emulated Xbox controller. In the future, you will also be able to select other emulated devices, but for now it is kept simple for the common case.

That said you can attach an emulated keyboard by using the monitor with `device_add` command and the `usd-kbd` device
