### ISSUE TITLE
Objects - like enemies - are rendered through walls

### ISSUE THREAD

**Issue by svensvond** [xemu-project/xemu#1475]
### Bug Description

Enemies can be seen through walls in games like Ghost Recon Advanced Warffighter for example - which renders these games as unplayable. Seems to be a larger issue.

![vMVmAZAE9U](https://github.com/xemu-project/xemu/assets/37634123/e8261b78-3700-4d69-a5f4-a75af4fe72a0)

### Expected Behavior

cannot be seen through 

### xemu Version

all till current 0.7.98

**Comment by mborgerson** [comment]
Duplicate #1437 #1016 #749 

You can find the issue listed already on the title compat page: https://xemu.app/titles/55530054/#Tom-Clancy-s-Ghost-Recon-Advanced-Warfighter
