### ISSUE TITLE
adding keyboard emulation support for Steel Battalion Line of Contact controller

### ISSUE THREAD

**Issue by cloudslsw** [xemu-project/xemu#1477]
### Feature Request

to get the game bypass to menu it need a Steel Battalion Line of Contact controller, or game will prompt controller isnt pluged, due to traditional duke/x360/one/series controller lack of buttons to play this game, can devs make a keyboard patch for this game to emulate and mapping the Steel Battalion Line of Contact controller?

**Comment by mborgerson** [comment]
Duplicate #389
