### ISSUE TITLE
On macOS, crashes instantly on opening.

### ISSUE THREAD

**Issue by veselle** [xemu-project/xemu#1479]
### Bug Description

On opening Xemu on macOS (A Mac Pro, from 2010, running macOS 12.6.7), the app crashes instantly.
![image](https://github.com/xemu-project/xemu/assets/16509978/9faa28d9-52b0-495b-9674-8a9ac167f6cb)

I dual boot with Windows, and Xemu opens fine there.

### Expected Behavior

The app should open.

### xemu Version

Any version, whether from the website, from source, or previous releases.

### System Information

OS: macOS Monterey Version 12.6.7
CPU: 2 x 3.46 GHz Quad-Core Intel Xeon
GPU: AMD Radeon RX 590 8 GB

### Additional Context

The crash log from Console.app:
[xemu-2023-07-15-182259.txt](https://github.com/xemu-project/xemu/files/12062980/xemu-2023-07-15-182259.txt)

**Comment by veselle** [comment]
Building from source with `-march=native instead of -march=ivybridge` fixes the issue.

**Comment by mborgerson** [comment]
I'll close the issue in favor of #1485 (don't hardcode IvyBridge in build.sh) and #1492 (warn on unimplemented instruction, which was the cause of this issue)
