### ISSUE TITLE
[Mercenaries][Destroy All Humans! 2] UI focusing issue

### ISSUE THREAD

**Issue by arozock** [xemu-project/xemu#148]
When the game displays UI over the main game window, it will cause xemu to focus and resize the screen to the UI component

Video demonstration:
[Destroy All Humans! 2](https://www.youtube.com/watch?v=WJv7FgA5cpg)
[Mercenaries](https://www.youtube.com/watch?v=ZGmQeE7cNrY)

Titles: 54510106, 4c410015

**Comment by dozz-a** [comment]
Also happens in Dungeons and Dragons Heroes [49470013] when entering the inventory.

**Comment by Triticum0** [comment]
This is link to #312

**Comment by dozz-a** [comment]
This issue is fixed in Dungeons and Dragons Heroes for newer builds (tested on 0.5.4-28-gcc6d19e099)!
