### ISSUE TITLE
Windows 7 PSA

### ISSUE THREAD

**Issue by insaneninja117** [xemu-project/xemu#1482]
### Bug Description

With XEMU 0.7.99 and the merge of QEMU v7.2.4 the emulator will no longer launch on Windows 7, erroring out from the missing api-ms-win-core-path-l1-1-0.dll.

Using https://github.com/nalexandru/api-ms-win-core-path-HACK allowed XEMU to launch normally and continue working. I don't expect this to be fixed given the status of Windows 7 but this is just for user/dev information if anyone still wanted to use this on Win 7.

### Expected Behavior

XEMU should launch without issue (this is just for the template's sake)

### xemu Version

0.7.99

**Comment by ratkosrb** [comment]
Let's link the last functional release.
https://github.com/xemu-project/xemu/releases/tag/v0.7.98

Also unfortunate that the drop of support for the OS wasn't taken into account in the previous release, to have the auto update say you are on the last version to support your computer if running on Windows 7, instead of telling you there's a new update like normal, and downloading a version that won't run anymore.

**Comment by mborgerson** [comment]
Thanks for the report, nice to see the workaround for Windows 7 users. We should probably mention it on the website.

@ratkosrb 

> Also unfortunate that the drop of support for the OS wasn't taken into account in the previous release, to have the auto update say you are on the last version to support your computer if running on Windows 7, instead of telling you there's a new update like normal, and downloading a version that won't run anymore.

I agree it would be nice if the updater was smarter and not update to something that won't work for you. However, I don't have the bandwidth to personally test and guarantee xemu will run on unsupported operating systems. If you want volunteer to help test PRs to discover issues like this for pre-release announcements, that would be appreciated.

**Comment by mborgerson** [comment]
Added a mention on the website. Closing issue now.

**Comment by insaneninja117** [comment]
Just an update given the recent uptick in activity and the merger of QEMU v9.2.0, 

XEMU still runs on Windows 7 as of v0.8.15, only needing the api-ms-win-core-path-l1-1-0.dll to be present alongside xemu.exe. This can either be taken from the link found in my opening post or from a Windows 8 beta build, both do the job.

The only loss of functionality I can see from running on Windows 7 at the moment is that trying to switch to Vulkan results in an immediate crash and sometime around v0.7.122-123 I lost the ability to have MSI Afterburner running at the same time as XEMU.

**Comment by wrobby493-cell** [comment]
Be strong in any situation you are going through know that many people go through the same problems almost every day. I’m happy to announce my finding of solutions for recovering my money from these crooks. If you’ve been ripped off email recoveryexpert326 at gmail dot com I was in the same shoes also and know how it feels to be ripped off by someone you trusted with your investment They take no upfront payment  Just email this recovery agent and thank me later God bless you and stay safe
