### ISSUE TITLE
Found possible source of "Intel Iris Xe instability".

### ISSUE THREAD

**Issue by DukeZilla** [xemu-project/xemu#149]
Hey. back with another report...

Been doing some digging through the older builds of xemu, realized that the older builds worked normally.
Managed to track the exact build of when the problems of instability first started occurring, which was:

- build-202010230430 (d6e52a0)

The build before that worked completely fine on my pc and I was able to boot into games, use the application, etc.
This build was named:

- build-202010222020 (f8a6326)

Hope this info helps on tracking down the true source of the problem.

Thanks in advance.

**Comment by Ernegien** [comment]
Possibly worth closing and responding to the original [issue](https://github.com/mborgerson/xemu/issues/137) instead.

**Comment by DukeZilla** [comment]
Thats reasonable, thanks
