### ISSUE TITLE
Player get stuck in ground Halo CE

### ISSUE THREAD

**Issue by ludd98** [xemu-project/xemu#1515]
### Title

https://xemu.app/titles/4d530004/#Halo-Combat-Evolved

### Bug Description

When falling from high height player get stuck and can not move. After letting the controller (stck) reset o idle position, and try to move again player moves normaly again

Steps
1. Star game
2. Start a map
3. Jump from high height
4. Try ro move, without letting controll stick reset

### Expected Behavior

Player should not get stuck in ground

### xemu Version

Version:      0.7.111
Branch:       master
Commit:       edecb41b9723d680f8e6ed87a8f709b8db6ca32f
Date:         Wed Aug  2 07:59:57 UTC 2023

### System Information

CPU:          AMD Ryzen 5 4600G with Radeon Graphics
OS Platform:  Windows
OS Version:    22H2
Manufacturer: ATI Technologies Inc.
GPU Model:    AMD Radeon(TM) Graphics
Driver:       4.0.0 Core Profile Context 23.7.1.230626
Shader:       4.60

**Comment by mborgerson** [comment]
Can you give more details please. What version of the game? How exactly can the issue be reproduced? Maybe a video of the issue? Have you confirmed this doesn't happen on a real Xbox?

**Comment by ludd98** [comment]
I will try to record a video of the behaviour when I get access to my computer again, and will check the version number.
I dont have access to a working real xbox to test with. 
I will update here at a later date.

**Comment by StianOby** [comment]
A video would be useful here. In Halo CE, jumping from heights without crouch landing will lead to getting "stuck" for a couple of seconds (and potentially also fall damage). In other words, what you are experiencing may be intended behavior, provided you are only stuck for a second or two.

**Comment by ludd98** [comment]
I did have some time now to test this more. And this is intendet behavior. The "stuck" is only for a second or two as described above.
