### ISSUE TITLE
Silent Crash on Startup

### ISSUE THREAD

**Issue by SunRobin-sudo** [xemu-project/xemu#1520]
### Bug Description

After I configured my settings I lost the ability to open xemu again where it would briefly open up, but close. The timing would vary though. I tried the CFG fix that someone suggested before, but it's not working on my computer even after I redownloaded xemu and restarted my computer.
1. Launch xemu
2. Configure settings
3. Restart xemu

### Expected Behavior

Xemu should open as normal after reconfiguring settings.

### xemu Version

Last working in Version 0.7.111

### System Information

OS: Windows 11
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Comment by dracc** [comment]
Try creating an empty file named `xemu.toml` right next to `xemu.exe`. You should be asked to set up xemu again. Pay extra attention to what file goes where - read the ["Required Files" page](https://xemu.app/docs/required-files/) again to make sure you don't mix them up.

**Comment by SunRobin-sudo** [comment]
It created the empty file, but when I tried opening xemu again it just creates another text document.

**Comment by SunRobin-sudo** [comment]
This is the text file you were talking about
Created QEMU launch parameters: F:\Roms\Xbox\xemu.exe -machine xbox,kernel-irqchip=off,avpack=hdtv -device smbus-storage,file=C:\Users\Triumphant King\AppData\Roaming\xemu\xemu\eeprom.bin -bios F:\Roms\Xbox\Blinx - The Time Sweeper (USA) (En,Ja) (Rev 1).xiso.iso -m 64 -drive index=0,media=disk,file=F:\Roms\Xbox\Blinx - The Time Sweeper (USA) (En,,Ja) (Rev 1).xiso.iso,locked=on -drive index=1,media=cdrom,file= -display xemu -device usb-hub,port=1,ports=4 -audiodev none,id=snd0 
xemu_version: 0.7.111
xemu_branch: master
xemu_commit: edecb41b9723d680f8e6ed87a8f709b8db6ca32f
xemu_date: Wed Aug  2 07:59:57 UTC 2023
xemu_settings_get_base_path: base path: C:\Users\Triumphant King\AppData\Roaming\xemu\xemu\
xemu_settings_get_path: config path: C:\Users\Triumphant King\AppData\Roaming\xemu\xemu\xemu.toml
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
OS_Version:  21H2
GL_VENDOR: Intel
GL_RENDERER: Intel(R) UHD Graphics 620
GL_VERSION: 4.0.0 - Build 26.20.100.7926
GL_SHADING_LANGUAGE_VERSION: 4.00 - Build 26.20.100.7926
WARNING: Image format was not specified for 'F:\Roms\Xbox\Blinx - The Time Sweeper (USA) (En,Ja) (Rev 1).xiso.iso' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
F:\Roms\Xbox\xemu.exe: Some ROM regions are overlapping
These ROM regions might have been loaded by direct user request or by default.
They could be BIOS/firmware images, a guest kernel, initrd or some other file loaded into guest memory.
Check whether you intended to load all this guest code, and whether it has been built to load to the correct addresses.

The following two regions overlap (in the memory address space):
  xbox.mcpx (addresses 0x00000000ba990000 - 0x0000000100000000)
  xbox.bios (addresses 0x00000000ff000000 - 0x0000000144670000)

**Comment by SunRobin-sudo** [comment]
I'm having trouble implementing the empty file. Every time I create it and I try to open xemu, it just creates another file instead and crashes.

**Comment by SunRobin-sudo** [comment]
I found out what the problem was. I had the hard disk image and bios set to the wrong file, but because the file was still on my computer Xemu kept crashing, so I deleted the file and xemu is working properly thanks.
