### ISSUE TITLE
Halo 2 (PAL version, French) : graphics problem

### ISSUE THREAD

**Issue by diabolik26** [xemu-project/xemu#1523]
### Title

https://xemu.app/titles/4d530064/#Halo-2 but in PAL version (French)

### Bug Description

The start of the "sacred icon" mission works fine (as well as all previous missions) but at some point the graphics (colors and textures) turn black, except for the player's weapon and indicators

![xemu-2023-08-16-17-30-26](https://github.com/xemu-project/xemu/assets/141806635/e1752bac-5c55-4c83-a035-9931b61f11b7)
![xemu-2023-08-16-17-30-32](https://github.com/xemu-project/xemu/assets/141806635/86ee8aa5-c7c5-4734-81bb-b09115b3ce5e)
![xemu-2023-08-16-17-30-44](https://github.com/xemu-project/xemu/assets/141806635/a3f6e56e-57e3-4060-a9cf-7026d7346f25)

### Expected Behavior

Colors and textures should appear like this

![xemu-2023-08-16-17-29-50](https://github.com/xemu-project/xemu/assets/141806635/8e6f83c7-c102-48da-adf8-e9939be6d52d)

### xemu Version

0.7.111 master

### System Information

OS platform : Windows 10
OS version : 22h2
CPU : Intel core I3 10100 3.6 ghz
GPU model : Nvidia Gefroce GT 1030/PCIe/SSE2
Driver : 4.0.0 Nvidia 536.67
Shader : 4.00 Nvidia via cg compiler

### Additional Context

Game in PAL version (France)

**Comment by 0Alastair1** [comment]
Seems to effect NTSC h2 versions as well.

**Comment by mborgerson** [comment]
Possibly fixed now. Can you try the latest version of xemu and let me know?

**Comment by 0Alastair1** [comment]
just tested and its fixed on my end.  thanks

**Comment by diabolik26** [comment]
I just tested it and it works.  Very cool !  However, I noticed some slowdowns in moments when there are a lot of characters on the screen, but nothing too annoying.  That's not going to stop me from finally being able to finish the game. Thank you very much!

**Comment by mborgerson** [comment]
Great, thank you both for your help testing and reporting!
