### ISSUE TITLE
RetroAchievements integration

### ISSUE THREAD

**Issue by awsms** [xemu-project/xemu#1524]
### Feature Request

[retroachievements.org](https://retroachievements.org/) is a service that provides a trophy/achievement unlocking mechanism similar to modern consoles, for retro games.

According to their docs, it's currently not implementable ([needs hashing method and memory map](https://docs.retroachievements.org/Emulator-Support-and-Issues/#xbox)).

**Comment by antangelo** [comment]
Duplicate of #582

**Comment by awsms** [comment]
dupes https://github.com/xemu-project/xemu/issues/582, sorry but searching for "retroachievements" didn't bring any results
