### ISSUE TITLE
Is it possible to add Zink OpenGl>Vulkan wrapper to XEmu?

### ISSUE THREAD

**Issue by xcom169** [xemu-project/xemu#1535]
### Feature Request

OpenGL drivers are still not so good on Windows (eg. Intel, AMD) however Vulkan drivers are somewhat better.
Is it possible to add Zink wrapper so on Windows we can use Vulkan instead of problematic OpenGL? 

### Additional Context

<code>
https://docs.mesa3d.org/drivers/zink.html
</code>

**Comment by RinMaru** [comment]
you can already do this but trust me it will only run worse on windows.
https://github.com/pal1000/mesa-dist-win
Open the archive and extract the the x64 folder and move all its files into the xemu folder.

**Comment by xcom169** [comment]
> you can already do this but trust me it will only run worse on windows. https://github.com/pal1000/mesa-dist-win Open the archive and extract the the x64 folder and move all its files into the xemu folder.

Thanks! I'll stick to Linux then.  
And what about ANGLE?  Is it not better than native Windows OGL drivers for Intel and AMD?

**Comment by RinMaru** [comment]
> > you can already do this but trust me it will only run worse on windows. https://github.com/pal1000/mesa-dist-win Open the archive and extract the the x64 folder and move all its files into the xemu folder.
> 
> Thanks! I'll stick to Linux then. And what about ANGLE? Is it not better than native Windows OGL drivers for Intel and AMD?

I cant test that myself so idk.

**Comment by mborgerson** [comment]
I'd like to avoid distributing Zink and deciding for users when to use it over native GL support. Users should be able to try and decide for themselves if they want to use Zink for their GL applications, and we can mention how to do it on the website for users to try until xemu eventually grows more native backends for users to pick from. If anyone wants to submit a PR for the website, they can do so at https://github.com/xemu-project/xemu-website
