### ISSUE TITLE
xemu: -drive index=0,media=disk,file=/home/obnoxiousloaf34/xbox_hdd.qcow2,locked=on: Could not open '/home/obnoxiousloaf34/xbox_hdd.qcow2': Read-only file system

### ISSUE THREAD

**Issue by PaperVb64** [xemu-project/xemu#1548]
### Bug Description

gives you the error "`xemu: -drive index=0,media=disk,file=/home/obnoxiousloaf34/xbox_hdd.qcow2,locked=on: Could not open '/home/obnoxiousloaf34/xbox_hdd.qcow2': Read-only file system`" whenever you load any hdd file.

1. Install xemu through Flatpak/Flathub
2. Setup the file (BIOS, MCPX BIOS, and the HDD.qcow2)
3. Run the file through flatpak run (error was discovered through this, still happens when ran through Application).
4. Get "`xemu: -drive index=0,media=disk,file=/home/obnoxiousloaf34/xbox_hdd.qcow2,locked=on: Could not open '/home/obnoxiousloaf34/xbox_hdd.qcow2': Read-only file system`" at the end of the script, and refuse to load.

### Expected Behavior

XEMU LOADS (no duh)

### xemu Version

Last Working: idk any version from 2020-2021
Current: dunno, it's not booting.

### System Information

OS: Debian GNU/Linux 11 (bullseye) on Chrome OS x86_64
GPU: On Board
GPU Driver: ¯\_(ツ)_/¯

### Additional Context

Last time i used xemu on this chromebook was during the 'demic, and it worked fine (albeit with hella lag), so i'm just confused why it does't work all of the sudden.

**Comment by dracc** [comment]
Known problem, it's due to how flatpak works. Workaround [here](https://xemu.app/docs/troubleshooting/#flatpak-release-will-not-load-bios-mcpx-rom-hard-drive).
