### ISSUE TITLE
Crash when launching from WSL after recent audio work

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#155]
Previously I was able to get around audio issues in legacy XQEMU by setting the environment variable `QEMU_AUDIO_DRV=none` however this no longer works.

```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
SDL_OpenAudioDevice failed
```

I use WSL primarily when working on things so this is very problematic.

**Comment by mborgerson** [comment]
Apparently SDL is confused by the WSL environment. Try specifying these environment variables before launching:

```SDL_DISKAUDIOFILE=/dev/null SDL_AUDIODRIVER=disk```

**Comment by GXTX** [comment]
Thank, that worked. Looking at their audio drivers, it seems i'd be easier just to use `dummy` instead.

I do wonder if it acts the same way on a system without any audio devices.
