### ISSUE TITLE
Ubuntu Mantic build for PPA

### ISSUE THREAD

**Issue by StianOby** [xemu-project/xemu#1554]
### Feature Request

Ubuntu 23.10 Mantic has been released. The PPA should have a .deb for the latest Ubuntu release.

**Comment by antangelo** [comment]
Likely similar issue to #1445

**Comment by StianOby** [comment]
I had the PPA working with 23.04, so I think #1445 can be closed as resolved.

For 23.10, there is likely a very minor adjustment that is needed. @mborgerson can probably fix it in a heartbeat (as he has done earlier with other Ubuntu versions).

**Comment by Kai99x** [comment]
When will it be fixed?

**Comment by mborgerson** [comment]
It took 6 or 7 heartbeats. Noble, Mantic added. Focal dropped.

**Comment by mborgerson** [comment]
I had enabled the build but it was unfortunately broken for some time. Should be fixed now according to https://code.launchpad.net/~mborgerson/+recipe/xemu-daily
