### ISSUE TITLE
Halo 2 missing sky box

### ISSUE THREAD

**Issue by Gareth17andMinnie14** [xemu-project/xemu#1558]
### Title

https://xemu.app/titles/4d530064/#Halo-2

### Bug Description

![Halo 2 Skybox Missing 1](https://github.com/xemu-project/xemu/assets/122693175/71d2221a-0c11-45db-ba1b-53df9a382b77)
![Halo 2 Skybox Missing 2](https://github.com/xemu-project/xemu/assets/122693175/47f393cb-d036-471d-87ac-aefba1822e5f)
![Halo 2 Skybox Missing 3](https://github.com/xemu-project/xemu/assets/122693175/89baf584-dc81-4e48-88c0-d2223487d3ca)
![Halo 2 Skybox Missing 4](https://github.com/xemu-project/xemu/assets/122693175/28d3160c-e3a1-46a0-b328-e5ddb49f997c)
![Halo 2 Skybox Missing 5](https://github.com/xemu-project/xemu/assets/122693175/57e893bb-a306-4d2c-bfbf-883f45bfa35d)
![Halo 2 Skybox Missing 6](https://github.com/xemu-project/xemu/assets/122693175/7bd3e09e-e8b8-4385-957f-43dab166e9e8)
![Halo 2 Skybox Missing 7](https://github.com/xemu-project/xemu/assets/122693175/7b58e827-cc5c-441b-ab3d-bdde72746319)
![Halo 2 Skybox Missing 8](https://github.com/xemu-project/xemu/assets/122693175/81bdf7a7-bdae-4be2-8db8-c91400c50325)

There are some skybox and graphical stuff missing from the game and it makes it look dark and empty 

### Expected Behavior

Nothing else but just some skybox & graphical issues.

### xemu Version

Version:      0.7.117
Branch:       master
Commit:       b605381adb3d13ad5b1be94d06bcfb896590d90a
Date:         Sun Nov 19 19:18:28 UTC 2023

### System Information

CPU:          Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver:       4.0.0 NVIDIA 546.17
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

MCPX Boot ROM MD5 Hash:        d49c52a4102f6df7bcf8d0617ac475ed
Flash ROM (BIOS) MD5 Hash:     ec00e31e746de2473acfe7903c5a4cb7

**Comment by mborgerson** [comment]
Duplicate https://github.com/xemu-project/xemu/issues/229

You can see open issues for a game on the compat page
