### ISSUE TITLE
[Question] Minimum required macOS version

### ISSUE THREAD

**Issue by shinra-electric** [xemu-project/xemu#1559]
### Bug Description

I've searched on the website, GitHub and Discord, but I haven't been able to find any mention of a minimum macOS version required to run Xemu. 

The app itself reports 10.6 Snow Leopard. I doubt this would be accurate, or that Macs from the 2009 era would be able to run Xemu well...

<img width="199" alt="Screenshot 2023-11-24 at 13 52 12" src="https://github.com/xemu-project/xemu/assets/50119606/7821058e-b9d9-4cf6-9720-9843db91b14e">

### Expected Behavior

It's possible to set the minimum macOS version in the Info.plist file in the app bundle. This would prevent a lot of invalid issues from people who are trying to run Xemu on Macs that can't handle it. 

### xemu Version

All

### System Information

macOS 

### Additional Context

I can make a PR to do this, but I don't know what the real technical minimum version is.

**Comment by Namean** [comment]
[System Requirements - Xemu](https://xemu.app/docs/about/#system-requirements)

Operating System releases that are **no longer supported by their vendor** are not officially supported by xemu.

https://endoflife.date/macos
Ended 1 month and 4 weeks ago
(26 Sep 2023)

This excludes all version prior to Big Sur i.e.  10.6 Snow Leopard.

Hope this helps

**Comment by shinra-electric** [comment]
But this is an arbitrary minimum, not a technical minimum. If running on Big Sur works fine, there is no reason to put a restriction on it. 

If there is a technical minimum, i.e. Xemu cannot work without feature X or feature Y introduced in a certain OS, that would be where to draw the line.

**Comment by mborgerson** [comment]
@shinra-electric 

> But this is an arbitrary minimum, not a technical minimum. If running on Big Sur works fine, there is no reason to put a restriction on it.

This policy is not arbitrary. If users run into bugs on platforms that are not supported by their vendor, I don't plan to spend any time chasing down those bugs. There is already extremely limited bandwidth for volunteer basis in-service platform release bug fixing. For this reason we state that such platforms are not officially supported. That said, we don't actively prevent people from running xemu on unsupported platforms--we just don't provide support for it.

> I can make a PR to do this, but I don't know what the real technical minimum version is.

I'm also not sure what the 'technical minimum' should be. Will you try several macOS releases to find out?

**Comment by shinra-electric** [comment]
> That said, we don't actively prevent people from running xemu on unsupported platforms--we just don't provide support for it.

What I’m suggesting is actively preventing xemu from running on versions of macOS that are known to not work. I’m not suggesting preventing it running on vendor unsupported platforms. 

> I'm also not sure what the 'technical minimum' should be. Will you try several macOS releases to find out?

Right now I only have hardware to test macOS 12, 13 and 14, which I would assume all work. I’ll have access to older Intel hardware (2015 MacBook Pro) over Christmas and will try out a few older OS’s if I get a chance.

**Comment by mborgerson** [comment]
Closed as answered
