### ISSUE TITLE
Midnight Club 3 DUB Edition Remix Crashes when Creating Save Game

### ISSUE THREAD

**Issue by useresuser** [xemu-project/xemu#156]
Works fine at the menu, but when starting a new game the emulator crashes

![Capture](https://user-images.githubusercontent.com/37781324/104794661-ca3b0880-5787-11eb-9e50-5eb92f1e898a.PNG)

Titles: 54540079

**Comment by mborgerson** [comment]
From compat report `5ffd0b56ed1c4bd7364bcc64`.

> The moment you press start to get to the main menu it crashes showing this error: ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:3949:pgraph_surface_invalidate: assertion failed: (surface != d->pgraph.color_binding)


Likely #116

**Comment by abaire** [comment]
@mborgerson this was duped by #349 which was recently fixed and should be closed (I have verified that I can get in game w/ 0.7.15, I believe there are several screenshots in discord from other people who have done the same)
