### ISSUE TITLE
Zarchive support instead of CHD

### ISSUE THREAD

**Issue by psyalemao** [xemu-project/xemu#1560]
### Feature Request

I wonder if Zarchive would be an alternative, it compress using zstd and Xenia supports it already. CHD is based on LZMA and utilizes a lot of CPU

**Comment by RinMaru** [comment]
> ### Feature Request
> 
> I wonder if Zarchive would be an alternative, it compress using zstd and Xenia supports it already. CHD is based on LZMA and utilizes a lot of CPU

Zarchive would only be beneficial if you using it on extracted games because it still cant compress junk data

**Comment by Shideravan** [comment]
Xemu already has support for CHD? Nice!

**Comment by RinMaru** [comment]
> Xemu already has support for CHD? Nice!

No it doesn't. It only supports xiso

**Comment by mborgerson** [comment]
I'll merge this issue with #238, because it is essentially the same request: support for compressed images, not necessarily a particular format. If someone wants to work on the feature, they can evaluate the options and pick a suitable compression library
