### ISSUE TITLE
Flatpak Distributed Xemu (Linux, aarch64) Fails to use vmwgfx on Multiple Linux Guests (Debian 12, Fedora 39) in VMWare Player 13.5

### ISSUE THREAD

**Issue by tomgade09** [xemu-project/xemu#1561]
### Bug Description

When installing aarch64 xemu from flatpak in a Debian 12 guest of VMWare Player 17 (most recent version, host is M1 Max Macbook Pro running MacOS Sonoma 14.1.1 - the most recent), the vmwgfx driver (VMWare Player guest-side GPU acceleration driver) is not used and Mesa falls back on llvmpipe, resulting in poor performance.  This issue occurs also occurs in a Fedora 39 guest in VMWare Player 13.5 on the same host and appears to be agnostic to the linux distro (based on these two examples).  Notably, when downloading and compiling xemu from source, this error does _not_ occur and vmwgfx is used as expected.

Error message (with `LIBGL_DEBUG=verbose`):
`libGL: using driver vmwgfx for 7`
`libGL: Can't open configuration file /etc/drirc: No such file or directory.`
`libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.`
`libGL: pci id for fd 7: 15ad:0406, driver vmwgfx`
`libGL: MESA-LOADER: failed to open /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory`

Steps to reproduce:

1. Run Debian 12 in VMWare Player 13.5 (free version) on MacOS 14.1.1 and ensure flatpak is working and using flathub as the repository of choice, as well as `open-vm-tools` and `open-vm-tools-desktop` packages are installed, and in VMWare Player settings: `Accelerate 3D Graphics` is enabled with any amount of memory selected (tested in independent runs with 64MB, 256MB, and 8GB options selected).
2. `flatpak install app.xemu.xemu`
3. Create symlink so `vmwgfx_dri.so` is seen where xemu is looking: `cd /usr/lib/aarch64-linux-gnu;  mkdir -p GL/default/lib;  ln -s /usr/lib/dri /usr/lib/aarch64-linux-gnu/GL/default/lib/dri`
4. `LIBGL_DEBUG=verbose flatpak run app.xemu.xemu`
5. Observe output - this error is contained in the output.

Steps taken to mitigate (unsuccessfully):

1. First, ensure that the `/usr/lib/aarch64-linux-gnu/GL/default/lib/dri` folder exists.  Initially, this didn't exist for me and the `vmwgfx_dri.so` file resided in `/usr/lib/dri`, so I created a symlink (step 3 above).  Now the driver should be located where xemu looks for it.
2. Compile from source.  This version of xemu _does_ use `vmwgfx` located in the same place.

### Expected Behavior

`vmwgfx` driver should be used without a `file not found` error.  The `vmwgfx_dri.so` is confirmed to exist in the folder indicated in the error message, and is used by xemu when compiled from source.

### xemu Version

0.7.117

### System Information

OS: Debian 12 guest in VMWare Player 13.5 on MacOS 14.1.1 Host
CPU: M1 Max, 64 GB RAM
GPU: M1 Max
GPU Driver: Native MacOS driver (host), `vmwgfx` (guest)

### Additional Context

tom@debian:~$ LIBGL_DEBUG=verbose flatpak run app.xemu.xemu
xemu_version: 0.7.117
xemu_branch: b605381adb3d13ad5b1be94d06bcfb896590d90a
xemu_commit: b605381adb3d13ad5b1be94d06bcfb896590d90a
xemu_date: Sun Nov 19 09:22:34 PM UTC 2023
xemu_settings_get_base_path: base path: /home/tom/.var/app/app.xemu.xemu/data/xemu/xemu/
xemu_settings_get_path: config path: /home/tom/.var/app/app.xemu.xemu/data/xemu/xemu/xemu.toml
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.
libGL: using driver vmwgfx for 7
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.
libGL: pci id for fd 7: 15ad:0406, driver vmwgfx
libGL: MESA-LOADER: failed to open /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open vmwgfx: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: vmwgfx
libGL: using driver vmwgfx for 7
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.
libGL: pci id for fd 7: 15ad:0406, driver vmwgfx
libGL: MESA-LOADER: failed to open /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open vmwgfx: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: vmwgfx
libGL: MESA-LOADER: dlopen(/usr/lib/aarch64-linux-gnu/GL/default/lib/dri/swrast_dri.so)
libGL: did not find extension DRI_Kopper version 1
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/tom/.drirc: No such file or directory.
libGL: did not find extension DRI2_Flush version 1
CPU: 
OS_Version: Freedesktop.org SDK 23.08 (Flatpak runtime)
GL_VENDOR: Mesa
GL_RENDERER: llvmpipe (LLVM 16.0.6, 128 bits)
GL_VERSION: 4.5 (Core Profile) Mesa 23.2.1 (git-49a47f187e)
GL_SHADING_LANGUAGE_VERSION: 4.50
Created QEMU launch parameters: xemu -machine xbox,bootrom=/home/tom/Desktop/xemu/mouse_rev0.bin,kernel-irqchip=off,avpack=hdtv -device smbus-storage,file=/home/tom/.var/app/app.xemu.xemu/data/xemu/xemu/eeprom.bin -bios /home/tom/Desktop/xemu/xboxbios-1.00.4627.03-complex_debug_ucodeupd-512k.bin -m 64 -drive index=0,media=disk,file=/home/tom/.var/app/app.xemu.xemu/data/xemu/xemu/xbox_harddisk-D4920.qcow2,locked=on -drive index=1,media=cdrom,file= -display xemu -device usb-hub,port=1,ports=4

**Comment by mborgerson** [comment]
I'm not really sure if this is an issue with xemu or with flatpak design and sandboxing. Do other flatpak apps work in the way you expect? You can find the packaging sources here if you'd like to debug it https://github.com/flathub/app.xemu.xemu/

By the way, there are native macOS builds for Apple Silicon you may be interested in

**Comment by tomgade09** [comment]
Thanks.  I've run the macOS build.  It seems to work well.  I'm not that familiar with flatpak, but on a cursory glance, it's not clear to me how this issue would develop based on the flatpak config files alone.  It's odd that the `vmwgfx_dri.so` library exists in the location that Mesa is looking for it, but isn't able to be read (and then `llvmpipe`, ~~in the same location~~ EDIT: not in the same location, is used).  I've read of a similar issue (failure to use a shared library by mesa) when there is a mismatch in libc++ version that various components are linked against.  Although in those cases, there was an error message that indicated the issue when running with `LIBGL_DEBUG=verbose`...

I haven't really run anything else in flatpak, so I can't compare.  Although other mesa programs (glxgears for example) use the correct `vmwgfx` library with no changes to the paths or environment variables.

**Comment by capezotte** [comment]
That's a Flatpak issue. The sandbox changes the `/usr` the app sees to the one from the official Flatpak runtime (which includes a custom build of Mesa) You can see it in the logs, it's likely far newer than Mesa on your Debian system, which will show up on Xemu built from source.

[The official Flatpak runtime does not ship with vmwgfx_dri.so (`svga`) for ARM CPUs.](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/extensions/mesa/mesa.yml?ref_type=heads#L50)

**Comment by tomgade09** [comment]
Thanks.  So from what I'm understanding, there isn't a way to use the debian mesa drivers with a flatpak distributed xemu, so the fix would be to use xemu from another source.  Is that right?  I guess that means nothing distributed via flatpak can use HW acceleration in a VM.

**Comment by capezotte** [comment]
> I guess that means nothing distributed via flatpak can use HW acceleration in a VM.

Yes (at least for VMWare on ARM CPUs, until `svga` gets added to the runtime).

**Comment by mborgerson** [comment]
Closed as not an xemu issue
