### ISSUE TITLE
NFL 2K 5 audio stutters, clips out constantly, graphics a little slow

### ISSUE THREAD

**Issue by Will0529** [xemu-project/xemu#1567]
### Bug Description

Xbox start-up animation graphics and audio perfect, but when game loads, the graphics stutter a little but the audio persistently cuts and cracks, making it painful for the ears. Can't find a setting or fix that could help me.

### Expected Behavior

Audio should play normally

### xemu Version

v0.7.177

### System Information

Windows 10
8 GB DDR4 ram
AMD Ryzen 3 3250U
AMD Vega 3 Graphics

### Additional Context

Computer works alright but an older game like this shouldn't be an issue for the hardware. I have a feeling I could do something on my end, but I have yet to find a fix.

**Comment by mborgerson** [comment]
Since report from August 2022 indicates 'very playable' on relatively low-end specs, I'll consider this a hardware performance issue, not necessarily an issue with xemu. Try disabling realtime dsp if you have it enabled--it is more accurate but runs a lot slower for now
