### ISSUE TITLE
OpenBSD platform support

### ISSUE THREAD

**Issue by kwillett7** [xemu-project/xemu#1568]
### Feature Request

I would really like an OpenBSD port and would love to help.  I know basic C, sh, bash, and python but am not a programmer by trade.

Currently I see that a port to FreeBSD has been started.

Could someone point me in the direction needed for an OpenBSD port?

Again, I don't expect this to be done for me but would like some help with it.

Thanks,
Kyle

**Comment by mborgerson** [comment]
It should probably work, but afaik nobody is regularly testing or working on xemu on Free/OpenBSD. If you want to help maintain BSD platform support, patches are welcome

**Comment by mborgerson** [comment]
No response, closed
