### ISSUE TITLE
Yellow line on top right and right of the screen in Fable as well as green and purple colors

### ISSUE THREAD

**Issue by AkihitoZero5454** [xemu-project/xemu#1576]
### Title

https://xemu.app/titles/4d53000d/#Fable
MS-013 [4d53000d]

### Bug Description

There is a yellow line in the top right and right of the screen as well as green and purple particles

### Expected Behavior

Screen should be clear

### xemu Version

v0.7.118

### System Information

Windows 10
GTX 1070 Ti
Ryzen 7 3700X 8 Core Processor

**Comment by AkihitoZero5454** [comment]
![Uploading xemu-2024-01-05-08-27-05.png…]()

**Comment by AkihitoZero5454** [comment]
![xemu-2024-01-05-08-27-05](https://github.com/xemu-project/xemu/assets/85499008/2e65e6ba-d2a8-4fa1-893b-b7ded747ab82)

**Comment by mborgerson** [comment]
I'll add it to #57
