### ISSUE TITLE
An enemy spawns within environment geometry making level unbeatable

### ISSUE THREAD

**Issue by aminimal** [xemu-project/xemu#1579]
### Title

https://xemu.app/titles/49470017/

### Bug Description

On Valley 2, an enemy spawns within the environment geometry making the level unbeatable as all enemies must be killed to beat the level.

### Expected Behavior

Enemy should spawn above ground so that it can be killed to complete the objectives for the level.

### xemu Version

v0.7.118

### System Information

OS: Windows 10
CPU: AMD Ryzen 5 3600X 6-Core Processor 3.79 GHz
GPU: NVIDIA GeForce GTX 1080ti
GPU DRIVER: 537.58 DCH

### Additional Context

I have retried the level multiple times and each time the enemy spawns below ground and/or is stuck in the level geometry and is not visible. The sound of the enemy can be heard and if the player stands in a certain spot they can even be damaged by the enemy, but can do no damage to the enemy. The enemy is the mosquito type insect on Valley 2 in the first area very near to a small rusty column object.

**Comment by dracc** [comment]
This sounds like the type of bug that would happen due to a bad dump rather than emulation issues. Does your dump of the game work on a physical Xbox?

**Comment by aminimal** [comment]
I tried a second dump and it hasn't happened. May have been my first dump after all.
