### ISSUE TITLE
KOF: Maximum Impact Maniax black screen

### ISSUE THREAD

**Issue by antoniodesousa** [xemu-project/xemu#1591]
### Title

https://xemu.app/titles/534e0007/#KOF-Maximum-Impact-Maniax

### Bug Description

After loading the game, nothing happens. It just shows a black screen.

### Expected Behavior

After loading the game, the "RenderWare" and "SNK Playmore" screens should show up. Followed but a cutscene.

### xemu Version

0.7.118.0

### System Information

OS: Windows 11 23H2
CPU: AMD Ryzen 6900HX
GPU: Radeon RX 6600M
GPU Driver: 24.1.1

**Comment by dracc** [comment]
Sounds like you have a bad dump because it runs just fine for me.

**Comment by antoniodesousa** [comment]
The dump is fine. I'm pretty sure of it. The game just don't boot on my system. Maybe, something to do with the GPU or drivers... I don't know. There's no errors anywhere at all.

**Comment by antoniodesousa** [comment]
It seems to be working fine in the latest release. So I gonna close the issue.
