### ISSUE TITLE
On the problem of creating HDD image with 80GB or more capacity

### ISSUE THREAD

**Issue by weiyan2006** [xemu-project/xemu#1593]
### Feature Request

I'm playing XEMU on my SteamDeck handheld recently, and I want to use a hard disk image with 80GB or more capacity. What should I do? Thanks a lot!

**Comment by dracc** [comment]
Not strictly a xemu issue, but w/e.

Instructions for setting up a custom HDD image here:
https://github.com/xemu-project/xemu-hdd-image

**Comment by mborgerson** [comment]
Closed as answered
