### ISSUE TITLE
CHD compression from version 0.262

### ISSUE THREAD

**Issue by Papermanzero** [xemu-project/xemu#1596]
### Feature Request

Currently xemu has not the possibility to load compressed isos. The discussion was always about which kind of compression or to use zarchive instead

CHD added the zstd/zarchive compression with mame version 0.262. That means all the benefits from Zarchive are now also available for CHD. Means the highest possible lossless compression of data together with dif file support and archive formats are now all avalable in chd.

so for isos as well as game folders (dlc, games) the best way to archive files is CHD.

**Comment by RinMaru** [comment]
This is a duplicate request. Reposting this everywhere is gonna get you blacklisted really quick..

**Comment by Papermanzero** [comment]
Oh sorry. Actually I did use the search function but only found the discussion with ZAR.

**Comment by mborgerson** [comment]
Closed as duplicate of #1584 #1289 #238 #129
