### ISSUE TITLE
Tom Clancy's Splinter Cell: Double Agent with fixed widescreen

### ISSUE THREAD

**Issue by ilwsm** [xemu-project/xemu#1598]
### Feature Request

Why the last version of Xemu cannot do that, like in this video?
https://www.youtube.com/watch?v=7n40jVKltpw

Look on people, they are not stretched, but in v0.7.118 - are stretched.

**Comment by mborgerson** [comment]
Check display mode and aspect ration options

**Comment by ilwsm** [comment]
Don't work.
Of course I've done this a million times.  Send me a screenshot of how it works for you on the new version.

**Comment by ilwsm** [comment]
@mborgerson please reopen this issue.

**Comment by mborgerson** [comment]
Share a screenshot of the problem you're having

**Comment by mborgerson** [comment]
By the way you need to enable widescreen mode in Xbox dashboard or with an eeprom editor if you want the game to use widescreen mode

**Comment by ilwsm** [comment]
I do it tomorrow.
But. what from this you don't understand:

> Look on people, they are not stretched, but in v0.7.118 - are stretched.

Here video, where peoples are stretched:
https://youtu.be/y3f3tGWsdN0
same as in v0.7.118

And here - people are not stretched:
https://www.youtube.com/watch?v=7n40jVKltpw

options: 16:9 and scale.

**Comment by mborgerson** [comment]
If it's stretched when you select 16:9 in xemu, then you need to do what I said above and enable widescreen in your dashboard settings

**Comment by ilwsm** [comment]
> eeprom editor

How should I know:  what, where and how is this done in general?

> enable widescreen in your dashboard settings

How do that, give me screen

And again, give me screen of last ver. xemu where people not stretched in this game.

**Comment by dracc** [comment]
> > eeprom editor
> 
> How should I know: what, where and how is this done in general?

It's all documented over at https://xemu.app
> > enable widescreen in your dashboard settings
> 
> How do that, give me screen

Depends on what dashboard you're using. NevolutionX has it in Settings -> Video.
> And again, give me screen of last ver. xemu where people not stretched in this game.

![image](https://github.com/xemu-project/xemu/assets/1279635/12c78576-0b79-4b1e-a3da-de1b1037a4c2)
Hard to tell what you're looking for as your videos look identical to me, but I hope this is good enough.

**Comment by ilwsm** [comment]
>eeprom editor
> It's all documented over at https://xemu.app/

Information for other mere mortals:
Download [eeprom editor](https://github.com/Ernegien/XboxEepromEditor/releases)

`eeprom_path = 'C:\Users\<User>\AppData\Roaming\xemu\xemu\eeprom.bin` _win users_
![image](https://github.com/xemu-project/xemu/assets/2471892/44103b4a-8179-46ea-a418-7290f8c16cc9)
Check `widescreen`.

> Hard to tell what you're looking for as your videos look identical to me

Absolutely **not identical**.
But nevertheless, the problem with widescreen ratio was solved by editing the EEPROM. Thanks !!

============
This my screen with fixed widescreen
![image](https://github.com/xemu-project/xemu/assets/2471892/3a1da027-a107-401d-a9f2-24230aefb37e)

But how to get rid of the white field on the left and top? Everything is fine on your screenshot in  v0.7.118.
I understand that the question is off topic, but still...

**Comment by ilwsm** [comment]
@dracc 
> But how to get rid of the white field on the left and top? Everything is fine on your screenshot in v0.7.118.

**Comment by dracc** [comment]
@ilwsm No idea, I did nothing and it just worked.Message ID:
***@***.***>

>
