### ISSUE TITLE
Meta: Performance Issue

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#1612]
### Title

https://xemu.app/titles/43430005/#Group-S-Challenge
https://xemu.app/titles/454d0003/#Total-Immersion-Racing
https://xemu.app/titles/4b420007/#Top-Gear-RPM-Tuning
https://xemu.app/titles/4d530035/#Top-Spin
https://xemu.app/titles/545400a9/#Torino-2006
https://xemu.app/titles/49470026/#The-Terminator-Dawn-of-Fate
https://xemu.app/titles/4947003b/#Terminator-3-Rise-of-the-Machines
https://xemu.app/titles/4947003e/#Terminator-3-The-Redemption
https://xemu.app/titles/4b4f0006/#Samurai-Warriors
https://xemu.app/titles/43430002/#Steel-Battalion
https://xemu.app/titles/4d570010/#NBA-Ballers
https://xemu.app/titles/4d57002e/#NBA-Ballers-Phenom
https://xemu.app/titles/4d530003/#Project-Gotham-Racing
https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2
https://xemu.app/titles/4d530017/#MechAssault
https://xemu.app/titles/584c0013/#MechAssault-2-Lone-Wolf-OutRun-2
https://xemu.app/titles/4d53006b/#MechAssault-2-Lone-Wolf
https://xemu.app/titles/56560029/#Die-Hard-Vendetta

### Bug Description

These games all have performance issues in one way or another which stop them from being in the playable category

### Expected Behavior

Should run at full speed

### xemu Version

Version 0.7.119

### System Information

OS: Windows 11
CPU: Intel Core I7-12700H 14 Core Processor
Graphics Device: NVIDIA GeForce RTX 4060
Driver Version: 551.86

### Additional Context

...

**Comment by ghost** [comment]
....I

**Comment by ghost** [comment]
Have A Problem

**Comment by ghost** [comment]
A Performance Issue

**Comment by dracc** [comment]
@mborgerson Please stop this madness already.

**Comment by ghost** [comment]
sorry

**Comment by ghost** [comment]
im sorry

**Comment by ghost** [comment]
i ll stop the madness now

**Comment by RinMaru** [comment]
> i ll stop the madness now

theres already a thread for you to report these in
