### ISSUE TITLE
FFP LIGHT_SPOT needs to be implemented

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#162]
https://github.com/mborgerson/xemu/blob/aab63105fce0b8f2699b520a157d2b0e95539e93/hw/xbox/nv2a/shaders.c#L569

Titles: 4c410005, 55530013, 5454008f, 47560004, 5655000d, 4b420001, 58490004, 47560003, 49460001, 53430001, 4947007b, 43430003, 564e0004, 55530038, 56550048

**Comment by Triticum0** [comment]
Other titles affected: 5454008f, 47560004, 5655000d, 4b420001, 58490004, 47560003, 49460001, 53430001, 4947007b, 43430003, 564e0004

**Comment by Fabxx** [comment]
Another title affected: 55530038
