### ISSUE TITLE
NXDK audio sample doesn't work.

### ISSUE THREAD

**Issue by hitchhikr** [xemu-project/xemu#1626]
### Bug Description

https://github.com/XboxDev/nxdk/tree/master/samples/xaudio sample from the NXDK works on the console but not in your emulator (it uses the AC97 codec only).
Same problem with or without DSP processing.

### Expected Behavior

Hear some audio being played.

### xemu Version

0.7.120 (but older versions behave identically).

### System Information

OS: Windows 11
CPU: Intel
GFX: NVIDIA
SFX: RealTek Audio

**Comment by mborgerson** [comment]
Duplicate #1529
