### ISSUE TITLE
Hi I am a android phone user I have a question can this emulator ported on android ?

### ISSUE THREAD

**Issue by PsyVHS77** [xemu-project/xemu#1633]
### Feature Request

I like this OG Xbox emulator on windows but I think about wanting a android version ? for playing on phone that way playing more OG Xbox games on this emulator maybe this be a reality if this version be made and I not a bad toxic user I am a nice user to like to support the emulation community and that also hopefully this be not out of the control on android because I heard android emulation community sometimes be toxic and that cost some Emulator's discontinued like ps2 Emulator and android aethersx2 lucky I am not from them people I am a supporter for respect the makers of all Emulator's including you guys
So thanks for reading my long question and as always rave on bro x3. 👍😀

Bye.

**Comment by mborgerson** [comment]
Duplicate #1281 #719 #501

**Comment by PsyVHS77** [comment]
> Duplicate #1281 #719 #501

O ok many people ask the Same question and that's be over asked the same request over and over again
O ya
I not see anyone had the same question of question and I washing myself and sorry to asked the same question 😔 I am not the only one who request the same android version 
Sorry 🙂
