### ISSUE TITLE
Title Name: Short Description

### ISSUE THREAD

**Issue by Pyro-420** [xemu-project/xemu#1648]
Ed, Edd, n Eddy: The Mis-Edventures : DOES NOT LOAD

https://xemu.app/titles/4d570032/#Ed-Edd-n-Eddy-The-Mis-Edventures

### Bug Description

XEMU isnt loading the game. I've downloaded it 2x off Vimm's Lair, and every other game title I have works but not this one. It is telling me that I need to insert a disc, regardless of how many times I reset the XEMU emulator and load the disc.

### Expected Behavior

Nothing is loading.

### xemu Version

Version:      0.7.121

### System Information

CPU:          12th Gen Intel(R) Core(TM) i9-12900K
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 4070/PCIe/SSE2
Driver:       4.0.0 NVIDIA 552.44
Shader:       4.00 NVIDIA via Cg compiler

**Comment by mborgerson** [comment]
Support is not provided for pirated content. Please buy the game and create a legitimate backup
