### ISSUE TITLE
 [Feature Request] macro remapping (like PCSX2)

### ISSUE THREAD

**Issue by UserGit-2021** [xemu-project/xemu#1676]
### Feature Request

It would be great to be able to remap multiple buttons into one button like in pcsx2.
![219905192-6a44124b-3f32-4666-8a4c-b4c2d8e133f9](https://github.com/xemu-project/xemu/assets/91757058/aa93129e-5632-48a0-b635-fc41a7c98464)
![изображение](https://github.com/xemu-project/xemu/assets/91757058/08434b34-ef17-46d7-a5c7-b8c86a25dc90)

**Comment by antangelo** [comment]
Duplicate of #136
