### ISSUE TITLE
When playing Iron Phoenix, the screen is blurry and often drops frames, it's difficult to stabilize the frame rate at 60

### ISSUE THREAD

**Issue by junelynn** [xemu-project/xemu#1690]
### Bug Description

When playing Iron Phoenix, the screen is blurry and often drops frames, it's difficult to stabilize the frame rate at 60

### Expected Behavior

I hope that the frame  is normal and the frame rate can be smoothly and stably maintained at 60

### xemu Version

V0.7.127

**Comment by mborgerson** [comment]
Please file again using the correct template with requested information including screenshots
