### ISSUE TITLE
Hard Disc image vs folder structure

### ISSUE THREAD

**Issue by arthur071169** [xemu-project/xemu#170]
While it is perfectly easy to FTP to the system when booted to access the hard disc, it is much easier to drag and drop into a folder structure such as CXBX-reloaded uses.

This allows for easier dashboard swapping, copying files extracted from Iso's (ahem!) to local hard disc partitions etc.

Could the option to *not* use a single Image file vs implementing a folder structure as above be considered.  If it is a limitation due to the LLE approach, perhaps a disk image 'browser' of sorts could be implemented into the menu of a powered off system?

regards,
Arthur.

**Comment by dracc** [comment]
> This allows for easier dashboard swapping, copying files extracted from Iso's (ahem!) to local hard disc partitions etc.

Sounds like way more work than just launching said .iso? I personally don't see any real benefit here, just user patterns that users don't want to change for no apparent reason.


I don't see FATX browsing being an issue of this emulator, it should be a goal for separate software IMO.

**Comment by mborgerson** [comment]
There are tools that can edit ISOs already, and it's trivial/fast to do so. There are no plans to support doing so within xemu at this time.

As for HDD there may be an external tool to help ease this process, but it is not planned to be integrated into xemu at this time either. FTP is the recommended approach for now.

**Comment by arthur071169** [comment]
Thanks for the reply.

regards,
Arthur.
