### ISSUE TITLE
Iron Phoenix: in the map "buddha's cave",Ground texture problems

### ISSUE THREAD

**Issue by junelynn** [xemu-project/xemu#1721]
### Bug Description

in the map "buddha's cave",Ground textures are incorrect.

### Expected Behavior

please fix the problem ASAP.

### xemu Version

V0.7.127

### System Information

CPU: 12th Gen Intel(R) Core(TM) i5-12600KF
Operating system:Windows 11 23H2
GPU: NVIDIA GeForce RTX 2060 running on driver 556.12.0.0

### Additional Context

![347275512-ba9019a6-6284-42a4-b3f6-7cd69878181c](https://github.com/user-attachments/assets/7fa2b84b-6e25-4d9d-a584-456f00e1c6f1)

**Comment by mborgerson** [comment]
Dup #1691
