### ISSUE TITLE
Xbox Playback DVD Kit Support

### ISSUE THREAD

**Issue by RageXbox** [xemu-project/xemu#173]
We can Possibly place DVDs in this emulator since Xbox is a DVD Player unless a DVD Kit is not plugged in. This should be a feature to play any DVD images. Found in the input menu as a peripheral.

**Comment by mborgerson** [comment]
It is possible to emulate the DVD playback kit, but this kit contains another ROM. I think it's very unlikely that people will dump the ROM from their kit and use xemu to watch DVDs on the official Xbox player app.

Nevertheless if someone (you?) would like to put some energy into researching and developing this, it would be good.

For now I'm going to close this issue.

**Comment by GXTX** [comment]
You can already do this by manually attaching the DVD kit via USB, but I don't see the point at all.
