### ISSUE TITLE
Conker: Live&Reloaded Crashes in vulkan build

### ISSUE THREAD

**Issue by Dacatzgoescodin5267** [xemu-project/xemu#1736]
### Bug Description

When going to, the part where you play multiplayer, it will crash the vulkan build of the emulator. (Creating a snapshot to bypass it seems to work but it will crash if a menu goes up)

Error code: ERROR:../hw/xbox/nv2a/pgraph/glsl/psh.c:592:get_sampler_type: assertion failed: (state->dim_tex[i] == 2)
Bail out! ERROR:../hw/xbox/nv2a/pgraph/glsl/psh.c:592:get_sampler_type: assertion failed: (state->dim_tex[i] == 2)

### Expected Behavior

Should, play multiplayer without crash

### xemu Version

0.7.131-114-g4b1c0b7fc7 (Vulkan build),  0.7.131 (Current-non vulkan build)

**Comment by antangelo** [comment]
Issues with unreleased PRs should be reported on the PR directly (in this case #1701).
