### ISSUE TITLE
Xemu Not playing highest quality audio that's available in the game

### ISSUE THREAD

**Issue by ghyujkilop** [xemu-project/xemu#1740]
### Feature Request

I was unsure whether to place this as bug or feature request but here goes. All the below has only been tested on the game [The Urbz: Sims in the City](https://xemu.app/titles/45410060/#The-Urbz-Sims-in-the-City).

I have been comparing the spectrals of the game audio files to the actual raw game audio data, and I noticed a decent discrepency.

You see the files inside audiostr.xwb when extracted are sitting at 24khz, however the songs themselves when redone at 44.1khz show an extra higher quality of audio that is currently not captured by the game.

How high the quality goes in game: https://i.imgur.com/lCjWGTp.png
What the actual games song is capable of going to: https://i.imgur.com/Gj5GKkX.png
A version I found on the web that can replace the quality: https://i.imgur.com/MEM5mAQ.png

If we can have a way to extract & repackage the .wav files in the .xwb to be the highest quality that the sepctrals can go to that would be good.

### Alternatives

I've tried doing this myself using [XWB-AudioReplacer](https://github.com/astrogab42/XwbAudioReplacer) however, the limitations of this is that it can't handle adding higher sized .wav files unless you edit/remove the XSB file limitations. 

Is there a way to remove this limitation?

**Comment by mborgerson** [comment]
xemu emulates Xbox audio hardware, it does not simply play game files. If you wish to compare xemu output for accuracy, please compare it to a recording made from a real Xbox, not source audio files.

**Comment by ghyujkilop** [comment]
As a side note to this, would it not make sense to have an option for those of us who want the highest quality audio from the game? I'm not sure how you'd implement this, but I get the idea of "stick to the original" but we also like to "improve the original" (like using internal resolution scaling for instance).
