### ISSUE TITLE
Allow Custom Textures

### ISSUE THREAD

**Issue by ghyujkilop** [xemu-project/xemu#1746]
### Feature Request

Dolphin has a similar feature where you can dump textures for certain games, then load them again.

I think improving performance is more important first, but this would be really cool!

### Alternatives

I would like the ability to directly dump the .arc files info, but I don't think this is possible. As I would like to edit game files if possible.

**Comment by mborgerson** [comment]
Duplicate https://github.com/xemu-project/xemu/issues/1337

Please search for existing issues before filing new ones.

**Comment by ghyujkilop** [comment]
Sorry I typed Custom & Textures & didn't see this!
