### ISSUE TITLE
Burnout 3: Takedown: Combination of issues

### ISSUE THREAD

**Issue by ghyujkilop** [xemu-project/xemu#1747]
### Title

[Burnout 3: Takedown](https://xemu.app/titles/4541005b/#Burnout-3-Takedown)

### Bug Description

Issues in [this video](https://youtu.be/_QxE3kmfHjk) (all tested on Native):

Video Issues:
1. Laggy everywhere except when choosing car & during aftertouch (which runs at around 80% of console equivalent).
2. Texture Misalignment/lines on ground (08:02).
3. Black bars at top of screen (08:04).
4. Multi-coloured/incorrectly rendered lake water (08:34).
5. Shimmering bottom bar (11:28).

Audio Issues:
1. FMV's are laggy & go out of time with audio (00:24).
2. Audio is Out of Sync to Gameplay (03:48).
3. Music Volume is much lower than sound volume (06:04).
4. Audio stutters with engine noise (06:18) & music (09:24) intermittently.

### Expected Behavior

[Burnout 3: Takedown (Xbox) Part 1](https://www.youtube.com/watch?v=d0TlBzqtKLA)

### xemu Version

v0.7.131

### System Information

Windows 11
RTX2070 8GB GDDR6
Intel I7-9750H Processor
32GB Dual Channel DDR4-2666Mhz Memory
FHD IPS 3ms 100% sRGB 144Hz Display
Infinity S7-9R7

**Comment by mborgerson** [comment]
Please make specific issues highlighting individual problems for tracking. Search for existing issues first to avoid duplicates
