### ISSUE TITLE
Halo 2 Multiplayer Map Pack: Assertion Failed! Error

### ISSUE THREAD

**Issue by ghyujkilop** [xemu-project/xemu#1748]
### Title

[Halo 2 Multiplayer Map Pack](https://xemu.app/titles/4d5300cd/#Halo-2-Multiplayer-Map-Pack)

### Bug Description

The Microsoft/Bungie intro for the game plays fine, but as soon as the intro ends I get this:
![ITg1zhH](https://github.com/user-attachments/assets/30c195c1-cad8-44b2-a463-7e584c54fe80)

### Expected Behavior

It to load as it should.

### xemu Version

v0.7.131

### System Information

Windows 11
RTX2070 8GB GDDR6
Intel I7-9750H Processor
32GB Dual Channel DDR4-2666Mhz Memory
FHD IPS 3ms 100% sRGB 144Hz Display
Infinity S7-9R7

**Comment by 0Alastair1** [comment]
duplicate https://github.com/xemu-project/xemu/issues/34

**Comment by mborgerson** [comment]
Closed as duplicate
