### ISSUE TITLE
Starting from the command line

### ISSUE THREAD

**Issue by Blad3forc3** [xemu-project/xemu#175]
Option to run fullscreen from the command line. when trying to change the iso file from command line the emulator reads the last iso from the ini file

**Comment by dracc** [comment]
I believe both issues mentioned already exist, both already resolved.
How did you try to specify what iso to run? I'm guessing you didn't do `-dvd_path <path/to/.iso>`.

Edit: Can't find an issue for the iso thingy, argument suggested above should work. #106 discussed the fullscreen aspect of your issue.

**Comment by Blad3forc3** [comment]
dvd_path fixed it but fullscreen command line?

edit  got it.. -full-screen
