### ISSUE TITLE
Burnout 3: Takedown: Multi-coloured/incorrectly rendered lake water

### ISSUE THREAD

**Issue by ghyujkilop** [xemu-project/xemu#1752]
### Title

[Burnout 3: Takedown](https://xemu.app/titles/4541005b/#Burnout-3-Takedown)

### Bug Description

Issue is at 8:34 in [this video](https://youtu.be/_QxE3kmfHjk) tested on native.

### Expected Behavior

[Burnout 3: Takedown (Xbox) Part 1](https://www.youtube.com/watch?v=d0TlBzqtKLA)

### xemu Version

Version: 0.7.131

### System Information

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
OS Platform: Windows
OS Version: 23H2
Manufacturer: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 2070/PCIe/SSE2
Driver: 4.0.0 NVIDIA 560.70
Shader: 4.00 NVIDIA via Cg compiler

**Comment by ghyujkilop** [comment]
Fixed in version 0.7.132.

**Comment by Adad-G** [comment]
> Fixed in version 0.7.132.

The issue was not fixed by the .132 version, you just had to restart the emulator. As I mentioned here: https://discord.com/channels/680221390359887933/680221390359888154/1269421526629748746
Before opening a request, do some research here on GitHub and on Discord with keywords.

**Comment by ghyujkilop** [comment]
> > Fixed in version 0.7.132.
> 
> The issue was not fixed by the .132 version, you just had to restart the emulator. As I mentioned here: https://discord.com/channels/680221390359887933/680221390359888154/1269421526629748746 Before opening a request, do some research here on GitHub and on Discord with keywords.

Problem was, I had closed & restarted more than once with the same issue.
