### ISSUE TITLE
Get Otogi and Grand theft auto 3 running on xemu

### ISSUE THREAD

**Issue by eltomas2003** [xemu-project/xemu#176]
These games crash after the first few moments see these videos
https://www.youtube.com/watch?v=l0T_JC0EA5w
and 
https://youtu.be/qTYuR331vCI?t=210

**Comment by mborgerson** [comment]
Thanks. If you are trying to report a crash, please provide more detailed information, such as the command line output after running this game. Until more information is provided, I'm going to close this issue since it lacks specifics.
