### ISSUE TITLE
(Feature Request) Disc support

### ISSUE THREAD

**Issue by RageXbox** [xemu-project/xemu#177]
When ever you insert an Xbox disc, it loads the game in the emulator like a real Xbox.

**Comment by GXTX** [comment]
You can tell xemu to use a physical disc drive instead of virtual, I don't believe anyone ever tested XQEMU/xemu with an Xbox drive. You should consider trying. :)

**Comment by mborgerson** [comment]
Your typical, unmodified consumer DVD drive is not going to be capable of switching to the game partition to read official Xbox discs, so the target user for this feature would be one with a specific drive or backups of their own discs. Practical benefit is just too limited to consider supporting this for now. If you want to look into it however, I encourage you to do so.
