### ISSUE TITLE
Version 0.7.132 has completely broken support for Series X Controller

### ISSUE THREAD

**Issue by OrganicOstrich** [xemu-project/xemu#1770]
### Bug Description

Latest update has completely broken support for Series X controller. The controller is still recognised by Xemu, and audio will even pass through via headphone jack, but the controller will not work. This is 100% Xemu, as the controller still works with all other emulators, and modern PC games. I have done multiple clean installs, but nothing has fixed this.  

### Expected Behavior

Controller should be automatically recognised like previous versions

### xemu Version

0.7.132 

### System Information

os_platform: Windows
os_version:  23H2
cpu: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
gl_vendor: NVIDIA Corporation
gl_renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
gl_version: 4.0.0 NVIDIA 556.12
gl_shading_language_version: 4.00 NVIDIA via Cg compiler

**Comment by Spidy123222** [comment]
Have you tried updating the firmware on the controller?

**Comment by antoniodesousa** [comment]
My Xbox Series X/S Controller works fine on 0.7.132

  CPU:  AMD Ryzen 9 6900HX with Radeon Graphics        
  OS Platform:  Windows
  OS Version:  23H2
  Manufacturer:  ATI Technologies Inc.
  GPU Model:  AMD Radeon RX 6600M
  Driver:  4.0.0 Core Profile Context 24.7.1.240711
  Shader:  4.60

**Comment by OrganicOstrich** [comment]
Updating the controller firmware did nothing, but updated the Nvidia drivers and did Windows Update which then made it start working again. Really strange but if it works, then it works.
