### ISSUE TITLE
Guest has not initialized the display (yet)

### ISSUE THREAD

**Issue by sekkingsoft** [xemu-project/xemu#178]
I keep getting this message: Guest has not initialized the display (yet)
Tried multiple different versjons, different roms, etc. with no luck. The emulator is using about 20-30 % CPU while displaying this, as well as changes in memory usage. So it seems to be doing something.

Specs: 2,8 GHz Intel i5 3360M, 8 gb ram, AMD Radeon HD 7500M graphics. Windows 10 Pro 1909.

![xemu](https://user-images.githubusercontent.com/59697679/106935197-5606db80-671b-11eb-8d03-a2f828d4ebb4.PNG)

**Comment by MasonT8198** [comment]
Okay so, Try packing your iso with Qwix, from it's folder format to xiso which qwix does, if you need help you can recomment or post on the discord :)

**Comment by Ernegien** [comment]
Please review the [getting started guide](https://github.com/mborgerson/xemu/wiki#getting-started) - this is usually a compatibility issue with your flash and/or boot ROMs.
