### ISSUE TITLE
xemu 0.7.133 crashes on startup on macOS: "Assertion failed: (glGetError() == GL_NO_ERROR), function pgraph_method, file pgraph.c, line 998"

### ISSUE THREAD

**Issue by svetlyo** [xemu-project/xemu#1788]
### Bug Description

Starting xemu crashes with:

```
Assertion failed: (glGetError() == GL_NO_ERROR), function pgraph_method, file pgraph.c, line 998.
Abort trap: 6
```

### Expected Behavior

xemu should not crash on startup.

### xemu Version

0.7.133

### System Information

OS: macOS Sonoma 14.7, CPU/GPU: Apple M3 Max 
CPU:
OS_Version: Version 14.7 (Build 23H124)
GL_VENDOR: Apple
GL_RENDERER: Apple M3 Max
GL_VERSION: 4.1 Metal - 88.1
GL_SHADING_LANGUAGE_VERSION: 4.10

**Comment by gottagofaster236** [comment]
This is a regression, crash not reproducible on v0.7.132

**Comment by mborgerson** [comment]
Perhaps an issue with glLineWidth. @faha223 can you take a look?

**Comment by gottagofaster236** [comment]
https://stackoverflow.com/a/34867791/6120487

**Comment by faha223** [comment]
Thanks @gottagofaster236 that's really helpful. I've submitted this PR to address the issue. Once the workflow run is done, can you try it out and let me know how it goes?

https://github.com/xemu-project/xemu/pull/1792

**Comment by svetlyo** [comment]
I've tried the build artifact https://github.com/xemu-project/xemu/actions/runs/11876322983/artifacts/2197726403 (the macOS, arm64, Release one for the PR 1792 (https://github.com/xemu-project/xemu/actions/runs/11876322983/job/33094533367?pr=1792))

It starts up just fine now.

**Comment by mborgerson** [comment]
Thanks
