### ISSUE TITLE
[Appimage]: Extra xemu sub-directory created (~/.local/share/xemu/xemu/)

### ISSUE THREAD

**Issue by davidhedlund** [xemu-project/xemu#1800]
### Bug Description

- The AppImage creates `~/.local/share/xemu/xemu/`
- All configuration data is stored in this nested `xemu` subdirectory

### Expected Behavior

The AppImage should create the configuration directory without the redundant subdirectory:
- It should create `~/.local/share/xemu/`
- All configuration data should be stored directly in this directory

### xemu Version

xemu-v0.7.132-x86_64.AppImage

### Additional Context

The AppImage version of xemu is currently creating a redundant subdirectory in the user's configuration path.

**Comment by mborgerson** [comment]
Not a bug. This is a result of the SDL2 preferences directory system: https://wiki.libsdl.org/SDL2/SDL_GetPrefPath

The top level xemu dir is the organization, the next level is the application name. If for example xemu project released a helper app that needed a directory, it would go under xemu/helper.

**Comment by davidhedlund** [comment]
> Not a bug. This is a result of the SDL2 preferences directory system: https://wiki.libsdl.org/SDL2/SDL_GetPrefPath
> 
> The top level xemu dir is the organization, the next level is the application name. If for example xemu project released a helper app that needed a directory, it would go under xemu/helper.

Thank you for explaining this.
