### ISSUE TITLE
EEPROM CLI Tool

### ISSUE THREAD

**Issue by freedbygrace** [xemu-project/xemu#1804]
### Feature Request

There is already code to programmatically generate a EEPROM.bin when you do not include one with XEMU. My question is, is it possibly to make this functionality a CLI took so that a random EEPROM can generated for easier setup when doing a large setup for a LAN party or something. Command line parameters could be used like the following example.

```
XEMU.exe --create-eeprom --template-path "PathToEEPROM" -SerialNumber "NewSerialNumber" -MACAddress "NewMACAddress" -Output-Path "NewPathToEEPROM.bin"
```

or

```
eepromcli.exe --create-eeprom --template-path "PathToEEPROM" -SerialNumber "NewSerialNumber" -MACAddress "NewMACAddress" -Output-Path "NewPathToEEPROM.bin"
```

**Comment by mborgerson** [comment]
I have a tool that does this: https://github.com/mborgerson/xbeeprom

We have issue #1355 open already for integrated eeprom editing. I'll add a note about CLI options and close this as a duplicate.
