### ISSUE TITLE
Z ording issues on several games

### ISSUE THREAD

**Issue by svensvond** [xemu-project/xemu#1805]
### Bug Description

Some games don't z-ordering correctly leading to seeing things you shouldn't

see #1016
see #749

### Expected Behavior

Should not be visible through objects

### xemu Version

all versions

### Additional Context

I want to bring this up since there is no fix for years now - it makes "a lot" of games unplayable - not sure if many are aware of.

**Comment by mborgerson** [comment]
This is not helpful. We do not need new issues highlighting existing issues that have not been fixed as fast as you would like.

If you want particular issues fixed faster and are prepared to pay contract engineering rates, contact me. Otherwise, be patient and the bugs will be fixed in due time.
