### ISSUE TITLE
Add Cerbios Compressed Image (CCI) Support

### ISSUE THREAD

**Issue by leonewt0n** [xemu-project/xemu#1809]
### Feature Request
Allow picking the CCI file for loading when using Cerbios,

https://github.com/Team-Resurgent/Repackinator
https://www.arcadepunks.com/xbox-master-games-collection-cci-complete

**Comment by mborgerson** [comment]
We have a discussion about compressed ISO's in #238, so I'll mark this issue as a duplicate
