### ISSUE TITLE
Docker: compile errors (win-cross)

### ISSUE THREAD

**Issue by polymetal0** [xemu-project/xemu#1824]
### Bug Description

Some errors show up when trying to build with Docker on Windows:

1. 
![vulkan error](https://github.com/user-attachments/assets/8ef21331-9744-4e56-9bb4-63efc9ab9cae)
2. 
![glslang error](https://github.com/user-attachments/assets/e4c0aefc-d80f-428b-9c4b-54e142b34f6d)
3.
![error](https://github.com/user-attachments/assets/a772a716-d58d-435c-ad6a-5d264e6ac746)

### Expected Behavior

Docker should build the project with command `docker run --rm -v $PWD/xemu:/xemu -w /xemu \
    -e CCACHE_DIR=/xemu/ccache \
    ghcr.io/xemu-project/xemu-win64-toolchain:latest \
    ./build.sh -p win64-cross`

### xemu Version

0.8.1

### Additional Context

I could fix the errors by adding the files to the project myself, and removing some lines in meson.build:

1. 
![vulkan](https://github.com/user-attachments/assets/fc73ffb1-c931-491f-8012-39151c22e25e)
contents
![vulkan content](https://github.com/user-attachments/assets/0b6748bd-5e6c-4350-b679-8271f7292adc)
2.
![glslang](https://github.com/user-attachments/assets/e0335475-f2ba-42a2-9d4e-5ca0ef2ef2c5)
contents
![glslang content](https://github.com/user-attachments/assets/09cde10c-a746-4dba-b8c7-169e23bca883)
3.
![error fix](https://github.com/user-attachments/assets/a074b40c-9238-4dc7-8ac4-8c42cd9bbe84)

**Comment by mborgerson** [comment]
Pull the latest docker image
