### ISSUE TITLE
Video diagnostics image from Conker during War Section (Very Low FPS)

### ISSUE THREAD

**Issue by 7oxicshadow** [xemu-project/xemu#189]
Not sure if this tells you anything but the war section on Conker seems to have a large number of inline elements when compared to other parts of the game. Given that other parts of the game seem to have ~700 inline elements and this section has >15000 I am guessing it is the source of the problem?

As you can see from the image it hovers around 2 fps.

![Screenshot_20210211_221315](https://user-images.githubusercontent.com/10350138/107705727-14e06f80-6cb7-11eb-9602-e1c81cd875db.png)

**Comment by mborgerson** [comment]
Thanks for testing, but discussion like this is best suited for the Discord server.

**Comment by 7oxicshadow** [comment]
True but I would prefer not to give discord my phone number. Either way as long as you have seen it now, Thats the main thing.

Thanks.

**Comment by mborgerson** [comment]
I can grant you access
