### ISSUE TITLE
Sky looks orange in GTA vice city

### ISSUE THREAD

**Issue by eltomas2003** [xemu-project/xemu#199]
[see here](https://www.youtube.com/watch?v=yhHaNZi2nN4) also the back window of the car sometimes looks red.

**Comment by Ernegien** [comment]
The GitHub issues system should be reserved for more technical discussion. If you can't dig up more detailed information on comparisons between retail/xemu or between xemu itself in case of regression (with specific examples/screenshots) it's probably best left for discussion on Discord instead.
