### ISSUE TITLE
Support specifying path to disc ISO from launch arguments

### ISSUE THREAD

**Issue by KevinLeenders** [xemu-project/xemu#20]
As discussed in Discord: https://discordapp.com/channels/680221390359887933/680221390359888154/763018501065277490

Great work: CakeLancelot

Please natively support loading ISO files from commandline, so we (end users) can implement  this emulator into our favorite front-end (eg LaunchBox).

Most front-ends use something like: xemu.exe "FULL\PATH\TO\ROM\FILE"

**Comment by klepp0906** [comment]
+1,  I want to give this a shot even though I'd need to convert my titles.   Wont even begin that mess until I know it supports CLI though.   I couch game too much so frontends or bust.

**Comment by CakeLancelot** [comment]
I do have a batch script that edits your xemu config file and launches a specified game, then puts it back to how it was when you're done. If you're on MacOS/Linux, it could probably be converted to a bash script easily enough. You can check it out [here](https://github.com/CakeLancelot/xemu-fe).

**Comment by klepp0906** [comment]
hey thanks for sharing.  If i get super impatient I'll give this a rip.  I dont doubt it works for its intended purpose but im a stickler for avoiding workarounds when I can.

Same reason i hope to swap to this as soon as viable as opposed to cxbxr.  Its more of an emulator than the aforementioned and while that doesnt really mean "much" to an end user, it tickles my ocd a fair bit for whatever reason.

**Comment by GXTX** [comment]
You could do something stupid like this.

Set `dvd_path` to `FRONTEND`. On launch you *must* specify that you want to connect a DVD drive using `-drive index=1,media=cdrom` to use some ISO with this you would append `file=<some path>`.

Doesn't break anything else specific to xemu as far as I can tell.

```patch
diff --git softmmu/vl.c softmmu/vl.c
index a6193761e9..9420f5ac42 100644
--- softmmu/vl.c
+++ softmmu/vl.c
@@ -3065,23 +3065,21 @@ void qemu_init(int argc, char **argv, char **envp)
     }
 
     const char *dvd_path = "";
+    static const char *front_end = "FRONTEND";
     xemu_settings_get_string(XEMU_SETTINGS_SYSTEM_DVD_PATH, &dvd_path);
-    if (strlen(dvd_path) > 0) {
+    if (strlen(dvd_path) > 0 && strcmp(front_end, dvd_path) != 0) {
         if (xemu_check_file(dvd_path)) {
             char *msg = g_strdup_printf("Failed to open DVD image file '%s'. Please check machine settings.", dvd_path);
             xemu_queue_error_message(msg);
             g_free(msg);
             dvd_path = "";
         }
-    }
-
-    // Always populate DVD drive. If disc path is the empty string, drive is
-    // connected but no media present.
-    fake_argv[fake_argc++] = strdup("-drive");
-    char *escaped_dvd_path = strdup_double_commas(dvd_path);
-    fake_argv[fake_argc++] = g_strdup_printf("index=1,media=cdrom,file=%s",
+        fake_argv[fake_argc++] = strdup("-drive");
+        char *escaped_dvd_path = strdup_double_commas(dvd_path);
+        fake_argv[fake_argc++] = g_strdup_printf("index=1,media=cdrom,file=%s",
         escaped_dvd_path);
-    free(escaped_dvd_path);
+        free(escaped_dvd_path);
+    }
 
     fake_argv[fake_argc++] = strdup("-display");
     fake_argv[fake_argc++] = strdup("xemu");
```

**Comment by klepp0906** [comment]
nice!  too soon to start asking about a --fullscreen switch huh? :p lol

**Comment by awsms** [comment]
Could we have an option that disable all xemu's gui elements and only boot to the console/game? Like "batch" modes in duckstation, dolphin etc
