### ISSUE TITLE
Possible Debug build for Xemu?

### ISSUE THREAD

**Issue by eltomas2003** [xemu-project/xemu#207]
If you want to be a tester for these more complex open source projects, use DEBUG build of the program. Learn what kind of information it spits out to you in console. Run games that are supported very well. Learn their console output. See if you can spot a pattern. Run unsupported games and check their debug output. See if you can catch on to what is missing/abnormal in the unsupported games. If documentation exists for the complex emulators, read them to get a gist of the program flow.

This could possibly be helpful for the development for Xemu.

**Comment by Ernegien** [comment]
Debug builds already exist for xemu in [releases](https://github.com/mborgerson/xemu/releases) but I'm not sure they're as magical as you think they are. Troubleshooting issues can still be highly technical in nature and require full stack knowledge of multiple subjects. All contributions are welcome (and there's plenty of low-hanging fruit for even non-technical people such as documentation) but this probably shouldn't be a GitHub issue.

**Comment by eltomas2003** [comment]
How do I access the debug builds?

**Comment by Ernegien** [comment]
It depends on your target platform, but here's the latest [debug build for Windows](https://github.com/mborgerson/xemu/releases/download/build-202102190417/xemu-win-debug.zip).
