### ISSUE TITLE
[Bug] Clipping in Halo 2

### ISSUE THREAD

**Issue by BiatuAutMiahn** [xemu-project/xemu#226]
`Existed in 76272d3 and fc73893, did not test prior builds`

`For this first screencap, the shadow is affect at the top, on the side of the MAC gun`
![ezgif-2-77f8b9cab93a](https://user-images.githubusercontent.com/6149596/109938887-813f0500-7c9e-11eb-9b12-644ff818a510.gif)

**Comment by Alastair0100** [comment]
is this the same issue? https://github.com/mborgerson/xemu/issues/55

**Comment by BiatuAutMiahn** [comment]
It is, yes. Im not sure about the gif though.

Edit: I removed the other issue that are from issue #55. I'm not sure about this lighting issue at a distance
