### ISSUE TITLE
[Bug] Some textures not rendered properly in MagiDeathFight!

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#242]
Xemu   
![2021 03 08-11 13](https://user-images.githubusercontent.com/71127352/110316936-5688df80-8003-11eb-8a79-441de3bad0cf.png)
Cxbx reloaded
![2021 03 08-11 26](https://user-images.githubusercontent.com/71127352/110317209-b97a7680-8003-11eb-9c68-e2208f76894b.png)
Xemu
![2021 03 08-11 30_01](https://user-images.githubusercontent.com/71127352/110317100-8df78c00-8003-11eb-9d21-4bf7a2fb0772.png)
Cxbx reloaded
![2021 03 08-11 38](https://user-images.githubusercontent.com/71127352/110317160-a36cb600-8003-11eb-9b48-88e549845a9f.png)

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: N/A

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by PatrickvL** [comment]
Not sure if mentioning Cxbx-Reloaded as a reference is the best here 🤔

**Comment by Triticum0** [comment]
I agree but dont have a capture card to use my xbox as a reference

**Comment by Triticum0** [comment]
The bugs still persists as well i found more bugs with the model which didn't appear when testing on AMD GPU
