### ISSUE TITLE
ToeJam & Earl III worked once but every time since I get black screen after hitting any button 

### ISSUE THREAD

**Issue by Jayinem** [xemu-project/xemu#251]
Nvidia GTX 1650 16 GB Ram up to 4.1Ghz
Processor	Intel(R) Core(TM) i5-9300H 4 Core(s), 8 Logical Processor(s)

I converted folder with XDVDMulleter, then when started having problems I Tried Qwix but it made no difference.

If I don't hit any button the cutscenes will just keep playing, but regardless of how long I wait if I hit ANY button to start the game  it will go to black screen and stay there. I'm using xinput but just to try it I switched to keyboard it made no difference.

**Comment by poobarfoob** [comment]
Might be a regression or cache corruption, try using a new dashboard image first and see if that fixes it

**Comment by Jayinem** [comment]
Seems to have worked, thanks!
