### ISSUE TITLE
Miscolored (rainbow) elements in Conker L&R

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#254]
Discovered after #104 and #253. Looks like a combiner bug but needs more investigation.

![image](https://user-images.githubusercontent.com/8210/110939268-61d55700-82f2-11eb-94dc-68584385e0ff.png)

Titles: 4d530051

**Comment by Xpmaster2002** [comment]
seems to be crashing at certain points right before of after something loads, like an ingame event starts then it crashes or an in game event finishes then it crashes...
![Untitled](https://user-images.githubusercontent.com/52110340/112744343-5a0de780-8f6d-11eb-9b8b-bce5ea657ace.jpg)

**Comment by Xcedf** [comment]
Don't know when happened exactly, but issue is fixed on latest release
tried vs my old build at two places with issue I know:
Before:
https://youtu.be/INN-RbSHi08
After:
https://youtu.be/FiBPthki_zg

Before:
https://youtu.be/yaTa9xXyN2E
After:
https://youtu.be/UCSHBlhG1LQ

Even Xbox emu for Xbox360 doesn't have this issue fixed

**Comment by mborgerson** [comment]
Great thanks
