### ISSUE TITLE
Eject disks during intro crashes xemu

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#255]
When ever you eject a disk while the intro FVM playing an assertion crashes the emulator:
Assertion failed: in_pitch >= in_width * 2, file /xemu/hw/xbox/nv2a/pgraph.c, line 4541
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L4541
Steps to reproduce this issue:
1.Insert a disk
2.Play FMV
3.Eject disk

### Expected Behavior

It should send you to the dashboard.

### Version
* Version: build-202106020756( 3884b8d)
* Last-known Working: Unknown

### System Information
| Field | Value |
|-------|-------|
| OS			|Windows 10 64-bit (21H1)| 
| CPU			| AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz		| 
| Graphics Device	| AMD Radeon RX 5700 XT		                |
| Graphics Driver	| 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017|

**Comment by MasonT8198** [comment]
What game? Also this is probably best discussed in the discord, you should join if you want!

**Comment by Triticum0** [comment]
I merged this issue with #330

**Comment by brad86m** [comment]
This still happens. Been like this for many years.

Every time I got to eject a disc to load a new one, I get the fatal error popup. Abort, Retry, Ignore options do nothing. I end up having to open the ini file to manually remove the current game entry.
