### ISSUE TITLE
[Feature request] Snapshot option in main menu

### ISSUE THREAD

**Issue by mrdeathjr28** [xemu-project/xemu#267]
Hi

Maybe can add snapshot option in main menu (more user frendly)

Thanks

**Comment by mborgerson** [comment]
It is planned, thanks

**Comment by MasonT8198** [comment]
Thanks, but this is planned for the future, currently the time effort is going into surface scaling, and performance improvements. In monitor you can use savevm and loadvm to use a snapshot
