### ISSUE TITLE
[Feature request] add internal resolution modes (for more quality)

### ISSUE THREAD

**Issue by mrdeathjr28** [xemu-project/xemu#268]
Hi

maybe can add internal resolution modes if is possible (for more quality) example: dolphin - ppsspp - pcsx2

thanks

**Comment by nex86** [comment]
I agree, 8X would be a doable thing, still depending on the game.
My 3080 is 50% utilized in conker at 4X.

**Comment by mborgerson** [comment]
It is being worked on, see feature branch. Please join Discord for general discussion instead of creating GitHub issues
