### ISSUE TITLE
Feature Request: make a UWP version to run on xbox one dev mode

### ISSUE THREAD

**Issue by adamcarter1** [xemu-project/xemu#272]
Lots of original OG xbox games will never get backward compatibility. Wondering if there was a way to add this to dev mode and play my old og xbox games on xbox one

**Comment by MasonT8198** [comment]
It’s not really in the cards right now, for the reasons of UWP is deprecated so soon it’ll be outdated anyway. B.) If it ever moves to retroarch when xemu gets more stable I can see it moving over to the xbox one that way. But no it’s not really planned

**Comment by BiatuAutMiahn** [comment]
Retroarch is what im waiting for

**Comment by mborgerson** [comment]
There are no plans to support Xbox One or Series X as target platforms at this time.

**Comment by MrGreedyPot** [comment]
After all these years we finally got Mesa and OpenGL now
Therefore Xemu could be ported via UWP?

https://github.com/aerisarn/mesa-uwp

**Comment by MrGreedyPot** [comment]
Citra is already being ported

https://github.com/YTReviveMe/RetroArch-uwp/releases
