### ISSUE TITLE
Wiki Instructions for Building on Ubuntu

### ISSUE THREAD

**Issue by mike-matera** [xemu-project/xemu#276]
Hello, 

I just tried to build the latest version on Ubuntu and it looks like the `ninja-build` package is required in recent versions. That's a non-default package so it would help people if the wiki had this command: 

```
sudo apt install build-essential libsdl2-dev libepoxy-dev libpixman-1-dev libgtk-3-dev libssl-dev libsamplerate0-dev ninja-build
```

With that fix the latest branch builds and runs fine.

**Comment by mborgerson** [comment]
That's right, it's a recent change. I'll update the wiki, thanks.
