### ISSUE TITLE
Graphical issues in 'Grabbed by the Ghoulies'

### ISSUE THREAD

**Issue by Phat-Joe** [xemu-project/xemu#286]
I believe this to be a lighting issue. cutscenes don't dsiplay properly. The game presents the story in a comic book fashion, and the pages are unreadable due to them being black. When ever the page turns, you can catch a glimpse of the panels, thats why I believe its the lighting of the game engine

**Comment by theboy181** [comment]
Do you happen to know what part of the emulation codes is causing this issue? If not I would share this information with the compatibility section in the emulator instead.

**Comment by mborgerson** [comment]
Thanks for reporting. Please update this issue to include screenshots of what happens in xemu vs on a real Xbox and include the version that you've tested with. You can update this issue or file a new one with the recently added templates.
