### ISSUE TITLE
Save state feature request

### ISSUE THREAD

**Issue by m-mkhaimer** [xemu-project/xemu#293]
### Feature Request
It's in the web site that the emulator have save states feature, however I can't find it any any version

### Alternatives
Nothing

**Comment by mborgerson** [comment]
See https://github.com/mborgerson/xemu/wiki/Snapshots

**Comment by ruthan** [comment]
This link, links nowhere to generic github page..

  On emulator page is that save states / snapshots are supported, but in emulator menu is nothing like - Save / LoadState, maybe its only on some hotkey, but its not enough.

**Comment by mborgerson** [comment]
@ruthan docs moved to website: https://xemu.app/docs/snapshots/

**Comment by ruthan** [comment]
Thanks, but command line based solution IMHO is not good enough.. and nobody sane would search it under some monitor, only some Linuxian madman maybe.

**Comment by mborgerson** [comment]
@ruthan The commands are easy to use, just follow the documentation. A point-and-click interface will come eventually. Understand this is a project developed by volunteers and provided to you at no cost, then manage your expectations accordingly.
