### ISSUE TITLE
Release does not include licenses

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#296]
The project seems to use a few different Open Source components and doesn't distribute the license's with it. Now that it's packed it's harder to see what open source components the project uses.

**Comment by MasonT8198** [comment]
It would be possible to pack the licenses in via Version.Rc

**Comment by mborgerson** [comment]
~~Yes, I was planning to do this shortly~~ You can now find license information for Windows and macOS builds in the release archive.
