### ISSUE TITLE
Build Artifacts have 2 .Zip Files

### ISSUE THREAD

**Issue by MasonT8198** [xemu-project/xemu#297]
1. (...) Download an artifact, Windows Version Specifically

### Expected Behavior

(...) The Artifact Build is not expected to have an extra folder.

### Additional Context

Since the recent build changes, pulling xemu artifacts has an extra folder, the zip folder, then when you unzip it there is another zip folder. Minor Housekeeping-esque nit.

**Comment by dracc** [comment]
I don't think this is the case anymore?
