### ISSUE TITLE
Def Jam Fight For NY SSX Tricky Ssx tours and the sims bustin out broken 

### ISSUE THREAD

**Issue by kenrealwilliams** [xemu-project/xemu#301]
**Def** Jam Fight For NY is not working and it’s broken and  another game malice is broken and another game ssx tours and ssx tricky and the sims bustin out is not working can you fix it they keep crashing and freezes

**Comment by theboy181** [comment]
I think you are supposed to be filling out the bug report for these. https://github.com/mborgerson/xemu/issues/new?assignees=&labels=bug&template=title-issue.md&title=Game+Name%3A+Brief+Issue+Description

You can also, use the HELP menu to submit compatibility issues, but I am certain these have been sighted already.

**Comment by blakeplusplus** [comment]
this should be closed as invalid/not planned
