### ISSUE TITLE
SSX Tricky And Malice Is broken And Def Jam Fight For Ny

### ISSUE THREAD

**Issue by kenrealwilliams** [xemu-project/xemu#303]
These games are broken and doesn't work on xemu and buggy and glitchy 
Xbox Games: **Malice** **Def**Jam**Fight****** **For** **NY**
TheSimsBustinOut****

**Comment by Ernegien** [comment]
Please stop opening up low-effort issues on this repository.

**Comment by kenrealwilliams** [comment]
Ok sorry
