### ISSUE TITLE
Support formats other than iso (jtag)

### ISSUE THREAD

**Issue by klepp0906** [xemu-project/xemu#31]
Long ago in the name of saving space, i extracted all my titles to folders without con as cxbxr was able to run them fine.  I'm unsure if there is a plan to support other formats in the future, but just in case it hasnt crossed your mind, I wanted to put this out there.

Thanks for your work on the project <3

**Comment by mborgerson** [comment]
Thanks! Loading game files outside of a .iso image is not a planned feature, so I'm going to close this issue. 

Fortunately, it's very easy to pack your game files into a .iso using extract-xiso, and it helps keep your games organized as well.

Come join us on the xemu Discord Server if you want to chat.

**Comment by dracc** [comment]
Xemu emulates the Xbox hardware, not the software.
This means you can put your extracted games on the HDD image just like you would on your physical Xbox.

**Comment by klepp0906** [comment]
oh, excellent.  I didnt even think to consider that.   The only caveat/complication created then being the folders are all named via redump standard now and I imagine to function when placed on the hdd/vfs they'd need to be named back to the titleid or whatnot?

also admittedly havent tried xemu yet so unsure if the feature is present, but I keep my emulators and titles on different disks (for space, backup, and organizational sake) so a feature to "add games" persay by scanning a directory would be awesome.

Otherwise it seems I'd be left with potentially not only renaming my titles, but moving things to my emulator drive, xemu to my game drive, or copying them which would then use double the space.

(also considered symlinks but the naming issue is still gonna be troublesome) unsure if xbox titles have the equivalent of like a ps3's param.sfo that could scrape for what title it actually is to circumvent this or?
