### ISSUE TITLE
Unknown Blend Source Factor assertion in some games

### ISSUE THREAD

**Issue by MasonT8198** [xemu-project/xemu#313]
### Title Information

* https://xemu.app/titles/45410065
* https://xemu.app/titles/4541004e
* https://xemu.app/titles/4541003b
* https://xemu.app/titles/45410087
* https://xemu.app/titles/45410061
* https://xemu.app/titles/45410044
* https://xemu.app/titles/45410038

### Bug Description

This Bug is based towards `Unknown Blend Source Factor 0xffffffff`

Line: 0xffffffff Assertion failed: false, file D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c, line 1447

### Expected Behavior

It should get past this assertion with the known factor

### Additional Context

This is for documentation purposes, however I encourage anyone who runs into this assertion `0xffffffff Assertion failed: false, file D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c, line 1447` to report it here that way it can be documented. Doing this allows the project to track this sort of issues that way they can be fixed. Thank you!

**Comment by Triticum0** [comment]
Other titles affected:
https://xemu.app/titles/45530019/#Project-Snowblind
https://xemu.app/titles/45410074/#Cricket-2005
https://xemu.app/titles/45410049/#Def-Jam-Fight-for-N
https://xemu.app/titles/4541001c/#NBA-Live-2003
https://xemu.app/titles/4541004a/#UEFA-Euro-2004-Portugal

*Whiplash is a different assertion move to it own pr

**Comment by MasonT8198** [comment]
> Other titles affected:
> https://xemu.app/titles/45530011/#Whiplash
> https://xemu.app/titles/45530019/#Project-Snowblind
> https://xemu.app/titles/45410074/#Cricket-2005
> https://xemu.app/titles/45410049/#Def-Jam-Fight-for-N
> https://xemu.app/titles/4541001c/#NBA-Live-2003
> https://xemu.app/titles/4541004a/#UEFA-Euro-2004-Portugal

Just for clarification, I'm assuming that you commented out the previous assertion on these, as I'm checking the compat logs and not seeing an unknown blend source factor in their description. @Triticum0

**Comment by Triticum0** [comment]
I check builds to l to make sure it was the same assertion
UEFA EURO 2004 June 23 https://github.com/mborgerson/xemu/blob/7f4b9d5480787df1b41e62447bedc4a76cfd198b/hw/xbox/nv2a/nv2a_pgraph.c#L1067
Def Jam Oct 29 https://github.com/mborgerson/xemu/blob/3c6596975d2704ef61ab1126b642e252571e73e3/hw/xbox/nv2a/pgraph.c#L1151
Project snowblind Jan 17 https://github.com/mborgerson/xemu/blob/aab63105fce0b8f2699b520a157d2b0e95539e93/hw/xbox/nv2a/pgraph.c#L1163
cricket 2005 24 Jan https://github.com/mborgerson/xemu/blob/aab63105fce0b8f2699b520a157d2b0e95539e93/hw/xbox/nv2a/pgraph.c#L1163
NBA Live 2003 26 Jan https://github.com/mborgerson/xemu/blob/9ca79f75d8ef61f3901faf47550d1377daf50d7f/hw/xbox/nv2a/pgraph.c#L1163

**Comment by MasonT8198** [comment]
> I check builds to l to make sure it was the same assertion
> 
> UEFA EURO 2004 June 23 https://github.com/mborgerson/xemu/blob/7f4b9d5480787df1b41e62447bedc4a76cfd198b/hw/xbox/nv2a/nv2a_pgraph.c#L1067
> 
> Def Jam Oct 29 https://github.com/mborgerson/xemu/blob/3c6596975d2704ef61ab1126b642e252571e73e3/hw/xbox/nv2a/pgraph.c#L1151
> 
> Project snowblind Jan 17 https://github.com/mborgerson/xemu/blob/aab63105fce0b8f2699b520a157d2b0e95539e93/hw/xbox/nv2a/pgraph.c#L1163
> 
> cricket 2005 24 Jan https://github.com/mborgerson/xemu/blob/aab63105fce0b8f2699b520a157d2b0e95539e93/hw/xbox/nv2a/pgraph.c#L1163
> 
> NBA Live 2003 26 Jan https://github.com/mborgerson/xemu/blob/9ca79f75d8ef61f3901faf47550d1377daf50d7f/hw/xbox/nv2a/pgraph.c#L1163

Okay thank you, I will add these later
