### ISSUE TITLE
[Assertion] Zeta surface clear for Z24S8 (float) is untested

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#322]
### Title Information
https://xemu.app/titles/454d0001/#Antz-Extreme-Racing
https://xemu.app/titles/4143000a/#ATV-Quad-Power-Racing-2
https://xemu.app/titles/494c0002/#Braveknight-Leverant-Eiyuuden
https://xemu.app/titles/4b4e0003/#ESPN-NFL-PrimeTime-2002
https://xemu.app/titles/5553000b/#Largo-Winch-Empire-Under-Threat
https://xemu.app/titles/4253000a/#Malice
https://xemu.app/titles/494c0001/#Metal-Dungeon
https://xemu.app/titles/54530005/#RoboCop
https://xemu.app/titles/41560009/#Rally-Fusion-Race-of-Champions
https://xemu.app/titles/49470004/#TransWorld-Snowboarding
https://xemu.app/titles/4553000e/#The-Italian-Job
https://xemu.app/titles/4d530048/#The-Wild-Rings
https://xemu.app/titles/41540001/#Touge-R

### Bug Description
The untested code is here:
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L3056-L3057

In particular, test this function:
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L6314-L6321

Steps to reproduce this issue:
1.Insert disk
2. Game crashes

### Expected Behavior

Should not hit assertion and make it into menus

<h3>Version</h3>
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

###Additional Context
This was ripped straight from xqemu (https://github.com/xqemu/xqemu/issues/215) so credit goes to JayFoxRox. I cross Referenced using the Compat list to make sure they were correct

**Comment by abaire** [comment]
@mborgerson FYI - I've started looking into this and I think we immediately run into precision issues with OpenGL.

~~I think the clear depth may be fixable by using double precision (see https://github.com/abaire/xemu/commit/c058d993355fc98cb67d5601b4ba07dcf5c3bbc5) and this seems to produce output that is similar, but not identical, to what I see on hardware when dealing with clear depths very near to `f24_max` with geometry that also has very high Z values.~~ Investigated more, at least on Linux it looks likely that the OpenGL implementation is using single precision for the depth clear behind the scenes - if I `glGet` the value as a double immediately after writing it as a double it's 0 for very small values requiring double precision.

Shallow geometry seems to be squashed into a small range > 0.0 such that clear depths from 0x000000 - ~0x800000 produce show nothing at all and then from ~0x80000 to 0xFEFFFF (`z24_max`) everything is visible. My guess is that this has to do with compressing the 24-bit float depths down to the (-1,1) NDC coordinates in the vertex shader, coupled with the (0,1) clear depth range, whereas the Xbox hardware lets you operate on full resolution floats directly.

I'm not enough of an OpenGL expert to know if there's a solution to this offhand. 
Poking around I see that there was an old Nvidia extension (`NV_depth_buffer_float`) that looks like the precursor to `FLOAT_32_UNSIGNED_INT_24_8_REV` being added. It supported `DepthRangedNV` which bypassed the `DepthRange` clamping behavior (which would remove the jump to doubles when doing a `glClear` and rule out precision loss there). I'm not sure if there's something similar to be able to deal with the precision in the vertex shader, but presumably having manufacturer-specific extensions would be a non-starter anyway.

**Comment by abaire** [comment]
Tracking this in case xemu moves to Vulkan before a GL-friendly solution is found: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_range_unrestricted.html
