### ISSUE TITLE
Unhandled NV_IMAGE_BLIT methods

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#324]
### Title Information

https://xemu.app/titles/41560005/#Blade-II - Crashes before Intros
https://xemu.app/titles/4d570011/#Dr-Muto - Crashes when going in-game
https://xemu.app/titles/4b420003/#Rogue-Ops  - Crashes After Intros
https://xemu.app/titles/56560029/#Die-Hard-Vendetta - Crashes when going in-game

### Bug Description
The games crash with an assertion:
Unknown blit operation: 0x2
https://github.com/mborgerson/xemu/blob/ebcc77c6c82e6457df9f7f769820fd5da0d6a0ce/hw/xbox/nv2a/pgraph.c#L915

### Expected Behavior
Should make it in-game

<h3>Version</h3>
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by abaire** [comment]
For Dr. Muto, `image_blit->operation` == `0x02` (as of Xemu 0.6.2-5, the only operation supported by `NV095_SIZE` is `NV09F_SET_OPERATION_SRCCOPY` which == `0x03`).

I'm assuming by context that this is `BLEND_AND` (https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/nouveau/include/nvhw/class/cl902d.h#L172)

**Comment by Triticum0** [comment]
@abaire Tested all the games on the list and there bilt operation are the same as Dr Muto

**Comment by abaire** [comment]
> @abaire Tested all the games on the list and there bilt operation are the same as Dr Muto

Perfect, this should be straightforward to fix then (at least an initial inefficient fix). Thanks for testing!

**Comment by Triticum0** [comment]
@abaire I retested and unfortunately Blade 2 uses 2 Blitting surface formats,So as well 0x2 it also has 0x6 blit surface format.

**Comment by abaire** [comment]
> @abaire I retested and unfortunately Blade 2 uses 2 Blitting surface formats,So as well 0x2 it also has 0x6 blit surface format.

No problem, thanks for checking! 

Looks like that will be `NV902D_SET_OPERATION_V_BLEND_PREMULT` which I hope will be straightforward based on what I've learned about the BLEND_AND. 
I think we'll need to add support for the `beta4` context and do per-channel multiplication but should be otherwise easy. I'm going to be away from my hardware until next week though, so I can write a test bed but won't be able to verify the behavior and implement it in xemu for a bit.

**Comment by Triticum0** [comment]
No Problem, The work you been for the last 2 month been amazing, so it can wait.

**Comment by abaire** [comment]
Hey @Triticum0 are you sure Blade 2 fails with `0x6` and not `0x5`? 

Digging more on the hardware it seems that `0x6` is not valid and that `0x5` is probably `NV902D_SET_OPERATION_V_BLEND_PREMULT`.

If it is `0x6`, I wonder if they're catching and handling the error that gets raised by the hw?

**Comment by Triticum0** [comment]
I tested it again and still gave me Unknown blit surface format: 0x6
I can re-dump my iso and retest tomorrow and then i can tell you for certain, that it blade 2 which is causing the issue.

**Comment by Triticum0** [comment]
I could also use your window debug pr if it would give you any useful info.

**Comment by abaire** [comment]
Very interesting.

The nv2a debug patch probably wouldn't tell us a ton as a) it's only part of the picture; and b) it is a live view and some of the DMA channels are likely to be modified while the game is running. It's mostly useful in tandem with the nv2a log, which would be useful.

If you don't mind doing a custom build, you could uncomment https://github.com/mborgerson/xemu/blob/master/hw/xbox/nv2a/debug.h#L32 and capture the data that gets printed to the console.This will probably make things unusably slow, but should show enough contextual info for me to duplicate the state in my test program (this is how I worked out the BLEND_AND handling). 

I guess it's possible that op `0x06` is supported but needs some setup that's totally different from operations `2-5`...

**Comment by Triticum0** [comment]
[Debug output.txt](https://github.com/mborgerson/xemu/files/7630337/Debug.output.txt)
@abaire It so big i can only send as an txt file. hopefully this helps

**Comment by abaire** [comment]
@Triticum0 this is excellent, thanks! I'll dig into it and see if I can figure out if it's doing something special.

**Comment by abaire** [comment]
@Triticum0 I should've just read your error report more carefully :). It's the surface format that isn't supported, I misread it to be the operation.

Surface format 6 looks like it's [`X8R8G8B8_Z8R8G8B8`](https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/-/blob/master/src/hwdefs/nv01_2d.xml.h#L260)

This is unrelated to this bug (which is focused on the blit operations) - would you mind spinning out a new bug tracking this error? 

Now that I've actually read your report correctly and with the nv2a trace you provided I can hopefully set up a test to see what it does to the Z-buffer and create a fix against the new bug.

**Comment by Triticum0** [comment]
Done, just comment if you want any changes to the issue #578

**Comment by abaire** [comment]
#581 should've fixed the Blade 2 issue (looks like I forgot to tag this bug in the PR since we had #578 tracking it explicitly)

**Comment by Triticum0** [comment]
#624 Fixed this issue. The games still need a report written for them.

But thank you Abaire and Matt for improving the emulator.

Here is some also some more low hanging issue which need to be verified if working correctly as there untested.
#367, #331, #379
