### ISSUE TITLE
[Assertion] pg->inline_elements_length == 0

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#329]
### Title Information

https://xemu.app/titles/4e4d0009/#Breakdown
https://xemu.app/titles/53450033/#ESPN-College-Hoops-2K5
https://xemu.app/titles/54540091/#College-Hoops-2K6
https://xemu.app/titles/545400af/#College-Hoops-2K7
https://xemu.app/titles/53450023/#ESPN-NBA-Basketball
https://xemu.app/titles/53450030/#ESPN-NFL-2K5
https://xemu.app/titles/53450032/#ESPN-NHL-2K5
https://xemu.app/titles/53450031/#ESPN-NBA-2K5
https://xemu.app/titles/545400ae/#NBA-2K7
https://xemu.app/titles/54540090/#NBA-2K6
https://xemu.app/titles/5454008d/#NHL-2K6
https://xemu.app/titles/545400ad/#NHL-2K7
https://xemu.app/titles/4e4d0008/#R-Racing
https://xemu.app/titles/5553001c/#Batman-Rise-of-Sin-Tzu

### Bug Description
The game crash as soon as try to go in-game with the Assertion:
https://github.com/mborgerson/xemu/blob/6f477f02a653a0417c82dc3a1473b1bd3e96bca0/hw/xbox/nv2a/pgraph.c#L2308

Steps to reproduce this issue:
1. Insert disk
2. go to the main menu
3. start new game/race
4. game crashes

### Expected Behavior
you should be able to go in-game

<h3>Version</h3>
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by MattPonton** [comment]
As of v0.6.1-20-g21718399f2

Issue also occurs with TItle:
https://xemu.app/titles/53450030/#ESPN-NFL-2K5

**Comment by Triticum0** [comment]
Thanks. I Will add it to the list

**Comment by abaire** [comment]
Relevant trace for NFL 2k5 on the dialog screen that pops just after the start screen, indicating that the profile has been loaded:

```
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_BEGIN_END<0x17FC> (NV097_SET_BEGIN_END_OP_TRIANGLE_STRIP<0x6>)
nv2a_pgraph_method_abbrev 0: 0x97 -> 0x1800 NV097_ARRAY_ELEMENT16 * 0
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_DRAW_ARRAYS<0x1810> (0x6000015)
nv2a_pgraph_method_abbrev 0: 0x97 -> 0x1800 NV097_ARRAY_ELEMENT16 * 10
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_BEGIN_END<0x17FC> (NV097_SET_BEGIN_END_OP_END<0x0>)
```

It is unusual for a mix of ARRAY_ELEMENT16 and DRAW_ARRAYS to be used, and this is what triggers the assertion.


https://github.com/abaire/nxdk_pgraph_tests/commit/33563d13bc1a4ed0b9367a89f1519416275cb588 is a test for this case (ARRAY_ELEMENT16 + DRAW_ARRAYS + ARRAY_ELEMENT16 in one BEGIN_END).
On hardware, the draws are concatenated; whatever indices are given via the first AE group are rendered, followed by the vertices specified via DRAW_ARRAYS, followed by whatever indices are given in the last AE group.
Results: https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Overlapping_draw_modes
