### ISSUE TITLE
Append_skinning_code is Untested

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#331]
### Title Information
https://xemu.app/titles/584d0003/#Championship-Bowling
https://xemu.app/titles/41510002/#Flight-Academy
https://xemu.app/titles/544b0001/#Magi-Death-Fight

### Bug Description
The games crashes with an assertion when going into gameplay
https://github.com/mborgerson/xemu/blob/6f477f02a653a0417c82dc3a1473b1bd3e96bca0/hw/xbox/nv2a/shaders.c#L276

### Expected Behavior
It should make it in-game

<h3>Version</h3>
<ul>
<li>Version: build-202106030108( <a href="https://github.com/mborgerson/xemu/commit/6f477f02a653a0417c82dc3a1473b1bd3e96bca0"><tt> 6f477f0</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

[Magi-Death-Fight-Crash-Log.zip](https://github.com/mborgerson/xemu/files/7947587/Magi-Death-Fight-Crash-Log.zip)

**Comment by RageXbox** [comment]
Flight Academy can be removed since I'm using latest master and I enabled untested append code it does the shader compilation failure. #315

**Comment by Triticum0** [comment]
It crashes for Magi-Death-Fight.

**Comment by RageXbox** [comment]
> It crashes for Magi-Death-Fight.

Where?
