### ISSUE TITLE
Halo CE: High pitch sound in Level 2

### ISSUE THREAD

**Issue by Spidy123222** [xemu-project/xemu#340]
### Title Information

* Titles: Halo: Combat Evolved (MS-004 [4d530004])

* https://xemu.app/titles/4d530004/#Halo-Combat-Evolved

### Bug Description

This issue is with the sound in halo combat evolved. It's in the second level and when you get your warthog. When you go into the tunnel and get close to the destination of the bridge there is a high pitch sound. I found the sounds output in audio Debug at 1B.
I don't know what it is for but it does require disabling it so it doesn't burn ears.

Steps to reproduce this issue:
1. Go to the second level.

2. Make sure to get in the warthog

3. Drive through tunnel/cave arrive close to destination before bridge.

4. Listen to sounds

### Expected Behavior

Have no high pitch sounds

### Version

* Version: 0.5.2-25-g6f477f02a6
* Last-known Working: Couldn't find any that had it working.

### System Information

| Field | Value |
|-------|-------|
| OS			| windows 10 Home 20H2 | LTS -->
| CPU			| AMD FX(tm)-4130 Quad Core Processor |
| Graphics Device	|AMD MSI R7 260x OC 2gb GDDR5			|
| Graphics Driver	|Radeon 21.4.1 |

**Comment by Slider-Whistle** [comment]
I'm not involved with this project at all, but weirdly enough I think the gearbox windows port (and master chief collection) has this issue as well. I just assumed that's how it was in the original.

**Comment by Spidy123222** [comment]
This was fixed. Unknown when but was fixed.
