### ISSUE TITLE
Dead or Alive 3: Object transparency issue

### ISSUE THREAD

**Issue by QbikEdge** [xemu-project/xemu#346]
### Title Information

- Titles: Dead or Alive 3
- https://xemu.app/titles/4d53002d/#Dead-or-Alive-3

### Bug Description

Hi guys
I have the problem that in DOA3 the arena walls don't become transparent when the fight shifts toward the edge of the arena so the Characters aren't visible to the player anymore.

Steps to reproduce this issue:

1.  In game select `SPARRING`/`Exercise`- Mode
2.  Choose your Charakters
3.  Hit the `Computer` till you both on the edge of the arena
4.  Make sure the camera looks towards the arena not fron the arena(See screenshot)

### Expected Behavior

On the left is Xemu behavior. On the right expected behavior from Xbox
![image](https://user-images.githubusercontent.com/32527357/121814413-45d6ae00-cc71-11eb-9987-4a36ed8cdbe3.png)

### Version

- Version: 0.5.4-1-g9eefab0e4a
- Branch: master
- Commit: 9eefab0e4a866ce9e26271a00a1b0f6b63b3244b
- Date: Sat Jun 12 06:16:08 UTC 2021
- Last-known Working: Unknown

### System Information

| Field           | Value                                  |
| --------------- | -------------------------------------- |
| OS              | Windows                                |
| CPU             | AMD Ryzen 5 4500U with Radeon Graphics |
| Graphics Device | AMD Radeon(TM) Graphics                |
| Graphics Driver | unknown                                |

### Additional Context

<details><summary>Report details</summary>

```Json
{
  "compat_comments": "",
  "compat_rating": "Playable",
  "cpu": "AMD Ryzen 5 4500U with Radeon Graphics         ",
  "gl_renderer": "AMD Radeon(TM) Graphics",
  "gl_shading_language_version": "4.60",
  "gl_vendor": "ATI Technologies Inc.",
  "gl_version": "4.0.13596 Core Profile Context 20.10.28.10 27.20.11028.10001",
  "os_platform": "Windows",
  "os_version": "Windows",
  "token": "",
  "xbe_headers": "WEJFSOJfsVoUD7svvBGc6ra9l/gOsF+JAv4VYg1GWhtZlYIfEkE/iUwcXUuX1HM9rvrAAbn6QYUfSm0MxWsgzEz/BAMtkFo2mId88Gx3Z19ScQIOgRmphQyfFOb0Eua1Btnh3KYhbwxYCQaxyPYBj///j2SJjQguY7S7BTFLV83fuQrKKNfzn7wUKX5B/OXEk68HpRi/uYe+I9hu0sX5KU6xoOZDJypu2FXefDA3+FRf0X3yq1JcV2AB1s8J85BkJvYdCGhT4gOigeQFPpmrDwE8oR0Wxlv8wpsYYsQOc7UGNOLif8WIzsbARxNwldAvWnj0KAxEAze8MB4f9xV10QIt2aIAAAEAPAoAAGBrxQB4AQAAGHJrPHgBAQAOAAAASAMBAAUAAAD51BgAVIkhAAAAAQAAABAAABAAAGALAQBgwckAAAAAAA1yazxmBwEAfQcBAFQHAQBAgyEAAAAAAAgAAADUBgEAJAcBANQGAQCIBwEAsgIAANABAADSOm08LQBTTUQAZQBhAGQAIABvAHIAIABBAGwAaQB2AGUAIAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///8AHAAAAAAAAAAAAAAABAAAAIPq2JTLm1HXH2yuMO8tKkWQBaRmq8Grack7CWQkwWpQHuA7CTvyevbVXV1Gvg00pBnPO/hp0C1mng57R4n1wiE504w3BKvQpvrpszg9urguGrVOVNrWfC14ga5ljjcWJNxE312DfgcirxXuQhPfgqwhox+RDm9ikW5FGgHmdPAm66spS5gjJ1W9sNtIS3uQvnGRONEkpzl+PWvzR8YC/5u8JgkditVrkLUr8Mgzh0JYfDbGpKCcaMqf+8Y9K9zQjWqBqXkNB7WQIAPZRmMQZMFcAxNPHhjvvJN+GDtqrf42bR1BirrLawQu6csMmV736Jh7YEMGuEbbVgdbGfT7x9iDO0tHzs3GjcIsj5unUZtoXYm4MQ0zkILoX7B8Mo/V5FgAAAAAQAQBwvBwAABAAAHC8HAByBgEAAQAAAFgGAQBaBgEA+ZD45mCFVgnY2NCxLTCug3yo66kHAAAAgMwdAGAdAQAA0BwA/OkAAHgGAQABAAAAWgYBAFwGAQDjGhy7Q1Dcga249qeeu9oiTIoLMwcAAADg6R4AqC4AAADAHQCgLgAAfAYBAAEAAABcBgEAXgYBAHXs0Gz5zoiLqn5x3vpSgjcLyBiQBwAAAKAYHwD8AgAAAPAdAPwCAACBBgEAAQAAAF4GAQBeBgEAtbrGug7BSg2UhBX2tgZ2kllIC4wHAAAAoBsfAES0AQAAAB4AFLIBAIcGAQABAAAAXgYBAGAGAQCGt6VMT+vTbYS2zgQD9TGpStdA5TYAAAAA0CAAkDMAAADAHwCQMwAAjgYBAAEAAABiBgEAZAYBAGIQais3kP8UbRSLG7gIqe12NlTfNgAAAKADIQDwAQAAAAAgAPABAACXBgEAAQAAAGQGAQBkBgEAEu+MctezxXdPiGdRk/uMmZrL7V02AAAAoAUhAMAGAAAAECAAwAYAAKAGAQABAAAAZAYBAGQGAQBToCSmiI8dnmW/extWeeQrmbm9fhYAAABgDCEAMAQAAAAgIAAwBAAAqQYBAAEAAABkBgEAZgYBAOf4YP8lYm1v2r19OIjG5MX8JSbkBwAAAKAQIQCccgAAADAgAJxyAACyBgEAAQAAAGYGAQBoBgEAgUkWtDwo5W/C3syrXCixq8fTyDcGAAAAQIMhAAinAwAAsCAAAKcDALYGAQABAAAAaAYBAGoGAQCc/PvoUxnb1bSAu9mBF4BpVAqz/wcAAABgKiUAXKugAABgJACUUBsAvQYBAAEAAABqBgEAbAYBAKmjdb2Ags2UDLyM1f8LR4TqvG9mJgAAAMDVxQCYbQAAAMA/AIRtAADDBgEAAQAAAGwGAQBuBgEAiUrDgfWKiwvdOK5lDABHlBuuI2Q4AAAAYEPGAAAoAAAAMEAAACgAAMkGAQAAAAAAbgYBAHAGAQCS8mjkf0TQboFkzpW6XtIqm7iAvwEAAgACAAQAAQABAAYAAgACAAIAAgABAAAALnRleHQARDNEAEQzRFgAWEdSUEgARFNPVU5EAFBTR1NGRDAwAFBTR1NGRF9JAFBTR1NGRF9CAFBTR1NGRF9QAFhQUAAucmRhdGEALmRhdGEARE9MQlkAJCRYVElNQUdFAABYQVBJTElCAAEAAAAmEAFARDNEOAAAAAABAAAAJhACQEQzRFg4AAAAAQAAACYQAUBYR1JBUEhDAAEAAAAmEAFARFNPVU5EAAABAAAAJhABQFhCT1hLUk5MAQAAACYQAUBMSUJDTVQAAAEAAAAmEAFATElCQ1BNVAABAAAAJhABQEQAbwBhADMALgBlAHgAZQAAAEM6XERvYTNcT3V0cHV0XFJlbGVhc2VcRG9hMy5leGUAAAAHM60DB1OtA6kD6gADc6cDMgCz/QMFA/3TQ/nqAAPj+TNHMyIA/wMFc/1zc6dz6gBz99Nz4/dDDwP/AwX/My4AA3oAA1IA+TMD+QMPM/8DA0P/E/kTBQOTo/dzB3OnYyNTowUTo9P3cwMHE3Pj9+OjEwkDo/fjkxMFQ1P5U3P5szMDI2MDBZP/QwPj/zP5AwND4/2zBfnT9dMDo//jAwNzJvATBSPj/2MDNvATIzPDYwXT/0X/o5P34wNjJvBDA/9z0/mz+XMT+VMT4/eTAyP549P50zbwAyNjg2MDAyLwQ+P/Q9P3kyP5owMj97MzMvATA1P340P34wWj96MD4/fTBdP3wwPT91MD+RMHEzMDAxP50/ej99P5E/lD0/kDAwP5k/njIyP5cwUD+WP500MTAwdz+SMFo/kD+SMD+QMPU/lz/eOz+RP5I/lzD9P34wMDk/kDBTP5E+P/0wMD4/fTB6P5E/kDQ/fTIgCj+SP9Q+P300P5Q/kDDQP5UwX54wdD+QMDs//jA/mjB9P5U/fjA5P3kyIA+wP74wP5c6P300P5AwUDByP5AwX5owfT85MjCQMz0/sj+UMFE/lzs/eTA+P3Mw8D+dMD+0Mj+TPj95ND+QUT+WP5B/mzBUMi8EMFc/kj+XMFo/kT+UMD+QMPM/lzA/njA1P5E/lDE/lzQ+P3c7P3sweT+WMj4/fT+aMDA6P5A9P34yNz+WMD+QMT+bOjDXP5IwP5QwOz+SP5AwPTIvCzA/lzBxMm8OMD0yrwcwMjJvCjA0P5A0P7kw3T+QMD9+MF+aNT+QUD4/2zAwP5Mwkj/3MDAwPjIvBjB2P940MFo/ezBdP5Mw1LBUcTAwNJE3OnkwcDQ6PDo3MTBRNJAwsDU9Pz43MTCQNDc6PT8+NzEwsDI1NHAwdJEwdJAw0AAA==",
  "xemu_branch": "master",
  "xemu_commit": "9eefab0e4a866ce9e26271a00a1b0f6b63b3244b",
  "xemu_date": "Sat Jun 12 06:16:08 UTC 2021",
  "xemu_version": "0.5.4-1-g9eefab0e4a"
}
```

</details>

**Comment by MattPonton** [comment]
I thought this might be a separate bug, but comparing with OG hardware it might be related.

### Bug
The dust particle effects found in Forest and Pancratium at first I thought were just way too big, but it looks more like it's an opacity issue as well. Let me know if you want me to write this up as a separate issue but I think it might be related.

Steps to Reproduce:

1. Select Sparring on Main Menu
2. Select Characters
3. Select Pancratium stage (Also happens on Forest, but the wind of Pancratium has the dust more often)
4. Observe the environment effect for dust blowing in wind.

### Expected Results
(Left: XEMU | Right: Xbox)
![comparison_doa3_dust_pancratium](https://user-images.githubusercontent.com/45347806/122449232-a3217680-cf73-11eb-8d4e-1a220d399319.png)

### Version

- Version: 0.5.4-7-ga7f3f8f212
- Branch: master
- Commit: a7f3f8f21221174efb65fdc0b8f7e2dd234c7412
- Date: Thu Jun 17 11:21:46 UTC 2021
- Last-known Working: Unknown

**Comment by MattPonton** [comment]
Both of the issues reported in this issue tracker no longer occur as of testing in the following version:

  "xemu_branch": "master",
  "xemu_commit": "83d4cbb4183e8f0d9bdc07eaf676c7e3ede6cc81",
  "xemu_version": "0.6.2-77-g83d4cbb418"

Suggest closing bug as fixed. @mborgerson
