### ISSUE TITLE
Dead or Alive 3 / Dead or Alive 2 Ultimate: Character Select displays out of position

### ISSUE THREAD

**Issue by MattPonton** [xemu-project/xemu#355]
### Title Information

* Titles: 
  * Dead or Alive 3 (54430001) TC-001
  * Dead or Alive 3 (4d53002d) MS-045
  * Dead or Alive 2 Ultimate (54430006) TC-006
* https://xemu.app/titles/4d53002d/#Dead-or-Alive-3
* https://xemu.app/titles/54430006#Dead-or-Alive-1-Ultimate

### Bug Description
For all versions of Dead or Alive 3 and Dead or Alive 2 Ultimate, the character models when rendered on Character Select are not appearing in the expected positions.

Steps to reproduce this issue:
1. Boot any version of Dead or Alive 3 or Dead or Alive 2 Ultimate.
2. Select Sparring.
3. Select Single or Tag Battle.
4. Select some characters but do not confirm to the Stage Select.

Dead or Alive 3:
![20210617211400_1](https://user-images.githubusercontent.com/45347806/122492468-cbc96080-cfb3-11eb-9206-9cf5473c1d25.jpg)

Dead or Alive 2 Ultimate:
![20210617211251_1](https://user-images.githubusercontent.com/45347806/122492450-c4a25280-cfb3-11eb-895c-ba66ea92e1dd.jpg)

### Expected Behavior
Each character is rendered in the correct position.

Dead or Alive 3:
![16_9 Solo 2021-06-17_21-15-47](https://user-images.githubusercontent.com/45347806/122492559-00d5b300-cfb4-11eb-8bb2-d94e2a72bf94.jpg)

Dead or Alive 2 Ultimate:
![16_9 Solo 2021-06-17_21-18-35](https://user-images.githubusercontent.com/45347806/122492578-07642a80-cfb4-11eb-88cc-08eac23a2a2c.jpg)

### Version
* Version: 0.5.4-7-ga7f3f8f212
* Date: Thu Jun 17 11:21:46 UTC 2021
* Branch: master
* Commit: a7f3f8f21221174efb65fdc0b8f7e2dd234c7412
* Last-known Working: Unknown

### System Information
| Field | Value |
|-------|-------|
| OS			| Windows 10 Pro v20H2 build 19042.1052 | 
| CPU			| Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz 3.79GHz |
| Graphics Device	| NVIDIA GeForce GTX 1080 |
| Graphics Driver	| 461.09 |

**Comment by MasonT8198** [comment]
Did you try the surface-clip branch as well to see if it fixed any issues

**Comment by MattPonton** [comment]
> Did you try the surface-clip branch as well to see if it fixed any issues

I am unfortunately unable to build any branch. It continues to give me an error when I attempt to build a branch.

Edit:
After being able to test the surface-clip branch build

Version: 0.5.4-4-g6aef19c411
Branch:  fix/surface-clip
Commit:  6aef19c411587242ed473cd95d49fded10514784
Date:    Sat Jun 12 06:57:11 UTC 2021

Dead or Alive 2 Ultimate is having a different but improved display than the master branch. See screen:
![unknown](https://user-images.githubusercontent.com/45347806/122495776-a12dd680-cfb8-11eb-8847-333c297d4611.png)

The models at least look mirrored but are still offset in position and scale.
