### ISSUE TITLE
Blinx: Some textures aren't displayed

### ISSUE THREAD

**Issue by Shideravan** [xemu-project/xemu#356]
### Title Information

* Blinx the Time Sweeper (4d530013)
* https://xemu.app/titles/4d530013/#Blinx-The-Time-Sweeper

### Bug Description

Some textures aren't correctly displayed, as seem in the fowllowing photos

Steps to reproduce this issue:
1. Go to any level. Stage 1-2 is a good place to see the issue as most of the objects aren't rendered properly. However, the issue happens even in Stage 1-1 (as in the first photo).

![img1](https://user-images.githubusercontent.com/12163923/122624094-1959d200-d075-11eb-9461-afeaed058af1.png)
![img2](https://user-images.githubusercontent.com/12163923/122624099-1bbc2c00-d075-11eb-8b15-56d251c7f1d8.png)

John Godgames made a video with the same graphical issue happening: https://www.youtube.com/watch?v=l9DlNDaD-mg

### Expected Behavior

https://youtu.be/qAoXkBD0Yds?t=772

### Version

* Version: 0.0.0-00-g0000000000
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 x64		| 
| CPU			| Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz			| 
| Graphics Device	| NVIDIA GeForce GTX 1070/PCIe/SSE2		| 
| Graphics Driver	| 4.0.0 NVIDIA 466.77			| 

### Additional Context

Nothing

**Comment by Triticum0** [comment]
Possibly related:https://github.com/espes/xqemu/issues/101 and https://github.com/xqemu/xqemu/issues/35

**Comment by alexd2580** [comment]
Can confirm. Same issue, some textures missing, not playable like this.
```
OS_Version: Arch Linux
Linux 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 510.54
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
```

**Comment by Triticum0** [comment]
The issue has been fixed please close this issue https://www.youtube.com/watch?v=i9uIhHoDYPk

**Comment by alexd2580** [comment]
Thank you, works as expected!

**Comment by Shideravan** [comment]
Thank you for the fix
