### ISSUE TITLE
Kung Fu Chaos: Camera Filter Issue 

### ISSUE THREAD

**Issue by Kohryujin** [xemu-project/xemu#358]
* Titles: Kung Fu Chaos MS-049 [4d530031]
* https://xemu.app/titles/4d530031/#Kung-Fu-Chaos

Bug Description
During the main mission mode of the game, a filter meant to mimic/exaggerate the effect of an old kung fu film is overlaid on the game. Xemu doesn't render this properly, causing a shifting/jittery effect in gameplay and the pause menu.

Steps to reproduce this issue:
1. Start the game.
2. Open Ninja Challenge Mode.
3. Skip the cutscene.
4. Pick a character.
5. Start the first challenge and observe.

https://drive.google.com/file/d/1z1xewF5QHBc_yi6F7TvZnYaBjIUvzKtw/view?usp=sharing
(Effect is even worse in gameplay than in video.)

Expected Behavior
The game should play normally, just with a "Kung Fu Film" effect on the screen. This is an actual setting under options as well, but you have to unlock the ability to change it, with it being on by default until you do.

Version
* Version: 0.5.4-7-ga7f3f8f212
* Last-known Working: Unknown

System Information
| OS				| Windows 10 Pro
| CPU			| AMD FX(tm)-8350 Eight-Core Processor
| Graphics Device	| Radeon RX 580
| Graphics Driver	| Radeon 21.4.1

**Comment by Kohryujin** [comment]
After further testing, I no longer think the "Kung Fu Film" setting has anything to do with this issue. It seems to specifically be combat stages in Ninja Challenge Mode that cause it. Tutorial stages don't have the problem, and bonus stages have a lesser version of it. The multiplayer/vs mode also has a lesser version where the combat isn't affected, but the pause menu still is.

**Comment by Processeur** [comment]
No more display issue since 5.4.19 release.

**Comment by mborgerson** [comment]
Fixed by #390
