### ISSUE TITLE
The Wild Rings: Crash upon loading

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#360]
### Title Information

https://xemu.app/titles/4d530048/#The-Wild-Rings

### Bug Description

xemu crashes upon starting this title.

Steps to reproduce this issue:
1. Load game

### Expected Behavior

xemu should not crash.

### Version

* Version: a7f3f8f21221174efb65fdc0b8f7e2dd234c7412
* Last-known Working: N/A

### System Information

os_platform: Windows
os_version: Windows
cpu: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
gl_vendor: NVIDIA Corporation
gl_renderer: Quadro P5000/PCIe/SSE2
gl_version: 4.0.0 NVIDIA 457.30
gl_shading_language_version: 4.00 NVIDIA via Cg compiler

**Comment by Triticum0** [comment]
Other title affected: 
Tiger Woods PGA Tour 06 
Tiger Woods PGA Tour 2004

**Comment by Triticum0** [comment]
The game doesn't crash before loading on Linux anymore but crash when trying load a match with the assertion.
xemu: ../hw/xbox/nv2a/pgraph.c:3057: pgraph_NV097_CLEAR_SURFACE_handler: Assertion `false' failed.

**Comment by Triticum0** [comment]
fixed with #539. i have tested to confirm
