### ISSUE TITLE
[Assertion] (pg->draw_arrays_length < ARRAY_SIZE(pg->gl_draw_arrays_start))

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#364]
* Titles: Nickelodeon Avatar: The Last Airbender (54510105)
* https://xemu.app/titles/54510105/#Nickelodeon-Avatar-The-Last-Airbender

### Bug Description

The game crash as it loads the first few frames of the 1st cut scene. With the Assertion: 2770
https://github.com/mborgerson/xemu/blob/a7f3f8f21221174efb65fdc0b8f7e2dd234c7412/hw/xbox/nv2a/pgraph.c#L2762-L2770

Steps to reproduce this issue:
1.Insert disk
2.Go to the menu
3.press start game
4.assertion get hit and the game crashes

### Expected Behavior
(https://youtu.be/VODwGD9tQSI?t=93)

### Version

* Version: 0.5.4-7-ga7f3f8f212
* Last-known Working: N/A

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by abaire** [comment]
@Triticum0 I don't own this game, but it sounds like it's just trying to draw more vertices than xemu currently allows. According to the comment around https://github.com/mborgerson/xemu/blob/7d6da227ba3b224647e35d2385419a3bec25a3b3/hw/xbox/nv2a/nv2a_int.h#L377 the current limit is arbitrary, can you try changing the "1000" on those two lines to something larger?

E.g.,
```
    GLint gl_draw_arrays_start[1500];
    GLsizei gl_draw_arrays_count[1500];
```

and then see if the assertion goes away?

**Comment by Triticum0** [comment]
@abaire The assertion went away with changing the limit to 1500

**Comment by abaire** [comment]
Cool, if you're up for it, it'd be good to figure out approximately when it goes away (i.e., see if it goes away with 1250, if it does, try 1100, if it doesn't, try 1350). When you know what the right number is, round it up to add some safety margin and submit a PR to fix it :)

**Comment by Triticum0** [comment]
Sure it will take a while thought because I'm not building from source

**Comment by Triticum0** [comment]
@abaire I got as low as 1040

**Comment by abaire** [comment]
@Triticum0 perfect. Want to make it 1250 so there's some headroom in case the game uses more vertices in another spot and create a PR so it can be fixed?
