### ISSUE TITLE
pgraph_update_surface_part Assertion

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#368]
### Title Information

* Titles: Battlefield 2: Modern Combat (45410062),America's Army: Rise of a Soldier(55530043)
* https://xemu.app/titles/45410062/#Battlefield-2-Modern-Combat
* https://xemu.app/titles/55530043/#America-s-Army-Rise-of-a-Soldier

### Bug Description
The games crash when starting the campaign and  going into the menu respectively. With the assertion : /hw/xbox/nv2a/pgraph.c:5529: pgraph_update_surface_part: Assertion `glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE' failed. https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L5529-L5530

Steps to reproduce this issue:
1. Insert disk
2. The games will crash before or after the main menu

### Expected Behavior
You should be able to make it to the menu or in-game.

### Version
* Version: 0.5.4-7-ga7f3f8f212
* Last-known Working: N/A

### System Information
Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

These are from back in march so they might be outdated. I also change the assertion to match the current build

**Comment by abaire** [comment]
FYI: I'm able to get into a playable state (past the menu) in https://xemu.app/titles/55530043/#America-s-Army-Rise-of-a-Soldier with a newer build (details below).

Tried both letting the intro FMVs play all the way through (and then pressing start on the pre-menu screen) and skipping via the start button.


Version: 0.6.1-27-g42f8873b23
Branch:  master
Commit:  42f8873b23b0f76dca4a7c15c078201263b0464c
Date:    Sat Oct 30 04:05:32 AM UTC 2021

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

**Comment by mborgerson** [comment]
Can we get a re-test on Windows + updated report

**Comment by Triticum0** [comment]
John Godgame and other youtuber tested battlefield 2 recently and it also did'nt crash.
https://www.youtube.com/watch?v=GdzTkgIOUQE
https://www.youtube.com/watch?v=qdFDNwL889g

**Comment by Triticum0** [comment]
@mborgerson Marco Love 360 Tested America's Army Rise of a Soldier on Window and it works so this assertion should be fixed don't know if you want to know what fixed it to avoid any regressions or if i should just close this issue

**Comment by Triticum0** [comment]
Games do not hit assertion anymore
