### ISSUE TITLE
Metal Arms: Title Screen Assertions

### ISSUE THREAD

**Issue by Kohryujin** [xemu-project/xemu#373]
### Title Information

* Titles: Metal Arms: Glitch in the System VU-010 [5655000a]
* https://xemu.app/titles/5655000a/

### Bug Description
Metal Arms Glitch in the System has three assertions that cycle on the title screen preventing starting/playing the game.

Steps to reproduce this issue:
1. Start the game.
2. Do NOT skip the intro logos (It causes its own assertion/crash).
3. You'll get the first assertion when it reaches what should be the title screen, hitting ignore lets you cycle through the three.

![Metal Arms Assert (1)](https://user-images.githubusercontent.com/85906547/123563138-fddf7d00-d780-11eb-8d17-72d619debcf3.png)
![Metal Arms Assert (2)](https://user-images.githubusercontent.com/85906547/123563140-01730400-d781-11eb-8d15-22c0836a9681.png)
![Metal Arms Assert (3)](https://user-images.githubusercontent.com/85906547/123563144-06d04e80-d781-11eb-9c6a-395ee8c405cc.png)

### Expected Behavior
The game should reach the title screen without issue.

### Version

* Version: v0.5.4-9-g7cde5a222c
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 Pro
| CPU			| AMD FX(tm)-8350 Eight-Core Processor
| Graphics Device	| Radeon RX 580
| Graphics Driver	| Radeon 21.4.1

### Additional Context
It seems you can start the game if assertion messages are disabled? Unable to test or confirm this myself.

**Comment by Spidy123222** [comment]
as of version 0.6.1-3-gfe4929c146 skipping the intros as fast as you can seems to skip main menu assertions. also going and making profile and getting in-game fast as you can get you ingame from a few tests I did. but part of asserting ingame is the miners when you get close enough to them will assert you if they are in the screen space or atleast close to it.
![Screenshot (139)](https://user-images.githubusercontent.com/64176728/133387216-140a3bb9-a5fe-44ff-b8b5-eb3327bdf468.png)

**Comment by Spidy123222** [comment]
I was reviewing some errors I get for metal arms glitch in system and it seems that I found a assertion also that isn't listed in OP using latest.![image](https://user-images.githubusercontent.com/64176728/137978415-b58e06b4-1b62-426d-a677-2aacce6e52f9.png)

**Comment by Triticum0** [comment]
This Can Be Closed
