### ISSUE TITLE
Meta: Crashes from Malloc Issues

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#375]
### Title Information

* Titles: 
*  ~~Crime Life: Gang Wars~~  (4b4e001c)
*  ~~Digimon World X~~ Fixed (42410002)
* ~~MotoGP: Ultimate Racing Technology 3~~ (54510088)
* ~~Second Sight~~ (434d0047)
* Phantom Dust (4d530046)
* ~~Links 2004~~  (4d53005d)
* ~~Torino 2006~~  (545400a9)
* ~~Ultimate Beach Soccer~~ (57450001)
* ~~Fahrenheit~~ (Needs to be tested on linux to check for assertion) (4947007b)

https://xemu.app/titles/4b4e001c/#Crime-Life-Gang-Wars
https://xemu.app/titles/42410002/#Digimon-World-X
https://xemu.app/titles/54510088/#MotoGP-Ultimate-Racing-Technology-3
https://xemu.app/titles/434d0047/#Second-Sight
https://xemu.app/titles/4d53005d/#Links-2004
https://xemu.app/titles/545400a9/#Torino-2006
https://xemu.app/titles/57450001/#Ultimate-Beach-Soccer
https://xemu.app/titles/4947007b/#Fahrenheit
https://xemu.app/titles/4d530046/#Phantom-Dust
### Bug Description
When trying to go in-game and performing certain actions in-game the game crashes with a malloc assertion.
Digimon World X and MotoGP: Ultimate Racing Technology 3: 
malloc(): corrupted top size

Crime LifeGang Wars, Second Sight and Links 2004:
 malloc(): invalid size (unsorted)

Torino 2006, Phantom Dust(while loading maps) and Second Sight (computer terminal crash):
xemu: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Ultimate Beach Soccer:
malloc(): mismatching next->prev_size (unsorted)

Steps to reproduce this issue:
1. Insert disk
2. start a game mode from the menu
3. before reaching in-game the game crashes
4. Press Start or go to the computer terminal in the first mission(Second sight) 

### Expected Behavior

The game should go in-game and not crash during game-play.

### Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Manjaro Linux		| 
| CPU			| Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz| 
| Graphics Device	| GeForce GTX 750 Ti/PCIe/SSE2| 
| Graphics Driver	| 3.3.0 NVIDIA 455.45.01			| 

### Additional Context

This game was tested by beard so thank for testing.
Source: https://xemu.app/titles/42410002/#Digimon-World-X

Edit: This look Like a Regression as it made it in-game on XQemu (https://www.youtube.com/watch?v=iFPVVo8adig)
https://docs.google.com/spreadsheets/d/1sVtQ9SNPathKAMCqfYtvJQP0bs0UeLzP9otPHvZDMwE/htmlview#gid=709879345

Second edit: Link 2004 Makes it Ingame on windows so it either fixed or affects windows differently?
**Phantom Dust Gbd output**

```
xemu: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

 Thread 33 "xemu" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffeeebf6640 (LWP 16346)]
 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory. 

```

**Comment by Triticum0** [comment]
This also affect Link 2004 with this assertion:
malloc(): invalid size (unsorted)

**Comment by RageXbox** [comment]
Retest to verify if it works it seems like this is fixed now

**Comment by Triticum0** [comment]
Hadet will test Phantom Dust, If It broken I'll reopen
