### ISSUE TITLE
ERROR:../ui/xemu.c:855:sdl2_display_very_early_init: assertion failed: (m_context != ((void *)0))

### ISSUE THREAD

**Issue by Sprosenax** [xemu-project/xemu#378]
its so annoying how can i solve?

**Comment by mborgerson** [comment]
xemu was unable to create an OpenGL context. What hardware do you have?

**Comment by Sprosenax** [comment]
GeForce 9600 GT (dx10) and open gl 3.3? cxbxr working well but i want this.

**Comment by mborgerson** [comment]
Minimum OpenGL version for xemu is 4.0. Sorry, looks like your card doesn't support it.
