### ISSUE TITLE
TEXGEN_OBJECT_LINEAR is Untested

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#379]
### Title Affected
* https://xemu.app/titles/49470023/#Crazy-Taxi-3
* https://xemu.app/titles/43430005/#Group-S-Challenge
* https://xemu.app/titles/4d570004/#SpyHunter
* https://xemu.app/titles/49470026/#The-Terminator-Dawn-of-Fate

### Bug Description

The untested code is here:
https://github.com/mborgerson/xemu/blob/7cde5a222cd77864b3bea5424970f6e86c85c28d/hw/xbox/nv2a/shaders.c#L430-L433

Steps to reproduce this issue:
1. Insert disk
2. Start game from menu
3. game crashes

Crazy taxi 3:
To reproduce:
1.) Start the game
2.) When the title screen appears, do not press START.
3.) Let the intro movie play, it will get to a certain part sometime after Gus' intro and spawn an "Assertion failed" with shaders.c

### Expected Behavior

should make it in-game uninterrupted.

### Version

* Version: 0.5.0-13-g9ca79f75d8
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows			| 
| CPU			| AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx			| 
| Graphics Device	| AMD Radeon(TM) Vega 8 Graphics 			| 
| Graphics Driver	|  3.3.14757 Core Profile Context 20.11.2 27.20.14501.18003			| 

### Additional Context

This game was tested by turbohao so thank for testing.
Source:  https://xemu.app/titles/4d570004/#SpyHunter

**Comment by Ernegien** [comment]
Also appears to affect Crazy Taxi 3.
