### ISSUE TITLE
[Regression]Project Gotham Racing 2: Crash when going in-game

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#384]
* Titles: Project Gotham Racing 2 (4d53004b)
* https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2

### Bug Description

The game crashes when trying to start a race with the assertion:(pg->surface_shape.color_format < ((sizeof(kelvin_surface_color_format_map) / sizeof((kelvin_surface_color_format_map)[0])) + (sizeof(struct { int:(!(!__builtin_types_compatible_p(typeof(kelvin_surface_color_format_map), typeof(&(kelvin_surface_color_format_map)[0])))) ? -1 : 1; }) - sizeof(struct { int:(!(!__builtin_types_compatible_p(typeof(kelvin_surface_color_format_map), typeof(&(kelvin_surface_color_format_map)[0])))) ? -1 : 1; }))))
https://github.com/mborgerson/xemu/blob/7cde5a222cd77864b3bea5424970f6e86c85c28d/hw/xbox/nv2a/pgraph.c#L4859-L4860

Steps to reproduce this issue:
1. Insert disk
2. Start a race from the main menu
3. Select a vehicle and map
4. The game crashes 

### Expected Behavior

* Version: v0.5.4-9-g7cde5a222c
* Last-known Working: v0.5.0-33 g8e29469ddb

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows			| 
| CPU			| Intel(R) Core(TM) i7-6700K CPU @ 4.00GH			| 
| Graphics Device	| GeForce GTX 1080/PCIe/SSE2			| 
| Graphics Driver	| 3.3.0 NVIDIA 436.30			|

**Comment by LeRutY** [comment]
"Version: 0.4.0-5-g23096561a3" Why not latest?

"Last-known Working: Unknown" It´s 0.5.0-33 g8e29469ddb. Really slow (not playable) but you can get into races

**Comment by Triticum0** [comment]
@LeRutY I'm using what on the xemu website(https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2). I never tested it myself, so i don't know if Project Gotham Racing 2 has Improved since October when it was lasted reported tested on that version.

**Comment by Triticum0** [comment]
If you can confirmed it working post a report on the website or post a screenshot here for references and i will close the issue.

**Comment by LeRutY** [comment]
"0.5.0-33 g8e29469ddb" is an outdated version, some months old. All newer builds exhibit the same issue of not getting into races (no idea if it´s the exact same error code, don´t know how to debug properly)

**Comment by Triticum0** [comment]
It probably is I will update the version to the lastest version and put "0.5.0-33 g8e29469ddb" as the last known working build. If you can post error code in the comment that would be appreciated

**Comment by LeRutY** [comment]
Sry, I was confusing things, I´m not getting any error code, the game along with the emulator just closes after the pre race introduction. Here is a screenshot though it won´t help
![Crash](https://user-images.githubusercontent.com/29675883/124132220-e1915800-da80-11eb-9d19-349e5d760193.png)

**Comment by LeRutY** [comment]
Sry, I was confusing things, I´m not getting any error code, the game along with the emulator just closes after the pre race introduction. Here is a screenshot (I always skip those sequences
![Crash](https://user-images.githubusercontent.com/29675883/124132494-2b7a3e00-da81-11eb-98f3-b450f0ff4962.png)
) though it won´t help

**Comment by LeRutY** [comment]
Sry, I was confusing things, I´m not getting any error code, the game along with the emulator just closes after the pre race introduction. Here is a screenshot (I skipped the introduction sequence right at the beginning, sometimes it shows a bit of the player car) though it won´t help
![Crash](https://user-images.githubusercontent.com/29675883/124132732-67ad9e80-da81-11eb-8d98-2dfda79c197d.png)

**Comment by LeRutY** [comment]
Sry, I was confusing things, I´m not getting any error code, the game along with the emulator just closes after the pre race introduction. Here is a screenshot (I skipped the introduction sequence right at the beginning, sometimes it shows a bit of the player car) though it won´t help
![Crash](https://user-images.githubusercontent.com/29675883/124132796-78f6ab00-da81-11eb-8ea9-a12e87e87757.png)

**Comment by Triticum0** [comment]
Try ruining xemu in cmd
you do this by opening command prompt then draping and dropping the xemu.exe in the cmd then when it crashes tell me if it has a assertion in the command prompt. If not it must be a segmentation fault of caused by a regression if it work on version 0.5.0-33 g8e29469ddb

**Comment by LeRutY** [comment]
No, even launching it via the cmd the emulator just closes without an assertion or similar

**Comment by Triticum0** [comment]
Sorry for taking so long to respond. This is most likely a segmentation fault regression. If you were on Linux, it would show up in the terminal. I'm going to close this issue and move it to  #376 as it is more appropriate. Thank you for testing.

**Comment by Triticum0** [comment]
@LeRutY I think the bug is fixed but you will need to retest to confirm for me.

**Comment by nickkeane** [comment]
Getting a crash in PGR2 w/ latest XEmu after skipping the race intro after doing Quick Race.

Also, can't seem to create a profile, it tells me i'm out of disk space or blocks.
