### ISSUE TITLE
DreamWorks Madagascar: Crashes after Intro screen.

### ISSUE THREAD

**Issue by RageXbox** [xemu-project/xemu#387]
### Title Information

* Titles: DreamWorks Madagascar AV-059 [4156003b]

* https://xemu.app/titles/4156003b/#DreamWorks-Madagascar

### Bug Description

After the Intro screen, it crashes with these:
Assertion failed!
File: D:/a/xemu/hw/xbox/nv2a/pgraph.c
Line 717: Expression: glGetError() = = GL_NO_ERROR
Line 4584: Expression: surface != d->pgraph.color_binding
Line 4831: Expression: glCheckFramebufferStatus(GL_FRAMEBUFFER = = GL_FRAMEBUFFER_COMPLETE
https://github.com/mborgerson/xemu/blob/7cde5a222cd77864b3bea5424970f6e86c85c28d/hw/xbox/nv2a/pgraph.c#L717
https://github.com/mborgerson/xemu/blob/7cde5a222cd77864b3bea5424970f6e86c85c28d/hw/xbox/nv2a/pgraph.c#L4584
https://github.com/mborgerson/xemu/blob/7cde5a222cd77864b3bea5424970f6e86c85c28d/hw/xbox/nv2a/pgraph.c#L4831
Steps to reproduce this issue:
1. Insert disc
2. Game crashes at Intro screen

### Expected Behavior

Goes properly to the menus without issues.

### Version

* Version: v0.5.4-9-g7cde5a222c
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| (Windows 10 (64-bit) 
| CPU			| (Intel(R) Xeon(R) CPU E5-2678 v3 @2.50 GHz) 
| Graphics Device	| (NVIDIA Quadro P5000) 
| Graphics Driver	| (NVIDIA 457.30)

### Additional Context

I tested this game at February 20th, 2021 and Line changed from 4072 to 4584 for some reason. DSP is disabled. I kept pressing "Ignore" until it goes for another assertion.

**Comment by Triticum0** [comment]
This issue is link to #288, #116 and #373

**Comment by RageXbox** [comment]
Fixed

**Comment by Triticum0** [comment]
@RageXbox Please Add new info to the compatibly list
