### ISSUE TITLE
Star Wars - Knights of the Old Republic: Hangs at load screen

### ISSUE THREAD

**Issue by Shoegzer** [xemu-project/xemu#393]
Thanks to #390, this title finally gets past the menu screens which now look mostly fine ~~(although the character portraits are still missing eyes)~~ (missing eyes fixed as of 3fd15218c76cedd89496db637c7ef5369ef35a63).  However, upon starting a game, xemu hangs at the loading screen:

![pic](https://user-images.githubusercontent.com/12475371/124333788-2e4d5f80-db63-11eb-9152-419ed8155820.png)

Currently, there is no compatibility page for this title on xemu.app, only its sequel.
 
Specs:
* OS: Linux Mint 20.1 / kernel 5.11
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 460.80
* Compiler: gcc-11.1.0
* Commit tested: aaf85224317b6823ee79381dfa57eecca3fb2ce9

**Comment by mborgerson** [comment]
You can find the compat page for this game here: https://xemu.app/titles/4c410003/#Star-Wars-Knights-of-the-Old-Republic

* Did you verify your dump works on a real Xbox?
* Did you try with a blank HDD image?

**Comment by Shoegzer** [comment]
Ah thanks.  It doesn't seem to be linked from the main page (at least not alphabetically), so I assumed it wasn't there.

I haven't yet tested this dump on the xbox but I'll try to do that soon.  I did get the same results with a blank HDD image though.

**Comment by Triticum0** [comment]
This is most likely a regression that was last known working here (https://www.youtube.com/watch?v=JiEcsegTVA4)

**Comment by Shoegzer** [comment]
Perhaps and I'm willing to agree, though while xemu is derived from xqemu, the codebase may have changed in fundamental ways such that calling it a "regression" may not be entirely accurate.  Also, I haven't personally seen this title go ingame since I started testing it against xemu about six months ago.

**Comment by Triticum0** [comment]
The game was able to get in-game back in December and March (0.5.0-80-gceee8d67b9), looking at discord logs on the Xemu server. I don't have the game to test, so I can't find when it regressed. The only reason I link the video is it was the only one on youtube and was the only other piece of evidence other than the last report I could find at the time for a regression.

This photo from December in Xemu ingame
![](https://cdn.discordapp.com/attachments/680488810429153315/790388080703045692/unknown.png)

**Comment by Shoegzer** [comment]
Closing this issue as the root cause was a bad dump.  @RealDoigt please close #620 as well.
