### ISSUE TITLE
Jet Set Radio Future: Map Bug

### ISSUE THREAD

**Issue by Kohryujin** [xemu-project/xemu#397]
### Title Information

* JSRF: Jet Set Radio Future IG-024 [49470018]
* https://xemu.app/titles/49470018/

### Bug Description
The maps on the pause screen are filled in gray blocks in the shape of the map instead of showing elevations, graffiti, and such.

Steps to reproduce this issue:
1. Start game.
2. Load into a level.
3. Pause the game and look at the map.

![JSRF map 0](https://user-images.githubusercontent.com/85906547/124822410-db4a2280-df3d-11eb-9566-f58de8b48250.png)

### Expected Behavior
The maps should look like this...

https://giantbomb1.cbsistatic.com/uploads/original/1/15777/2143183-img_20120304_054531.jpg

### Version

* Version: 0.5.4-21-gf03015e20e

### System Information

| Field | Value |
|-------|-------|
| OS			|Windows 10 Pro| 
| CPU			| AMD FX(tm)-8350 Eight-Core Processor| 
| Graphics Device	|Radeon RX 580| 
| Graphics Driver	| Radeon 21.4.1| 

### Additional Context
This isn't a huge issue during early levels since they are pretty small or linear. But later maps can be big sprawling multi-tiered places where finding things without the map might turn into a "needle in a haystack" situation.

**Comment by JPLeBreton** [comment]
From the looks of the xemu VS actual hardware screenshot, the map meshes are meant to have their normals flipped, which isn't happening in xemu. It's quite possible the map marker sprites are getting drawn and then covered up by the non-flipped, non-backface-culled map mesh.

**Comment by abaire** [comment]
I think this is a bit more complicated than a culling issue. It appears that at least the outer wall polygons as well as the floor should be alpha blended, but are being rendered opaque. Attaching some HW screenshots with various camera angles to illustrate.
I also tried simply flipping the front face definition in the pgraph code and inverting the cull enable/disable, but neither resulted in anything useful (I can see via the nv2a debug that there are a bunch of operations w/ culling disabled, but the back face is the only one ever culled and the winding is never modified).

Default view:
![jsrf_map_default_camera](https://user-images.githubusercontent.com/448413/146447186-d617a735-a2f3-485c-9f6f-3d21f95f26f8.png)

Looking through a side wall:
![jsrf_map_side_angle_camera](https://user-images.githubusercontent.com/448413/146447216-61a58d56-1a5c-4c69-a8d9-1c03066404df.png)

Looking through the "floor" of the map:
![jsrf_map_underside](https://user-images.githubusercontent.com/448413/146447237-0590cacb-4f7f-4a87-8ac5-28a9f5647dd2.png)

**Comment by abaire** [comment]
After running some more tests, it looks like xemu doesn't handle materials w/ alpha transparency at all (looks like it's dropped as unhandled), so I'm guessing that's at least part of the problem.
