### ISSUE TITLE
Van Helsing: Title Screen Assertion (Regression)

### ISSUE THREAD

**Issue by Kohryujin** [xemu-project/xemu#405]
### Title Information

* Titles: Van Helsing VU-041 [56550029]
* https://xemu.app/titles/56550029/

### Bug Description

The game asserts when trying to load in the title screen.

Steps to reproduce this issue:
1. Load up the game.
2. Skip logos and attract cinematic.
3. You'll see a loading icon and then the game will assert.

![Van Helsing Assertion 1](https://user-images.githubusercontent.com/85906547/125182853-a3faa080-e1df-11eb-8261-b59e1c0eb61d.png)

### Expected Behavior

Normally the title screen would load in allowing you to start or load a game, etc..

### Version

* Version: 0.5.4-25-ged7cbef976
* Last-known Working: 0.2.0 (According to the compat reports)

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 Pro		| 
| CPU			| AMD FX(tm)-8350 Eight-Core Processor		| 
| Graphics Device	| Radeon RX 580		| 
| Graphics Driver	| Radeon 21.4.1		|

**Comment by Triticum0** [comment]
It was playable back in march https://www.youtube.com/watch?v=HzyUA5sKUwc

**Comment by Kohryujin** [comment]
> It was playable back in march https://www.youtube.com/watch?v=HzyUA5sKUwc

Would you happen to know which builds of Xemu came out in March then? I wouldn't mind testing to find out exactly when playability broke if I had a start point to go off of.

**Comment by Kohryujin** [comment]
After some testing, it seems that this build of Xemu... https://github.com/mborgerson/xemu/actions/runs/975192291
Works without this particular assertion.

And this build... https://github.com/mborgerson/xemu/actions/runs/994891094
Is the one that introduces the error.

**Comment by Triticum0** [comment]
@Kohryujin Add the word (Regression) to the title of the issue. Also retest it might work now

**Comment by Kohryujin** [comment]
Retested, still broken.
![image](https://user-images.githubusercontent.com/85906547/139699263-be5f5b08-5b74-4e78-af3b-405eb2f875be.png)

I feel like I've seen that error before or it was talked about, and not just for this game. But it's been long enough that I'm not sure what the fix was named that caused the regression.

**Comment by Triticum0** [comment]
Also affect Phantom crash

**Comment by abaire** [comment]
In this particular case, the game uses a surface at `101c000` with swizzle enabled and a size of 128x128.
It then sets a clip rect that has a 1,1 offset and a clip width/height of 126. 

The clip offset triggers https://github.com/mborgerson/xemu/blob/38a0e46f8c59c6da50029c1b53712070f211ac74/hw/xbox/nv2a/pgraph.c#L5761 which erroneously causes the surface to be treated as 129x129, causing it to overlap with the zeta surface at 0x102C000.

Based on what I've seen from HW in the [surface clip tests](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/surface_clip_tests.cpp), specifying a clip region that goes beyond the end of the surface results in the nv2a raising an exception, so it's unclear to me why xemu is growing the required size based on the clip offset.

**Comment by abaire** [comment]
@mborgerson 's https://github.com/mborgerson/xemu/blob/0adb1c1b07684174b358340374018a4023b9961d/hw/xbox/nv2a/pgraph.c#L5580 fixes this problem. 

The underlying issue is that surface clipping should never affect swizzled surfaces, so the offset is being incorrectly applied in this case, triggering the erroneous overlap. In a swizzle case, the clip size is used as the surface size, so it's guaranteed to never be larger than the actual surface allocation.
