### ISSUE TITLE
Last version that supports OpenGL 3.3?

### ISSUE THREAD

**Issue by 60fpshacksrock** [xemu-project/xemu#408]
I am using Windows 7 and noticed that OpenGL 4 seems to be a requirement.
I would have asked on the Discord but it wants a phone number, which it won't be getting.

So could I have a link to the last version that works on  Windows 7?
If not I will just stick with CXBX-R.

**Comment by MasonT8198** [comment]
I don't remember the exact version we stopped supporting OpenGL 3.3 however this version should work https://github.com/mborgerson/xemu/releases/tag/build-202010250953 , you can slowly work your way up the releases from here to find the last version

Note: This will not have quite a few performance improvements and such. You could probably merge a few changes in of course. But this is not advised and isn't supported by the project. However you're free to try

Edit: We use the phone detection in discord to help mitigate the use of bots and such in the server, we don't use that information for anything else

**Comment by poobarfoob** [comment]
> I am using Windows 7 and noticed that OpenGL 4 seems to be a requirement.
> I would have asked on the Discord but it wants a phone number, which it won't be getting.
> So could I have a link to the last version that works on Windows 7?
1. This should not be a problem. I used a RTX 3060 in Windows 7 and XEMU worked just fine with it. What is your graphics card then?
2. Yea Mason already explained this.
3. Mason already linked a version that should use OpenGL 3.3.

**Comment by MasonT8198** [comment]
Windows 7 can support OpenGL 4, the hardware is the limiting factor here

**Comment by Spidy123222** [comment]
> I don't remember the exact version we stopped supporting OpenGL 3.3 however this version should work https://github.com/mborgerson/xemu/releases/tag/build-202010250953 , you can slowly work your way up the releases from here to find the last version
> 
> Note: This will not have quite a few performance improvements and such. You could probably merge a few changes in of course. But this is not advised and isn't supported by the project. However you're free to try
> 
> Edit: We use the phone detection in discord to help mitigate the use of bots and such in the server, we don't use that information for anything else

We don't get any phone information. It's only discord. Discord is the only thing that allows the user to join and the server sets the requirements so the server requires a phone number to be set to prevent bots essentially what you said.

**Comment by 60fpshacksrock** [comment]
@MasonT8198 - Thank you for the link.

And to those wondering about my Graphics Card (Nvidia), it was originally called Geforce 8200. After some updates the name changed to Geforce 9200.

Also, does this emulator support D3D11?

**Comment by Spidy123222** [comment]
> @MasonT8198 - Thank you for the link.
> 
> 
> 
> And to those wondering about my Graphics Card (Nvidia), it was originally called Geforce 8200. After some updates the name changed to Geforce 9200.
> 
> 
> 
> Also, does this emulator support D3D11?

It only supports Opengl desktop. Likely the next backend would be Vulkan likely if a other one was added.

**Comment by 60fpshacksrock** [comment]
Okay. Thanks again.
