### ISSUE TITLE
(Regression) Project Gotham Racing 2: Crashes the emulator if resolution scale is set to 1x

### ISSUE THREAD

**Issue by LeRutY** [xemu-project/xemu#412]
### Title

https://xemu.app/titles/4d53004b/#Project-Gotham-Racing-2

MS-075 [4d53004b]

### Bug Description

Specific tracks like the first two in the "Kudos World Series" are crashing the game and xemu right before race start. The same track works in "Time Attack"

Steps to reproduce this issue:

 1.   Insert disk
 2.  Start the first race in the "Kudos World Series"
 3.  The emulator crashes after the flythrough (showing "Welcome to Florence")

### Expected Behavior

You should be able to start and finish the races

### xemu Version

Version: 0.6.3
Last-known Working: 0.5.0-36-gafed1a4835

### System Information

OS: Windows 10 64 Bit
CPU: i7 7700K
GPU: GTX 1080
GPU Driver: 512.15

### Additional Context

The "dsp_cpu.c" error shown below also appears when restarting an event

**Comment by LeRutY** [comment]
Update: Not only do events exist which are crashing the emulator before the race starts, there are also certain events (for example Timed Run 9 and 10) in which you are able to drive till the end but still can´t be finished properly (crash occuring after showing "Race finished" for a couple of seconds)

**Comment by LeRutY** [comment]
Update: Not only do events exist which are crashing the emulator before the race starts, there are also certain events (for example Timed Run 9 and 10) in which you are able to drive till the end but still can´t be finished properly (crashing after showing "Race finished" for a couple of seconds)

**Comment by LeRutY** [comment]
Update 2: This "Assertion failed" error comes up when disabling "Flythrough" in the game options (I described it as "pre race introduction", it´s the same thing) and then starting a race It crashes in the loading screen, you don´t get to see ingame graphics
![Assertion](https://user-images.githubusercontent.com/29675883/125857488-4ffca341-833e-4caa-8b1f-0cc85961d7d2.png)

**Comment by LeRutY** [comment]
Update 2: This "Assertion failed" error comes up when disabling "Flythrough" in the game options and then starting any race. It crashes in the loading screen, you don´t get to see ingame graphics. I´m not sure if it helps resolving the regression though
![Assertion](https://user-images.githubusercontent.com/29675883/125858294-8f5f8282-a2a9-414d-84b7-beddcfc6f36d.png)

**Comment by dracc** [comment]
That error is related to the DSP. I'm willing to bet that you've enabled surround sound ("DTS") and/or Digital Audio ("Dolby Digital"), which are not properly supported at this time.

**Comment by LeRutY** [comment]
No, I don´t have any of those two enabled, I´ve checked with the eeprom editor

**Comment by LeRutY** [comment]
No, I don´t have any of those two enabled, I´ve checked with the eeprom editor

**Comment by LeRutY** [comment]
"dracc" and "Thrimbor" both have posted segementation faults on the discord server
[dracc.txt](https://github.com/mborgerson/xemu/files/6871470/dracc.txt)
[Thrimbor.txt](https://github.com/mborgerson/xemu/files/6871471/Thrimbor.txt)

**Comment by LeRutY** [comment]
NOTE: You get the same "dsp_cpu.c" error shown above when trying to load a system link multiplayer race. Clicking on "Retry" shuts down Xemu, while "Ignore" keeps outputting the error BUT switching between "Line: 1024" and "Line: 1035". Video https://www.youtube.com/watch?v=IdElNgHO-YY

**Comment by LeRutY** [comment]
The event start crash is only happening at the original xbox resolution, selecting a higher render scale somehow fixes it https://www.youtube.com/watch?v=AiRLI0n07gA

**Comment by antangelo** [comment]
This is the surface binding being uploaded:
```
$1 = {entry = {tqe_next = 0x0, tqe_circ = {tql_next = 0x0, tql_prev = 0x7ffee867ef00}}, access_cb = 0x7ffeea81a450, vram_addr = 54358016, fmt = {bytes_per_pixel = 2, gl_internal_format = 33189, 
    gl_format = 6402, gl_type = 5123, gl_attachment = 36096}, shape = {z_format = 0, color_format = 3, zeta_format = 1, log_width = 0, log_height = 0, clip_x = 0, clip_y = 0, clip_width = 909, 
    clip_height = 909, anti_aliasing = 0}, dma_addr = 0, dma_len = 134197247, color = false, swizzle = false, width = 909, height = 909, pitch = 2048, size = 1861632, gl_buffer = 373, cleared = false, 
  frame_time = 292, draw_time = 172008, draw_dirty = false, download_pending = false, upload_pending = false}
```

The issue seems to be caused by the fact that the texture pitch (`width * surface->fmt.bytes_per_pixel`) is not word aligned, which is what `glTexImage2D` expects by default. Setting the internal render scaling to a multiple of 2 happens to fix the alignment, which is why the problem disappears.

I think the DSP assertion failure is unrelated, you should open a separate issue for that if it is still present.
