### ISSUE TITLE
Support explicit aspect ratio display scaling for widescreen support

### ISSUE THREAD

**Issue by Trevor-Z** [xemu-project/xemu#413]
### Feature Request

There is no Scaling Mode that can display 16:9 games like Ninja Gaiden Black correctly in fullscreen on a 21:9 monitor.

"Scale" is 4:3 even if the game supports widescreen and we set the dashboard accordingly, and "Stretch" fills all the screen, so it works on 16:9 displays but goes all the way to 21:9 in this case.

So I'd like to suggest a new mode to enforce 16:9, or a tweak to "Scale" mode so that it keeps the correct proportions based on the dashboard settings.

**Comment by mborgerson** [comment]
I agree, this should be supported.

**Comment by mborgerson** [comment]
Fixed in #438
