### ISSUE TITLE
(Regression) Brute Force: Game Crashes With Seg. Fault Error In Linux Before 1st Mission Starts 

### ISSUE THREAD

**Issue by ThatDudeYouMetThatOneTime** [xemu-project/xemu#414]
### Title

https://xemu.app/titles/4d53001e/#Brute-Force

### Bug Description

When using Xemu in Linux, this game will crash either before the loading screen prior to the cutscene of the 1st mission, or before the 1st mission's cutscene finishes.

**Steps To Reproduce The Issue**
1.) Boot up Xemu, preferably through your terminal to see the output upon crashing, selecting your ISO of Brute Force.
2.) Skip past all the intros, menus, cutscenes, etc. by mashing start.
3.) Observe the game closing Xemu either during the loading screen before mission 1, or during mission 1's cutscene. After Xemu closes, you should see an error saying: "Segmentation fault (core dumped)." Usually, the mission 1 cutscene tends to make the game close Xemu more often than the loading screen.

### Expected Behavior

The game should not crash during the 1st cutscene and resume to allow you to play the game.

### xemu Version

0.5.4-28-gcc6d19e099

Last working: unknown

### System Information

OS: Ubuntu 20.04.2LTS (Linux)
CPU: I5-7400T @2.40GHz (4 cores, 4 threads)
GPU: Mesa Intel HD Graphics 630 (KBL GT2)
GPU Driver: Integrated GPU (?)

**Comment by mborgerson** [comment]
Does not appear to be an issue with v0.7.17
