### ISSUE TITLE
Magatama: Environment Becomes Extremely Bright At Certain Camera Angles, Main Character Textures Also Darken

### ISSUE THREAD

**Issue by ThatDudeYouMetThatOneTime** [xemu-project/xemu#419]
### Title

https://xemu.app/titles/4d530066/#Magatama

NTSC-J MS-102

### Bug Description

The environment becomes a nearly blindingly bright yellow-ish white when the camera is moved in certain directions all around the character. When the environment becomes brighter, the textures on the main character, and other NPCs, appear to darken. This can happen in cutscenes as well.

Steps To Reproduce The Issue: 
1.) Boot up your ISO of Magatama.
2.) Press start at the title screen, skipping the intro FMV. 
3.) Watch the 1st cutscene to see the issue in a cutscene. Then, once you get to gameplay, turn the camera around to observe the environments becoming exceedingly bright and the main character and NPCs' textures darkening, while in some camera angles it appears fine. 
![Screenshot from 2021-07-21 13-00-19](https://user-images.githubusercontent.com/81947301/126529892-35b0fb77-e3b7-4cfc-8345-3ff4e8651aa1.png)
![Screenshot from 2021-07-21 13-01-19](https://user-images.githubusercontent.com/81947301/126529904-40fff81d-06a9-4c12-b6a6-3e6c4552a473.png)

### Expected Behavior

The environments should not become incredibly bright by having the camera be in certain positions. It should look more like the following images: 
![Screenshot from 2021-07-21 13-00-47](https://user-images.githubusercontent.com/81947301/126530334-b6c8422a-36cb-4472-973a-98aa28f4c802.png)
![Screenshot from 2021-07-21 13-01-23](https://user-images.githubusercontent.com/81947301/126530357-09b97977-d455-4230-8389-d4dc6941cdf6.png)

### xemu Version

0.5.4-39-gedf3735718

### System Information

OS: Ubuntu 20.04.2 LTS
CPU: Intel® Core™ i5-7400T CPU @ 2.40GHz 
GPU: Mesa Intel® HD Graphics 630 (KBL GT2)
GPU Driver: Integrated GPU (?)

**Comment by Triticum0** [comment]
The game also crashes with an assertion after you finish the first tutorial.
/hw/xbox/nv2a/pgraph.c:4371: pgraph_gl_fence: Assertion `result == GL_CONDITION_SATISFIED || result == GL_ALREADY_SIGNALED' failed.**

**Comment by abaire** [comment]
@ThatDudeYouMetThatOneTime @Triticum0 can we get a re-test of this? There have been a ton of fixes since this bug was reported and the latest [compatibility report](https://xemu.app/titles/4d530066/#Magatama) using 0.7.21 implies that the graphics issues has been resolved.

**Comment by ThatDudeYouMetThatOneTime** [comment]
@abaire I just played through the 1st tutorial and the 1st level. It looks like this issue can now be closed, as I did not encounter any of the issues I posted about a year ago.

**Comment by abaire** [comment]
@ThatDudeYouMetThatOneTime awesome, mind closing it then? (Only you, as the author, or @mborgerson can)

**Comment by ThatDudeYouMetThatOneTime** [comment]
Oh, yeah sure. I didn't realize only either Matt or I could close an issue I had posted.
