### ISSUE TITLE
Whacked!: Video freezes on first frame, associated audio continues playing

### ISSUE THREAD

**Issue by n1ckn4m3** [xemu-project/xemu#422]
### Title

https://xemu.app/titles/4d530027/#Whacked

### Bug Description

Video renders first frame, audio continues but video stays stuck on first frame.  

Steps to reproduce:
1. Boot game
2. Start single player campaign

### Expected Behavior

Expectation is that video will continue to play in sync with audio.

Result is that video locks on first frame while audio continues.

### xemu Version

Version: 0.5.4-39-gedf3735718
Branch:  master
Commit:  edf373571879bf90baeeb617aa9a0a1cde25097b
Date:    Tue Jul 20 17:39:54 UTC 2021

### System Information

OS: Windows 10.0.19043
CPU: Intel (R) Core i9-10900KF CPU @ 5.1GHz
GPU: Nvidia Geforce RTX 3080 Ti
GPU Driver: 471.11

### Additional Context

Video files are .BIK, Video/Audio codec information as follows:

Video: BIKi 640x480 15.013fps [Video (BIKi, 640x480, 15.013 fps)]
Audio: BINK 44100Hz 2.0 chn [Audio (BINK, 44.1 kHz, 2.0 chn, 16 bit)]

**Comment by WestDrop** [comment]
any update or fix for this issue?

**Comment by n1ckn4m3** [comment]
> any update or fix for this issue?

Issue still persists on latest version of xemu (v0.6.1-12-ga8c73197da), no change yet.

**Comment by Triticum0** [comment]
This is fixed and can be closed

**Comment by n1ckn4m3** [comment]
Confirmed, fixed, should be closed.
