### ISSUE TITLE
Black with missing lighting effects

### ISSUE THREAD

**Issue by vanderleivieirainacio** [xemu-project/xemu#432]
### Title

https://xemu.app/titles/45410083/#Black

### Bug Description

The game doesn't have lighting effects like on xbox consoles. 
![Captura de tela 2021-07-28 091117](https://user-images.githubusercontent.com/46516229/127322505-5f80c7f8-7468-489a-9339-16ecfe1e11c1.png)

### Expected Behavior

This is the correct way that lighting effects should present themselves for more trustworthy gameplay. 
![Captura de tela 2021-07-28 091715](https://user-images.githubusercontent.com/46516229/127321422-b9e74c9b-3a73-49bc-888f-44ef1d3ff268.png)

### xemu Version

v0.6.0 

### System Information

OS: Windows 10 64-bit
CPU: AMD Ryzen 1700 @3.0GHz
GPU: Sapphiretech Radeon RX 580 4GB
GPU Driver: AMD Software Adrenalin 2020 version 21.7.2

**Comment by didizx** [comment]
> ### Title
> https://xemu.app/titles/45410083/#Black
> 
> ### Bug Description
> The game doesn't have lighting effects like on xbox consoles. ![Captura de tela 2021-07-28 091117](https://user-images.githubusercontent.com/46516229/127322505-5f80c7f8-7468-489a-9339-16ecfe1e11c1.png)
> 
> ### Expected Behavior
> This is the correct way that lighting effects should present themselves for more trustworthy gameplay. ![Captura de tela 2021-07-28 091715](https://user-images.githubusercontent.com/46516229/127321422-b9e74c9b-3a73-49bc-888f-44ef1d3ff268.png)
> 
> ### xemu Version
> v0.6.0
> 
> ### System Information
> OS: Windows 10 64-bit CPU: AMD Ryzen 1700 @3.0GHz GPU: Sapphiretech Radeon RX 580 4GB GPU Driver: AMD Software Adrenalin 2020 version 21.7.2
> 
> ### Additional Context
> _No response_

**Comment by HadetTheUndying** [comment]
This appears to be fixed now if you could retest, and close if it is.

**Comment by Triticum0** [comment]
@HadetTheUndying yes it been fixed this can be closed https://youtu.be/WR0Og9a_M6A?t=250

**Comment by gordonfreeman01** [comment]
@vanderleivieirainacio Please close this issue, it is causing incorrect compatibility reports for the game on the website.

@Triticum0 Given the age of this closed issue, it is very likely the user who opened the issue is no longer watching this thread, please help with closing this issue as it is making the compatibility report incorrect.
