### ISSUE TITLE
Sonic Heroes crashes on loading screen

### ISSUE THREAD

**Issue by vanderleivieirainacio** [xemu-project/xemu#434]
### Title

https://xemu.app/titles/5345002b/#Sonic-Heroes

### Bug Description

The Sonic Heroes game crashes on the loading screen before it can actually be played. 
![Captura de tela 2021-07-28 101935](https://user-images.githubusercontent.com/46516229/127331521-7ad040b5-2167-451d-bb03-2619b8b08993.png)

### Expected Behavior

The game should be completely playable without these crashing errors. 

### xemu Version

v0.6.0

### System Information

OS: Windows 10 64-bit
CPU: AMD Ryzen 1700 @3.0GHz
GPU: Sapphiretech Radeon RX 580 4GB
GPU Driver: AMD Software Adrenalin 2020 version 21.7.2

**Comment by KBouder** [comment]
The game no longer crashes at loading screen, but does come to a complete freeze after loading into a level.

**Comment by RinMaru** [comment]
> The game no longer crashes at loading screen, but does come to a complete freeze after loading into a level.

just tried and this issue is still a problem (Crashing at loading screen)

**Comment by KBouder** [comment]
> > The game no longer crashes at loading screen, but does come to a complete freeze after loading into a level.
> 
> just tried and this issue is still a problem (Crashing at loading screen)

How strange...does it happen every time for you?

**Comment by RinMaru** [comment]
> > > The game no longer crashes at loading screen, but does come to a complete freeze after loading into a level.
> > 
> > 
> > just tried and this issue is still a problem (Crashing at loading screen)
> 
> How strange...does it happen every time for you?

yep it always crashed when loading the first stage after cutscene. you can hit ignore for all pop ups till the entire emu hardcrashes

**Comment by KBouder** [comment]
> 
I just gave it another try with the same results. The level loaded very quickly, in game was at a very low frame rate then froze at this point. I should also note that during loading, I got no pop-up errors and the emulator itself did not crash.
![image](https://user-images.githubusercontent.com/11525691/161597163-922353df-d9c9-4ef6-a9e1-2064dbd95230.png)

Specs:
Windows 11
Ryzen 7 2600X @ 3.70 GHz
NVidia RTX 2070
32 GB RAM
[xemu.log](https://github.com/mborgerson/xemu/files/8411838/xemu.log)
The log does not seem to show any useful information.

![image](https://user-images.githubusercontent.com/11525691/161598578-a8a5aff9-1c11-4f7a-a180-cb8aed7f848d.png)
Starting the game with Team Rose actually gets into game fully without freezing (but much slower than realtime)
![image](https://user-images.githubusercontent.com/11525691/161598908-c6a00a0a-8163-4900-9db2-dd0dc3de0b9d.png)
The game freezes at this point on that level (S00 Sea Gate).

**Comment by RinMaru** [comment]
> > 
> 
> I just gave it another try with the same results. The level loaded very quickly, in game was at a very low frame rate then froze at this point. I should also note that during loading, I got no pop-up errors and the emulator itself did not crash. ![image](https://user-images.githubusercontent.com/11525691/161597163-922353df-d9c9-4ef6-a9e1-2064dbd95230.png)
> 
> Specs: Windows 11 Ryzen 7 2600X @ 3.70 GHz NVidia RTX 2070 32 GB RAM [xemu.log](https://github.com/mborgerson/xemu/files/8411838/xemu.log) The log does not seem to show any useful information.

this might be a AMD GPU issue. i noticed we both have Polaris GPUs and you have Nvidia

**Comment by RageXbox** [comment]
Hardscale seems to fix the freezing and crashing from upscaling.

**Comment by abaire** [comment]
@vanderleivieirainacio based on your findings over in #919 can you close this since it's working on 0.7.15?

**Comment by vanderleivieirainacio** [comment]
Yes, thanks for the hard work.
