### ISSUE TITLE
Title Name: Short Description

### ISSUE THREAD

**Issue by elvijsfreimanis** [xemu-project/xemu#440]
### Dino Crisis 3 Electro Velociraptor texture bug. Makes game unplayable

https://xemu.app/titles/43430003/#Dino-Crisis-3

### Bug Description

![1](https://user-images.githubusercontent.com/88353128/127935154-f3dd74d3-4490-40cd-a71e-a24e3d14b772.jpg)

1. Playing game normally from the beginning.
2. reaching area with electric velociraptors
3.the screen becomes filled with broken moving textures of the velociraptors moving model
4.exiting the area or killing the monster restores the screen to normal.
all other monsters are displayed normally

### Expected Behavior

I have seen others play this title without this issue. It is expected that I should also have no issues with the electric velociraptor texture bug.

### xemu Version

v0.6.0

### System Information

dell aoi 7450 optiplex
windows 10
i5 7400
8gb ddr4
amd discreet onboard graphics chip R7m465x 2gb 
m2 ssd 128gb
Driver Packaging Version
19.30.31.20-191126a-348909E-RadeonSoftwareAdrenalin2019

**Comment by elvijsfreimanis** [comment]
Updating graphics driver
![2](https://user-images.githubusercontent.com/88353128/127940609-e65c6443-3d27-4c97-9c74-524956576b75.jpg)
Ok, updated graphics driver to Driver Version
21.09.03.08-210511a-368456C-RadeonSoftware

And it's fixed.

**Comment by MasonT8198** [comment]
So updating the graphics driver fixes this issue, seems this issue can be closed then.
