### ISSUE TITLE
Destroy All Humans! 2: No in-game models.

### ISSUE THREAD

**Issue by WhynautTV** [xemu-project/xemu#441]
### Title

https://xemu.app/titles/54510106/#Destroy-All-Humans-2

### Bug Description

When playing with a build after build-202107190558 (v0.6.0), most models that are not the terrain or buildings do not appear. Things like NPC's, vehicles, and most entities do not appear at all.

https://user-images.githubusercontent.com/48634646/128599724-cb48bf44-d0be-48ef-b69f-4c9acd00f78f.mp4

### Expected Behavior

![image](https://user-images.githubusercontent.com/48634646/128599835-c5332e16-959e-47c3-aee0-91a419a1a743.png)
Models in earlier build.

### xemu Version

v0.6.0

Last working in: v0.5.4-29-g0b9a2e1a8f

### System Information

OS: Windows 10 Pro
CPU: Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
GPU: NVIDIA GeForce GTX 1660 SUPER
GPU DRIVER: NVIDIA 27.21.14.6089

**Comment by RinMaru** [comment]
same issue in the first game
