### ISSUE TITLE
Npcap bridged network - failed to open interface 'xxx' for capture: winpcap library is not loaded

### ISSUE THREAD

**Issue by binarymaster** [xemu-project/xemu#442]
### Bug Description

I'm currently trying to experiment with xemu bridged networking with pcap (on Windows platform). When I run xemu.exe without parameters, and then enable bridged networking in app settings - everything works. However when I manually specify parameters via command line, application does not start with an error.

My command line:
```
xemu.exe -netdev pcap,id=pcap,ifname=\Device\NPF_{9FFBFCD2-B51D-4853-91F7-99F317D7DEA7}
```

Error output:
```
Created QEMU launch parameters: xemu -cpu pentium3 -machine xbox,bootrom=C:\Tools\xqemu\mcpx_1.0.bin,kernel-irqchip=off -device smbus-storage,file=C:\Tools\xqemu\eeprom.bin -bios C:\Tools\xqemu\cromwell.bin -m 64 -drive index=0,media=disk,file=C:\Tools\xqemu\hdd_fat32.qcow2,locked=on -drive index=1,media=cdrom,file= -display xemu -audiodev none,id=snd0 -netdev pcap,id=pcap,ifname=\Device\NPF_{9FFBFCD2-B51D-4853-91F7-99F317D7DEA7}
xemu: -netdev pcap,id=pcap,ifname=\Device\NPF_{9FFBFCD2-B51D-4853-91F7-99F317D7DEA7}: failed to open interface '\Device\NPF_{9FFBFCD2-B51D-4853-91F7-99F317D7DEA7}' for capture: winpcap library is not loaded
```

I think that it tries to create pcap network backend earlier than the actual pcap initialization happens (when it's being started without parameters).

### Expected Behavior

It is expected to start and run with this parameter without problems.

### xemu Version

xemu_version: 0.6.0
xemu_branch: master
xemu_commit: 3c1fcf620256babded72d7f4c72f6ad414d5b306
xemu_date: Tue Jul 27 00:00:45 UTC 2021

This is the latest version.

**Comment by MasonT8198** [comment]
Seems like a rather simple fix
