### ISSUE TITLE
Advent Rising: Freezing when attempting gameplay

### ISSUE THREAD

**Issue by retroNUC** [xemu-project/xemu#443]
### Title

https://xemu.app/titles/4d4a0009/#Advent-Rising

NTSC

### Bug Description

Launch a new game, then attempt to enter gameplay scene after initial cutscenes.

Both the 'Skip Cutscene' button on the pause menu and letting the cutscene play out to the natural switch to gameplay both freeze the game.

![image](https://user-images.githubusercontent.com/71151161/129373500-a932c10c-1953-41f3-8bcf-58610c9dbb6b.png)

### Expected Behavior

Expectation that gameplay is 'playable' (according to compatibility report from January 2021), so possibly a regression.

### xemu Version

0.6.0

### System Information

OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
GPU: Intel(R) Iris(R) Xe Graphics
GPU Driver: 30.0.100.9684

**Comment by mborgerson** [comment]
Please check the version of xemu listed in the existing compatibility report to determine whether this is a regression or not. If the old version works, then it's a regression. Otherwise, you may have a bad game dump. Please confirm and I will re-open if necessary.

**Comment by retroNUC** [comment]
Unfortunately I'm unable to text the exact version from the existing compatibility report on this hardware, as it's Intel GPU (which only got support in a later version). I'll try the same dump on another hardware setup.

**Comment by dracc** [comment]
> Unfortunately I'm unable to text the exact version from the existing compatibility report on this hardware, as it's Intel GPU (which only got support in a later version). I'll try the same dump on another hardware setup.

Make sure to test the same exact dump on your physical Xbox console too. :)
