### ISSUE TITLE
32 bit?

### ISSUE THREAD

**Issue by Torrex18** [xemu-project/xemu#454]
### Bug Description

I can't start because it asks for 64 bit

### Expected Behavior

does not start

### xemu Version

the newest versions

### System Information

Windows 7 32 bit
Intel Pentium Dual-Core E2180 @2.0 GHz
3GB de ram
Intel q35 Express Chipset Family

**Comment by MasonT8198** [comment]
This isn’t a bug, xemu doesn’t support 32 bit installs, there is a build issue that prevents you from building on 32bit but your pc doesn’t seem to support the minimum OpenGL requirement for xemu, much less the performance necessary to run a game at even reasonable speeds

**Comment by mborgerson** [comment]
Sorry, there are no plans to actively support 32b Windows releases.
