### ISSUE TITLE
Futurama: FMV videos are broken

### ISSUE THREAD

**Issue by Shideravan** [xemu-project/xemu#457]
### Title

https://xemu.app/titles/46490002/#Futurama

### Bug Description

All the game's FMV videos are broken.

### Expected Behavior

The videos plays normally

### xemu Version

0.6.1-7-g05d21c6e94

**Comment by NotSoCheezy** [comment]
Experienced this myself. FMVs show only the first frame but play back audio fine.

Version: 0.6.1-12-ga8c73197da

**Comment by n1ckn4m3** [comment]
Are the video files .BIK format?  There's a similar issue with "Whacked!", and I'm curious to find out if Futurama also uses the same file format and specific codec to see if these are related and help run down the cause of the issue.

Is the video shown as "BIKi" video codec and "BINK" audio codec in something like MPC-BE or VLC?

**Comment by InfectedSonic** [comment]
> Are the video files .BIK format? There's a similar issue with "Whacked!", and I'm curious to find out if Futurama also uses the same file format and specific codec to see if these are related and help run down the cause of the issue.
> 
> Is the video shown as "BIKi" video codec and "BINK" audio codec in something like MPC-BE or VLC?

the file format is .xmv with the video codec being WINDOWS MEDIA VIDEO 8(wmv2)
 audio codec is IMA WAV ADPCM AUDIO

**Comment by stupidjokeaccount11** [comment]
Similar issue in Darkwatch, the FMVs load but get stuck on the first frame while the audio continues to play. However, I did manage to get the videos to play one time before they stopped working again. When one of the FMVs loaded and froze on the first frame, I changed the Rendering Scale from 1x (what I launched the game with) to 3x, and the video began playing. A few more FMVs played without issue. But when I restarted xemu, the FMVs no longer worked, and changing the Rendering Scale didn't seem to work anymore. Using version 0.6.2-75-g8919bae311

**Comment by joshuamoorexyz** [comment]
Is this issue still being worked on?

**Comment by abaire** [comment]
As mentioned above, this may be the same underlying issue as #422, explicitly linking the two here.

**Comment by abaire** [comment]
Doing a pgraph trace from the start of the program, it sets the texture offset for the video once and then just renders a quad to the screen each frame during the playback using the fixed function pipeline and a trivial combiner that just copies the texture value to r0 and uses r0 as the final value.

```
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_OFFSET[0]<0x1B00> (0x3749000)
nv2a_pgraph_method 0: NV20_KELVIN_PRIMITIVE<0x97> -> NV097_SET_TEXTURE_FORMAT[0]<0x1B04> (0x12429 {DMA_A, BORDER_SOURCE_COLOR, LC_IMAGE_CR8YB8CB8YA8, MipmapLevels:1, 2D, BaseSizeU:1, BaseSizeV:1, BaseSizeP:1})
```

The texture appears to be perma-cached, so either there's some path that isn't emulated at all (e.g., a hardware decoder, I'm not very familiar w/ xbox video capabilities) or there's a CPU write to the surface that isn't resulting in the surface being marked as dirty so xemu never uploads it to the GPU.


As a hack I bypassed the early exit in `pgraph_bind_textures` that is taken if a `TextureBinding` exists without an associated `SurfaceBinding` and that makes things work. So I'm fairly certain xemu is failing to realize that the CPU is modifying the texture RAM, which causes it to permanently use the initial value at the time the texture offset was set. I also suspect this is the cause of #937.

As another hack, checking the texture memory dirty bitmap also seems to work:
```
        if (!pg->texture_dirty[i] && tbind &&
            (!surface || tbind->draw_time == surface->draw_time)) {
            bool reusable = true;
            if (!surface) {
                reusable = !pgraph_check_texture_dirty(d, texture_vram_offset, 100);
            }
            if (reusable) {
                glBindTexture(pg->texture_binding[i]->gl_target,
                              pg->texture_binding[i]->gl_texture);
                continue;
            }
        }
```

UPDATE: Minimal test case:
Palette cycling does not seem to work on hardware, so this is just a problem with direct texture manipulation.
[Test case](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_cpu_update_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_CPU_Update)

**Comment by Triticum0** [comment]
Game Affect
SSX 3
Commandos Strike Force
Battlefield 2 Modern Combat (Different issue)
