### ISSUE TITLE
JET SET RADIO FUTURE: Cannot Save 

### ISSUE THREAD

**Issue by dragonasia** [xemu-project/xemu#461]
### Title

https://xemu.app/titles/49470018/#JSRF-Jet-Set-Radio-Future

### Bug Description

BUG with the game, cannot save with the robot, not working. 

### Expected Behavior

BUG with the game, cannot save with the robot, not working. 

### xemu Version

0.6

### System Information

OS: Linux/Batocera
I5 8279U 16 GO
Intel Iris 655

**Comment by mborgerson** [comment]
Can you provide more info please [e.g. how can I reproduce this?]

**Comment by MasonT8198** [comment]
How did you create this iso @dragonasia
