### ISSUE TITLE
Assert when saving xemu settings (user folder containing cyrillic characters)

### ISSUE THREAD

**Issue by down555** [xemu-project/xemu#470]
### Bug Description

First, xemu fails to cteate an eeprom and gets this error:
![eefail](https://user-images.githubusercontent.com/45518431/135904703-502b7842-d798-4c90-9465-376fdeb03184.jpg)
When i try to save settings i get an assert like this: 
![assert](https://user-images.githubusercontent.com/45518431/135905163-d0f58426-edde-4837-aec5-d8892e25442d.jpg)
I've tested under a VM with no cyrilic characters in the username, and the eeprom and settings save properly there.

### Expected Behavior

Eeprom should correcty generate and the emulator should be able to save settings without crashing.

### xemu Version

0.6.1-12-ga8c73197da

**Comment by MasonT8198** [comment]
Create xemu.ini next to xemu.exe and inform me of your results

**Comment by mborgerson** [comment]
Tracking in #479. Will close this issue as duplicate
