### ISSUE TITLE
filed to generate eppromfiles

### ISSUE THREAD

**Issue by aguetkriegerisch** [xemu-project/xemu#476]
### Bug Description

xemu fails while reading machine settings.

So, when I clicked 'save' on machine settings, i got an alert that says:
 
assertion failed!
![image](https://user-images.githubusercontent.com/39163176/136291481-a1c7aa7c-7b3f-46ee-8b2e-6e393736eb28.png)

and then, rading log files  i saw this warnings:

Created QEMU launch parameters: C:\Users\Alonso agüet\Desktop\xemu.exe -cpu pentium3 -machine xbox,kernel-irqchip=off -m 64 -drive index=1,media=cdrom,file= -display xemu -audiodev none,id=snd0 
C:\Users\Alonso agüet\Desktop\xemu.exe: GLib: g_hash_table_lookup: assertion 'hash_table != NULL' failed
C:\Users\Alonso agüet\Desktop\xemu.exe: GLib: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
Failed to load BIOS '(null)'
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0

I tried to find the .ini file in AppData\Roaming\xemu\xemu\xemu.ini but nothing is there, only the empty xemu folder 

I also tried diferent bios files:
![image](https://user-images.githubusercontent.com/39163176/136292271-3243bf9a-7551-4499-bd19-9501c9958dd3.png)

but got the same issue.

i have installed this versions of visual c++ libraries:
![image](https://user-images.githubusercontent.com/39163176/136292694-843864a5-cb19-4fc2-a942-2908ce987575.png)

### Expected Behavior

xemu start properly

### xemu Version

xemu_version: 0.6.1-12-ga8c73197da
xemu_branch: master
xemu_commit: a8c73197daae6f952b2f0edcc85e4bcf63dd38ee
xemu_date: Fri Oct  1 21:10:50 UTC 2021
xemu_settings_get_path: config path: C:\Users\Alonso agüet\AppData\Roaming\xemu\xemu\xemu.ini

### System Information

Processor: AMD A6-4400M
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon HD 7520G
GL_VERSION: 4.0.13397 Core Profile Context 15.200.1055.0
GL_SHADING_LANGUAGE_VERSION: 4.40

**Comment by MasonT8198** [comment]
Create a xemu.ini file next to xemu.exe

**Comment by aguetkriegerisch** [comment]
> Create a xemu.ini file next to xemu.exe
ok i tryed, but got the same. 
I need to write ther some configs? coz i leave it empty.
![image](https://user-images.githubusercontent.com/39163176/136293075-a9af4e8d-7d00-465f-b7f9-c749b1d95cf4.png)

**Comment by MasonT8198** [comment]
This would be best done in the file explorer, in a folder, instead of on the desktop

**Comment by aguetkriegerisch** [comment]
> This would be best done in the file explorer, in a folder, instead of on the desktop
ok it works thanks :'D

**Comment by aguetkriegerisch** [comment]
> This would be best done in the file explorer, in a folder, instead of on the desktop
ok it works thanks :'D
