### ISSUE TITLE
Doom 3: Main Menu - Game Freezes After 10 seconds in the menu

### ISSUE THREAD

**Issue by Joshua-1248** [xemu-project/xemu#477]
### Title

https://xemu.app/titles/41560020/#Doom-3

Doom 3
AV-032 [41560020]

### Bug Description

Goes into the menus just fine until about 10-15 seconds later, then the game freezes completely with the audio still functional, but making a weird loop.

Something to do with the background video failing to loop over possibly.

Hitting A repeatedly to get through the menu as quickly as possible will avoid the freeze and the game will go in-game with decent performance, but some textures will be glitchy and hand models have flickering blackish triangles on them.

### Expected Behavior

Main menu background video shouldn't freeze the game.

### xemu Version

Xemu | v0.6.1
Linux version

**Comment by Triticum0** [comment]
This also happens in Double-S.T.E.A.L when trying to start a level there probably related to the same issue

**Comment by thekovic** [comment]
Can't reproduce this anymore on v0.7.120. I can idle in the menu for seemingly any amount of time without the game freezing.
