### ISSUE TITLE
File paths containing non-ASCII characters are unsupported

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#479]
### Bug Description

If file path contains non-ascii characters (e.g. Cyrillic), the user interface will not display the characters properly (glyphs are not in the font) and, if the user's name contains such characters creating xemu.ini file and EEPROM file will fail with default paths. This is a major usability issue.

The path management issues for config and EEPROM appear possibly localized to Windows, cannot repro on Linux. macOS state unknown. Unclear if this is a bug in SDL2 or xemu. Path rendering affects all platforms.

A workaround is to install xemu to C:\xemu, and create C:\xemu\xemu.ini manually.

Issue has been reported multiple times. #99 #470 #476

### Expected Behavior

xemu should work on all platforms, regardless of locale, and displaying paths correctly.

### xemu Version

v0.6.1-12-ga8c73197da

### System Information

N/A

**Comment by MasonT8198** [comment]
I’m now adding this to the site’s FAQ page, but it would be nice if we could add the message to create a xemu.ini file next to xemu.exe upon assertion itself 

edit: or just do it automatically

**Comment by mborgerson** [comment]
We should just fix the issue, not document around it

**Comment by CookiePLMonster** [comment]
> Unclear if this is a bug in SDL2

I'm yet to see an Unicode bug in upstream SDL2, so my money is on xemu code exclusively.

**Comment by mborgerson** [comment]
@CookiePLMonster it's likely an issue with xemus fopen/open on Windows, which will use ansi by default. We need to convert to wide chars to support Unicode from existing utf-8 paths. PRs welcome if you want to work on it.
