### ISSUE TITLE
Make a UWP build of xemu to run non-backwards compatible games on the xbox one / series x|s

### ISSUE THREAD

**Issue by OrionMelaeno** [xemu-project/xemu#487]
### Feature Request

I know, I know, theres backwards compatibility available on the xbox so you can play older games, but that's a different story for the ones not supported.

The thing is, what if you wanna play a game you like but you realize its not on the list, well you could play it on pc, but the problem is you dont have a pc or yours is just a potato BUT what if you DO have an xbox one or series x|s.

Well now the thing im asking is to make a UWP build so you can download it and send the files to your xbox through dev mode (and possibly make a retail version) so you would be finally be able to play that one game you always wanted to play.

**Comment by dracc** [comment]
Please close, duplicate of #272.

**Comment by mborgerson** [comment]
Thanks for asking. I do understand the motivation for requesting the feature, but it's not a goal, at least not today.

Ideally Microsoft would expand their BC catalog for Xbox console owners. Maybe send a request to them about getting your favorite game playable.
