### ISSUE TITLE
Unimplemented texture color format 0x2f

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#491]
### Bug Description

Crash due to unimplemented texture format.

https://xemu.app/titles/49470004/#TransWorld-Snowboarding

### Expected Behavior

No crash.

### xemu Version

21718399f2680b5d2e48e554f9dfd591f3efc0f2

**Comment by abaire** [comment]
Note: This doesn't seem to hit until actually trying to get into a level (I went to freeplay and it aborted after loading)
