### ISSUE TITLE
Dead or Alive 3: Sunburst texture is obscuring view in the Iron Hell stage

### ISSUE THREAD

**Issue by MattPonton** [xemu-project/xemu#494]
### Title

* Titles: 
  * Dead or Alive 3 (54430001) TC-001
  * Dead or Alive 3 (4d53002d) MS-045
* https://xemu.app/titles/4d53002d/#Dead-or-Alive-3

### Bug Description

There is a sunburst texture that is fullscreen on the camera when playing on the Iron Hell stage. It causes the game to have its brightness too high, sometimes obscuring the players.

Steps to Reproduce:

1. Insert disk
2. Progress to main menu
3. Select Sparring
4. Select Single or Tag Battle
5. Select any character and opponent(s)
6. Select Iron Hell stage

### Expected Behavior

The game renders the view as expected.

### xemu Version

Last Tested version: 0.6.1-20-g21718399f2

Issue started occurring with the `Render Scaling` support release.

### System Information

OS: Windows 10 Pro v20H2 build 19042.1052
CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz 3.79GHz
Graphics Device: NVIDIA GeForce RTX 3080 Ti
Graphics Driver: 472.12

### Additional Context
![20210920130114_1](https://user-images.githubusercontent.com/45347806/137027643-c3a68863-cda8-4c55-a590-bd3fe05476f7.jpg)

**Comment by MattPonton** [comment]
The issue reported no longer occurs as of testing in the following version:

"xemu_branch": "master",
"xemu_commit": "83d4cbb4183e8f0d9bdc07eaf676c7e3ede6cc81",
"xemu_version": "0.6.2-77-g83d4cbb418"

Suggest closing bug as fixed. @mborgerson

**Comment by mborgerson** [comment]
Awesome
