### ISSUE TITLE
HeXen + XBMC + DVD2XBOX Visual C++  Assertion Failed

### ISSUE THREAD

**Issue by Danik2343** [xemu-project/xemu#502]
### Bug Description

dsp_emu.ini
Assertion Failed
Line 40
Titles [HOMEBREW]:HeXen + XBMC + DVD2XBOX
Title [ORIGINAL GAMES]: Fatal Frame
MCPX 1.0, MCPX 1.1 Not supported with emulator.

### Expected Behavior

Programs and games were launched without this error, but in some moments you can ignore, sometimes it is impossible to use, constantly clicking on skip. 

### xemu Version

Version: 0.6.1-23-g5a80cfa2d9
Branch:  master
Commit:  5a80cfa2d95390438f17e5c4cd5e0c072bb0c4a4
Date:    Thu Oct 14 19:19:37 UTC 2021

### System Information

OS:Microsoft Windows 11 Enterprise
CPU:HexaCore AMD FX-6350, 3918 MHz (19.5 x 201)
GPU: Nvidia GEFORCE 960
GPU VER: 496.13

**Comment by Danik2343** [comment]
XMBC can be used, but constantly clicking on skip to switch to another menu item takes a long time, for hexen you just need to press a few times and everything will work fine in the menu.

**Comment by mborgerson** [comment]
Disable surround sound in your dash settings, or remove your EEPROM file and xemu will generate a new one for you.

**Comment by Danik2343** [comment]
XEMU Best! Error gone out!
Thank Very Much!
