### ISSUE TITLE
SpongeBob: Battle for Bikini Bottom: Error pg-> color_binding || pg-> zeta_binding

### ISSUE THREAD

**Issue by SharkdudeDev** [xemu-project/xemu#503]
### Title

https://xemu.app/titles/5451001a/#Nickelodeon-SpongeBob-SquarePants-in-Battle-for-Bikini-Bottom

NTSC game version 1.00

### Bug Description

If you do a jump attack(not spin) or the helmet attack, it throws this C++ error for some reason.

### Expected Behavior

What's supposed to happen on the not spin jump attack is spongebob makes a lot of bubbles that attack an enemy instead of **crashing the whole game with a C++ error.**

### xemu Version

 0.6.1-23-g5a80cfa2d9

### System Information

OS: Windows 11 Home
CPU: AMD Athlon Gold 3150U 
GPU: AMD Radeon
GPU Driver: AMD Radeon Driver v27.20.21030.1005

**Comment by Triticum0** [comment]
This also affects Cold fear (5553004b) and Area 51 (4d570005)
