### ISSUE TITLE
Unreal Championship assert fail on linux

### ISSUE THREAD

**Issue by mrcmunir** [xemu-project/xemu#507]
### Title

https://xemu.app/titles/49470024/#Unreal-Championship

### Bug Description

 1) Load the game 
 2) After First logo cause assert fail on linux compared with windows you can pass logo/intro with sometimes can loop sound
![Screenshot from 2021-10-26 00-47-32](https://user-images.githubusercontent.com/1274014/138786904-49262e51-9d95-4010-be4d-4f43d2a3401a.png)
 .

### Expected Behavior

When load first logo and intro no freeze loop or cause assertion .

### xemu Version

tested up to 0.6.1.27-g42f7763b23

### System Information

OS : Ubuntu 21.10
CPU : Tegra TX1 
GPU : TX1 jetson nano dev kit.
Driver : Jetpack L4T 32.6.1

**Comment by dracc** [comment]
Do you get the same "assertion failed" message when not running through `gdb`?

**Comment by mrcmunir** [comment]
> Do you get the same "assertion failed" message when not running through `gdb`?

Yes  happen without it I run with gdb for stack debug .
Tested with 4627 1.03 bios too and not helped here .

**Comment by mrcmunir** [comment]
I can't reproduced this anymore tested in the actual 0.7.71 so will closed this issue.
