### ISSUE TITLE
Incorrect video rendering in pre-menu FMV

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#512]
### Title

https://xemu.app/titles/4541003a/#Tiger-Woods-PGA-Tour-2004
NTSC

### Bug Description

Graphical corruption in pre-menu video plaback.

The FMV is rendered on the top part of the screen with a hall of mirrors effect in the lower half (see screenshot). The problem persists throughout the video playback and on the initial "press start" menu screen, but is resolved if you let it sit long enough to get into attract mode (where it's rendering 3D instead of FMV)

Guessing this will be related to #511 

![Screenshot_20211029_205855](https://user-images.githubusercontent.com/448413/139519483-603deb8b-6266-491c-81a3-7fd4f2497769.png)

![Screenshot_20211029_210129](https://user-images.githubusercontent.com/448413/139519530-0cac7a29-78a0-45c0-a277-e29e5c904f3e.png)

### Expected Behavior

Content should play back without corruption.

### xemu Version

Version: 0.6.1-27-g42f8873b23
Branch: master
Commit: 42f8873
Date: Sat Oct 30 03:42:42 AM UTC 2021

### System Information

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

**Comment by mborgerson** [comment]
Is this different from #511? If not you can put the title link in the other issue and close this as a duplicate so we can track them together

**Comment by abaire** [comment]
Nope, I'm guessing it's the same. Closing as dup.
