### ISSUE TITLE
Center scaling mode is broken when using rendering scale

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#515]
### Bug Description

When using rendering scale when in center scaling mode it causes zoom in on to the center of the virtual screen
![Screenshot from 2021-10-31 00-59-13](https://user-images.githubusercontent.com/71127352/139562129-eea44c27-917b-42df-9be4-4f0d8f5df83e.png)
.

### Expected Behavior

should improve image quality while not changing screens dimensions.

### xemu Version

0.6.1-29-gc1e4e87f5f

### System Information

OS: Ubuntu 20.04.3 LTS
CPU: Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
GPU: Mesa Intel(R) HD Graphics (BDW GT1)
GPU Drivers: 4.6 (Core Profile) Mesa 21.0.3

**Comment by mborgerson** [comment]
This is intended behavior for 'center'. If you want improved quality while seeing the whole image, select scale.

**Comment by Triticum0** [comment]
ok i will close issue
