### ISSUE TITLE
implement "Auto (Window Size)" Internal Resolution Rendering / Widescreen Hack

### ISSUE THREAD

**Issue by rrrcabral** [xemu-project/xemu#517]
### Feature Request

1. instead of integers multiples, give the option to scale the internal rendering to actual size of the screen, to render for example exactly in 1080p.. 4k... (the resolution of actual user screen),
Citra has that, Duckstation has that.

2. another quest: widescreen hack will be good, duckstation has that too, Parallel N64 has that, Flycast(dreamcast) has that.

**Comment by mborgerson** [comment]
1. Just pick the nearest integer multiple

2. xemu supports widescreen scaling. Adding hacks for games to force them to use widescreen is not a goal, just patch the game
