### ISSUE TITLE
Hexen 2021 Iso no longer booting (Bios shadow booting???)

### ISSUE THREAD

**Issue by HoRnEyDvL** [xemu-project/xemu#519]
### Bug Description

It looks like when you load the Hexen 2021 iso it either  chain loads (PBL) or (Shadows) a different bios kernel, 5838.01 before launching Hexen which is based on Unleashe X 

In the old version of Xemu Version: 0.6.1-24-g5ae39a321a this works fine and Hexen boots up, however in the latest version of Xemu it just freezes on loading.

Nothing shown in the log file.

Steps to reproduce. Try  loading Hexen 2021 disk either by launching it from a dashboard or starting xemu up with the disk loaded.

### Expected Behavior

Should boot into Hexen Installers CD menu (Unleash X)

### xemu Version

Current version not working : Version: 0.6.1-33-gbbcd5763e6

Last know working version : Version: 0.6.1-24-g5ae39a321a 

### System Information

Windows 10
AMD 5950X
GTX 980
64GB RAM

**Comment by HoRnEyDvL** [comment]
Running with Serial Out we get this message

*** Fatal System Error: 0x0000000a
                       (0x00000029,0x00000002,0x00000000,0x8001D4BD)

**Comment by maxdlpee** [comment]
Still not fixed by 0.6.2

**Comment by HoRnEyDvL** [comment]
follow up update.

Just realized for some reason it says  Found Xcalibre encoder before crashing.

Found XCalibur Encoder

*** Fatal System Error: 0x0000000a
                       (0x00000000,0x00000002,0x00000000,0xD001CA87)

**Comment by HoRnEyDvL** [comment]
previous versions worked as per screenshot attached.

![image](https://user-images.githubusercontent.com/73101201/145305008-2b3a5028-240e-42d2-beea-8297f72840c8.png)

**Comment by oblivioncth** [comment]
From the quick testing I did, I just wanted to clarify that the exact first release that broke this was **0.6.1-29-gc1e4e87f5f**, making the last working version **0.6.1-27-g42f8873b23**.

**Comment by mborgerson** [comment]
Can someone (@HoRnEyDvL @maxdlpee @oblivioncth) test with the latest version of xemu? I think this should be fixed now. Let me know.

**Comment by HoRnEyDvL** [comment]
@mborgerson Just tested
Version: 0.6.2-25-g7f6655bb34
Branch:  master
Commit:  7f6655bb344df27cf4524043c74fe49eb47a0757
Date:    Sat Jan  8 02:03:52 UTC 2022

Hexen now boots,

![image](https://user-images.githubusercontent.com/73101201/148627827-042100de-69bd-4f08-8082-dfab52f45a11.png)

**Comment by mborgerson** [comment]
Thanks for the report and quick test

**Comment by HoRnEyDvL** [comment]
Closing Ticket Cheers.
