### ISSUE TITLE
upscaling certain games crashes the emulator.

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#520]
### Title

https://xemu.app/titles/544d000f/#Dinotopia-The-Sunstone-Odyssey (Fixed)
https://xemu.app/titles/54430009/#Gungriffon-Allied-Strike (Fixed)
https://xemu.app/titles/42410001/#Digimon-Battle-Chronicle (Fixed)
https://xemu.app/titles/42410002/#Digimon-World-X (Fixed)
https://xemu.app/titles/534300f9/#Commandos-Strike-Force (Fixed)
https://xemu.app/titles/4541003c/#SSX-3 (Fixed)
https://xemu.app/titles/5553004c/#Peter-Jackson-s-King-Kong-The-Official-Game-of-the-Movie (Fixed)
https://xemu.app/titles/4d570015/The-Suffering (Fixed)
NTSC TM-015 

### Bug Description

Assertion failed:surface->pitch >= (surface->width * surface->fmt.bytes_per_pixel), file /xemu/hw/xbox/nv2a/pgraph.c, line 5056
https://github.com/mborgerson/xemu/blob/6f507c80af546e0f5d316622d20f78820423ce6e/hw/xbox/nv2a/pgraph.c#L5391
Steps to reproduce this issue:
1.Start game
2.Make it in-game
3.Upscale to 2x
4.Crashes

### Expected Behavior

You should be able to upscaling with no issue

### xemu Version

0.6.1-29-gc1e4e87f5f

Last working:N/A

### System Information

OS: Ubuntu 20.04.3 LTS
CPU: Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
GPU: Mesa Intel(R) HD Graphics (BDW GT1)
GPU Drivers: 4.6 (Core Profile) Mesa 21.0.3

**Comment by mborgerson** [comment]
May be resolved by #942

**Comment by Triticum0** [comment]
Tested Digimon World X and it fixed it
Edit: #942 doesn't fix it. It already fixed in the main build

**Comment by Triticum0** [comment]
I Test most of the games the issue seems fixed
