### ISSUE TITLE
Audio, Graphics  and Video issues with Capcom vs. SNK 2 EO

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#525]
### Title

https://xemu.app/titles/43430008/#Capcom-vs-SNK-2-EO

### Bug Description

The sound effects and voices had issues and sounds horrible and disappear, the video had some problems (some 3D graphics  like the background in the tittle display are broken and the fps had latency and is very slow for moments).

When I want to go into my dashboard the emulator crashes and I can't access to the network mode.

### Expected Behavior

3D graphics and sound effects should work without any problem, plus there should be no latency and no fps drop.

Here a demonstration of how looks like now:

[https://youtu.be/QKeJyDvXRQk](url)

### xemu Version

v0.6.1-33-gbbcd5763e6
Oct 30, 2021

### System Information

Os: MacOS CPU: Intel Iris Plus 650 
MacOS Big Sur 11.2
MacBook Pro Late 2017

**Comment by Triticum0** [comment]
had the same problems on Linux

**Comment by mborgerson** [comment]
Please narrow the scope of your issue down to a single, specific problem description. You can open multiple issues if necessary.

**Comment by ghost** [comment]
Hi, first to all, the audio had problems and the sound effects are very affected
