### ISSUE TITLE
Second Sight is affected with malloc.c:2379: sysmalloc: Assertion 

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#529]
### Title

https://xemu.app/titles/434d0047/#Second-Sight

NTSC CM-071

### Bug Description

When going to the computer on the first mission the game crash with this error:
xemu: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

### Expected Behavior

I should be able to use the computer without it crashing and corrupting the save functionally.

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Ubuntu 20.04.3 LTS
CPU | Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Graphics Device | Mesa Intel(R) HD Graphics (BDW GT1)
Graphics Driver | Drivers: 4.6 (Core Profile) Mesa 21.0.3

**Comment by mborgerson** [comment]
Can you lump this issue and the other two you filed together. I believe I know why they are broken and have a fix for them. Let's just track them together for now.

https://github.com/mborgerson/xemu/issues?q=is%3Aissue+is%3Aopen+malloc+

**Comment by Triticum0** [comment]
Surel i thought they where different issues so i separated them. window not show malloc assertions made me think there where segfaults when i test them on windows.

**Comment by Triticum0** [comment]
Do you want me to due add it to this issues as a comment #119
