### ISSUE TITLE
Halo:CE laser effect missing parts

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#53]
There is apparently blue colored tube object surrounding the beam which is not rendering correctly.

Xbox:
![](https://i.imgur.com/RfWj3e3.png)

xemu:
![](https://i.imgur.com/aeXQF3y.jpg)

Screenshots courtesy ngrst183.

Title: 4d530004

**Comment by Jakey757** [comment]
it seems like xemu might be darking the output of this shader too much, the tube isnt so much as missing, but one of the input textures is too dark. 

the same ingame shader is duplicated and is used on another object that is easier to see
https://cdn.discordapp.com/attachments/576156733538566160/773547947384111164/2020-11-04_09-03-01.mp4
one of the interiors of b40 with 2 hunters and rockets

original hardware
https://youtu.be/jnzf0Riv01A?t=100
https://youtu.be/jnzf0Riv01A?t=1950

i noticed this while trying to replicate the shader on PC, and i was using xemu as a reference. Somebody pointed out the tube was "flashing" too quickly. the tube is just a rotated texture sliding around the model its on, the brighter it is the more it "fills" the tube.

investigated by examining the original "tags" or building blocks for the game from retail map files
![pythonw_A4S6Jx8JCB](https://user-images.githubusercontent.com/49990481/98172085-b7ba6e00-1ebe-11eb-918a-7046e9c7cd5e.png)
Input C here is being modified before being sent out by "mapped to"

**Comment by mborgerson** [comment]
Great info @Lolibox, this will help debug
