### ISSUE TITLE
[fix/hard-scale] Spyro: A Heros Tail Assertion Error 

### ISSUE THREAD

**Issue by JaceMayer** [xemu-project/xemu#532]
### Bug Description

When scaling up to 10x on the fix/hard-scale branch during the sgt. Byrd flying challenge, Xemu crashes with the following error.

`Assertion failed: (glGetError() == GL_NO_ERROR), function pgraph_download_surface_data_to_buffer, file ../hw/xbox/nv2a/pgraph.c, line 5149.`

### Expected Behavior

The emulator shouldn't crash

### xemu Version

fix/hard-scale branch

### System Information

OS: Mac OS Monterey 
CPU: Apple M1 (8 core, 8GB RAM)
Controller: Xbox series X (Bluetooth)

### Additional Context

I know branches are considered unstable, just wanted to be helpful incase nobody has encountered this yet.

**Comment by mborgerson** [comment]
Please don't file bugs about work in progress branches. You can report the issues you encounter in discord
