### ISSUE TITLE
Mercenaries: Playground of Destruction: Draw distance too short

### ISSUE THREAD

**Issue by gurufabbes** [xemu-project/xemu#533]
### Title

https://xemu.app/titles/4c410015/#Mercenaries

### Bug Description

Newest version used: 0.6.2

Gameplay wise it runs pretty well aside from the render distance being restricted. 
You can only see so far in front of you before a mist like area hides game objects like buildings and roads.

Performance is great. Opening Presentation works better for PS2 emulator.

Main issue is draw distance which makes it unplayable.

Video here shows issue: https://www.youtube.com/watch?v=kGs_PTvy3rg&t=574s

### Expected Behavior

Draw distance should be larger.

### xemu Version

xemu_version: 0.6.1-33-gbbcd5763e6

### System Information

RTX 2070 mobile on laptop

**Comment by mborgerson** [comment]
Please include more specific screenshots of current vs expected

**Comment by gurufabbes** [comment]
Original Xbox: https://www.youtube.com/watch?v=cB1R5NEO5hU&t=5032s

Current Xemu: https://www.youtube.com/watch?v=kGs_PTvy3rg&t=574s
