### ISSUE TITLE
Phantom Crash: Working audio, controller input, but no video.

### ISSUE THREAD

**Issue by Swift016** [xemu-project/xemu#534]
### Title

https://xemu.app/titles/47450002/#Phantom-Crash

US version.

### Bug Description

Game boots with audio and controller input (able to skip past intro with button input) but no video. Splash screen loads with audio and controller input, but no video. Able to navigate menus, etc. If you leave the splash screen for a while, it will load a demo video, which does have visuals.

### Expected Behavior

Game has visuals.

### xemu Version

build-202110302121

### System Information

10900k
RTX 3090

**Comment by Triticum0** [comment]
It mean to crash with this assertion:xemu: ../hw/xbox/nv2a/pgraph.c:4897: pgraph_surface_invalidate: Assertion `surface != d->pgraph.zeta_binding' failed.
Aborted (core dumped)
but only happen when booting from the dashboard

**Comment by GeneralAtrox** [comment]
Can confirm this still happens.
Build tested: v0.6.2-90-g6f507c80af

i9-11900H
64GB DDR4
RTX 3080

**Comment by GeneralAtrox** [comment]
![Xemu Screenshot 2022 04 09 - 13 28 56 31](https://user-images.githubusercontent.com/10944811/162574198-b2551e09-2c1c-4578-a3d8-45fff02ba7b2.png)

Game does work if you can navigate the menus blind. 

Just missing UI elements, but they aren't essential for play.
![image](https://user-images.githubusercontent.com/10944811/162575429-e65650c8-6892-452d-bcdc-d69bfe5a0bbe.png)

**Comment by wxvu** [comment]
Pleased to report that Phantom Crash's texture issues have been fixed, and that the game currently has no known graphical issues.
![PCxemuChart](https://user-images.githubusercontent.com/53349573/165230086-b1ff145c-b049-4271-a9a0-61eed35c76d9.png)

**Comment by GeneralAtrox** [comment]
Thank you very much to whomever fixed it!

**Comment by Seeyeay** [comment]
![DSC_0363](https://user-images.githubusercontent.com/120281729/206876325-fbc00b6a-3b6b-450b-a354-bcb9493889ad.JPG)
This is not working on steamdeck. Everything works great until you get into a rumble (the fighting arenas), a large diagonal line from bottom left to the top right appears on screen. The bottom portion is fine, but the top begins ghosting all your movements on top of itself. Youll see your reticle ghosting and the previous menu. Its unplayable in this state
