### ISSUE TITLE
Some title have heavy exploding geometry ingame and menus

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#537]
### Title

https://xemu.app/titles/5454001b/#Robotech-Invasion
https://xemu.app/titles/5454007c/#Spy-vs-Spy
https://xemu.app/titles/4e4d0019/#Curious-George

### Bug Description

When in menu and in-game server game breaking exploding geometry make these games unplayable.
Robotech: invasion
![Screenshot from 2021-11-02 17-56-38](https://user-images.githubusercontent.com/71127352/140659708-cf60ea67-e3c9-4097-967e-336ef4cc5b4c.png)
Others are similar in-game and menus are mostly a black screen but change when moving the menu items.
Steps to reproduce this issue:
1.Insert disk
2.Skip intro
3.menu broken

### Expected Behavior

menus should look like this.
Curious George:
![Screenshot from 2021-11-07 19-44-50](https://user-images.githubusercontent.com/71127352/140659679-efed2d58-1374-46bd-93b1-78a8dc729668.png)
Spy vs Spy:
![Screenshot from 2021-11-07 19-48-42](https://user-images.githubusercontent.com/71127352/140659694-77af77b0-75f7-425c-9269-9af172d3c29e.png)
Robotech Invasion:
![Screenshot from 2021-11-07 19-49-42](https://user-images.githubusercontent.com/71127352/140659698-c71ab27d-4973-4cf2-8f4f-075d35467507.png)

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Ubuntu 20.04.3 LTS
CPU | Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Graphics Device | Mesa Intel(R) HD Graphics (BDW GT1)
Graphics Driver | Drivers: 4.6 (Core Profile) Mesa 21.0.3

**Comment by abaire** [comment]
So far there are at least two different root causes leading to exploding geometry; it'd be interesting to re-test this with #688 (the fix for #686 and #174).

**Comment by Triticum0** [comment]
@abaire I tested spy vs spy and they was no difference so the issue unrelated.

**Comment by abaire** [comment]
Thanks!

**Comment by Triticum0** [comment]
I created a log it if it helps
[log.zip](https://github.com/mborgerson/xemu/files/7988555/log.zip)

**Comment by Triticum0** [comment]
@abaire I Did some research and it turns out all these games use the same game engine which is why they all have the same issue.

https://www.retroreversing.com/xbox-game-engines

**Comment by abaire** [comment]
Hey @Triticum0 can you re-test with PR #1080 to see if any games other than Spy vs. Spy are fixed? It might also be worth checking #309, it's unclear how many different issues there are causing the corruption in different games.

**Comment by Triticum0** [comment]
Sure

**Comment by Triticum0** [comment]
Yeah, #309 should be edited or closed. My info at the bottom of the page is relevant but most of the issues stated at the top have been fixed.

**Comment by Triticum0** [comment]
@abaire #1080 fixes all the games allowing them to have the correct menus and go ingame
