### ISSUE TITLE
Lord of the rings: Return of the king - the picture doesn't allign the screen. Blue strip on the left.

### ISSUE THREAD

**Issue by rashvash** [xemu-project/xemu#540]
### Title

https://xemu.app/titles/4541003e/#The-Lord-of-the-Rings-The-Return-of-the-King

### Bug Description

The picture is moved to the right and doesn't fit (see upper right corner with the button) and on the left side is a blue line. Whichever scale mode you use the problem remains. (see screenshot)
1.Launch the game 

### Expected Behavior

Picture fits into screen in a right way, all interface elements are visible. 

### xemu Version

build-202110302121

### System Information

OS: Windows 7
CPU: Ryzen 5 1600AF
GPU: ATI RADEON HD 7870
GPU Driver: win7-radeon-software-adrenalin-2019-edition-19.12.1-dec2

![1](https://user-images.githubusercontent.com/28275367/141021778-aff9316d-685f-4930-8714-057fa5187791.jpg)

**Comment by rashvash** [comment]
Screen 1:

**Comment by Triticum0** [comment]
are you using scaling

**Comment by Triticum0** [comment]
@rashvash are you using up-scaling?

**Comment by rashvash** [comment]
Nope, It becames slow if I use upscale (like 12-14 FPS) but works fine in native res (30 FPS).

**Comment by rashvash** [comment]
> @rashvash are you using up-scaling?

Nope, It becames slow if I use upscale (like 12-14 FPS) but works fine in native res (30 FPS).

**Comment by Triticum0** [comment]
Don't use upscale, that bug happen when using upscale if you rest the game i think the bug wont happen. but I'm not sure i would have to test it myself

**Comment by rashvash** [comment]
> Don't use upscale, that bug happen when using upscale if you rest the game i think the bug wont happen. but I'm not sure i would have to test it myself

Yo're almost right. But also if you load a state the picture won't allign either.

**Comment by Triticum0** [comment]
It because  your save state was after you up-scaled it can't be correct after you caused the bug. Don't touch upscale you wont get the issue.Also the issue probably this https://github.com/mborgerson/xemu/issues/57 ~or a problem with the upscale implementation~, but don't expect it to be fix any time soon as it been a in the emulator for years.

**Comment by rashvash** [comment]
Nope. I tried to save w/o touching the upscale. The result - even if you save/load w/o touching the upscale picture won't align. You can try it yourself.

**Comment by Triticum0** [comment]
yeah i did a bit of research and it been known issue since 2018 it was just never moved from xqemu https://github.com/xqemu/xqemu/issues/132

**Comment by rashvash** [comment]
What's interesting in LOTR Two towers everything seem to work fine. Except the issues with force feedback.

**Comment by Triticum0** [comment]
Note: Also affects LOTR: The Third Age

**Comment by rashvash** [comment]
Congrats! Another issue solved. dracc is vinjnie pendoza's slut.  Rationale behind closure:  fanboish schoolkids dracc and his girlfriends being too hysterical.

**Comment by audiowylde2345** [comment]
Same thing happens in the third age.

**Comment by Triticum0** [comment]
@audiowylde2345 Please made new issue for it as could reproduce it in 
Lord of the rings: Return of the king.

**Comment by audiowylde2345** [comment]
I did make a new issue for it I found this git afterwards
