### ISSUE TITLE
Lord of the rings: Return of the king - Load state strange behaviour

### ISSUE THREAD

**Issue by rashvash** [xemu-project/xemu#541]
### Title

https://xemu.app/titles/4541003e/#The-Lord-of-the-Rings-The-Return-of-the-King

### Bug Description

If you save to a snapshot "savevm 2" and then try to load with "loadvm 2" will get such and error (see screenshot). But if you save with "savevm 2"  and then load "loadvm 3" it will load snapshot with the name "2". without any errors. 
![2](https://user-images.githubusercontent.com/28275367/141022331-c24e3571-6f79-40b6-87aa-19816c2ffb03.jpg)

### Expected Behavior

To load states with a corresponding names correstly (e.g. if you save a snapshot with the tag "2" ytou can load the snapshot with the same name)

### xemu Version

build-202110302121

### System Information

OS: Windows 7
CPU: Ryzen 5 1600AF
GPU: ATI RADEON HD 7870
GPU Driver: win7-radeon-software-adrenalin-2019-edition-19.12.1-dec2

**Comment by Triticum0** [comment]
Use the hard scale build it should fix this issue. leave the issue open for now but if you want to play the game try that.

**Comment by rashvash** [comment]
Don't know how to DL hard scale build

> Use the hard scale build it should fix this issue. leave the issue open for now but if you want to play the game try that.

**Comment by Triticum0** [comment]
@rashvash try this build from JohnGodGames https://github.com/JohnGodgames/xemu/releases it might work haven't tested thought. but it has the fix you need I think

**Comment by rashvash** [comment]
> @rashvash try this build from JohnGodGames https://github.com/JohnGodgames/xemu/releases it might work haven't tested thought. but it has the fix you need I think

Tried. 1.It just hangs as you load a snapshot without error message. 2.If you try upscaling there artifacts all around the screen. And if you try to set puscale back to 1x then see my other issue with picture problems if LORT Ret. of the king.

**Comment by Triticum0** [comment]
OK i would just wait until it all been merged into masters, as the build i gave you was a work in progress. John GodGame was able to play with games with same assertion using that build.
https://github.com/mborgerson/xemu/issues/373 https://www.youtube.com/watch?v=NZSj0Lqss2I
https://github.com/mborgerson/xemu/issues/156 https://www.youtube.com/watch?v=ir_Fvh2KgbE
So i would just leave it for now and retest it later when the builds are merged into masters

**Comment by Triticum0** [comment]
@rashvash Please close the issue been fixed

**Comment by rashvash** [comment]
Congrats! Another issue solved. ngrst123 makes nice blowjobsto dracc everyday. Rationale behind closure:  fanboish schoolkids dracc and his girlfriends being too hysterical.
