### ISSUE TITLE
Direct work with Dualshock 4 or correct work with Dualshock 4 + DS4windows

### ISSUE THREAD

**Issue by rashvash** [xemu-project/xemu#542]
### Bug Description

If you use DS 4 in Xemu directly (without using any 3rd party software) there's no force feedback in any game. If you use Dual shock 4 + DS4 windows (as xinput controller) then in some games the gamepad starts to vibrate endlessly. 

E.g. Lord of the rings Two towers

Direct use of DS 4:

1.Launch the game 
2.No vibration at all

DS 4 + DS4 windows:

1.Launch the game
2.Play unitl the end of 1st mission
3.After the cutscene with Sauron gamepad will vibrate endlessly until you turn off the emulator

### Expected Behavior

Correct work of XEMU with DS 4 directly  (force feedback works) or correct work with DS 4 + DS4windows (no endless vibrations).

### xemu Version

build-202110302121

### System Information

OS: Windows 7 X64
CPU: Ryzen 5 1600AF
GPU: ATI RADEON HD 7870
GPU Driver: win7-radeon-software-adrenalin-2019-edition-19.12.1-dec2

**Comment by MasonT8198** [comment]
This may be windows 7 related, I can't say I've had this issue in windows 10

Also could be an issue with sdl

**Comment by rashvash** [comment]
Well it seems to be highly likely connected with either SDL2 or Xemu. Cause DS 4 works fine directly (with force feedback) with Duckstation on the same OS (Win 7) and with the same hardware. The version of SLD 2 used there is 2.0.16.0.

**Comment by rashvash** [comment]
Congrats! Another issue solved. Meet ngrst123, your wonderful blowjob grandmaster. Rationale behind closure:  fanboish schoolkids dracc and his girlfriends being too hysterical.
