### ISSUE TITLE
Seablade and Nba jam menu is not fully rendered

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#547]
### Title

https://xemu.app/titles/544d0009/#SeaBlade
https://xemu.app/titles/41430013/#NBA-Jam

### Bug Description

The text on the menu screen for both games are missing.
xemu:
![Screenshot from 2021-11-02 22-48-01](https://user-images.githubusercontent.com/71127352/141383159-517f2d88-1f77-4cdd-b5e9-e6b9758cc28f.png)

xemu:
![Screenshot from 2021-11-02 22-48-27](https://user-images.githubusercontent.com/71127352/141383256-5a0d826a-32e4-4ad8-9d59-3d530d54fdde.png)

xemu:
![Screenshot from 2021-11-02 22-48-31](https://user-images.githubusercontent.com/71127352/141383263-6c3a3dc9-a4d9-41ca-8b81-edeced543d21.png)

xemu:
![Screenshot from 2021-11-11 23-30-03](https://user-images.githubusercontent.com/71127352/141383478-fc8dd2d9-80f4-4f6e-9fb1-e83364794bca.png)

### Expected Behavior

Text should be rendered 
xbox:
![Screenshot from 2021-11-11 23-52-06](https://user-images.githubusercontent.com/71127352/141385456-3669e142-d431-4c3a-840d-55b3bc44f0d4.png)

xbox:
![Screenshot from 2021-11-11 23-52-14](https://user-images.githubusercontent.com/71127352/141385470-337b8c37-e27a-4502-a47d-6ecb2af7239f.png)

xbox:
![Screenshot from 2021-11-11 23-52-35](https://user-images.githubusercontent.com/71127352/141385486-8ef52b53-da25-49bd-95bb-c5bfb37a8625.png)

xbox:
![Screenshot from 2021-11-11 23-50-26](https://user-images.githubusercontent.com/71127352/141385769-4ba49ca6-fa89-48d7-a78e-22db0c2efc90.png)

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: N/A

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

Interesting tidbit the same bug on Nba jam also occurs on pcsx2

**Comment by abaire** [comment]
For SeaBlade at least I'm relatively confident this is an issue with the way xemu handles [`pvideo`](https://github.com/mborgerson/xemu/blob/master/hw/xbox/nv2a/pgraph.c#L4590).

If I run SeaBlade with my debugger branch and examine the backbuffer, the menu text is all there and is rendered correctly. My guess is that the pvideo output is actually supposed to be rendered under the 3d content, but is getting placed on top instead. I haven't looked at how pvideo is supposed to work at all yet so I'm not sure if there's just some configuration or default that's not being respecte.

**Comment by abaire** [comment]
I'm initially suspicious of https://github.com/mborgerson/xemu/blob/b3f56db428f7796345fb39907a6a87ccf82336c2/hw/xbox/nv2a/pgraph.c#L4633

My assumption is that they're doing an overlay w/ color keying enabled and xemu just hasn't implemented that for the pvideo.

**Comment by abaire** [comment]
Confirmed that it's a color keying issue. Based on the fact that the 3d framebuffer had a black background, I hardcoded a check into the fragment shader at https://github.com/mborgerson/xemu/blob/b3f56db428f7796345fb39907a6a87ccf82336c2/hw/xbox/nv2a/pgraph.c#L4549

```
        "            if (out_Color.rgba == vec4(0.0)) {\n"
        "               out_Color.rgba = texture(pvideo_tex, coord);\n"
        "            }\n"
```

and the menu is displayed correctly. At the moment I'm not sure how the color key color is specified or if it's a feature that can be toggled, so more investigation is needed.

![Screenshot_20220122_100653](https://user-images.githubusercontent.com/448413/150650398-1bae5fa0-77c6-4e3a-a2e0-c965195ff00a.png)

**Comment by abaire** [comment]
Relevant noveau stuff:
Color key reg is 
https://github.com/samnazarko/linux-imx6/blob/1f8e1249cf0662847f2b50cb59eb45ffb33ede61/drivers/gpu/drm/nouveau/dispnv04/nvreg.h#L490

And enabling color keying is done as part of the display register: NV_PVIDEO_FORMAT_DISPLAY_COLOR_KEY https://searchcode.com/file/207258952/drivers/gpu/drm/nouveau/dispnv04/overlay.c/

**Comment by abaire** [comment]
@Triticum0 can you re-test NBA Jam when you have a chance? I don't own it and have only tested w/ SeaBlade. I'd be particularly interested if it does _not_ work as I'm not entirely sure the color key handling (ignoring alpha) is correct.

**Comment by Triticum0** [comment]
Doesn't fix NBA Jam Seem to be an ordering problem as pcsx2 has the same issue  https://github.com/PCSX2/pcsx2/issues/5262.
Also tested [Rolling](#584) and it doesn't fix that issue. Good Work!!
