### ISSUE TITLE
Strange work of save/load snapshots

### ISSUE THREAD

**Issue by rashvash** [xemu-project/xemu#548]
### Bug Description

The work of snapshots seems to be strange as well. I delete snapshots with delvm name of snapshot. It is deleted from the list (it's not on the list if you check it with info snapshots). But it's not deleted from xbox HDD (and real HDD as well).
And if I save a snapshot in e.g. LOTR ret. of the king with savevm 4, then delete it with delvm 4. Then save a snapshot with savevm 4 in Tenchu. Then load it with loadvm 4 - it loads LOTR's snapshot.

### Expected Behavior

1.Real deletion of snapshots (not only from the list of snapshots but real deletion from xbox HDD (and real HDD)
2.Complete deletion of snapshots so that a snapshot saved in one game then deleted won't load after you save in an other game with the same name of snapshot.

### xemu Version

build-202110302121

**Comment by Triticum0** [comment]
I would rename the title it not very clear looking at it what your taking about

**Comment by rashvash** [comment]
Suggestions?

**Comment by Triticum0** [comment]
Snapshots don't delete correctly using delvm on windows 7. That if your using win7

**Comment by Darknior** [comment]
I will not create an issue for that i prefer ask it here, but i have read on web site we must use debug/console to write "savevm ??" to make a savestate or snapshot, ok.
But when we play on TV with gampad it is impossible, is there a way to do it with gamepad ? or keyboard with a shortcut ?
Or maybe a linux command i can launch in the shell with  a key2pad ?
Thanks a lot

**Comment by Triticum0** [comment]
@Darknior A shortcut button combination command for controllers hasn't been implemented, sorry probably not what you wanted to hear. You can use the ~ key to open up the monitor, but you have to do the command manually to save the VM using the keyboard. As currently, savestate slots are a feature present in Xemu.

**Comment by Darknior** [comment]
> @Darknior A shortcut button combination command for controllers hasn't been implemented, sorry probably not what you wanted to hear. You can use the ~ key to open up the monitor, but you have to do the command manually to save the VM using the keyboard. As currently, savestate slots are a feature present in Xemu.

Thanks a lot for your answer. It's what i have understand on web site. So bad because it is impossible to use it with only a gamepad. I really wish it will be added in a near future the feature to do it with a button combination. 
Or if it is complicated a keyboard KEY or combination key. To make, load savestate, and an other to up and down the save slot.
For now i understand it is a test feature but it is impossible to use for real gamer users on TV ;)
But it is cool to know the feature is already working and it will come one day ...

**Comment by rashvash** [comment]
Congrats! Another issue solved Rationale behind closure:  fanboish schoolkids dracc and his girlfriends being too hysterical.
