### ISSUE TITLE
Braveknight: Lieveland Eiyuuden: NV097_SET_SURFACE_FORMAT_ZETA_Z24S8 assertion failed

### ISSUE THREAD

**Issue by Nes370** [xemu-project/xemu#554]
### Title

https://xemu.app/titles/494c0002/#Braveknight-Leverant-Eiyuuden

### Bug Description

Game crashes at launch due to graphics error.

Steps to reproduce this issue:
1. Launch game

![image](https://user-images.githubusercontent.com/25238987/142533005-3c4cadbd-9614-4928-a760-1ee0aa0dbee7.png)
![image](https://user-images.githubusercontent.com/25238987/142533246-eb85612f-9d20-492d-8fd4-83efe5a0f4db.png)

2. Press ignore

![image](https://user-images.githubusercontent.com/25238987/142533409-34f16dd1-5265-4c31-a60b-a17a59ac5760.png)

### Expected Behavior

Game should display graphics and progress to title screen.

### xemu Version

0.6.2-3-g1a15d83c44

### System Information

OS: Windows 10
CPU: Intel Core i5-10600K CPU @ 4.10 GHz
GPU: NVIDIA GeForce RTX 3070
GPU Driver: NVIDIA 496.76

### Additional Context

Recent commit fixed NV097_SET_SURFACE_FORMAT_ZETA_Z16 error, but now faces this issue.

**Comment by Triticum0** [comment]
I've added it on to issus #322 Please close this issue.
