### ISSUE TITLE
Booting MCPX 1.1 kernels broken again

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#555]
### Bug Description

At some point it broke again.

### Expected Behavior

Work

### xemu Version

master

**Comment by Ernegien** [comment]
This appears to only affect retail version 5838, other matching 1.1 retails and scene bios images still function.

**Comment by mborgerson** [comment]
@GXTX Please update the issue to include more details:

* What is meant by "broke"? What is happening?
* What kernel image you're using, including some hash
* What version of xemu was last functional for you
* Confirm your bootrom hash

**Comment by GXTX** [comment]
```
game (
	name "xbox-5101"
	description "Xbox v1.2/v1.3/v1.4/v1.5 (Kernel Version 1.00.5101.01)"
	rom ( name xbox-5101.bin size 262144 crc e8a9224e md5 769898e9682e1f5d065b5961460d03e6 sha1 5108e1025f48071c07a6823661d708c66dee97a9 )
)

game (
	name "xbox-5530"
	description "Xbox v1.4/v1.5 (Kernel Version 1.00.5530.01)"
	rom ( name xbox-5530.bin size 262144 crc 9569c4d3 md5 e455feb286dfc16272ad94d773c24460 sha1 40fa73277013be3168135e1768b09623a987ff63 )
)

game (
	name "xbox-5713"
	description "Xbox v1.4/v1.5 (Kernel Version 1.00.5713.01)"
	rom ( name xbox-5713.bin size 262144 crc 58fd8173 md5 e27bbf815c67bcbf359907a68ea46978 sha1 8b7ccc4648ccd78cdb7b65cfca09621eaf2d4238 )
)

game (
	name "xbox-5838"
	description "Xbox v1.6 (Kernel Version 1.00.5838.01)"
	rom ( name xbox-5838.bin size 262144 crc 5be2413d md5 c5907d241de37c22b083b6e30fa934b0 sha1 b9489e883c650b5e5fe2f83a32237dbf74f0e9f1 )
)
```

Are non-function with current master. I am only opening this for documentation, work with Ryzee to further verify this issue - he has the same issue with master *before* & after the USB work in #550.

**Comment by GXTX** [comment]
It's an issue with eeprom generation. Retested using my own eeproms, all 1.1's boot.

**Comment by mborgerson** [comment]
Great. In future issues, please include more detail when you create an issue.

**Comment by GXTX** [comment]
Thanks
