### ISSUE TITLE
there's any advantage to change 64MB to 128MB in Settings?

### ISSUE THREAD

**Issue by rrrcabral** [xemu-project/xemu#558]
### Bug Description

i know that 128MB is the development kits memory,
but change to this in xemu has any benefit? change to 128MB cause incompatibilty?

### Expected Behavior

.

### xemu Version

.

**Comment by dracc** [comment]
It has the same benefits as adding 128 MB RAM to your physical Xbox, i.e. not much.
Shouldn't cause trouble.

**Comment by Triticum0** [comment]
This should be closed as it not an issue. Question should be asked on the [discord](https://discord.com/invite/ayyjsuM)
