### ISSUE TITLE
Framebuffer upload during `pgraph_gl_sync` can fail

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#56]
```
xemu/hw/xbox/nv2a/pgraph.c:3671: pgraph_gl_sync: Assertion `glGetError() == GL_NO_ERROR' failed.
```
Title: 4d53006e

**Comment by wilkovatch** [comment]
It could be #40, to be sure re-test it when #48 is merged

**Comment by dracc** [comment]
@wilkovatch Thanks for your input. I get this result when testing with b995ece6945f9f90d4 from #48 
According to @mborgerson, it's a different issue.

**Comment by dracc** [comment]
Not sure exactly when it happened, but this issue seems to have been fixed. Closing.
