### ISSUE TITLE
The Suffering <Assertion Failed>

### ISSUE THREAD

**Issue by DTGillespie** [xemu-project/xemu#562]
### Title

https://xemu.app/titles/4d570015/

### Bug Description

On instantiation of the render pipeline within the first scene of a New Game—

[System Out: /hw/xbox/nv2a/pgraph.c:5062: pgraph_download_surface_data_to_buffer: Assertion `surface->pitch >= (surface->width * surface->fmt.bytes_per_pixel)' failed.]

### Expected Behavior

Assertion of 'surface->pitch >= (surface->width * surface->fmt.bytes_per_pixel' to equal true

### xemu Version

0.6.2.1-ga3e507860e

### System Information

Linux Dell-G5-5590 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1650/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 495.44
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler

**Comment by Triticum0** [comment]
@DTGillespie Where you using Render scaling when testing, if so disable it and you be able to make it ingame.
Also I will add to this to #520 if it was due to the up-scaling and then you can close the issue. It make the issue list less bloated that way.

**Comment by DTGillespie** [comment]
> @DTGillespie Where you using Render scaling when testing, if so disable it and you be able to make it ingame. Also I will add to this to #520 if it was due to the up-scaling and then you can close the issue. It make the issue list less bloated that way.

Yes I was using render scaling and disabling it corrected the Assertion Failure, thank you.
