### ISSUE TITLE
The need for speed series(excluding Need for Speed: Hot Pursuit 2) and MTX motorcross dont render correctly

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#564]
### Title

https://xemu.app/titles/41560022/#MTX-Mototrax
https://xemu.app/titles/45410047/#Need-for-Speed-Underground
https://xemu.app/titles/4541005a/#Need-for-Speed-Underground-2
https://xemu.app/titles/4541007b/#Need-for-Speed-Most-Wanted
https://xemu.app/titles/4541009e/#Need-for-Speed-Carbon

### Bug Description

When going in-game for these games, all objects rendered on screen excluding car models are not correctly rendered this is present for all the games. Also Affects Menus if you manage to make it in-game (Menu don't render with the need for speed series).
Need for Speed Underground
![Screenshot from 2021-11-21 17-25-54](https://user-images.githubusercontent.com/71127352/142773324-7d6407d3-793b-4dff-8a9b-2f7c7fe92677.png)

Need for Speed Underground 2
![Screenshot from 2021-11-21 17-25-36](https://user-images.githubusercontent.com/71127352/142773315-bb7ab732-6bb1-4f50-b823-032ab3a7858a.png)

Need for Speed Most Wanted
![Screenshot from 2021-11-21 17-26-06](https://user-images.githubusercontent.com/71127352/142773340-6f72cf97-c489-461e-a30a-67b75606588c.png)
Step to reproduce:
1.Insert disk
2.Mash a to enter a race 

### Expected Behavior

It should render correctly

### xemu Version

Version: 0.6.2
Branch: master
Commit: 5faa241
Date: Sat Nov 20 08:53:11 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Ubuntu 20.04.3 LTS
CPU | Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Graphics Device | Mesa Intel(R) HD Graphics (BDW GT1)
Graphics Driver | Drivers: 4.6 (Core Profile) Mesa 21.0.3

### Additional Context

Video for issue are below:
[Need for Speed Underground](https://www.youtube.com/watch?v=2OWLHfFzUSQ)
[Need for Speed Underground 2](https://www.youtube.com/watch?v=vh6PFLvl_1c)
[Need for Speed Most Wanted](https://www.youtube.com/watch?v=fzoIA1uDxCA)

Big thank to guru emulation for the footage

**Comment by B00MST3R** [comment]
it doesn't even load for me on my mac with the xemu app, it plays the game with sound, but shows a blank screen only.
