### ISSUE TITLE
Halo: CE doesn't go ingame

### ISSUE THREAD

**Issue by Shoegzer** [xemu-project/xemu#58]
Select "Campaign" mode, player profile, then "Normal" difficulty.  Screen fades to black and remains there.

**Comment by mborgerson** [comment]
This title is known to have cache problems. Try with a new hard disk image, or clear your cache partitions.

**Comment by Shoegzer** [comment]
Thanks, will do.

Actually @mborgerson is there an easy way to clear cache partitions or should I install a custom dash for that?

**Comment by Shoegzer** [comment]
Just tried with a new HD image but getting the same result - black screen on game start.  Tested with commit 4cd7c98025825362216f2e26fc8930219b585250 using Linux Mint 20 and kernel 5.4 compiled with gcc 9.3.0.  Request reopen?

**Comment by mborgerson** [comment]
Please:
* Test with latest master revision
* Confirm you have downloaded a fresh HDD image from here: https://github.com/mborgerson/xemu-hdd-image/

Questions:
* Which Halo release and have you modified disc contents at all? Are you using stock Halo:CE?
* How have you packed your ISO? Please try with extract-xiso if using a different tool.
* Which BIOS rev?

**Comment by Shoegzer** [comment]
All good suggestions, thanks!

I just updated to latest master but I'm getting the same black screen.  I did try downloading your hd image but you may want to check the "download a pre-built image here" link, it's broken (at least it appears so for me).  I'm happy to download and try against it though.

This is stock Halo:CE, as an uncompressed .iso.  Using 4627 bios.

**Comment by mborgerson** [comment]
Link fixed, thanks!

**Comment by Shoegzer** [comment]
Perfect, and you were right - it was the HD image.  The game works fine now.

As a suggestion, you may want to create a quick template which testers would see when opening an issue.  This would ask the tester to use the stock HD image from your site, plus indicate the bios, flash and boot rom, commit level, OS/kernel used, compiler used, etc.  At least in my case, it might have saved you a bit of headache and time asking me for them (though honestly I should have remembered to do this to begin with).

Thanks again!

**Comment by mborgerson** [comment]
Thanks, I do plan to create issue templates, just haven't got to it yet.

Glad you were able to get it working. Come join us in the xemu Discord Server to chat if you'd like.
