### ISSUE TITLE
Lighting problems

### ISSUE THREAD

**Issue by RageXbox** [xemu-project/xemu#580]
### Bug Description

For some reason the startup animation has a lighting problem where the background is darker than hardware and at the end the flash is brighter than hardware. Halo 2 has one where the Battle Rifle number screen is not shining. Possibly all the other games has one too.
https://xemu.app/titles/4d530064/#Halo-2
### Expected Behavior

Should light correctly as real hardware.

### xemu Version

v0.6.2-9-g69ceec4446

### System Information

Windows 10 (64-bit) 
(Intel(R) Xeon(R) CPU E5-2678 v3 @2.50 GHz) 
(NVIDIA Quadro P5000)
(NVIDIA 472.47)

### Additional Context

![093C27BD-2124-4D3D-9DB5-7E1F67568FFA](https://user-images.githubusercontent.com/76413188/144318185-6c574540-1615-435a-ace7-a7a53925e838.png)
![D9FD24C2-4399-48AB-8766-0CDF652C5FD3](https://user-images.githubusercontent.com/76413188/144318191-90f0015a-fcec-41dd-bf4a-5b6891a5aa07.png)
Xemu
![Screenshot_2021-11-30_202809](https://user-images.githubusercontent.com/76413188/144319345-456cc49f-d74d-4739-bb72-4208b34e26d2.png)
Hardware
![Screenshot_2021-11-30_203053](https://user-images.githubusercontent.com/76413188/144319378-96c6c4ca-d697-4833-b7f7-16b4c0945efc.png)

**Comment by abaire** [comment]
@RageXbox can you update this with the results from the latest master? Are there still remaining issues that should be tracked here or are they tracked elsewhere already?

**Comment by Triticum0** [comment]
Xbox boot screen fixed
