### ISSUE TITLE
 nv2a PIO is not emulated yet

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#588]
### Bug Description

This prevents Xbox-Linux from booting.

However, having Xbox-Linux would probably be good for simple tests.
The research about PIO might also help with debugging retail games.

### Additional Context

his was ripped directly from https://github.com/xqemu/xqemu/issues/27 So big thank to JayFoxRox for the information. looking at the code it is still not implemented so I will leave this hear for now. If I'm incorrect please remove, but looking at NV2A I cant see a file with that name so I think my assumption correct. This seem Low Priority anyway so this will be hear for a couple more years.

**Comment by GXTX** [comment]
Xbox-Linux doesn't boot because of #95 not that.

**Comment by Triticum0** [comment]
Ok, thank for the info.
