### ISSUE TITLE
Steel Battalion Crash on Start

### ISSUE THREAD

**Issue by HadetTheUndying** [xemu-project/xemu#59]
Title "Steel Battalion" will crash on start.

<details>
<summary>"Steel Battalion Crashes on Launch"</summary>
```
xemu: /home/hadet/Documents/projects/xemu/xemu/hw/xbox/nv2a/pgraph.c:2482: pgraph_method: Assertion `false' failed.
[1]    13161 abort      ./xemu
```
</details>

**Comment by HadetTheUndying** [comment]
Line of Contact, the "Sequel" will get to the menus but generates the same crash line.

**Comment by mborgerson** [comment]
Thanks for filing! This issue and #60 are the same. I'll update #60 with this info and close this issue.
