### ISSUE TITLE
Huge performance issues and crashes.

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#590]
### Bug Description

None of the games i tried work correctly.
They all have massive performance issues, and some started crashing, which didn't happen before (at least for colin mcrae rally 3)

Games tested:behaviour : 
Colin McRae rally 3 : Crashes before loading any race, only the super specials are selectable instead of normal tracks, championship mode crashes before shakedown
007 Nightfire: Extremely low framerate. (10/20fps instead of 60) crashes after the ending cutscene of the tutorial level
Burnout Revenge: Very low framerate, 29 fps instead of 60
Note : my CPU is used by less of 60% while using Xemu, GPU is at 30FPS

Footage of all of this happening : https://www.youtube.com/watch?v=d63MEWMfBf4

### Expected Behavior

Playing Xbox games

### xemu Version

Version: 0.6.2-10-gaa7acc8f64
Branch:  master
Commit:  aa7acc8f64e64bb517a0bd0e5e41672671e61df1
Date:    Fri Dec  3 01:12:29 UTC 2021

### System Information

OS: Windows 10 Enterprise Edition (21h1)
CPU: Intel Core i7-7700
GPU: nVidia GeForce GTX 1060 6gb (with factory overclock from PNY)
RAM: 16gb of ram

### Additional Context

Edit : after testing the same games on CBCX-Reloaded, the crashing issues might come from the ISOs as the same crashes happened, but the performance issue is still unresolved (007 nightfire ran at fullspeed with 0 drops, but with missing audio and some minor visual issues.)

**Comment by mborgerson** [comment]
Join Discord server for support

**Comment by ghost** [comment]
> Join Discord server for support

I will when i don't have to give my phone number to spyware.
