### ISSUE TITLE
xemu does not fully load or no xbox logo

### ISSUE THREAD

**Issue by Minetheground** [xemu-project/xemu#592]
### Bug Description

here is a log file

-------log-------
Created QEMU launch parameters: C:\Users\Minetheground\Documents\xemu\xemu.exe -machine xbox,bootrom=C:\Users\Minetheground\Documents\xemu\mcpx\mcpx_1.0.bin,kernel-irqchip=off -device smbus-storage,file=C:\Users\Minetheground\AppData\Roaming\xemu\xemu\eeprom.bin -bios C:\Users\Minetheground\Documents\xemu\complex4627v1.03\Complex_4627v1.03.bin -m 128 -drive index=0,media=disk,file=C:\Users\Minetheground\Documents\xemu\xbox_hdd.qcow2\xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=C:\Users\Minetheground\Downloads\Visual Tnt.iso -display xemu -audiodev none,id=snd0 
xemu_version: 0.6.2-10-gaa7acc8f64
xemu_branch: master
xemu_commit: aa7acc8f64e64bb517a0bd0e5e41672671e61df1
xemu_date: Fri Dec  3 01:12:29 UTC 2021
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GT 730/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 472.12
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
xemu_settings_get_path: config path: C:\Users\Minetheground\AppData\Roaming\xemu\xemu\xemu.ini
config_parse_callback: [system] flash_path = C:\Users\Minetheground\Documents\xemu\complex4627v1.03\Complex_4627v1.03.bin
config_parse_callback: [system] bootrom_path = C:\Users\Minetheground\Documents\xemu\mcpx\mcpx_1.0.bin
config_parse_callback: [system] hdd_path = C:\Users\Minetheground\Documents\xemu\xbox_hdd.qcow2\xbox_hdd.qcow2
config_parse_callback: [system] eeprom_path = C:\Users\Minetheground\AppData\Roaming\xemu\xemu\eeprom.bin
config_parse_callback: [system] dvd_path = C:\Users\Minetheground\Downloads\Visual Tnt.iso
config_parse_callback: [system] memory = 128
config_parse_callback: [system] shortanim = false
config_parse_callback: [system] hard_fpu = true
config_parse_callback: [audio] use_dsp = false
config_parse_callback: [display] scale = scale
config_parse_callback: [display] ui_scale = 1
config_parse_callback: [display] render_scale = 1
config_parse_callback: [input] controller_1_guid = keyboard
config_parse_callback: [input] controller_2_guid = 
config_parse_callback: [input] controller_3_guid = 
config_parse_callback: [input] controller_4_guid = 
config_parse_callback: [network] enabled = false
config_parse_callback: [network] backend = pcap
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [network] pcap_iface = 
config_parse_callback: [misc] user_token = 
config_parse_callback: [misc] check_for_update = true
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
-------log----------

### Expected Behavior

it should show a screen saying enter a xbox disc and to have the log file pass

### xemu Version

0.6.2-10-gaa7acc8f64

### System Information

Device name	DESKTOP-NCK4DBL
Processor	Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz   3.91 GHz
Installed RAM	16.0 GB
Device ID	E0687E60-76AA-40C1-8F50-9E1116D39E99
Product ID	00325-81126-33897-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	21H2
Installed on	‎29/‎11/‎2021
OS build	22000.348
Experience	Windows Feature Experience Pack 1000.22000.348.0

**Comment by mborgerson** [comment]
Check your BIOS

Join the Discord server for support.
