### ISSUE TITLE
JSRF: Cannot enter sewer area

### ISSUE THREAD

**Issue by AlmostReady7** [xemu-project/xemu#594]
### Title

https://xemu.app/titles/49470018/#JSRF-Jet-Set-Radio-Future

NTSC-U Combo Disc version

### Bug Description

Loading screen stuck in half-second loop.

I don't know how to recreate this glitch, per se, but when I enter the sewer area, the loading screen gets stuck in an approximately half-second loop.

I already completed the sewer area and had beaten the game, but now when I enter the sewer level, even from other save files, it gets stuck in this loop.

### Expected Behavior

You enter new areas of the game by moving the player-character into a corridor. The game then displays a loading screen for a few seconds. The loading screen sometimes repeats, sounding broken, but is expected to display the player-character entering the new area.

### xemu Version

0.6.2-10-gaa7acc8f64

Last working in the same version.

### System Information

OS: Windows 10
CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50 GHz 3.50 GHz
GPU: NVIDIA GeForce GTX 970
GPU Driver: 456.71

**Comment by mborgerson** [comment]
Have you tried clearing your cache?

**Comment by AlmostReady7** [comment]
I have not. How do you do that?

**Comment by GXTX** [comment]
Various dashboards have such a feature, such as https://github.com/dracc/NevolutionX

**Comment by theoldsport** [comment]
Ran into the same issue in a different area. Clearing cache partition resolved it

**Comment by AlmostReady7** [comment]
Oh, I never responded back to the thread, but yes, clearing the cache
through an alternative dashboard fixed the problem for me as well.
