### ISSUE TITLE
Support for emulated memory cards

### ISSUE THREAD

**Issue by strikersix23** [xemu-project/xemu#596]
### Feature Request

Use an 128mb fatx formated img file as an memcard

### Alternatives

Usimg an img file as an usb

### Additional Context

this would allow transfer of a raw rip of usb and memstick data to the host

**Comment by binarymaster** [comment]
Looks like a duplicate of #90 and/or #389.

**Comment by strikersix23** [comment]
Is there a temporary way to do so?

**Comment by GXTX** [comment]
There is yes, read QEMUs docs on usb-storage devices. Should close this issue as dupe.

**Comment by strikersix23** [comment]
I have but every hub/hub I use is rejected which one can I use?

**Comment by GXTX** [comment]
Any port that's not in-use. See my report in #90 for more info.

**Comment by Ryzee119** [comment]
Now that xemu supports  internal daughterboard and the controller internal hub you need to use hub `1.x.2` or `1.x.3` (which reflect the two ports on top of the original controller)

Where x=3,4,1,2 for player 1,2,3,4  respectively

**Comment by strikersix23** [comment]
Is there an example of use for xemu moniter

**Comment by GXTX** [comment]
See my original issue and read QEMUs docs.

**Comment by Ryzee119** [comment]
There appears to be a bug in qemu where device_add hangs. Stop first then resume. See https://gitlab.com/qemu-project/qemu/-/issues/650. This works for me

```
drive_add 0 if=none,id=usbdisk1,file=./test1.img
stop
device_add usb-storage,drive=usbdisk1,port=1.3.2
cont
```

test1.img needs to be an existing blank file of 8MB for an original size.

![image](https://user-images.githubusercontent.com/21236406/146660845-f46c4e04-f4b6-497a-a794-936d02617875.png)

**Comment by Ryzee119** [comment]
Works great, 4x8MB memory cards at once over 2 controllers.
![image](https://user-images.githubusercontent.com/21236406/146660928-d4fc067f-e0d6-492e-8bf9-19af13176a49.png)

**Comment by strikersix23** [comment]
Thank you

**Comment by strikersix23** [comment]
can this  be added to the documentation on the website?

**Comment by GXTX** [comment]
Can this be closed as invalid duplicate?
