### ISSUE TITLE
NV097_SET_SURFACE_FORMAT_ZETA_Z16 needs verification

### ISSUE THREAD

**Issue by Dragonslayer182** [xemu-project/xemu#60]
The Voodoo Vince demo on the Crimson Skies disc crashes upon trying to go in-game after selecting play on the main menu. This is the resulting error:

ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:2482:pgraph_method: assertion failed: (0)
Bail out! ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:2482:pgraph_method: assertion failed: (0)

Titles: 4d53005f, 4d530021, 43430002, 43430009

https://xemu.app/titles/4156000f/#Star-Wars-Obi-Wan
https://xemu.app/titles/494c0002/#Braveknight-Leverant-Eiyuuden
https://xemu.app/titles/4b4e0003/#ESPN-NFL-PrimeTime-2002
https://xemu.app/titles/43430005/#Group-S-Challenge
https://xemu.app/titles/4b4e0019/#Dance-Dance-Revolution-Ultramix
https://xemu.app/titles/41430003/#Legends-of-Wrestling
https://xemu.app/titles/4143000f/#Legends-of-Wrestling-II
https://xemu.app/titles/4143001d/#Showdown-Legends-of-Wrestling
https://xemu.app/titles/4d570029/#Mortal-Kombat-Shaolin-Monks
https://xemu.app/titles/45530016/#Backyard-Wrestling-2-There-Goes-the-Neighborhood
https://xemu.app/titles/4d530034/#Inside-Pitch-2003
https://xemu.app/titles/424d0002/#Reign-of-Fire
https://xemu.app/titles/53450029/#Spikeout-Battle-Street
https://xemu.app/titles/41540001/#Touge-R

**Comment by HadetTheUndying** [comment]
So i went ahead and started fiddling around with this a bit. Removing the Associated line does allow Steel Battalion to go into the Menu, The menu is rendered wrong and very slowly after this though. Some menu elements are totally black with frames around them. I was unable to test if the game would run after this because I haven't done the work to be able to use the controller within xemu yet and i cannot navigate any further than this because of it. Will continue to update, Might play around with it some more if i can be pointed in the correct direction.

**Comment by Triticum0** [comment]
Other title with assertion:
https://xemu.app/titles/494c0002/#Braveknight-Leverant-Eiyuuden
https://xemu.app/titles/4b4e0003/#ESPN-NFL-PrimeTime-2002
https://xemu.app/titles/43430005/#Group-S-Challenge
https://xemu.app/titles/4b4e0019/#Dance-Dance-Revolution-Ultramix
https://xemu.app/titles/41430003/#Legends-of-Wrestling
https://xemu.app/titles/4143000f/#Legends-of-Wrestling-II
https://xemu.app/titles/4143001d/#Showdown-Legends-of-Wrestling
https://xemu.app/titles/4d570029/#Mortal-Kombat-Shaolin-Monks
https://xemu.app/titles/45530016/#Backyard-Wrestling-2-There-Goes-the-Neighborhood
https://xemu.app/titles/4d530034/#Inside-Pitch-2003
https://xemu.app/titles/424d0002/#Reign-of-Fire
https://xemu.app/titles/53450029/#Spikeout-Battle-Street
https://xemu.app/titles/41540001/#Touge-R

**Comment by ChaseDerick** [comment]
I can't figure out how to reproduce this error on 0.8.96, due to another issue #34.

Going to assume issue is still fixed (For at least [Crimson Skies: High Road to Revenge](https://xemu.app/titles/4d530021#Crimson-Skies-High-Road-to-Revenge))

**Comment by Triticum0** [comment]
This was fixed while back
