### ISSUE TITLE
New MacOS compiles are damaged and not open on Big Sur 11.2

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#609]
### Bug Description

The latest MacOS versions are damaged and cannot open..
<img width="416" alt="Captura de Pantalla 2021-12-29 a la(s) 2 46 10 a  m" src="https://user-images.githubusercontent.com/87793814/147634706-7eca568d-c82b-4fa4-a4d0-888b93ff85e6.png">
.

### Expected Behavior

The emulator could be open with no issues...

### xemu Version

v0.6.2-18-g6454b7b9d4
Dec 29, 2021

### System Information

Os: MacOS CPU: Intel Iris Plus 650
MacOS Big Sur 11.2
MacBook Pro Late 2017

**Comment by mborgerson** [comment]
Thanks for reporting!
