### ISSUE TITLE
Input fails to work on Xbox bios revisions 3944 and 4034.

### ISSUE THREAD

**Issue by Aerocatia** [xemu-project/xemu#61]
When used with the 1.0 MCPX (or compatible ROM) these BIOS dumps will boot the Xbox dash, but input fails to work.

3944 SHA-256 `2BDA1753B6E535AF95FA9D7F7C6B1CE746F4DE3F470856814E63A72D94BCB3B8`
4034 SHA-256 `6053CEC50EEA1F246AE830C31A4D0DDC75A0FCC1530C168E125A8995433B65FA`

Side note, games don't boot with these either.

**Comment by Alastair0100** [comment]
also effects bios revision 4134

**Comment by GXTX** [comment]
Fixed in #550
