### ISSUE TITLE
Marvel vs. Capcom 2 starts in Xemu‘s latest versions 

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#614]
### Title

https://xemu.app/titles/43430007/#Marvel-vs-Capcom-2-New-Age-of-Heroes

### Bug Description

The game is "starts" in compatibility status and have a lot of glitches and sounds issues...
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 27 53 a  m" src="https://user-images.githubusercontent.com/87793814/147803400-6f7b9412-0139-4454-98bd-1b9840a961bd.png">
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 27 43 a  m" src="https://user-images.githubusercontent.com/87793814/147803431-1083df20-fa13-4701-8f7b-d7fda8a34903.png">
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 28 05 a  m" src="https://user-images.githubusercontent.com/87793814/147803501-3d5e8f7c-bf35-4822-b651-78bd23872355.png">
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 28 28 a  m" src="https://user-images.githubusercontent.com/87793814/147803527-c643ec3e-9bd4-49af-8f3c-604695c60366.png">
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 28 37 a  m" src="https://user-images.githubusercontent.com/87793814/147803605-2f8374ca-0a57-4b1d-9bee-85d41bfe47a7.png">

### Expected Behavior

The game should be launched fine and it would be full playable.

### xemu Version

Latest Release: v0.6.2-21-gd0f241c516
Dec 29, 2021

### System Information

Os: MacOS CPU: Intel Iris Plus 650
MacOS Big Sur 11.2
MacBook Pro late 2017

**Comment by ghost** [comment]
More scans of bugs:
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 45 26 a  m" src="https://user-images.githubusercontent.com/87793814/147804068-19820bea-4997-4d01-9eb0-230073ac39ea.png">

The depth effects are glitching.
<img width="1136" alt="Captura de Pantalla 2021-12-31 a la(s) 12 45 40 a  m" src="https://user-images.githubusercontent.com/87793814/147804078-aba83c1c-c01c-47b9-bbe6-acc6698e033e.png">

**Comment by Audiowylde23** [comment]
It doesn't work at all just black screen

**Comment by Audiowylde23** [comment]
Any update on this game it doesn't boot at all ?

**Comment by antoniodesousa** [comment]
Same, it doesn't boot at all. It's just black screen and nothing happens.
I don't know how it's marked as playable.

**Comment by Audiowylde23** [comment]
> Same, it doesn't boot at all. It's just black screen and nothing happens. I don't know how it's marked as playable.

Makes no sense at all. I'm sticking to Dreamcast version. Best thing about emulation is there are always options.
