### ISSUE TITLE
mem_dirty in pgraph_update_surface_part is always false under TCG

### ISSUE THREAD

**Issue by antangelo** [xemu-project/xemu#615]
### Bug Description

The offending code is here: https://github.com/mborgerson/xemu/blob/57795d81cbc26be2fd4ae764ad7656e27b790af6/hw/xbox/nv2a/pgraph.c#L5404-L5406

The condition short circuits to false when `tcg_enabled()` is true. As a result, dirty memory is never actually detected in practice.

Although unsupported, I've verified that using KVM will fix various graphical glitches that come through this code path. Specifically, these glitches occur when the pitch and offset of the surface are unchanged (resulting in `surface->buffer_dirty` being false) but the memory is changed. In such cases, the surface must be updated, but isn't under TCG.

### Expected Behavior

`mem_dirty` should be set to true if the corresponding memory address is marked dirty and the TCG accelerator is used.

### xemu Version

0.6.2-21-gd0f241c516

In previous versions, `surface->buffer_dirty` was set true if the surface pitch/offset was set at all, even if the value is unchanged. The most recent update changed this behavior, which reveals this bug.

**Comment by mborgerson** [comment]
> various graphical glitches that come through this code path.

Please list the glitches you've found that were resolved

**Comment by antangelo** [comment]
Strike force bowling (43560008) has the following viewport glitch on 0.6.2-21-gd0f241c516:
![bowling glitch](https://user-images.githubusercontent.com/25046221/147979232-ab9a50b9-cd36-4fa0-a614-67a08ad620a4.png)
This is resolved under KVM. I haven't been able to test other titles as of yet.

**Comment by mborgerson** [comment]
This particular issue is caused by something else, I'll fix it
