### ISSUE TITLE
Jet Set Radio Future [U]: does not start

### ISSUE THREAD

**Issue by Shoegzer** [xemu-project/xemu#62]
Booting this title results in the message "Please insert an Xbox disc..." and the game will not start, even though emulation status is listed as "[Starts](https://xemu.app/titles/49470018/)".  No regions other than USA were tested.

**Test info:**
- OS: Linux Mint 20, kernel 5.4
- CPU/GPU: Intel i7-7700HK, Nvidia 1070M, driver 450.80
- Compiler: gcc 9.3.0.
- Commit: 5aa0cec31b5560c0434de8e368ff07d1bb53228b
- BIOS: 4627
- Boot ROM: mcpx_1_0.bin
- Hard Disk Image: Stock, sourced from xemu site
- Game Region: USA

Hopefully this issue report is appropriate here (for example if the emulation status noted above is based on a different region of the game) but please feel free to close if not.

**Comment by mborgerson** [comment]
Thanks for the test info. A couple questions:

* Did you pack your ISO with extract-xiso?
* Did you try restarting xemu?

**Comment by Shoegzer** [comment]
You bet.  To answer your questions, it's an uncompressed .iso, and yes I did restart xemu.  Hope it helps.

**Comment by mborgerson** [comment]
Please confirm you have re-packed with extract-xiso. "redump" style ISOs are not compatible with xemu.

**Comment by Shoegzer** [comment]
Oh, I see!  I had no idea that was required.  The converted iso works now so I'll close the issue, but a few quick questions for you:

- What's the difference between the two formats?
- Can the xiso format "round trip" once converted; i.e. can it be reverted to the source format with a hash that matches the original?  I didn't see the option within extract-iso.
- Is xemu support for redump-style isos planned for some future point?

Thanks again.

**Comment by dracc** [comment]
* Redump format contains the full\* disc whereas the re-packed image only contains the game data partition.
* No, the redump format image contains filler data at the end which is seemingly random - can't be accurately recreated (yet).
* While not a priority, I'm sure redump support is on the wishlist.

\* The full disc contains a few more tricks and partitions than the redump format seems to care for, but for simplicity you can just think of it as the full 1:1 copy of an Xbox Game Disc with the Video partition (as seen when you put your game disc in a non-Xbox DVD drive), Game Data partition (where the game lives) and the "random" filler data.

**Comment by Shoegzer** [comment]
Thanks @dracc.  I had no idea the xiso format was not the full disc but that's too bad.  Support for the redump format would definitely be nice, particularly as it would promote accurate preservation of the original game source.  For now we'll need to keep titles around in both formats with one for xemu use exclusively.

**Comment by Shoegzer** [comment]
Update: For some reason now even the second copy of JSRF (the one that's been packed with extract-xiso) doesn't work either - I just get a black screen on booting or reset.  Is this a known issue @mborgerson?  If so I'm happy to reopen this issue or file a new one for it.  Tested with commit 416e12c3b32e215a2cff04bb2a535cdf84beca4d.  Thanks.

Update 2: Nevermind @mborgerson, this was due to a corrupt hard drive image.  Replacing with a clean image fixed the issue.  Not sure how image keep getting corrupted but I'm guessing it has something to do with the fact that the emulated system is being powered on and off constantly while ingame, which was not meant to happen with such frequency on an actual Xbox.  Thanks anyway.  Thumbs way up for all the amazing improvements lately btw.
