### ISSUE TITLE
nxdk binaries using NV097 methods with minimal changes to surface pitch/format leads to corrupted display

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#626]
### Bug Description

#607 seems to have introduced a regression that breaks nxdk-based binaries that make use of the 3D hardware but that do not make modifications to the surface format.

Example of the nxdk `triangles` sample:
![Screenshot_20220108_103818](https://user-images.githubusercontent.com/448413/148655766-37c953b6-e8d3-4c8e-a4f1-3c780135972e.png)

### Expected Behavior

Display should not be corrupted.

Same exact nxdk sample iso with commit 57795d81c reverted:
![Screenshot_20220108_103957](https://user-images.githubusercontent.com/448413/148655803-f93f6600-6084-4ec7-a600-23d0e45698b7.png)

### xemu Version

Any version post commit 57795d81c will exhibit this behavior.

### System Information

Tested on Kubuntu w/ Nvidia and M1 macOS machines.

**Comment by mborgerson** [comment]
Thanks for reporting, I'll take a look

Update: Issue is identified. Fix incoming.
