### ISSUE TITLE
Kernel "5713" fails to boot

### ISSUE THREAD

**Issue by Aerocatia** [xemu-project/xemu#63]
Attempting to use this BIOS results in the "Guest has not initialized the display" message.

BIOS: 5713, dumped from a "1.4" Xbox with xdump. 
EEPROM: "Retail 1.1-1.4" Hardware type, dumped from the same Xbox.
MCPX Boot ROM `mouse_rev1.bin` MCPX 1.1 replacement.

**Comment by Alastair0100** [comment]
its not just 5713 but any high number bios

**Comment by Fabxx** [comment]
The Dashboard version that works best is the 4627 afaik. Higher versions won't work and if i'm not wrong lower too

**Comment by SnowyMouse** [comment]
I cannot get my 5000+ BIOS stuff to work, either. (that is, the 5838 BIOS and EEPROM extracted from my 1.6 Xbox)

**Comment by Alastair0100** [comment]
i think every bios under 4627 works

**Comment by mborgerson** [comment]
This has been root-caused in #71
