### ISSUE TITLE
Marvel vs. Capcom 2: The game don't pass from the menu screen

### ISSUE THREAD

**Issue by ghost** [xemu-project/xemu#637]
### Title

https://xemu.app/titles/43430007/#Marvel-vs-Capcom-2-New-Age-of-Heroes

### Bug Description

This game don't pass from the menu screen. 

### Expected Behavior

The game should be works fine and run at 59-60 fps.

### xemu Version

v0.6.2-35-gd54ce00f02
Jan 9, 2022

### System Information

Os: MacOS CPU: Intel Iris Plus 650
MacOS Big Sur 11.2
MacBook Pro late 2017

### Additional Context

I made this issue report because the other are not very specific, my apologies.

<img width="1136" alt="2A7139BF-36D3-4E19-86BB-352C7294F66D" src="https://user-images.githubusercontent.com/87793814/148706752-f1dc153e-2536-4877-9a22-de65999bd3a3.png">
<img width="1136" alt="C07EAE7C-478E-4D32-B130-6A75CD057395" src="https://user-images.githubusercontent.com/87793814/148706762-77eef6b4-bd1e-44ba-8597-3e4ce67ac4af.png">
<img width="1136" alt="7AE7FC49-19EB-402A-AEA3-81013FEE491D" src="https://user-images.githubusercontent.com/87793814/148706770-31827f94-8983-4eaf-9a83-be099b0de85d.png">

**Comment by mborgerson** [comment]
This issue is not specific enough beyond the existing compatibility report.

Moreover, if you do file an issue and would like to add more details, you can always update an existing issue. No need to file new issues and close old, identical ones.
