### ISSUE TITLE
[Feature Request] DualSense support

### ISSUE THREAD

**Issue by Shoegzer** [xemu-project/xemu#642]
### Feature Request

This would add support for Sony's PS5 DualSense controller, which is replacing others such as the DS4 (already supported in xemu) in popularity.  I can help test any efforts to add this pad in linux.

**Comment by MasonT8198** [comment]
This is related to some SDL issues, so we are on an older release until those are fixed :(

**Comment by Shoegzer** [comment]
I see, that's too bad.  Do you know what the issues are, and if the SDL team is looking into them?  

This pad does work in other emulators (dolphin, pcsx2, rpcs3, yuzu etc.) so I'm guessing they've advanced to newer SDL2 requirements as the issues must not be affecting them.

Incidentally, using sdl2-2.0.10 globally here.

**Comment by Shoegzer** [comment]
Actually @MasonT8198, I assume you're referring to [this](https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5) commit, where xemu downgraded its local SDL2 library to 2.0.12 (though I'm still trying to find the reason - do you know?).  

So from what you've said, I assume DualSense only works with some SDL version higher than 2.0.12, and the other cases where the pad works are forcing the higher requirement locally even though I'm using 2.0.10 globally:
```
$ sdl2-config --version
2.0.10
```
Again I could be off by this, it's my best guess.

**Comment by mborgerson** [comment]
SDL version is held because hot plugging was broken on Windows. If you want to check if it's fixed I'd love to update.

**Comment by Shoegzer** [comment]
Thanks @mborgerson.  It seems from [here](https://github.com/libsdl-org/SDL/issues/4147) that the issue with hot plugging in Windows has been closed.  The final post links to the commit which resolves the issue.  Would this suffice?

**Comment by homeisfar** [comment]
I updated the SDL dependency in sdl2.mk to version 2.0.20 (sha256: c56aba1d7b5b0e7e999e4a7698c70b63a3394ff9704b5f6e1c57e0c16f04dd06). I built it and ran the .exe binary in Windows, and tested hot plugging two different controllers. It all works, and I think it's safe to say that SDL2 does not need to be held back anymore. 

The up-to-date SDL2 also correctly detected and used my DualSense under Linux, although in the input configuration the rumble did not activate when pressing the triggers. Aside from that minor issue, all the controls mapped correctly. The rumble did work on the other controllers I tried. 

If you'd like, I can open a pull request.

**Comment by Shoegzer** [comment]
Thanks @homeisfar!  Do you mean that rumble doesn't work at all, or just in the input configuration area?  I'll help you test your PR when you have a chance to open one.

**Comment by mborgerson** [comment]
I'll go ahead and do the SDL2 update. Thanks for the info!

Edit: I've confirmed the rumble issue with my DS4 controller and my Xbox One controller is not working at all. Each of these issues are show stoppers for upgrading and need investigation first.

**Comment by homeisfar** [comment]
Just FYI the two controllers I tried were an Xbox Series X controller and the other an 8bitdo pro 2 in DirectInput mode (It presents itself to the OS as an Xbox 360 controller). I don't own an Xbone controller, however, to test that one out.

**Comment by mborgerson** [comment]
Good news, I've figured out the SDL issues we will be able to upgrade shortly.

**Comment by mborgerson** [comment]
I've pushed an update with new SDL. Can you check if this is working now? Thanks

**Comment by ryzendew** [comment]
![image](https://user-images.githubusercontent.com/84041391/164949946-a6195c7f-bea3-4e1d-9317-c792d2e95854.png)
it works now thanks

**Comment by MasonT8198** [comment]
Yep, thanks matt

**Comment by Shoegzer** [comment]
Not working here yet unfortunately.  Tested commit 5c02155e56077217ce0c9bbb8b17ec71f9c2f0a5 with Linux Mint 20.3 and a wireless DualSense:

![pic](https://user-images.githubusercontent.com/12475371/164951580-603530e7-dfee-44eb-9356-3f7c83625d93.png)

**Comment by mborgerson** [comment]
@Shoegzer you probably need to update your sdl

**Comment by Shoegzer** [comment]
Ah thanks, and yeah, I'm still using sdl2-2.0.10 globally as per the Ubuntu repo.  I had assumed the updated SDL2 was going to be included as a submodule though.  Any way of still doing that or will users need to update?

**Comment by homeisfar** [comment]
Very nice. I just built the latest git from Linux -- Series X and DualSense both working with rumble and hotplugging on both. Wired on both.

@Shoegzer the SDL2 referenced in the sdl2.mk file is for cross compiling from Linux for Windows. For Linux itself it uses the development library your distro installed, so you will have to manually put the include headers in your path from SDL's source or somesuch thing.

**Comment by mborgerson** [comment]
The new LTS release of Ubuntu is out and ships with a newer SDL so if you upgrade your install I think it'll work for you. I have considered statically linking SDL for Linux, but with the new LTS I'm not sure it's worth the effort today

**Comment by Shoegzer** [comment]
Thanks guys.  Yup, the Mint team will update to version 21 soon which will use the updated Ubuntu repo so I suppose I'll wait for that as it shouldn't be long now.  I've compiled SDL2 before and ran into issues that took a while to manually work through so that method is suboptimal.  With that in mind I think it would be nice to have submodules for this sort of thing down the road as libraries / deps tend to change over time.

Not to distract from what's been done here with SDL2, because it sounds like it works well and that's very much appreciated!

**Comment by mborgerson** [comment]
@Shoegzer you may be able to find a ppa that has the latest sdl

**Comment by Shoegzer** [comment]
Actually I was able to work through some local issues and SDL2-2.0.20 compiled, and indeed the DualSense pad now works.  I'll close this now to free up the issue log.  Thanks again for this!
