### ISSUE TITLE
Midtown Madness 3: Freezes at a specific point in the game

### ISSUE THREAD

**Issue by Fanatic-64** [xemu-project/xemu#643]
### Title

https://xemu.app/titles/4d53002a/#Midtown-Madness-3

NTSC MS-042

### Bug Description

Steps to reproduce this issue:
1. In the main menu, select WORK UNDERCOVER
2. Select WASHINGTON D.C.
3. Select CAR SALESMAN
4. Select DIVA MANNERS
(Steps 3. and 4. will require having unlocked them first, either by completing previous jobs or using a cheat code to unlock everything (while holding Left Stick down press LT, RT, LT, LT, LT, RT, RT, RT, LT, LT, RT, RT).)
5. You will be told to "go fast". A few seconds after this (possibly when the objective is complete?) the game will freeze. Note that xemu itself does not crash when this happens.

### Expected Behavior

The game should not freeze and should continue normally.

### xemu Version

0.6.2-39-g01c2f0fa74

### System Information

OS: Windows 10
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU: NVIDIA GeForce GTX 1060
GPU Driver: NVIDIA Studio Driver 511.09 WHQL (30.0.15.1109)

### Additional Context

I've completed everything under SINGLE RACE and the entire PARIS half of WORK UNDERCOVER, and collected most car paints, and have not encountered any instances of the game freezing other than the one described here.

**Comment by BigheadSMZ** [comment]
This is not a valid issue, but rather the product of a bad dump. A clean dump from an original disc and this issue does not happen.

**Comment by LeRutY** [comment]
I think the multiplayer crashes (https://youtu.be/pjWpHhSG0kk?t=243) aren´t related to the "Diva Manners" issue so I´m going to open a new one just for the multiplayer

**Comment by ThanosK-byte** [comment]
> I think the multiplayer crashes (https://youtu.be/pjWpHhSG0kk?t=243) aren´t related to the "Diva Manners" issue so I´m going to open a new one just for the multiplayer

Have you managed to solve the singleplayer issue?

**Comment by Triticum0** [comment]
This is still an issue

**Comment by BigheadSMZ** [comment]
This pinged my email for some reason today so I'm just going to mention that I already mentioned the solution to this issue. The problem is a known bad dump, especially if it came from a "HDD ready" place. Try a good dump from a good disc (or elsewhere) and it will not freeze during the diva manners mission. I have personally verified this. There is also a "fix" available for the broken version which I can't/won't link but is not far off...
