### ISSUE TITLE
New pgraph named debug output produces incorrect/misleading names for looped handlers

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#644]
### Bug Description

https://github.com/mborgerson/xemu/commit/057e7fcfa18fd5ae23456eae093b7c127796e9d7 switched from printing raw values when `DEBUG_NV2A` is set to printing symbolic strings. While this is generally helpful, it discards some information and produces misleading output for cases where `INC_METHOD_LOOP_BEGIN` is in use.

For example, previously for a call to `NV097_SET_LIGHT_LOCAL_RANGE`, xemu would print
`nv2a: pgraph method (0): 0x97 -> 0x1024 (0x7149f2ca)`

This preserves the fact that the command is `0x1024` (`NV097_SET_LIGHT_LOCAL_RANGE`)

With the LUT change, the output discards the actual value and produces a misleading string:
`nv2a: pgraph method (0): NV097_SET_LIGHT_AMBIENT_COLOR (0x7149f2ca)`

I assume the same issue would apply for slot handling; e.g., I'm not sure we could tell the difference between setting the color for light1 from setting the color for light0.

### Expected Behavior

I think there are a few options:

1. Don't attempt to provide symbolic names at all, let them be cleaned up through some external post-processing of the log
2. Only provide symbolic names for non-looped handlers
3. Provide a best guess at the symbolic name, but always include the raw command as well so it can be post-processed.
4. Provide the correct symbolic name inside of the looped handlers (so it'd print the wrong thing but be followed by a more detailed correct thing. This has the benefit of exposing all of the parameters rather than just the first and has been critical in my debugging efforts, but it has a perf penalty).

Or some combination thereof. I think it's always useful to pass along the raw data for machine processing down the line, and it's definitely been very useful to me to have the full set of params inside of the loops (https://github.com/abaire/xemu/commit/1f84379d1599f8c3fbc8a207e764bdc82e1ab900 is what I've been using, along with some other logging tweaks)

### xemu Version

Latest master build, anything after 057e7fcfa18fd5ae23456eae093b7c127796e9d7 will exhibit this behavior.

**Comment by mborgerson** [comment]
Thanks for reporting! I've pushed a patch that retains trivial machine parsing, shows offset relative to named method, and fixes logging for looped methods.

**Comment by abaire** [comment]
Thanks!

Looks better to me. I think it's still potentially confusing since you need to know what the offsets from the base actually translate to and where the boundaries are between command groups, but it at least gives a quick indication that you're probably dealing with lighting if you see `nv2a: pgraph method (0): 0x97 -> 0x1118 NV097_SET_LIGHT_AMBIENT_COLOR+0x118 (0x0)`

Having the raw value there will already enable updating that in post-processing though, so all good.

**Comment by mborgerson** [comment]
I agree there is room for improvement for the case of multiple differently named methods handled by a single handler. This is good enough for now, so I'll leave it for future work.

**Comment by abaire** [comment]
> I agree there is room for improvement for the case of multiple differently named methods handled by a single handler. This is good enough for now, so I'll leave it for future work.

Definitely, this is a big improvement over the raw numbers; hopefully it'll help testers trim logs down to the interesting bits.
