### ISSUE TITLE
Commas in file names are unsupported by the Qemu command line interface potentially breaking xemu startup.

### ISSUE THREAD

**Issue by Aerocatia** [xemu-project/xemu#65]
Qemu does not support using commas `,` in file names as it uses this character to separate sub-arguments in command line arguments.

xemu generates command line arguments for Qemu on start up as a way to set up the emulation, and if you previously loaded a disc image with a comma in the file name using the GUI setting then the generated argument on the next start up will contain file name with a comma. this gets interpreted as an extra sub-argument and causes the emulator to fail to start.

EDIT: commas can be escaped by doubling them.

**Comment by Ernegien** [comment]
The changes required to escape file paths should be rather trivial and are built starting here: https://github.com/mborgerson/xemu/blob/5aa0cec31b5560c0434de8e368ff07d1bb53228b/softmmu/vl.c#L2923

It appears commas can be [escaped by doubling them](https://github.com/usnistgov/corr-panda/blob/master/qemu-options.hx#L540), although you'd want to test to ensure this is still true.

**Comment by Aerocatia** [comment]
I did look in there, however I did not know Qemu had the double comma thing.
