### ISSUE TITLE
Please add support for Xbox hardware revision 1.x (whatever revision that supports 5838 BIOS)

### ISSUE THREAD

**Issue by Danik2343** [xemu-project/xemu#656]
### Feature Request

Please add support for Xbox hardware revision 1.x (whatever revision that supports 5838 BIOS).

### Alternatives

BIOS 5838 doesen't work with mcpx 1.1

**Comment by Ernegien** [comment]
You need to use a matching v1.6 EEPROM; it should work. You'll be unable to load unsigned code however.

**Comment by GXTX** [comment]
Requires changing encoder as well.

**Comment by binarymaster** [comment]
Perhaps this issue needs to be renamed to "Please add support for Xbox hardware revision 1.x" (whatever revision that supports 5838 BIOS).

**Comment by GXTX** [comment]
@binarymaster there's no problem other than user error with this ticket.

**Comment by binarymaster** [comment]
I see.
