### ISSUE TITLE
Halo:CE specular breaking during UI events

### ISSUE THREAD

**Issue by Jakey757** [xemu-project/xemu#66]
Model's cubemap masking seem to break when help events and other UI pop ups occur in the campaign
![xemu_TbsGB2Mmpw](https://user-images.githubusercontent.com/49990481/98173474-2bf61100-1ec1-11eb-851c-b290f117dfb2.png)
^ crewman becomes extremely shiny

Title: 4d530004

**Comment by mborgerson** [comment]
This appears to be fixed, but do not recall when.
![xemu-2023-01-11-18-46-31](https://user-images.githubusercontent.com/8210/211956343-a3e4c3b4-3f5d-47be-835c-728e364c9d5c.png)
