### ISSUE TITLE
Internal USB hub commit causes major performance drops for NXDK apps using SDL event polling

### ISSUE THREAD

**Issue by 7oxicshadow** [xemu-project/xemu#663]
### Bug Description

I have a project that uses NXDK and SDL to parse an xiso and create a list of any xbe files it finds.

https://github.com/7oxicshadow/xbox_xbe_launcher

It appears that the following commit (input: Add controller internal usb hub [5faa241]) causes problems with SDL's event polling system within nxdk.

**The previous commit (input: Add USB Daughterboard ) gives the following frame rates:**
![image](https://user-images.githubusercontent.com/10350138/150198462-8a1b4b8e-753b-4893-81d2-d9f10fc4c6b6.png)

**The problem commit (input: Add controller internal usb hub) gives the following frame rates:**
![image](https://user-images.githubusercontent.com/10350138/150198016-2a761f42-b55b-4623-99a6-ff92a19b871d.png)

I have narrowed it down to the following SDL call within my project:
    SDL_GameControllerUpdate();

This call should be forcing the SDL event queue to be parsed. Is it possible that the USB hub is firing excessive events that SDL doesn't like or is causing some sort of timeout?

### Expected Behavior

Consistent 60 FPS operation

### xemu Version

Problem commit : 
https://github.com/mborgerson/xemu/commit/5faa2419e7cfca1e03a8e3113de2df6453caf2e5

Any build beyond that point has the issue

### System Information

Fedora 34 (KDE)
i7 6700k
32GB ram
GTX 1070

**Comment by 7oxicshadow** [comment]
As the commit was relatively small, I have just built the master branch with the offending commit removed and can confirm that the FPS is back to 60FPS again

**Comment by Ryzee119** [comment]
This could be a nxdk bottle neck in the hub code somewhere too.
Ill have to dig into this a bit.

Last time I checked, xemu did create alot of unneeded usb packets with the controller but as the perf is hub related this is a bit weird. Hubs could be doing this too.

**Comment by Ryzee119** [comment]
Can you retest on the nxdk sdl_gamecontroller sample?

Admittely our PC specs are quite different and Im using Windows if that makes a difference, using 3 controllers connected im getting a solid 59~60 fps

![image](https://user-images.githubusercontent.com/21236406/150219651-f7a94a35-4df3-46ed-9519-3210d264069e.png)

**Comment by 7oxicshadow** [comment]
did u have any troubles building with the latest nxdk?

I am getting this on linux:

![image](https://user-images.githubusercontent.com/10350138/150221886-32ebd9eb-278c-4907-96ae-43052cb060fb.png)

**Comment by 7oxicshadow** [comment]
nvm got it building. will build xemu clean now and test

**Comment by 7oxicshadow** [comment]
sdl_gamecontroller sample confirmed working. Must be something unique to my project then. Will have to compare the two.

**Comment by Ryzee119** [comment]
There's a few unoptimised things in the input code (in nxdk and XEMU) which I am looking at now, although I dont expect this is adding alot of overhead but you never know. Give me a hour or two.

If youre happy to share your xiso with me I can see if what I am doing is having an improvement

**Comment by 7oxicshadow** [comment]
I think I have spotted an anomaly at my end that might explain a thing or two.

The example explicitly determines which pad to read based on an event:
```

      else if (e.type == SDL_CONTROLLERBUTTONDOWN) {
        if (e.cbutton.button == SDL_CONTROLLER_BUTTON_START) {
          pad = (SDL_GameControllerFromInstanceID(e.cdevice.which));
        }
      }
```

where as my project gets the pad using in the following way:

```
    pad = SDL_GameControllerOpen(0);
    if (pad == NULL) {
        debugPrint("Failed to open gamecontroller 0\n");
        cleanup_and_exit();
    }
```

**Comment by 7oxicshadow** [comment]
well i tried moving stuff around but it didnt seem to make a difference :(

[nxdk.zip](https://github.com/mborgerson/xemu/files/7901171/nxdk.zip)

I have attached my project that doesn't seem to work the same as the nxdk sample and the source can be found here:
https://github.com/7oxicshadow/xbox_xbe_launcher/blob/main/main.c

I will have another look at it tomorrow as it is late here.

Many thanks for looking into the issue.

**Comment by Ryzee119** [comment]
You're using quite an old version of nxdk thats almost a year old. I would recommend you update your submodule. This is before nxdk got all new usb code.

Building against latest, doesnt not seem to have any issues for me

**Comment by 7oxicshadow** [comment]
Oh wow. I somewhat foolishly assumed that externals in git tracked master. Now I think about it, it makes sense that it shouldn't.

I have updated the externals and built against latest and can confirm that this is no longer an issue.

Again, many thanks for taking a look at this. The older versions of NXDK must have been very inefficient around USB handling.
