### ISSUE TITLE
Need for Speed Underground: FMVs not rendered to screen

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#673]
### Title

https://xemu.app/titles/45410047/#Need-for-Speed-Underground

### Bug Description

The intro FMV for Need For Speed: Underground is never rendered to the front buffer. Looking at the textures I can see that the movie is being loaded, just never blitted.

### Expected Behavior

The FMV should be visible during the intro.

### xemu Version

Version: 0.6.2-53-g6b821d2062
Branch:  master
Commit:  6b821d2062f28d8b04c7e02447ed066b50936eea
Date:    Mon Jan 24 09:41:21 PM UTC 2022

### System Information

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

**Comment by abaire** [comment]
Looks like they use the fog component in the final combiner, presumably to do fade-in and out. The fog coord seems to be set to 1, however, so it ends up always using a passed in uniform that happens to be black rather than the calculated fragment color from the texture.

```
// Stage 0
r0.rgb = clamp(vec3(((max(t0.rgb, 0.0) * max(v0.rgb, 0.0)) * 2.0)), -1.0, 1.0);
r0.a = clamp((((max(t0.a, 0.0) * max(v0.a, 0.0)) * 2.0)), -1.0, 1.0);
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(r0.rgb, 0.0)), vec3(max(c0_8.rgb, 0.0)), vec3(max(pFog.aaa, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

**Comment by abaire** [comment]
`FOG_PARAMS` is also set to an unusual value (compared to other titles I've looked at). It's `{1, 1, 0}` so the fog coord is entirely dependent on the vertex shader's calculation. Following the shader code, I only ever see it modifying `oFog.w`, so there's probably some interesting HW-specific behavior that we're missing in xemu.

**Comment by abaire** [comment]
I also see that the `FOG_GEN_MODE` is set to `NV097_SET_FOG_GEN_MODE_V_SPEC_ALPHA` which may be worth looking into.

**Comment by abaire** [comment]
Confirmed with a test that the xemu handling of NV097_SET_FOG_GEN_MODE_V_SPEC_ALPHA results in different output than HW.

**Comment by abaire** [comment]
Looking further, the gen mode is a red herring, gen mode is not used outside of the fixed function shader.

I've found a major difference in behavior when using fog.alpha in the final combiner. In my initial testing the hardware treats this as no-fog whereas xemu treats it as full fog.

**Comment by mborgerson** [comment]
> Looking further, the gen mode is a red herring, gen mode is not used outside of the fixed function shader.
> 
> I've found a major difference in behavior when using fog.alpha in the final combiner. In my initial testing the hardware treats this as no-fog whereas xemu treats it as full fog.

Fog alpha still needs investigation. This comment got accidentally removed recently https://github.com/mborgerson/xemu/blob/5778854dbd8ad3f8d44d0542f4760228db07a855/hw/xbox/nv2a/shaders.c#L839 but it would be great if someone can look into it

**Comment by abaire** [comment]
> > Looking further, the gen mode is a red herring, gen mode is not used outside of the fixed function shader.
> > I've found a major difference in behavior when using fog.alpha in the final combiner. In my initial testing the hardware treats this as no-fog whereas xemu treats it as full fog.
> 
> Fog alpha still needs investigation. This comment got accidentally removed recently
> 
> https://github.com/mborgerson/xemu/blob/5778854dbd8ad3f8d44d0542f4760228db07a855/hw/xbox/nv2a/shaders.c#L839
> 
> but it would be great if someone can look into it

I removed that one intentionally; fog alpha (as in the fog color's alpha channel) does not appear to have any effect on the final calculation.

I'm doing some substantially more thorough testing of the fog coordinate output from the vertex shader right now and am seeing some confusing results. It looks like setting any component of the fog output should be treated the same as setting fog.x, but xemu only uses fog.x as the fogDistance when a vertex program is in use. Hoping to determine this conclusively shortly, just need to rule out weirdness related to the awkward interaction with Cg shaders via the nxdk (specifically the binding of transform constants and how they like to change when Cg optimizes things, making it very easy to miss things and invalidate results).

**Comment by mborgerson** [comment]
> I removed that one intentionally; fog alpha (as in the fog color's alpha channel) does not appear to have any effect on the final calculation.

I'd like to see more tests done to know for sure

> I'm doing some substantially more thorough testing of the fog coordinate output from the vertex shader right now ... Hoping to determine this conclusively shortly

Awesome

> just need to rule out weirdness related to the awkward interaction with Cg shaders via the nxdk (specifically the binding of transform constants and how they like to change when Cg optimizes things, making it very easy to miss things and invalidate results).

It's a pain

**Comment by abaire** [comment]
Very interesting behavior on this bug, my findings are that the HW seems to treat the leftmost write as the fog coordinate.

E.g.:

```
oFog.y = 1.0
```
will set the fog coordinate to 1.0 (as will `.x`, `.z`, or `.w`)

Setting
```
oFog.xw = [0.25, 1.0]
```
will set the fog coordinate to 0.25.

```
oFog.yw = [0.75, 0.0]
```
will result in 0.75 and so-on for any combination.

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/3c23adb4fcb6a059f42a34b76d0e931d1fb9cd30/src/tests/fog_tests.cpp#L329)
[Results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Fog_coord_vec4)

I think fixing this may require checking in the xemu shader to see if the vertex program mutates `oFog` at all, and will then have to take whatever modification is closest to the x component.
