### ISSUE TITLE
Additional Info

### ISSUE THREAD

**Issue by inukaze** [xemu-project/xemu#691]
### Feature Request

Hi there, this is not feature request for XEmu. 

The thing was i try to join to discord but that need a phone number in this right moment i don't have one, and becuase of that i can't talk on discord in your server.

Well the thing is very simple, i had write your compat list on a google sheet document -> https://docs.google.com/spreadsheets/d/17Uvos_8zQlE8X__WkJ_faH8LDfnnEnLHy1DDjmSvlBM/edit?usp=sharing

But the unique thing i don't know is, which are really exclusive titles for original Xbox ?
That is the unique thing i need to know.

Thank you for readme

### Alternatives

I don't have.

### Additional Context

Im from venezuela, and a phone number here can be expensive, i don't have 120 bucks for get a new phone line number yet. and that make me imposible join to discord because need phone number verification step ¬¬

**Comment by dracc** [comment]
Interesting discussion, but not really an issue of xemu.
A full list of exclusive titles for the Xbox can be found in mere seconds by using google.
Example: https://en.wikipedia.org/wiki/Category:Xbox-only_games

I doubt discord wants a landline number at your location, it's most probably cellphone based verification over there too.

**Comment by inukaze** [comment]
Thank you very much. 

But i really don't trust on Wikipedia articles because are ease to manipulate and make the people fell on Sophisma (is when a lie is take it like true) [ If you translate with google translator the spanish word «Sofisma» the result is «Sophistry» and that is another thing complete diferent to Sophisma. ] , because of things like "Cognitive Ease" (neither trusth on google because make use and abuse of this), the mayority of users on internet just make a seach on google and trust automatically in the three first result even with the information are not right . 

Is more trust the users of the console, and in this case the users of xemu.

**Comment by dracc** [comment]
Being critical of your sources is always a good idea, but in this case it's a simple thing to fact check (use mobygames.com or similar as a secondary source) and not really critical information - Wikipedia is most certainly good enough.

**Comment by inukaze** [comment]
Thank you very much. i had use the Wikipedia info in this case, after i use another sites to re-check from another sources the exclusive list on my list i had add a few titles exclusives not appears has been tested on xemu yet. i put gray background to the cell and purple color to text XD.

**Comment by dracc** [comment]
Why did you list them as unknown? I did some random picking of titles you listed as unknown, and all were tested and had a known state in the official database.
Also, I'm not sure why you bother setting up a secondary compatibility list which is out of date.

**Comment by inukaze** [comment]
The games i put on purple, when i wrote the list, i don't see a entry on compatibility list, and well, because i write one by one, i suppose i skip some titles on the process XD.

Let me check, well if you notice another mistake on my list, let me know to fix it :D
