### ISSUE TITLE
nv2a 0x97 -> 0x037c (glShadeModel?) unhandled

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#692]
### Title

https://xemu.app/titles/4d53006e
https://xemu.app/titles/4d5300d1
https://xemu.app/titles/53430007

### Bug Description

According to the debug output, 0x97 -> 0x037c is unhandled.
In the [NV20 nouveau sources](https://gitlab.freedesktop.org/mesa/mesa/-/blob/184a690fca700aa9ef2ae2e58b0f4bd86562aa6d/src/mesa/drivers/dri/nouveau/nv20_3d.xml.h#L323), this instruction is `SET_SHADE_MODEL`, and the values it can take matches what is received in the function calls.

I encounter this call when trying to launch Forza Motorsport, I'm sure it's used in many other titles too.

### Expected Behavior

The NV2A instruction 0x037C should be handled.

### xemu Version

0.6.2-55-gcaf84884c4

### System Information

N/A

**Comment by Triticum0** [comment]
Also, affect rolling
https://xemu.app/titles/53430007/#Rolling

**Comment by abaire** [comment]
Added a [test case](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/lighting_normal_tests.cpp) for this. I think `glShadeModel` is deprecated so this will need to be done via [glsl interpolation qualifiers](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Interpolation_qualifiers).
