### ISSUE TITLE
Jade Empire Assertion Failed nv2a/pgraph.c

### ISSUE THREAD

**Issue by guruemulation** [xemu-project/xemu#694]
### Title

https://xemu.app/titles/4d53006d/#Jade-Empire

### Bug Description

Assertion failed at the character selection screen.

Steps to produce this issue:
1. Launch game
2. Select new game

![Jade Empire assert](https://user-images.githubusercontent.com/30950311/152059417-ad194b3c-0ad3-4cdf-93ed-183e7263ece4.png)

### Expected Behavior

This wasn't an issue on earlier versions of Xemu.
Most textures were rendered black but proceeding past the character screen was no issue.
![Jade Empire assert 1](https://user-images.githubusercontent.com/30950311/152060162-6a3c597c-2a2f-4bfe-a9eb-3b0411688aa3.png)

### xemu Version

Version: 0.6.2-58-ga13f3f48a2

Working in Version: 0.6.0

### System Information

OS: Windows 10
CPU: AMD Ryzen 5 3550H
GPU: Radeon Vega 8 Mobile 2.10 Ghz
CPU: Radeon Software Version 21.30.23.01

**Comment by Triticum0** [comment]
This is caused due the render scale implementation.

**Comment by Triticum0** [comment]
Fixed. please close
