### ISSUE TITLE
nv2a 0x97 -> 0x1d7c (glEnable(GL_MULTISAMPLE)?) unhandled

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#703]
### Title
https://xemu.app/titles/53430007
https://xemu.app/titles/4d53006e

### Bug Description

According to the debug output, 0x97 -> 0x1d7c is unhandled.
In the [NV20 nouveau sources](https://gitlab.freedesktop.org/mesa/mesa/-/blob/184a690fca700aa9ef2ae2e58b0f4bd86562aa6d/src/mesa/drivers/dri/nouveau/nv20_3d.xml.h#L2018), this instruction is `3D_MULTISAMPLE_CONTROL`.

The parameter of the call has so far been observed as one of the following:
`0x0`, `0x1`, `0xffff0000`, `0xffff0001`

### Expected Behavior

The NV2A instruction 0x1D7C should be handled.

### xemu Version

0.6.2-55-gcaf84884c4

### System Information

N/A

**Comment by Triticum0** [comment]
Also, affect rolling, 0xffff0001
https://xemu.app/titles/53430007/#Rolling

**Comment by jackchentwkh** [comment]
NV097_SET_ANTI_ALIASING_CONTROL                    0x00001D7C

**Comment by Triticum0** [comment]
Affect NHL Rivals 2004 from being playable https://xemu.app/titles/4d53004e/#NHL-Rivals-2004

**Comment by abaire** [comment]
https://github.com/xemu-project/xemu/pull/1187 added support for this command. There is likely still some work to do but it may be enough to fix the games in this issue.
