### ISSUE TITLE
Grabbed by the Ghoulies: Missing geometry

### ISSUE THREAD

**Issue by Metalsasi** [xemu-project/xemu#721]
### Title

https://xemu.app/titles/4d530053/#Grabbed-by-the-Ghoulies

### Bug Description

There is missing geometry on certain models in the game.

Steps to reproduce:
1. Launch game
2. Defeat the imps in the first room
3. Meet the butler

Butler is missing his head. Only eyes are visible.
![missinghead](https://user-images.githubusercontent.com/2479696/152660563-360f1734-fd1b-4e45-b6ca-519b98629613.JPG)

### Expected Behavior

Butler's head is visible.

### xemu Version

v0.6.2-64-g758e36d398

### System Information

OS: Windows 10 Home
GPU: NVIDIA GeForce GTX 1660 SUPER
Processor: Intel(R) Core(TM) i5-10400F CPU
Driver version: 511.23

**Comment by Metalsasi** [comment]
It's seems like the issue is caused by a broken vertex shader, and swapping the MAC and ILU operation in the vertex shader generator solves the issue. 

Two MOV operations were the culprit in this situation:
The wrong behaviour is that R2 is populated and R1 gets the same value:
MOV(R2,xyz, c[A0+96]);
MOV(R1,xyz, R2)
  
The right behaviour is that R1 backs up the value of  R2 and than R2 can load something else.
MOV(R1,xyz, R2)
MOV(R2,xyz, c[A0+96]);

**Comment by PatrickvL** [comment]
Sounds like this will be fixed with #720

**Comment by abaire** [comment]
I think this is not the same as #720 but is a similar issue where the generated glsl code introduces strict ordering that differs from the hardware.

@Metalsasi do you know if there are general guarantees about the order of MAC/ILU ops? Should we just detect mutation of inputs in paired MAC/ILU instructions and leverage temp vars in the same way as the pixel shader change?

**Comment by Metalsasi** [comment]
@abaire, I don't know of any kind of guarantee yet. From curiosity I tried to swap all ILU/MAC operations, just to see if the few games I have will work or not, but I didn't see any change. It is not to say that these operations should be swapped. Because there might be titles that does not work well this way. Maybe it could be possible to create tests for this as well, or create a build that testers could use to check other titles to see if they are working properly with swapped operations?

**Comment by abaire** [comment]
> @abaire, I don't know of any kind of guarantee yet. From curiosity I tried to swap all ILU/MAC operations, just to see if the few games I have will work or not, but I didn't see any change. It is not to say that these operations should be swapped. Because there might be titles that does not work well this way. Maybe it could be possible to create tests for this as well, or create a build that testers could use to check other titles to see if they are working properly with swapped operations?

I think ideally we can craft some tests, but it may require manually creating the bytecode; I think the vp20compiler does some degree of optimization that may make it challenging to generate exactly what you want from higher level shader code.

I don't think testing via titles is viable, some failure modes may be less obvious than the GbtG bug you're addressing and it's also possible that they're only triggered very rarely and for a short period of time.

Maybe @mborgerson knows for sure, but I'd guess that just using a temporary variable anytime a register is used as both an input and an output in a MAC+ILU pairing is likely to be safe since I think they're independent and execute in parallel in HW.

**Comment by abaire** [comment]
This problem also causes #789

**Comment by abaire** [comment]
https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/vertex_shader_independence_tests.cpp has a test that exercises this bug in xemu
