### ISSUE TITLE
ts fp asserts

### ISSUE THREAD

**Issue by re4thewin** [xemu-project/xemu#745]
### Title

https://xemu.app/titles/45410066/#TimeSplitters-Future-Perfect

### Bug Description

![image](https://user-images.githubusercontent.com/32232919/155267960-6c76c799-224c-4dc0-a6de-de348b0401bf.png)
happens at the beginning and end of many cutscenes can be ignored
![image](https://user-images.githubusercontent.com/32232919/155268328-048f5d35-bd70-491d-b180-9518ff141f37.png)
infinite assert cannot proceed in 3rd mission

### Expected Behavior

no asserts

### xemu Version

0.6.2-77

### System Information

OS:Windows 10
CPU:i9 9900kf
GPU:asus rog strix oc 1070

### Additional Context

very playable other than progress hindering asserts

**Comment by LeRutY** [comment]
The exact same error message appears in multiplayer when playing the "Virus" game mode

**Comment by Triticum0** [comment]
@re4thewin It should be fixed if you retest.
