### ISSUE TITLE
Crash during start up Read-only image 

### ISSUE THREAD

**Issue by BearzRobotics** [xemu-project/xemu#748]
### Bug Description

I installed xemu via flatpak, because my distro doesn't have it in it's repo. When filling out the settings and restarting the app crashes. Its complaining about it being a read only filesystem. However this is not the case. I don't believe its an issue with sandboxing because it can find the other two bin files. In fact by deleting the path to the hard drive image it launches just fine. when launching from the terminal it displays this.

xemu_version: 
xemu_branch: edbe932d8c4780f92665372e15f672874be5e93b
xemu_commit: edbe932d8c4780f92665372e15f672874be5e93b
xemu_date: Fri Jan  7 01:21:35 AM UTC 2022
OS_Version: Freedesktop.org 21.08.10 (Flatpak runtime)
GL_VENDOR: AMD
GL_RENDERER: Radeon RX 580 Series (POLARIS10, DRM 3.42.0, 5.14.21-210.current, LLVM 12.0.1)
GL_VERSION: 4.6 (Core Profile) Mesa 21.3.5 (git-112de3a07a)
GL_SHADING_LANGUAGE_VERSION: 4.60
xemu_settings_get_path: config path: /home/dakota/.var/app/app.xemu.xemu/data/xemu/xemu/xemu.ini
config_parse_callback: [system] flash_path = /mnt/doc/xbox/xemu/MyStuff/Complex_4627.bin
config_parse_callback: [system] bootrom_path = /mnt/doc/xbox/xemu/MyStuff/mcpx_1.0.bin
config_parse_callback: [system] hdd_path = /mnt/doc/xbox/xemu/MyStuff/xbox_hdd2.qcow2
config_parse_callback: [system] eeprom_path = /home/dakota/.var/app/app.xemu.xemu/data/xemu/xemu/eeprom.bin
config_parse_callback: [system] dvd_path = 
config_parse_callback: [system] memory = 128
config_parse_callback: [system] shortanim = false
config_parse_callback: [system] hard_fpu = true
config_parse_callback: [audio] use_dsp = false
config_parse_callback: [display] scale = scale
config_parse_callback: [display] ui_scale = 1
config_parse_callback: [display] render_scale = 1
config_parse_callback: [input] controller_1_guid = 
config_parse_callback: [input] controller_2_guid = 
config_parse_callback: [input] controller_3_guid = 
config_parse_callback: [input] controller_4_guid = 
config_parse_callback: [network] enabled = false
config_parse_callback: [network] backend = user
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [network] pcap_iface = 
config_parse_callback: [misc] user_token = 
config_parse_callback: [misc] check_for_update = 
Created QEMU launch parameters: xemu -machine xbox,bootrom=/mnt/doc/xbox/xemu/MyStuff/mcpx_1.0.bin,kernel-irqchip=off -device smbus-storage,file=/home/dakota/.var/app/app.xemu.xemu/data/xemu/xemu/eeprom.bin -bios /mnt/doc/xbox/xemu/MyStuff/Complex_4627.bin -m 128 -drive index=0,media=disk,file=/mnt/doc/xbox/xemu/MyStuff/xbox_hdd2.qcow2,locked=on -drive index=1,media=cdrom,file= -display xemu 
WARNING: Image format was not specified for '/mnt/doc/xbox/xemu/MyStuff/xbox_hdd2.qcow2' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
xemu: Could not open '/mnt/doc/xbox/xemu/MyStuff/xbox_hdd2.qcow2': Read-only file system

### Expected Behavior

Xemu should start. 

### xemu Version

Version: 
Branch:  edbe932d8c4780f92665372e15f672874be5e93b
Commit:  edbe932d8c4780f92665372e15f672874be5e93b
Date:    Fri Jan  7 01:21:35 AM UTC 2022

### System Information

OS: Solus (Linux)
AMD® Radeon rx 580 series
Open Source AMD drivers

**Comment by antangelo** [comment]
Do you believe that it's not sandboxing or do you know it's not sandboxing? I've seen a similar problem solved by expanding the sandbox restrictions before.

Also, flatpak is managed elsewhere: https://github.com/flathub/app.xemu.xemu so you may want to file the issue there.

**Comment by mborgerson** [comment]
The instructions here https://xemu.app/docs/download/#flatpak state

> Note: Only the ~/.var/app/app.xemu.xemu/data/xemu/xemu directory can be written by xemu. The Hard Disk image has to be placed there, for example at ~/.var/app/app.xemu.xemu/data/xemu/xemu/xbox_hdd.qcow2.

But you have placed your hard disk image at '/mnt/doc/xbox/xemu/MyStuff/xbox_hdd2.qcow2'. Try moving the image into the suggested place
