### ISSUE TITLE
Rainbow Six 3 / Rainbow Six Black Arrow / Ghost Recon Advanced Warfighter: Character models and lightsources are rendered through walls and objects

### ISSUE THREAD

**Issue by LeRutY** [xemu-project/xemu#749]
### Title

https://xemu.app/titles/55530013/#Tom-Clancy-s-Rainbow-Six-3 US-019
https://xemu.app/titles/55530037/#Tom-Clancy-s-Rainbow-Six-3-Black-Arrow US-055
https://xemu.app/titles/55530054/#Tom-Clancy-s-Ghost-Recon-Advanced-Warfighter US-084 

### Bug Description

See title. Note that only some specific lightsources are affected. Example of the character models https://youtu.be/75bZssKsr5U?t=1102

### Expected Behavior

People and the lightsources should only be seen when nothing is between them and the player

### xemu Version

0.6.2-78-g2b27021eef

### System Information

OS: Windows 10 64 Bit
CPU: Intel i7 7700K @ 4.20 Ghz
GPU: Nvidia Geforce GTX 1080
GPU Driver: 496.13

**Comment by KhanArtist** [comment]
player does not hold gun correctly, hand is through the gun, and same issue: character models and light sources are rendered through walls and objects.

**Comment by mborgerson** [comment]
Added to #1016
