### ISSUE TITLE
Forza Motorsport: Black areas when EEPROM set to non-English

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#75]
Setting the EEPROM language to German gives this weird black-out in the menus of Forza Motorsport.
Resetting it back to English removes the glitch.
Glitch does not occur on real hardware.
![screenshot](https://i.imgur.com/aCcZfOb.png)

Title: 4d53006e

**Comment by dracc** [comment]
[related?](https://github.com/MakeMHz/xbox-hd-plus/issues/22)

**Comment by allkern** [comment]
This was possibly fixed. Tried a couple of languages, both of them don't cause the bug anymore.

![image](https://user-images.githubusercontent.com/15825466/134285068-6bf9e581-53b8-4965-9d68-92d1d5588344.png)

Title: 4d53006e

xemu 0.6.1-8-gd7e926fc63
