### ISSUE TITLE
Soul Calibur 2: 2nd player not rendering

### ISSUE THREAD

**Issue by theboy181** [xemu-project/xemu#76]
Second player is not rendering on the player select screen, it does seem that its placed further to the right. When you start a 2P match you will see your characters weapon coming from the far right.
![image](https://user-images.githubusercontent.com/9299743/99210755-81f96d00-277b-11eb-90bf-eee71c85a84c.png)

Title: 4e4d0003

**Comment by abaire** [comment]
I don't see this with a head build as of now, perhaps it was fixed somewhere along the way?

Version: 0.6.2-39-g01c2f0fa74
Branch:  master
Commit:  01c2f0fa74d1f67ec135eaeed81f029058ef25a0

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

![Screenshot_20220110_213629](https://user-images.githubusercontent.com/448413/148887165-cbc4bc45-f05e-40ef-add3-d337e546d50b.png)

**Comment by Triticum0** [comment]
This was properly fixed with this #390 you can ask Matt to close the issue
