### ISSUE TITLE
Terminator Redemption Graphic Error

### ISSUE THREAD

**Issue by orderorder** [xemu-project/xemu#764]
### Title

https://xemu.app/titles/4947003e/#Terminator-3-The-Redemption

### Bug Description

![Captura de pantalla de 2022-03-11 11-47-31](https://user-images.githubusercontent.com/7293829/157853414-f2144d77-f954-4ba7-870d-a5053f2fac30.png)

### Expected Behavior

Graphics and textures are expected to display correctly

### xemu Version

0.6.2-79-ga32f271d55

Branch master

### System Information

Manjaro Linux Release 21.2.4

AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G

Mesa 21.3.7-1

Same problem with windows other cpus or graphic cards

**Comment by Triticum0** [comment]
The issue Been fixed

**Comment by Triticum0** [comment]
@orderorder Please close
