### ISSUE TITLE
Ninja Gaiden Black shadow problem

### ISSUE THREAD

**Issue by ko81e24wy** [xemu-project/xemu#781]
### Title

https://xemu.app/titles/5443000d/#Ninja-Gaiden-Black

### Bug Description

Ryu's shadow missing or incorrect
![1111](https://user-images.githubusercontent.com/38323456/158743788-f1466add-7aac-4f9a-a990-27dcbffb325c.jpg)
enemy shadows are blobs, xemu just renders it fine,Ryu's are dynamic, so it's probably stencil related maybe
![shadows](https://user-images.githubusercontent.com/38323456/159090657-ca7f6251-8bfb-46e9-91b8-31ec348b214a.jpg)

### Expected Behavior

expect to display correctly

### xemu Version

Version: 0.6.2-82-ghttps://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837235
Branch: master
Commit: 2ff5f23
Date: Thu Mar 17 04:24:58 UTC 2022

### System Information

  "cpu": "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz",
  "gl_renderer": "NVIDIA GeForce GTX 1080/PCIe/SSE2",
  "gl_shading_language_version": "4.00 NVIDIA via Cg compiler",
  "gl_vendor": "NVIDIA Corporation",
  "gl_version": "4.0.0 NVIDIA 515.36",
  "os_platform": "Windows",
  "os_version": "Windows 11"

**Comment by mborgerson** [comment]
Please split out each of the problems into a different issue so each issue is about only a single problem

**Comment by ko81e24wy** [comment]
PR #840 fixed the shadow issue of Ryu
master
![xemu_2022_04_28_15_01_20_824](https://user-images.githubusercontent.com/38323456/165696134-5db5c9c2-c5ca-4249-b1ed-e4c81bc1086f.jpg)
PR
![xemu_2022_04_28_14_59_51_485](https://user-images.githubusercontent.com/38323456/165696162-d9d6bffb-cdbc-4508-a71c-262ebbce75b0.jpg)

**Comment by ko81e24wy** [comment]
https://www.youtube.com/watch?v=nA0YK8lEx4U
