### ISSUE TITLE
Splinter cell Double Agent: surface lights being rendered in distance only

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#787]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

https://user-images.githubusercontent.com/30447649/159268426-56095736-f2ef-4a5a-a26c-ec254534f490.mp4

![light xemu](https://user-images.githubusercontent.com/30447649/162148483-5840cdd4-315c-4cb2-a6ec-126705d38b9d.png)

Happens in all levels

### Expected Behavior

lights should remain rendered on surface while getting closer to them.

hardware:
![hardware](https://user-images.githubusercontent.com/30447649/160233256-b9152ebf-2826-42e0-9246-ec5319010d45.jpg)

### xemu Version
xemu_version: 0.6.2-88-g6e1969001e

### System Information

Manjaro Linux
i7-10700 4.80GHz
GTX 970 STRIX 4GB VRAM
Nvidia driver 510.54 - CUDA Version 11.6

### Additional Context

**Comment by abaire** [comment]
Just to make sure it's tracked: this should be re-tested once #807 is fixed. I would guess that the SC engine uses the same approach for all light applications and the lack of shadow map support that presumably causes 807 probably impacts (or causes) this issue as well.
