### ISSUE TITLE
Splinter cell double agent: Texture rendering popup

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#789]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

https://user-images.githubusercontent.com/30447649/159268614-e446b662-4300-442f-b982-7f8c496cdc47.mp4

Level: Iceland, beginning

### Expected Behavior

Textures shouldn't have popup effects that change their color/view

### xemu Version

xemu_version: 0.6.2-88-g6e1969001e

### System Information

Manjaro Linux
i7-10700 4.80GHz
GTX 970 STRIX 4GB VRAM
Nvidia driver 510.54 - CUDA Version 11.6

**Comment by abaire** [comment]
This looks like an interesting light mapping issue.

The render pass uses a relatively bright texture (`NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT1_A1R5G5B5`, 512x512) and a gradient texture (`NV097_SET_TEXTURE_FORMAT_COLOR_SZ_A8R8G8B8`, 64x1). The gradient texture is used to determine the blend factor between the color texture * the vertex diffuse and the color texture * a constant.

Relevant pixel shader:
```
vec4 v0 = pD0;
vec4 v1 = pD1;
vec4 ab;
vec4 cd;
vec4 mux_sum;
pT0.xy = texScale0 * pT0.xy;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
vec4 t1 = vec4(0.0); /* PS_TEXTUREMODES_NONE */
vec4 t2 = vec4(0.0); /* PS_TEXTUREMODES_NONE */
pT3.xy = texScale3 * pT3.xy;
vec4 t3 = textureProj(texSamp3, pT3.xyw);
vec4 r0;
r0.a = t0.a;
vec4 r1;
// Stage 0
ab.rgb = clamp(vec3(((t0.rgb * v0.rgb) * 4.0)), -1.0, 1.0);
r0.rgb = ab.rgb;
ab.a = clamp(((t0.a * v0.a)), -1.0, 1.0);
r0.a = ab.a;
// Stage 1
ab.rgb = clamp(vec3((c0_1.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))), -1.0, 1.0);
r1.rgb = ab.rgb;
ab.a = clamp(((t3.a * c0_1.a)), -1.0, 1.0);
r1.a = ab.a;
// Stage 2
mux_sum.rgb = clamp(vec3(((max(r1.aaa, 0.0) * r1.rgb) + (r0.rgb * (1.0 - clamp(r1.aaa, 0.0, 1.0))))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
// Final Combiner
fragColor.rgb = max(clamp(vec4(v1.rgb + r0.rgb, 0.0), 0.0, 1.0).rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(r0.a, 0.0);
}
```

Interestingly it's using a left shift 2 on the first stage, which would make things extremely bright unless the diffuse vertex color is low (the first few vertices are in the 0.01 range but there are nearby vertices in the 0.5 range that would immediately become fully saturated)

I suspect that the problem may lie in the vertex shader, and I see places where there is concurrent modification of temporary variables as observed by @Metalsasi when investigating Grabbed by the Ghoulies. That said, the order actually seems reasonable (the shared input value is only mutated in the second command)
```
  /* Slot 68: 0x00000000 0x004FA01E 0x3437B800 0x2E301818 */
  MUL(oD0,w, R3.xywz, c[125]);
  MUL(R3,xyz, R3.xywz, c[125]);
```
and while naively switching the two produces a darker texture, it still looks overlit.

**Comment by abaire** [comment]
Roughly the same area:
![Screenshot_2022-04-06T17:07:45](https://user-images.githubusercontent.com/448413/162094716-c62277bc-d2fc-41a0-8efb-c2ee9e513e77.png)

Alpha removed:
![Screenshot_2022-04-06T17:07:45](https://user-images.githubusercontent.com/448413/162094794-0d1fd1c9-2a59-44e8-be40-833479f4b777.jpg)

**Comment by abaire** [comment]
Looking farther up in the vertex shader there are several other unsafe mutations along the lines of @Metalsasi 's report. Fixing these with a temporary variable also fixes this bug.
