### ISSUE TITLE
Splinter cell double agent: Nightvision filter displaying artifacts

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#790]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

https://user-images.githubusercontent.com/30447649/159268681-f7a22121-4efa-40bc-b96c-8ef09037aec1.mp4

![image](https://user-images.githubusercontent.com/30447649/162150319-68dc3ced-823f-43db-be1f-a1a0504b2b35.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/30447649/162150492-d1a24520-726d-486d-ab0b-1429674f34bb.png)

![image](https://user-images.githubusercontent.com/30447649/162150995-13500427-e36d-4c5f-b4ad-38782e20b957.png)

nightvision should be clean and not show altered visuals

### xemu Version
xemu_version: 0.6.2-88-g6e1969001e

### System Information

Manjaro Linux
i7-10700 4.80GHz
GTX 970 STRIX 4GB VRAM
Nvidia driver 510.54 - CUDA Version 11.6

**Comment by abaire** [comment]
@revix-0 when you have a moment, please re-test with #831 and if it doesn't fix the issue, please provide comparison screenshots between xemu and hardware at roughly the same camera position to illustrate the difference.

All of the goggle modes are potentially untrustworthy without #831 and I don't know the game well enough to know what you mean by altered visuals in the video without a comparison screenshot.

**Comment by abaire** [comment]
831 does not fix this issue.

Looking at the rendering, it seems that the game builds the entire scene, then creates an overlay by re-sampling the back buffer. I'd need to do a hardware trace to be sure, but I suspect that this is oversaturating and causing at least some of the issue.

I think this is the relevant pixel shader:
```
pT0.xy = texScale0 * pT0.xy;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
pT1.xy = texScale1 * pT1.xy;
vec4 t1 = textureProj(texSamp1, pT1.xyw);
pT2.xy = texScale2 * pT2.xy;
vec4 t2 = textureProj(texSamp2, pT2.xyw);
pT3.xy = texScale3 * pT3.xy;
vec4 t3 = textureProj(texSamp3, pT3.xyw);
vec4 r0;
r0.a = t0.a;
// Stage 0
mux_sum.a = clamp((((t0.a * c0_0.a) + ((1.0 - clamp(vec4(0.0).a, 0.0, 1.0)) * -c0_0.b))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 1
mux_sum.a = clamp((((t1.a * c0_1.a) + ((1.0 - clamp(vec4(0.0).a, 0.0, 1.0)) * r0.a))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 2
mux_sum.a = clamp((((t2.a * c0_2.a) + ((1.0 - clamp(vec4(0.0).a, 0.0, 1.0)) * r0.a))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 3
mux_sum.a = clamp((((t3.a * c0_3.a) + ((1.0 - clamp(vec4(0.0).a, 0.0, 1.0)) * r0.a))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 4
ab.rgb = clamp(vec3((r0.aaa * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))), -1.0, 1.0);
r0.rgb = ab.rgb;
// Final Combiner
fragColor.rgb = max(clamp(vec4(v1.rgb + r0.rgb, 0.0), 0.0, 1.0).rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(r0.a, 0.0);
```
The texture inputs are just the backbuffer (it's the same exact texture used in each unit)

This mechanism would also mean that the shader is very sensitive to errors in the normal rendering, so if xemu renders things even slightly more bright than the hardware, that error will be multiplied by 4 when using the night vision effect. 

Even disabling all but the first pass leads to an image that is considerably brighter than the one I captured on HW (though it's far less oversaturated)

xemu with a modified pixel shader:
![cave_with_single_pass_light_enhancer](https://user-images.githubusercontent.com/448413/162234012-cc224d1f-1882-4993-b264-276f052ad807.jpg)

Hardware around the same area:
![Screenshot_2022-04-07T07:45:16](https://user-images.githubusercontent.com/448413/162234192-ea93fa9c-5fd8-40e9-a477-fc316cc22227.jpg)

**Comment by abaire** [comment]
Comparison of ~the same place with no night vision, the xbox version is darker with more subtle highlights on the texture

xemu:
![xemu_no_night_vision](https://user-images.githubusercontent.com/448413/162236434-a3d1b5b4-7401-4564-9cf9-f185bee79882.png)

HW:
![xbox_no_night_vision](https://user-images.githubusercontent.com/448413/162238006-85c29706-a6f0-4f56-8b9a-83de6ac51526.png)

**Comment by abaire** [comment]
Looking a bit further up in the draw chain, the inputs to the nightvision filter come from an earlier draw call that combines what looks like a normal map with the backbuffer. The output of this draw substantially attenuates the alpha of the backbuffer (so the backbuffer is both an input and output of the draw).

When the texture is used to create the night vision filter (which only utilizes the alpha channel), the attenuation appears to have been lost, causing the effect to be many times stronger than it should be. I assume this is another case of xemu optimizing away a download/upload from OpenGL that is actually required.


Pixel shader of the draw whose output appears to be ignored):
```
vec4 v0 = pD0;
vec4 v1 = pD1;
vec4 ab;
vec4 cd;
vec4 mux_sum;
pT0.xy = texScale0 * pT0.xy;
vec4 t0 = textureProj(texSamp0, pT0.xyw);
vec4 t1 = vec4(0.0); /* PS_TEXTUREMODES_NONE */
/* PS_TEXTUREMODES_DOTPRODUCT */
float dot2 = dot(pT2.xyz, dotmap_zero_to_one(t0.rgb));
vec4 t2 = vec4(0.0);
/* PS_TEXTUREMODES_DOT_ST */
float dot3 = dot(pT3.xyz, dotmap_zero_to_one(t0.rgb));
vec4 t3 = texture(texSamp3, texScale3 * vec2(dot2, dot3));
vec4 r0;
r0.a = t0.a;
vec4 r1;
// Stage 0
ab.rgb = clamp(vec3(dot(t3.rgb, c0_0.rgb)), -1.0, 1.0);
r0.rgb = ab.rgb;
ab.a = clamp(((t3.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))), -1.0, 1.0);
t3.a = ab.a;
// Stage 1
ab.rgb = clamp(vec3(dot(t3.rgb, c0_1.rgb)), -1.0, 1.0);
r1.rgb = ab.rgb;
mux_sum.a = clamp((((r0.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0))) + ((max(t3.b, 0.0) - 0.5) * (2.0 * max(vec4(0.0).a, 0.0) - 1.0)))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 2
mux_sum.rgb = clamp(vec3(((r0.a >= 0.5) ? vec3((r0.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))) : vec3((t3.aaa * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
mux_sum.a = clamp((((r0.a >= 0.5) ? ((r0.a * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))) : ((t3.a * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 3
mux_sum.a = clamp((((r0.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0))) + ((max(r1.b, 0.0) - 0.5) * (2.0 * max(vec4(0.0).a, 0.0) - 1.0)))), -1.0, 1.0);
r0.a = mux_sum.a;
// Stage 4
mux_sum.rgb = clamp(vec3(((r0.a >= 0.5) ? vec3((r0.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))) : vec3((r1.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)))))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
mux_sum.a = clamp((((r0.a >= 0.5) ? ((r0.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))) : ((r1.b * (1.0 - clamp(vec4(0.0).a, 0.0, 1.0)))))), -1.0, 1.0);
r0.a = mux_sum.a;
// Final Combiner
fragColor.rgb = max(clamp(vec4(v1.rgb + r0.rgb, 0.0), 0.0, 1.0).rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

**Comment by abaire** [comment]
[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_render_update_in_place_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_render_update_in_place)
