### ISSUE TITLE
Splinter cell double agent: lock pick and bomb panel not diisplaying correctly

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#792]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

![lockpick](https://user-images.githubusercontent.com/30447649/159268825-7241580b-af3e-48e7-81f2-46812de5fe5a.png)
![bomb](https://user-images.githubusercontent.com/30447649/159302943-6e7aad7a-34ae-45c4-b155-a6ee0c912947.png)

These objects appear to be shadowed, might be missing light reflection on these.

Where can be found: Iceland second part, you can lock pick some doors
Bomb panel: JBA HQ Part 2, 9th level, at the dock and roof.

### Expected Behavior
![correct](https://user-images.githubusercontent.com/30447649/159056551-59de2f0d-bbdf-49fb-93de-b8c47c56146b.png)
![correct2](https://user-images.githubusercontent.com/30447649/159056361-ce8d3457-4b97-4c76-ada1-109d8c89f8c0.png)

### xemu Version

xemu_version: 0.6.2-88-g6e1969001e

### System Information

Manjaro Linux
i7-10700 4.80GHz
GTX 970 STRIX 4GB VRAM
Nvidia driver 510.54 - CUDA Version 11.6

**Comment by Triticum0** [comment]
Silent Hill 2 suffers from the same issue on the Rotating Cube Puzzle

**Comment by Fabxx** [comment]
@Triticum0  this issue got addressed with wip shadow samplers, test with them and see if changes

**Comment by Fabxx** [comment]
Issue was resolved with shadow sampler PR.
