### ISSUE TITLE
Splinter cell double agent Issue #7: weird FPS uncap in a specific zone

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#793]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

Idk if that happens on hardware as well, this is kinshasa, elevator at the beginning of the level.

https://user-images.githubusercontent.com/30447649/159095178-166964b6-f9af-40c3-98a3-3268a6146bee.mp4

### Expected Behavior

FPS should stay at 30? Testing needed

### xemu Version

0.6.2-84-gcd5d3df626

**Comment by mborgerson** [comment]
Please figure out if there's actually a discrepancy vs hardware before filing a bug report

**Comment by Fabxx** [comment]
I apologize for this inconvenience, since i don't own the actual hardware i wanted to let  the devs in general know about this issue so others might investigate in this, but if i'll figure it out from other sources such as youtube video, i'll keep it posted here.
