### ISSUE TITLE
Fable - The Lost Chapters: Glowing surfaces

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#796]
### Title

https://xemu.app/titles/4d5300d1/#Fable-The-Lost-Chapters

### Bug Description

Some elements (walls, floors, carpets, ...) have a strong glow, unlike on hardware.
![Screenshot](https://i.imgur.com/i4HFSTW.png)

### Expected Behavior

Elements shouldn't glow like that.

Screengrab from YouTube, same doorway but slightly different angle:
![Not My Picture](https://i.imgur.com/iKG3q3Q.png)

### xemu Version

0.6.2-85-gf0abe3c4fc

### System Information

OS: Debian Linux Testing/Unstable 5.16.0-4-amd64
CPU: Ryzen 1700
GPU: AMD R9 290X
GPU DRIVER: AMDGPU/Mesa 22.0

**Comment by nickkeane** [comment]
Getting the same issue

**Comment by dracc** [comment]
![image](https://user-images.githubusercontent.com/1279635/165163911-9fc6789f-15aa-4605-aa1e-f260804829bf.png)
Fixed as of 0.6.3.

**Comment by mborgerson** [comment]
Nice
