### ISSUE TITLE
Project Snowblind: Crash when pressing start on the intro screen

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#798]
### Title

https://xemu.app/titles/45530019/#Project-Snowblind

### Bug Description

Pressing start on the intro screen results in a crash of the guest machine: 

`MMU fault: ExceptionIndex: EXCP0E ErrorCode: 2 ReturnAddr: 7FB984DDC26B EIP: 74D20`

![Screenshot_20220318_205701](https://user-images.githubusercontent.com/448413/159105795-83c25ae5-ffe3-4372-9427-b65af99c637f.png)

### Expected Behavior

The game should proceed past the intro screen and be playable.

### xemu Version

Version: 0.6.2-82-ghttps://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837235
Branch: master
Commit: 2ff5f23
Date: Sat Mar 19 03:47:53 AM UTC 2022

### System Information

"cpu": "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz",
"gl_renderer": "NVIDIA GeForce GTX 1070/PCIe/SSE2",
"gl_shading_language_version": "4.00 NVIDIA via Cg compiler",
"gl_vendor": "NVIDIA Corporation",
"gl_version": "4.0.0 NVIDIA 470.103.01",
"os_platform": "Linux",
"os_version": "Ubuntu 21.10",

**Comment by Triticum0** [comment]
It work back in November https://m.youtube.com/watch?v=nhQGvpuWWzY so it could be linux specific.

**Comment by Triticum0** [comment]
@abaire Doesn't crash on windows. [link](https://xemu.app/titles/45530019/#Project-Snowblind) Might want to retest.

**Comment by abaire** [comment]
Yup, verified that it works on 0.7.18. Possible that something was fixed, or that there was an issue with my HDD image (I re-tested with a clean image).
