### ISSUE TITLE
Serious Sam: Skybox is broken

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#801]
### Title

https://xemu.app/titles/54540004/#Serious-Sam

### Bug Description

The skybox in the game is only half rendered when entering the first level.
![Screenshot_20220318_213310](https://user-images.githubusercontent.com/448413/159106903-90188d6a-5140-46cd-960b-86d3980595af.png)

Rotating the view will cause it to display a different, glitchy skybox (or all black, or half correct half not, it's unpredictable).

### Expected Behavior

The skybox should not glitch out.

### xemu Version

Version: 0.6.2-82-ghttps://github.com/mborgerson/xemu/commit/https://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837235387a296fc9a5f11943b4dd29bd2837235
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837
Date: Sat Mar 19 03:47:53 AM UTC 2022

### System Information

"cpu": "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz",
"gl_renderer": "NVIDIA GeForce GTX 1070/PCIe/SSE2",
"gl_shading_la844c-cc0d466e4729.png)
nguage_version": "4.00 NVIDIA via Cg compiler",
"gl_vendor": "NVIDIA Corporation",
"gl_version": "4.0.0 NVIDIA 470.103.01",
"os_platform": "Linux",
"os_version": "Ubuntu 21.10",

**Comment by abaire** [comment]
SSam uses the fixed function pipeline for rendering.

In renderdoc I see geometry being rendered clearly out of place up in the sky, and this appears to be what blanks out the skybox. For the first draw:



```
Position:
|x|y|z|
|--|--|--|
|-128|	-4|	-128|
|128|	-4|	-128|
|128|	0|	-128|
|-128|	0|	-128|
|-128|	-4|	-128|
|128|	0|	-128|

compositeMat:
c[0] 319.9999695, 0.00, -320.00, 0.00        float4
c[1] 0.00, -319.999939, -240.00, 0.00        float4
c[2] 0.00, 0.00, -1.6777220E+07, -419431.53125 float4
c[3] 0.00, 0.00, -1.00, 0.00                 float4


invViewport {0.003125, 0.00, 0.00, -0.9983398}
{0.00, -0.0041667, 0.00, 0.9977865}
{0.00, 0.00, 5.9604633E-07, -8.9999971}
{0.00, 0.00, 0.00, 1.00} float4x4 (column_major)
```


Interestingly, the geometry that blacks out the sky has invalid texture coords: `-INF, INF,NaN,INF`; the incoming vertex does not specify w, which triggers a divide by zero in the fixed function pipeline (there is explicit handling for this in the programmable path).


UPDATE: It looks like the blacked out texture is supposed to be a rain effect, when I "fix" the w coord by handling the 0/inf case, it becomes partially transparent and properly fades out as the sky goes to blue. The geometry still seems incorrect with respect to the width (it should presumably span the whole viewing area) but once it fades the skybox is more correct (though still not entirely so, if I spin around I can get it to show another texture over part of the sky).

UPDATE: Comparing to a nv2a-trace, the geometry position actually seems to be correct (it's just on the right side of the sky in HW as well), so there is more to figure out here. 

In xemu the entire mountain range behind the temple is also missing, though it sometimes blinks in depending on rotation.

**Comment by abaire** [comment]
[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/w_param_tests.cpp)
[HW result](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-W_param)

**Comment by abaire** [comment]
Investigating a bit more, I see that it is rendering what looks like the correct background, it just ends up behind some of the earlier draws. Given that this game uses the fixed pipeline and uses non-default z clip ranges, I believe this is failing due to #843.

**Comment by Triticum0** [comment]
@abaire Does the problem still occur? As I couldn't reproduce the issue

**Comment by mborgerson** [comment]
Looks correct on my machine, also with nvidia graphics.

![image](https://github.com/xemu-project/xemu/assets/8210/66ae759b-d3b3-42ef-acd3-9ed3a5bd4f61)
