### ISSUE TITLE
Serious Sam: Items are rendered through geometry that should occlude them

### ISSUE THREAD

**Issue by abaire** [xemu-project/xemu#802]
### Title

https://xemu.app/titles/54540004/#Serious-Sam

### Bug Description

On the first level it's possible to see items through walls (e.g., in the first screenshot a gun can be seen in the upper right of the screen through the column):

![Screenshot_20220318_213628](https://user-images.githubusercontent.com/448413/159107017-b206601d-5c61-44d5-beaa-f70c2f43c971.png)

These persist as the camera is moved:
![Screenshot_20220318_213730](https://user-images.githubusercontent.com/448413/159107026-88822459-21d6-4d5a-9180-81d72a00d355.png)

though getting very close can cause them to disappear (for me the gun stayed hidden until I opened and closed the menu)
![Screenshot_20220318_213818](https://user-images.githubusercontent.com/448413/159107045-6f803b76-0b64-4555-87bf-1b89040e5c62.png)

### Expected Behavior

Geometry should consistently occlude items behind it

### xemu Version

Version: 0.6.2-82-ghttps://github.com/mborgerson/xemu/commit/https://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837235387a296fc9a5f11943b4dd29bd2837235
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/2ff5f23235387a296fc9a5f11943b4dd29bd2837
Date: Sat Mar 19 03:47:53 AM UTC 2022

### System Information

"cpu": "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz",
"gl_renderer": "NVIDIA GeForce GTX 1070/PCIe/SSE2",
"gl_shading_la844c-cc0d466e4729.png)
nguage_version": "4.00 NVIDIA via Cg compiler",
"gl_vendor": "NVIDIA Corporation",
"gl_version": "4.0.0 NVIDIA 470.103.01",
"os_platform": "Linux",
"os_version": "Ubuntu 21.10",

**Comment by Triticum0** [comment]
Similar issue affects 
Chicago enforcer (gun)
