### ISSUE TITLE
Elder scrolls Morrowind: rendering covered by black screen

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#813]
### Title

https://xemu.app/titles/42530005/#The-Elder-Scrolls-III-Morrowind-Game-of-the-Year-Edition

### Bug Description

![elder](https://user-images.githubusercontent.com/30447649/159349420-7151058a-dbe5-448f-b0d0-7468ed7790cb.png)

### Expected Behavior

Rendering should not be covered.

### xemu Version

xemu_version: 0.6.2-88-g6e1969001e

**Comment by mborgerson** [comment]
The version of xemu in the screenshot does not match the version of xemu reported in the 'xemu Version' section. Moreover, [this issue was previously fixed](https://github.com/mborgerson/xemu/issues/469). Can you update to latest xemu and test again and report back.

**Comment by Fabxx** [comment]
Confirm that with the update the issue has been resolved, closing issue as this is invalid.
