### ISSUE TITLE
Virtua Cop 3: Heat wave effect not cleared properly

### ISSUE THREAD

**Issue by legend800** [xemu-project/xemu#815]
### Title

Virtua Cop 3 (not in compat. list)

### Bug Description

A heat wave effect from mid-boss fight is not cleared properly and screws up rest of level, making the screen blurry and waving around. 

![2022-03-14_22_59_49-xemu___v0 6 2-80-g5d02cdf512](https://user-images.githubusercontent.com/20983844/159197506-06c8b54d-756c-40e1-b18b-6d7623da2746.png)

### Expected Behavior

Effect cleared.

### xemu Version

0.6.2-80-g5d02cdf512

### System Information

Windows 10 64-bit
GeForce GTX 3070
AMD Ryzen 5900x
32GB RAM

**Comment by GXTX** [comment]
The effect is supposed to be there while you're in the city.

**Comment by legend800** [comment]
Ok, if you're sure, I can close it. It looks really undesired but I do believe it clears up when you go into the subway. I originally thought it didn't but it's probably because of the tanking fps due to this other issue: 
https://github.com/mborgerson/xemu/issues/816
