### ISSUE TITLE
Can not open HDD Image : "Read-only file system"

### ISSUE THREAD

**Issue by mjadev360** [xemu-project/xemu#820]
### Bug Description

- installed XEMU via flatpak
- I downloaded the HDD image, extracted it into a directory in my "Home" directory, checked the permissions.
- In the settings I selected the xbox_hdd.qcow2 file, and saved
- When I restart XEMU it instantly closes
- running XEMU from the command line I get the following error: 

> Could not open '/home/username/Games/xemu/hdd/xbox_hdd.qcow2': Read-only file system

### Expected Behavior

Nothing in the installation instructions says to do anything else with this hdd image, so I would expect XEMU to be able to open it without any issues

### xemu Version

0.6.2-88-g6e1969001e

### System Information

OS: Manjaro Linux
CPU: Ryzen 7 5800x
GPU: Radeon RX 6800

**Comment by antangelo** [comment]
See #748

**Comment by mjadev360** [comment]
crap, I also just noticed that part in the documentation after posting this.

thank you

**Comment by mjadev360** [comment]
I will say that it would be convenient if this information was also included in the "Required Files" section of the documentation.

It only appears in the "Installation" section which I glossed over because I installed from the software manager.
