### ISSUE TITLE
Obi-Wan Lighting issues

### ISSUE THREAD

**Issue by Deadliestbridge** [xemu-project/xemu#829]
### Title

https://xemu.app/titles/4156000f/#Star-Wars-Obi-Wan

### Bug Description

Lighting appears to flicker and not function properly in the two areas that are playable
![Screenshot (19)](https://user-images.githubusercontent.com/102270510/160215928-b1cb3291-8b20-490f-988e-300112badd91.png)
![Screenshot (20)](https://user-images.githubusercontent.com/102270510/160215935-9b33f48a-2dc4-4386-8c77-231e9a9d0fab.png)
![Screenshot (21)](https://user-images.githubusercontent.com/102270510/160215939-d15ebaa7-5711-4664-8763-7559c02956ba.png)
![Screenshot (22)](https://user-images.githubusercontent.com/102270510/160215945-a7f5cfb3-5df3-4561-b960-ea91bcdfc83a.png)
![Screenshot (28)](https://user-images.githubusercontent.com/102270510/160216294-3d0b97fb-7394-4212-a200-119ea0ea8fc1.png)
![Screenshot (29)](https://user-images.githubusercontent.com/102270510/160216300-f5add238-e5a8-48bb-8bc0-0a1431cd5646.png)
![Screenshot (30)](https://user-images.githubusercontent.com/102270510/160216303-3991d913-ed18-4c29-9007-07ec2e5489b3.png)

### Expected Behavior

![Screenshot (24)](https://user-images.githubusercontent.com/102270510/160216126-f37c8eac-271a-470a-bee3-125f27bea952.png)

### xemu Version

Version: 0.6.2-90-g6f507c80af

### System Information

OS: Win 10
CPU: Ryzen 3600
GPU: Nvidia 3080 12Gb 
GPU Driver: 512.15

### Additional Context

This game uses alot of reflection mapping so it could be the cause of this game's instability

**Comment by Deadliestbridge** [comment]
![xemu-2022-05-17-22-10-18](https://user-images.githubusercontent.com/102270510/168944178-9fe249e8-74e6-4087-a381-263314289ee3.png)
![xemu-2022-05-17-22-35-34](https://user-images.githubusercontent.com/102270510/168945460-f7f6a132-70f6-49e4-93e6-9f5984af707e.png)
![image](https://user-images.githubusercontent.com/102270510/168945599-9a36ae9a-58bb-4010-8af5-e76f2c03e3a4.png)
![image](https://user-images.githubusercontent.com/102270510/168946024-b2c95136-2142-434d-a99c-a580cead7051.png)
![xemu-2022-05-17-22-39-23](https://user-images.githubusercontent.com/102270510/168946134-1b68100d-5f16-4d47-8f3d-70b2ef0a6ded.png)
![xemu-2022-05-17-22-41-09](https://user-images.githubusercontent.com/102270510/168946144-8289a1f5-7af1-42fd-a0c7-7cdc8bc8c2bf.png)


the shadow issue is now localized to obi wan from the two playable levels that can be ran environments seem to be working as intended, to access the first level launch the tutorial first and then the first level can be played to completion, I also uploaded some screenshots of the current issue and HW for comparison

**Comment by abaire** [comment]
Shadow depth func is set to `GREATER`, depth format is `LU_IMAGE_DEPTH_Y16_FLOAT` (that already explains at least some of the problem: [I didn't implement float support so it's dividing things incorrectly](https://github.com/mborgerson/xemu/blob/7d6da227ba3b224647e35d2385419a3bec25a3b3/hw/xbox/nv2a/psh.c#L650)), and it's 3d projective.

**Comment by abaire** [comment]
Fixing the float comparison causes the shadow to be less corrupt looking, but still ends up as a big rectangle instead of the actual shadow. Looking in renderdoc, the depth map appears very unusual, the top half of it has 0 and 1 noise and the bottom half has what appears to be two copies of the character's shadow set to 0 surrounded by pixels set to `0.0078279`

Example (with the white point set low enough for what I assume is the actual shadow to be visible):
![bad_shadow_map](https://user-images.githubusercontent.com/448413/171256115-88072ccf-681a-49ad-a141-2b6c2aa7178f.png)


If I look at previous draws to the same texture, I see a valid looking depth map. This could just be a problem where the texture mode is being handled incorrectly by renderdoc.

**Comment by abaire** [comment]
Easy fix (on top of the float support in the shader), xemu was erroneously using `GL_FLOAT` instead of `GL_HALF_FLOAT`.

![Screenshot_20220531_112042](https://user-images.githubusercontent.com/448413/171257644-248c9c0a-9830-40b9-a7f0-55dd3ef5e560.png)
