### ISSUE TITLE
Robotech Battlecry no longer loads levels properly

### ISSUE THREAD

**Issue by BlazeModz** [xemu-project/xemu#830]
### Title

https://xemu.app/titles/544d0002/#Robotech-Battlecry

### Bug Description

Game has seemingly experienced a regression. Works fine (for the most part, has some bad framerate issues) on Xemu Version 0.5.4 and below, was playable at the very least, though. However, on every single new version past that, Battlecry always crashes when loading a level, completely unplayable now.

### Expected Behavior

When pressing "A" after a level finishes loading, a cutscene will start, then proceed into gameplay.

### xemu Version

0.6.2-73-gf3c7a3afd1

Last working in: 0.5.4-44-g3c1fcf6202

### System Information

OS: Windows 10
GPU: Nvidia 1050 Ti
CPU: Intel Core i7-6850k

### Additional Context

I'm not exactly sure what caused this regression, however it might have something to do with how the newer versions of Xemu handle the game itself, in terms of how it loads levels? Seems like a new feature, or something of that nature, has cause the game to fail, and crash whenever loading levels.

**Comment by antangelo** [comment]
Can you provide details about the crash? Is it an assertion failure? Does xemu just exit? Is there anything in the logs?

**Comment by BlazeModz** [comment]
> Can you provide details about the crash? Is it an assertion failure? Does xemu just exit? Is there anything in the logs?

Hello, yeah, it seems to be an assertion failure. You'll press A and hear the start of the level for about a second, then Xemu immediately closes. Here is what the log has to say about the crash: _ERROR:/xemu/tcg/i386/tcg-target.c.inc:2428:tcg_out_op: assertion failed: (0)_

**Comment by mborgerson** [comment]
> > Can you provide details about the crash? Is it an assertion failure? Does xemu just exit? Is there anything in the logs?
> 
> Hello, yeah, it seems to be an assertion failure. You'll press A and hear the start of the level for about a second, then Xemu immediately closes. Here is what the log has to say about the crash: _ERROR:/xemu/tcg/i386/tcg-target.c.inc:2428:tcg_out_op: assertion failed: (0)_

@BlazeModz Awesome, thanks for the report; I'll fix it. In the mean time, you can probably get in game by disabling hard_fpu in your xemu.ini file.

**Comment by BlazeModz** [comment]
> > > Can you provide details about the crash? Is it an assertion failure? Does xemu just exit? Is there anything in the logs?
> > 
> > 
> > Hello, yeah, it seems to be an assertion failure. You'll press A and hear the start of the level for about a second, then Xemu immediately closes. Here is what the log has to say about the crash: _ERROR:/xemu/tcg/i386/tcg-target.c.inc:2428:tcg_out_op: assertion failed: (0)_
> 
> @BlazeModz Awesome, thanks for the report; I'll fix it. In the mean time, you can probably get in game by disabling hard_fpu in your xemu.ini file.

Woah, That was so fast haha! Thanks so much, I'll try that out really quick ^^ although, I don't seem to have a xemu.ini file? Do I need to make one manually or..? Sorry haha I'm not sure how exactly this emulator works, entirely ^^;

**Comment by mborgerson** [comment]
It will be at C:/Users/YourName/AppData/Roaming/xemu/xemu/xemu.ini

**Comment by BlazeModz** [comment]
> It will be at C:/Users/YourName/AppData/Roaming/xemu/xemu/xemu.ini

OMG Thank you so much haha! Ack, I feel so stupid, I should have figured to at least search there once, I've even seen the folder there before haha!
Wow, that totally worked, I got in after disabling that! Thanks so much!! ♥

**Comment by mborgerson** [comment]
No problem! Thanks again for the bug report

**Comment by Triticum0** [comment]
Also affect [Nezmix](https://xemu.app/titles/4d530023/#Nezmix) #903 and scaler

**Comment by mborgerson** [comment]
Duplicate #1119
