### ISSUE TITLE
Splinter cell Double Agent: Shadows not being rendered on surfaces/objects

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#833]
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

the shadows are not being projected on surfaces/objects like in the screens:
![shadow xemu](https://user-images.githubusercontent.com/30447649/162236384-678aa18f-b8b5-45e0-981c-79fdad2befaf.png)
![shadow xemu 2](https://user-images.githubusercontent.com/30447649/162236389-faf939ed-9fb4-484c-82db-31a798f5f3d5.png)
![xemu shadow 3](https://user-images.githubusercontent.com/30447649/162236393-bcfba6a3-caed-4dfe-a604-053aa17c54dd.png)

Happens in all levels, the most noticable one is the JBA HQ part 1/2

### Expected Behavior

![hardware](https://user-images.githubusercontent.com/30447649/162236467-1affa0a7-556e-4158-9a86-ad8af7c97fa6.png)
![shadow3](https://user-images.githubusercontent.com/30447649/162236469-d06aa460-7999-4944-9d2d-c3a3e6f6a430.png)
![shadow hardware](https://user-images.githubusercontent.com/30447649/162236471-f5e4c39d-4f08-4ee3-9d69-1044440d676c.png)

### xemu Version

0.6.2-90-g6f507c80af

### System Information

Manjaro Linux
i7-10700 4.70GHz
GTX 970 STRIX
NVIDIA driver: 510.54
CUDA version: 11.6
RAM: DDR4 2933MHz HyperX Predator

**Comment by abaire** [comment]
Looking at a hardware trace for the steam pipe area on the first level, I can clearly see the fan shadow as a separate texture, so this may end up being the same texture application issue that I suspect causes #807. This should be re-tested whenever that bug is fixed.
