### ISSUE TITLE
Sphinx and the cursed mummy: dsp56k_read_memory: Assertion `address < DSP_YRAM_SIZE' failed

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#834]
### Title

https://xemu.app/titles/54510023/#Sphinx-and-the-Cursed-Mummy

### Bug Description

The game crashes on startup with the assertion error
happens on:
../hw/xbox/mcpx/dsp/dsp_cpu.c:1012

dsp emulation disabled in xemu.ini and surround disabled in EEPROM

### Expected Behavior

The game should be able to show intro videos, menu ecc.

### xemu Version

0.6.2-90-g6f507c80af

### System Information

manjaro linux
i7-10700 4.80Ghz
gtx 970 strix 4gb 
nvidia driver 510.16
cuda version 11.6
RAM ddr4 2933mhz hyperX predator

**Comment by Triticum0** [comment]
Added to #332 so you can close the issue
