### ISSUE TITLE
sonic riders corruption on display in cutscene

### ISSUE THREAD

**Issue by re4thewin** [xemu-project/xemu#836]
### Title

https://xemu.app/titles/53450087/#Sonic-Riders

### Bug Description

corruption on top and left edge of screen *shine on face and mustache also missing*

![](https://cdn.discordapp.com/attachments/680488810429153315/958185880558899210/unknown.png)

### Expected Behavior

no corruption *also shine on mustache and face present*
![192 168 1 139-image20](https://user-images.githubusercontent.com/32232919/162544567-3900578c-9f47-441e-913a-3e0946508307.png)

### xemu Version

0 6 2 90

### System Information

OS windows 10
CPU 9900KF 
GPU Nvidia 1070

**Comment by abaire** [comment]
Mind patching #735 to see if the problem goes away? If it does, can you close this as a duplicate of #725?

**Comment by abaire** [comment]
Also, the shine on the face should be reported separately; likely a specular lighting issue (there are a number of similar reports)

**Comment by re4thewin** [comment]
> Mind patching #735 to see if the problem goes away? If it does, can you close this as a duplicate of #725?

at 1x it does fix the eggman display *i forgot to check that part the other day oops* ill redo this for the specular only
