### ISSUE TITLE
Juiced: Game is now Broken, Does not start

### ISSUE THREAD

**Issue by Dabil** [xemu-project/xemu#841]
### Title

https://xemu.app/titles/545100ef/#Juiced

NTSC

### Bug Description

Assert Error on Game booting: hw/xbox/nv2a/pgraph.c Line 5992. Was previously playable, became broke starting on xemu 0.5.4-39-gedf3735718 on 07-20-21

### Expected Behavior

Game should boot and play.

### xemu Version

Problem started on xemu 0.5.4-39-gedf3735718 07-20-21. Previous to that the game was playable. 

### System Information

OS: Windows 10
CPU: AMD Ryzen 9 5950X
GPU: GTX 1070

### Additional Context

Will add a log later.

**Comment by Dabil** [comment]
Log: 

Created QEMU launch parameters: C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\xemu.exe -machine xbox,bootrom=C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\Xbox BIOS\mcpx_1.0.bin,kernel-irqchip=off -device smbus-storage,file=C:\Users\dbill\AppData\Roaming\xemu\xemu\eeprom.bin -bios C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\Xbox BIOS\Complex_4627v1.03.bin -m 64 -drive index=0,media=disk,file=C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\xbox_hdd.qcow2\xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=C:\ROMS\Microsoft Xbox\Juiced (USA,, Europe).iso -display xemu -audiodev none,id=snd0 -full-screen 
xemu_version: 0.6.5
xemu_branch: master
xemu_commit: a809d8557d48005f9e88145d398b87851b76e8fa
xemu_date: Sat Apr 30 05:06:34 UTC 2022
xemu_settings_get_path: config path: C:\Users\dbill\AppData\Roaming\xemu\xemu\xemu.toml
CPU: AMD Ryzen 9 5950X 16-Core Processor            
OS_Version: Windows
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 3070/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 512.15
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0

**Comment by abaire** [comment]
I believe this is a dup of #420, the assert that is failing was added just after 5.4-39
