### ISSUE TITLE
xemu failing to compile due to Meson

### ISSUE THREAD

**Issue by Shoegzer** [xemu-project/xemu#854]
### Bug Description

xemu is failing to compile due to an issue with Meson, throwing the following exception in the build log:

`../meson.build:2067:0: ERROR: File genconfig/gen_config.py does not exist.`

### Expected Behavior

xemu compiles.

### xemu Version

Issue observed with commit: 87919cfb13e401f381b5cfb7baff034aa02d39c0
Last known good commit: 440f4c53ec72c2148f770fd908ed41e991a16f2a

### System Information

OS: Linux Mint 20.3 / kernel 5.13
CPU: Intel i7-10870H
GPU: Nvidia GTX 3070 / driver 510.60
Compiler: gcc-11.1.0

### Additional Context

Meson log: [meson-log.txt](https://github.com/mborgerson/xemu/files/8556383/meson-log.txt)

**Comment by antangelo** [comment]
Update your submodules

**Comment by Shoegzer** [comment]
Thanks, I thought I had done that but I guess not.  May be helpful to add a `--submodules` flag to the git clone operation indicated [here](https://xemu.app/docs/building-from-source/#linux) but that's another issue.
