### ISSUE TITLE
Intel HAXM Acceleration broken

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#87]
Attempting to use HAXM with xemu produces odd results.

Retail dash will be a black screen, games are black screens, intro animation is very choppy, XDK dash partially displays.

Launched with: `.\xemu.exe -machine xbox,accel=hax`
Version: `2702f45` with `v7.6.5 HAXM`

![output-haxm-hacked](https://user-images.githubusercontent.com/858612/99893416-02bdda80-2c4e-11eb-926e-fa3a808b69a4.gif)

**Comment by mborgerson** [comment]
HAXM and other accelerators are not supported at this time
