### ISSUE TITLE
Outrun 2 - Missing screen filter 

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#870]
### Title

https://xemu.app/titles/53450036/#OutRun-2

### Bug Description

When playing this game there is a filter which covers the whole screen which is missing which causes loss of saturation to most of the image
Xemu:
![screen01](https://user-images.githubusercontent.com/71127352/165976456-a64ca5b1-4d2d-4620-a9c5-3c4e7d2a654a.jpg)

### Expected Behavior

Xbox:
![screen](https://user-images.githubusercontent.com/71127352/165976536-8f111179-4bf3-492c-b28d-c0b9b1495860.jpg)

### xemu Version

0.6.3-8-g30a872fa83

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

**Comment by MellowEdge** [comment]
I think the image you posted looks too saturated, maybe quirk of the capture hardware/software? Although I gotta agree that while UI looks alright, the actual game looks dull compared to Eurogamer screenshots for example
![image](https://user-images.githubusercontent.com/26963226/169033450-83eb321a-c27b-46f8-b085-4e54c31d01ea.png)
![image](https://user-images.githubusercontent.com/26963226/169033523-70591267-b386-49b2-b56b-95abbc1b2328.png)
![image](https://user-images.githubusercontent.com/26963226/169033408-25ec65f5-e856-4dff-a3bb-02bd0da765d3.png)

**Comment by Triticum0** [comment]
Thanks, those are good comparison screen shoots. This affects other games such as silent hill 2, but I Don't if it's a screen filter or some post-processing effect to Increase the saturation of the colours.

**Comment by Triticum0** [comment]
This issue been fixed
![xemu-2022-06-05-20-20-39](https://user-images.githubusercontent.com/71127352/172067088-bfffaf38-29ab-447d-89f5-b52f78cb9ae9.png)
