### ISSUE TITLE
Need for Speed: Most Wanted - Map doesn't render

### ISSUE THREAD

**Issue by Dabil** [xemu-project/xemu#876]
### Title

https://xemu.app/titles/4541007b/#Need-for-Speed-Most-Wanted
EA-123 [4541007b]

### Bug Description

Streets do not render on the Map on the radar or on the map view.

![Need for Speed Most Wanted No Map](https://user-images.githubusercontent.com/1447072/166121076-a90de4e5-9efc-4915-872f-549bae804bb2.jpg)

![Need for Speed Most Wanted No Map on radar](https://user-images.githubusercontent.com/1447072/166121078-74b51b50-7ab5-4dcd-ab97-d546cde4b636.jpg)

### Expected Behavior

Streets should be visible so that you can see the best routes to use. This is crucial during police chases. The map objects do render so at least you can get a general sense of which direction to go. 

### xemu Version

0.6.5 commit a809d8557d48005f9e88145d398b87851b76e8fa

### System Information

OS: Windows 10
CPU: AMD Ryzen 9 5950X 16-Core Processor
GPU: NVIDIA GeForce RTX 3070/PCIe/SSE2
GPU Driver: 4.0.0 NVIDIA 512.15

### Additional Context

Created QEMU launch parameters: C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\xemu.exe -machine xbox,bootrom=C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\Xbox BIOS\mcpx_1.0.bin,kernel-irqchip=off -device smbus-storage,file=C:\Users\dbill\AppData\Roaming\xemu\xemu\eeprom.bin -bios C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\Xbox BIOS\Complex_4627v1.03.bin -m 64 -drive index=0,media=disk,file=C:\Users\dbill\LaunchBox\Emulators\xemu-win-release\xbox_hdd.qcow2\xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=C:\ROMS\Microsoft Xbox\Need for Speed - Most Wanted (USA).iso -display xemu -audiodev none,id=snd0 
xemu_version: 0.6.5
xemu_branch: master
xemu_commit: a809d8557d48005f9e88145d398b87851b76e8fa
xemu_date: Sat Apr 30 05:06:34 UTC 2022
xemu_settings_get_path: config path: C:\Users\dbill\AppData\Roaming\xemu\xemu\xemu.toml
CPU: AMD Ryzen 9 5950X 16-Core Processor            
OS_Version: Windows
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 3070/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 512.15
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0

**Comment by abaire** [comment]
In renderdoc the source texture looks reasonable, but the format is `0x0E` which is `NV097_SET_TEXTURE_FORMAT_COLOR_L_DXT23_A8R8G8B8`. I don't think we have a test case for DXT23 yet and am initially suspicious that xemu may not properly support that compressed format.

Added some [basic tests](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_format_dxt_tests.cpp) and [HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_DXT), in the trivial case xemu seems to match hardware.


Pixel shader:
```
vec4 r0;
r0.a = t0.a;
// Stage 0
ab.rgb = clamp(vec3(((max(t0.rgb, 0.0) * max(v0.rgb, 0.0)) * 2.0)), -1.0, 1.0);
r0.rgb = ab.rgb;
ab.a = clamp(((max(t0.a, 0.0) * max(v0.a, 0.0))), -1.0, 1.0);
r0.a = ab.a;
// Stage 1
ab.rgb = clamp(vec3((max(r0.rgb, 0.0) * max(t1.aaa, 0.0))), -1.0, 1.0);
r0.rgb = ab.rgb;
ab.a = clamp(((max(r0.a, 0.0) * max(t1.a, 0.0))), -1.0, 1.0);
r0.a = ab.a;
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(r0.rgb, 0.0)), vec3(max(c0_8.rgb, 0.0)), vec3(max(pFog.aaa, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

It's using the fog value in the final color combine, so there's a good chance that is the issue.

UPDATE: Confirmed, if I override the fog alpha and set it to something other than 1, the map renders correctly.


The vertex shader fog params are both 1.0
