### ISSUE TITLE
Xbox disc not recognized on Linux

### ISSUE THREAD

**Issue by ccontino84** [xemu-project/xemu#88]
I have a couple of ISO files that I used to run with xqemu, but now they are not working with xemu. I have an up to date ArchLinux and have installed the binary deb package for Ubuntu using debtap.
No matter what I do, I always get the message "Please insert an Xbox disc..."
xemu log:

> $ xemu
xemu_settings_get_path: config path: /home/cloud/.local/share/xemu/xemu/xemu.ini
config_parse_callback: [system] flash_path = /mnt/blackhole/ROMs/xbox/xbox-4627_debug.bin
config_parse_callback: [system] bootrom_path = /mnt/blackhole/ROMs/xbox/mcpx_1.0.bin
config_parse_callback: [system] hdd_path = /mnt/blackhole/ROMs/xbox/xbox_hdd.qcow2
config_parse_callback: [system] eeprom_path = /home/cloud/.local/share/xemu/xemu/eeprom.bin
config_parse_callback: [system] dvd_path = /mnt/blackhole/ROMs/xbox/ISOs/Jet Set Radio Future.iso
config_parse_callback: [system] memory = 64
config_parse_callback: [system] shortanim = true
config_parse_callback: [display] scale = scale
config_parse_callback: [display] ui_scale = 1
config_parse_callback: [input] controller_1_guid = keyboard
config_parse_callback: [input] controller_2_guid = 
config_parse_callback: [input] controller_3_guid = 
config_parse_callback: [input] controller_4_guid = 
config_parse_callback: [network] enabled = false
config_parse_callback: [network] backend = user
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [misc] user_token = 
Created QEMU launch parameters: xemu -cpu pentium3 -machine xbox,bootrom=/mnt/blackhole/ROMs/xbox/mcpx_1.0.bin,short-animation,kernel-irqchip=off -device smbus-storage,file=/home/cloud/.local/share/xemu/xemu/eeprom.bin -bios /mnt/blackhole/ROMs/xbox/xbox-4627_debug.bin -m 64 -drive index=0,media=disk,file=/mnt/blackhole/ROMs/xbox/xbox_hdd.qcow2,locked -drive index=1,media=cdrom,file=/mnt/blackhole/ROMs/xbox/ISOs/Jet Set Radio Future.iso -display xemu 
dsp_init
dsp_init
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active

Command to run the same ISO in xqemu:

> xqemu -cpu pentium3 -machine xbox,bootrom=/mnt/blackhole/ROMs/xbox/mcpx_1.0.bin,short-animation -m 64 -bios /mnt/blackhole/ROMs/xbox/xbox-4627_debug.bin -drive index=0,media=disk,file=/mnt/blackhole/ROMs/xbox/xbox_hdd.qcow2,locked -drive index=1,media=cdrom,file="/mnt/blackhole/ROMs/xbox/ISOs/Jet Set Radio Future.iso" -usb -device usb-xbox-gamepad

Any idea?

**Comment by dracc** [comment]
Try removing whitespace from the XISO filename.

**Comment by Aerocatia** [comment]
Don't install binary packages meant for other distros like that, you will have better luck building it with the AUR script.

**Comment by Ernegien** [comment]
Xemu now generates a new blank factory EEPROM by default if you haven't specified one. You'll need to open it (/home/cloud/.local/share/xemu/xemu/eeprom.bin) with [this tool](https://github.com/Ernegien/XboxEepromEditor/releases/download/1.0.0.0/XboxEepromEditor.zip) using Mono/Wine and set your default language and time zone; usually this is handled by the original Xbox dashboard on startup.

**Comment by ccontino84** [comment]
Thanks a lot @Ernegien that was the only issue, now it works perfectly :)
I think that the part about the EEPROM is missing in the "Getting started" guide, isn't it?

**Comment by ccontino84** [comment]
Since you are there.. do you also know why the audio doesn't work?

**Comment by dekay** [comment]
Audio is still a work in progress and is not yet enabled.  Please be patient.
