### ISSUE TITLE
Fatal Frame: Black screen on main menu, missing effects in-game

### ISSUE THREAD

**Issue by GXTX** [xemu-project/xemu#880]
### Title

https://xemu.app/titles/54430004/#Fatal-Frame-Zero-Special-Edition

There's also FF2 which presents in a similar fashion.

### Bug Description

The main menu is a black screen, xmvs are also black. Game runs if you nav the menus. In-game we're missing some screen blur and other things. Entering the camera view all effects stop working and it's just a black box.

![mainmenu](https://user-images.githubusercontent.com/858612/166621187-73c4a35c-aa1c-4983-87f3-8099182f9248.png)
![ingame](https://user-images.githubusercontent.com/858612/166621193-248c2c51-2552-46ae-945b-99305c9756ee.png)
![missing](https://user-images.githubusercontent.com/858612/166621196-b047f3a4-ce21-438b-a083-19d24f2e1a2e.png)

### Expected Behavior

https://youtu.be/MFvtcdo3co0?t=155

### xemu Version

Version:      0.6.6
Branch:       master
Commit:       c2e0067538fa5d24e57effce1adca172db6e8117
Date:         Mon May  2 21:11:26 UTC 2022

### System Information

CPU:                Intel(R) Xeon(R) CPU E3-1290 V2 @ 3.70GHz
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Driver:       4.0.0 NVIDIA 511.79
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

Fatal Frame 2 has the same problem. Perhaps fixing one will fix the other. :)

**Comment by mborgerson** [comment]
Reported as fixed now

**Comment by GXTX** [comment]
There's a bug when scaling which stops you from being able to take pictures of ghosts, it also breaks fights. Would you like a 2nd issue?

1x
![1x](https://user-images.githubusercontent.com/858612/170114544-b5fbb8a0-8b6b-40dd-82aa-23993efe37f0.png)

2x
![2x](https://user-images.githubusercontent.com/858612/170114545-c6526cf6-2a71-43f1-a1c4-5ac8f4604caa.png)

**Comment by mborgerson** [comment]
Yeah let's make another issue for this. Thanks!
