### ISSUE TITLE
Forza Motorsport: Incorrect lighting in car selection screen

### ISSUE THREAD

**Issue by dracc** [xemu-project/xemu#886]
### Title

https://xemu.app/titles/4d53006e

### Bug Description

The cars in the car selection screen look far darker than their intended color.

In this screenshot, the car in the middle of the screen is supposed to be a vibrant red color with white stripes:
![image](https://user-images.githubusercontent.com/1279635/169667034-b7e1aae7-5f9b-4258-81ae-abe3e92be674.png)

### Expected Behavior

Colors/Lighting should work.
Same car, as captured in a video by John Godgames:
![image](https://user-images.githubusercontent.com/1279635/167012657-787ba8c5-799f-4652-bb60-560e941f7b67.png)

### xemu Version

v0.7.17

### System Information

```
CPU:          AMD Ryzen 7 1700 Eight-Core Processor          
OS Platform:  Linux
OS Version:   Debian GNU/Linux bookworm/sid
Manufacturer: AMD
GPU Model:    AMD Radeon R9 200 Series (hawaii, LLVM 14.0.3, DRM 3.44, 5.17.0-1-amd64)
Driver:       4.6 (Core Profile) Mesa 22.0.3
Shader:       4.60
```

**Comment by Fabxx** [comment]
Tested with https://github.com/mborgerson/xemu/pull/840 (other PRs won't produce this fix, tested them individually)

this seems to fix mostly the car, but still looks a bit dark in comparison

![image](https://user-images.githubusercontent.com/30447649/167021193-7cbaea69-c794-4579-b991-2f9fc40e1386.png)

**Comment by abaire** [comment]
Hey @dracc can you re-test now that #840 is merged? If the colors are still off can you update your screenshot & version info capturing the new behavior? 
Thanks!

**Comment by dracc** [comment]
> Hey @dracc can you re-test now that #840 is merged? If the colors are still off can you update your screenshot & version info capturing the new behavior? Thanks!

Done! :)

**Comment by dracc** [comment]
Cars look great in the selection screen now, closing. :)
