### ISSUE TITLE
MechAssault 2: Lone Wolf

### ISSUE THREAD

**Issue by Denis329149** [xemu-project/xemu#897]
### Feature Request

The game runs until press start.

**Comment by MasonT8198** [comment]
Perhaps some more detail please?

Is there an assertion in your log? What exactly do you mean by "The game runs until press start."

**Comment by Denis329149** [comment]
Can this game be fully playable? Thanks in advance.

**Comment by HadetTheUndying** [comment]
Can you verify the size in KB or your Mechassault 2 dump? Mine gets to the menus, I just freshly dumped it the other night. It does not get in game. Another user reporting no menus has a dump that is smaller than mine

**Comment by abaire** [comment]
@Denis329149  Please close this and file a title issue including all data from the title issue template. This issue is not at all useful and will not result in any progress towards fixing whatever is wrong with MechAssault 2.

**Comment by mborgerson** [comment]
Please always follow the issue templates, providing appropriate detail etc
