### ISSUE TITLE
"Invalid Boot ROM file...

### ISSUE THREAD

**Issue by VibingPenguin** [xemu-project/xemu#902]
### Bug Description

Maybe I'm stupid but I don't know what happened to xemu:

I've used the Complex_4627v1.03 file which is like 1000 kb big. Since one update on xemu I did a few days ago it's not possible to use that because it says that this file is too big and should be 512 kb big. Plkease excuse me for being stupid but I'm a noob on such topics.

thx for help I guess

### Expected Behavior

It should work with nthe file I have because it did a few days ago

### xemu Version

0.7.2

**Comment by mborgerson** [comment]
You've got the files mixed around. Boot ROM should 512 bytes.
