### ISSUE TITLE
Netmix (Sneakers) during loading xemu was terminated

### ISSUE THREAD

**Issue by IceLoveTizeR** [xemu-project/xemu#903]
### Title

https://xemu.app/titles/4d530023/#Nezmix

### Bug Description

Main menu launches so well, options and setting working in correctly, game does not load.

### Expected Behavior

At this moment of loading in frozen (2 sec) and xemu terminated:

![xemu-sneakers](https://user-images.githubusercontent.com/85007949/167302971-a63abf2a-4029-4ad2-b15b-ea80c5964531.png)

### xemu Version

0.7.2 | master | 722579bf01f9b164bb5b1abaac065d2c3023fdc7 | Sun May  8 06:05:26 UTC 2022

### Additional Context

Output:

```
ERROR:/xemu/tcg/i386/tcg-target.c.inc:2428:tcg_out_op: assertion failed: (0)
Bail out! ERROR:/xemu/tcg/i386/tcg-target.c.inc:2428:tcg_out_op: assertion failed: (0)
```

**Comment by Triticum0** [comment]
Disable hard Fpu in Xemu ini File As a workaround.
It is located In...   
C:/Users/YourName/AppData/Roaming/xemu/xemu/xemu.ini

**Comment by Triticum0** [comment]
Also, Nexmix is spelt wrong on the title.

**Comment by mborgerson** [comment]
Duplicate #1119
