### ISSUE TITLE
Game screen only in quarter of total window/screen

### ISSUE THREAD

**Issue by littlecubba** [xemu-project/xemu#905]
### **Game screen only in quarter of total window/screen**

This has happened once before on an earlier 5 build, game screen is only a quarter of total window/screen.
<img width="654" alt="Screenshot 2022-05-08 at 17 45 37" src="https://user-images.githubusercontent.com/32203594/167306992-7c5ed40b-da5e-445b-bc9f-c8e2c93bf2f5.png">

Using the new inbuilt screen grabber you get a full screen.
![xemu-2022-05-08-17-38-59](https://user-images.githubusercontent.com/32203594/167307784-c70c25fb-f392-4b56-947b-0e54e2ae025f.png)

### Expected Behavior

Game should be in full area of window/screen

### xemu Version

Version:      0.7.2
Branch:       master
Commit:       722579bf01f9b164bb5b1abaac065d2c3023fdc7
Date:         Sun May  8 06:07:01 UTC 2022

### System Information

CPU:          Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
OS Platform:  macOS
OS Version:   Version 12.3.1 (Build 21E258)
Manufacturer: Intel Inc.
GPU Model:    Intel(R) UHD Graphics 630
Driver:       4.1 INTEL-18.5.8
Shader:       4.10

**Comment by Triticum0** [comment]
Does Spy vs Spy work?

**Comment by Arkus** [comment]
I've run into the same issue. Also running on macOS.


### xemu Version

Version: 0.7.2
Branch: master
Commit: [722579b](https://github.com/mborgerson/xemu/commit/722579bf01f9b164bb5b1abaac065d2c3023fdc7)
Date: Sun May 8 06:07:01 UTC 2022

### System Information
CPU:          
OS Platform:  macOS
OS Version:   Version 12.3 (Build 21E230)
Manufacturer: Apple
GPU Model:    Apple M1 Max
Driver:       4.1 Metal - 76.3
Shader:       4.1

<img width="1392" alt="Screen Shot 2022-05-08 at 10 03 38 PM" src="https://user-images.githubusercontent.com/193032/167333907-8ff247d3-589e-47a0-8c86-3d12cec12353.png">

**Comment by littlecubba** [comment]
Spy vs Spy from title onwards (ie... menu, game) is all screwy.
But that's not the point.

This issue affects ALL of my games where the "game play area" is only being displayed in a quarter of the total viewable screen/window


Another example, Jet Set Radio we all know works beautifully, here's a grab of Xemu's full window
<img width="668" alt="Screenshot 2022-05-09 at 16 58 04" src="https://user-images.githubusercontent.com/32203594/167450795-94916598-8eac-41ef-9cec-8580764aafb0.png">


<img width="668" alt="Screenshot 2022-05-09 at 16 58 47" src="https://user-images.githubusercontent.com/32203594/167451910-73ff7ebb-dab7-4533-93f0-4ff88fa71a92.png">


Strange thing is, using Xemu's new built in screen grabber it grabs the image as a FULL screen.
![xemu-2022-05-09-16-59-41](https://user-images.githubusercontent.com/32203594/167452325-96c37570-8233-4199-9641-9fa7b049088c.png)
