### ISSUE TITLE
Phantom Dust: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

### ISSUE THREAD

**Issue by HadetTheUndying** [xemu-project/xemu#906]
### Title

https://xemu.app/titles/4d530046/#Phantom-Dust

### Bug Description

Game Freezes/Crashes while loading maps with this output while running a debug build and debugging with gdb:

```
xemu: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Thread 33 "xemu" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffeeebf6640 (LWP 16346)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

It is possible to get in game into the first area with Edgar, but it crashes upon loading the next room, after the Cutscene triggered from talking to Edgar a second time. Loading a Multiplayer game on any map also triggers this crash

### Expected Behavior

Able to load maps, play multiplayer etc.

### xemu Version

Version:      0.7.0-6-g3947814ab1
Branch:       master
Commit:       3947814ab1a314e301b6af10cdd824e72af68160
Date:         Mon May  9 01:10:20 AM UTC 2022

### System Information

CPU:          AMD Ryzen 7 2700X Eight-Core Processor         
OS Platform:  Linux
OS Version:   Void Linux
Manufacturer: AMD
GPU Model:    AMD Radeon RX Vega (VEGA10, DRM 3.44.0, 5.16.20_1, LLVM 12.0.1)
Driver:       4.6 (Core Profile) Mesa 21.3.7
Shader:       4.60

### Additional Context

This happens with any save games. Two different dumps of the game from two different xboxes and two different disks. So my original thought that it might be my dump is definitely not true.

**Comment by Triticum0** [comment]
Dupe of #375 please close

**Comment by HadetTheUndying** [comment]
Done
