### ISSUE TITLE
Gladius Lucas Arts

### ISSUE THREAD

**Issue by FJCFJC123** [xemu-project/xemu#917]
### Title

https://xemu.app/titles/4c410008/#Gladius 

LA-008 [4c410008]

### Bug Description

This issue is super minimal and has been current since i originally tested it back on version Version 0.6.0 but assumed it would be worth labeling as a bug. To keep it short when you pull the camera away from the gladiators in battle their face's will contort. Once you move the camera closer to them they will restore to a normal state so to speak, I did test on a real XBOX just to ensure it wasn't a view distance thing by default and the issue is only apparent on XEMU. Has no effect on gameplay just figured id note it, posted below are some screen captures showing the bug in different view distances.  

![xemu-2022-05-14-13-11-29-min](https://user-images.githubusercontent.com/86930879/168442401-556d0788-0050-4365-a92e-f1eea5aa8d4d.png)
![xemu-2022-05-14-13-11-32-min](https://user-images.githubusercontent.com/86930879/168442402-a0d418e5-df53-4ccb-b76e-e18759c55bc8.png)
![xemu-2022-05-14-13-11-36-min](https://user-images.githubusercontent.com/86930879/168442403-fac3acf5-5076-49b6-84b4-3e7e0a480ba6.png)

### Expected Behavior

Character faces should stay the same at any view distance

### xemu Version

Version 0.6.0 - Version 0.7.3

### System Information

OS: Windows 10
CPU: Intel Core I5 8600K
GPU: Nvidia GTX 1080
RAM; 32GB DDR4 3200MHZ

**Comment by FJCFJC123** [comment]
Forgot to note problem is consistent with or without internal upscaling enabled

**Comment by mborgerson** [comment]
Are you sure this doesn't happen on hardware? It's common to use more primitive models at further distances from the camera. Can we get a side-by-side comparison against hardware

**Comment by FJCFJC123** [comment]
Will do my best to get a capture on my OG Xbox just unsure how quality will be, dont have any form of a capture card, but i will post some comparisons today.

**Comment by FJCFJC123** [comment]
I was incorrect my original test on OG hardware was a different map due to where i was in the game at the time, it is in fact just a render distance thing. Apologies for the false bug report will close it out.
