### ISSUE TITLE
Splinter cell:  pgraph_surface_invalidate: assertion "surface != d->pgraph.zeta_binding" failed

### ISSUE THREAD

**Issue by Fabxx** [xemu-project/xemu#932]
### Title

https://xemu.app/titles/5553000c/#Tom-Clancy-s-Splinter-Cell

### Bug Description

The game crashes when you try to load the first part of level abbatoir
Steps to reproduce:
Create a profile with !LAMAUDITE! name, this will unlock all the levels
load this level here:
![image](https://user-images.githubusercontent.com/30447649/169168079-1de4a4bc-75d8-43c7-8a46-56bbd1e5da5f.png)

then it will crash.

### Expected Behavior

the game shouldn't crash with the assertion after the loading is complete

### xemu Version

0.7.13

### System Information

CPU:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
OS Platform:  Linux
OS Version:   Manjaro Linux
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.68.02
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

GDB stack trace:
[stack.txt](https://github.com/mborgerson/xemu/files/8721323/stack.txt)

**Comment by abaire** [comment]
Note, it only hits the assert after hitting "start" once loading of the level is completed.

The last few surface interactions:
```
nv2a: Target: [ ZETA @ 31b8000] (ln) aa:0 clip:x=0,w=1024,y=0,h=512
nv2a:  Match: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a:    Hit: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a: Target: [ ZETA @ 31b8000] (ln) aa:0 clip:x=0,w=1024,y=0,h=512
nv2a:  Match: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a:    Hit: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a: Target: [ ZETA @ 31b8000] (ln) aa:0 clip:x=0,w=1024,y=0,h=512
nv2a:  Match: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a:    Hit: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a: Target: [ ZETA @ 31b8000] (ln) aa:0 clip:x=0,w=1024,y=0,h=512
nv2a:  Match: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a:    Hit: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a: Target: [ ZETA @ 31b8000] (ln) aa:0 clip:x=0,w=1024,y=0,h=512
nv2a:  Match: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a:    Hit: [ ZETA @ 31b8000 (1024x512)] (ln) aa:0, clip:x=0,w=1024,y=0,h=512,p=4096
nv2a: Target: [COLOR @ 32b8000] (ln) aa:0 clip:x=0,w=512,y=0,h=512
nv2a: Evicting overlapping surface @ 31b8000 (1024x512)
nv2a: [GPU->RAM] ZETA (lin) surface @ 31b8000 (w=1024,h=512,p=4096,bpp=4)
qemu-system-i386: ../hw/xbox/nv2a/pgraph.c:5399: pgraph_surface_invalidate: Assertion `surface != d->pgraph.zeta_binding' failed.
Signal: SIGABRT (Aborted)
```

At a glance it appears to be a legitimate overlap, zeta @ 31b8000 + 0x200000 = 0x33B8000 which is higher than 0x32b8000

pgraph output (not examined yet):
[sc_overlap.txt](https://github.com/mborgerson/xemu/files/8721395/sc_overlap.txt)

**Comment by abaire** [comment]
This looks like the same underlying problem as #893. Relevant bits from the pgraph leading up to the crash:

```
NV097_SET_SURFACE_PITCH<0x20C> (0x8000800 {Color:2048, Zeta:2048})
NV097_SET_SURFACE_COLOR_OFFSET<0x210> (0x32B8000)
NV097_SET_SURFACE_ZETA_OFFSET<0x214> (0x0)
NV097_SET_SURFACE_CLIP_HORIZONTAL<0x200> (0x2000000 offset:0 size:512)
NV097_SET_SURFACE_CLIP_VERTICAL<0x204> (0x2000000 offset:0 size:512)
NV097_SET_DEPTH_TEST_ENABLE<0x30C> (NV097_SET_DEPTH_TEST_ENABLE_V_FALSE<0x0>)
NV097_SET_STENCIL_TEST_ENABLE<0x32C> (NV097_SET_STENCIL_TEST_ENABLE_V_FALSE<0x0>)
NV097_SET_SURFACE_FORMAT<0x208> (0x9090128 {LE_A8R8G8B8, Z24S8, Type:Pitch, AA:Center_1, Width:512, Height:512})
NV097_CLEAR_SURFACE<0x1D94> (0xF0)
nv2a: Target: [COLOR @ 32b8000] (ln) aa:0 clip:x=0,w=512,y=0,h=512
nv2a_pgraph_surface_created [0x032b8000, 0x033b8000)
nv2a: Evicting overlapping surface @ 31b8000 (1024x512)
nv2a: [GPU->RAM] ZETA (lin) surface @ 31b8000 (w=1024,h=512,p=4096,bpp=4)
nv2a_pgraph_surface_invalidated 0x031b8000
qemu-system-i386: ../hw/xbox/nv2a/pgraph.c:5399: pgraph_surface_invalidate: Assertion `surface != d->pgraph.zeta_binding' failed.
Signal: SIGABRT (Aborted)
```

So as in the Steel Battalion case, the zeta buffer has been set to null (I'm assuming that the DMA settings were not adjusted from the last zeta offset) and xemu erroneously asserts when evicting the stale value of the zeta buffer.
