### ISSUE TITLE
Sonic Heroes and Mortal Kombat Shaolin Monks do not create files saved in Xemu emulator storage.

### ISSUE THREAD

**Issue by vanderleivieirainacio** [xemu-project/xemu#945]
### Title

https://xemu.app/titles/5345002b/#Sonic-Heroes
https://xemu.app/titles/4d570029/

### Bug Description

Both Sonic Heroes and Mortal Kombat Shaolin Monks are unable to save data to the storage (virtual hard drive) of the Xemu emulator.

### Expected Behavior

Both games must create save data so that you don't have to start from the beginning every time, and can continue where you left off in those games.

### xemu Version

Xemu 0.7.17-66b57dca9c5c461c13cd44f977bd357677200be3

### System Information

OS:Windows 11
CPU: AMD Ryzen 7 1700
GPU: AMD Radeon RX 580 4GB
GPU Drive: AMD Software: Adrenalin Edition 22.5.1

**Comment by re4thewin** [comment]
You probably need to delete the corrupted save files off your drive image

**Comment by RinMaru** [comment]
Works fine here

**Comment by vanderleivieirainacio** [comment]
> Você provavelmente precisa excluir os arquivos salvos corrompidos da imagem da unidade

That's right, it really was saved corrupted. Thanks for informing.

**Comment by vanderleivieirainacio** [comment]
> Funciona bem aqui

Yes, delete the corrupt salvo and both worked. Thanks.
