### ISSUE TITLE
Phantasy Star Online Episode I & II: Stretched / Corrupted Textures

### ISSUE THREAD

**Issue by nolrinale** [xemu-project/xemu#953]
### Title

https://xemu.app/titles/4d53004a/#Phantasy-Star-Online-Episode-I-II

### Bug Description

In most areas the map textures appears corrupted or "stretched"

render scale is set to 1x in all attached screenshots

### Expected Behavior

The textures of the maps elements are displayed correctly and not "stretched"

### xemu Version

Version:      0.7.55
Branch:       master
Commit:       db389b15086753cb7b72e05b24af205baa742bc3
Date:         Sun Jun 26 06:03:08 UTC 2022

### System Information

CPU:          
OS Platform:  macOS
OS Version:   Version 12.4 (Build 21F79)
Manufacturer: Apple
GPU Model:    Apple M1
Driver:       4.1 Metal - 76.3
Shader:       4.10

### Additional Context

Stretched Skybox Textures (notice the clouds)
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/169716559-4a1e3344-3887-4be2-a69c-87c26abf3897.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/169716903-df4fd39f-c849-428d-b1d7-b7e6be9867c0.png">

<img width="1392" alt="Screenshot 2022-05-22 at 23 39 21" src="https://user-images.githubusercontent.com/5244595/169717690-1da890c8-80d7-49f5-ae3f-df62d391f312.png">

Wall Textures Stretched
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/169716624-b8b2dd77-cc20-496b-89fd-e80ca48a59fd.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/169717678-c4abb41b-9873-487e-b76f-d366e8d70fc2.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5244595/169718341-5bf3fbf2-cd6d-4cec-b1d3-cd20f18d8ba1.png">

In Multiplayer Mode Map (Stretched Skybox)
<img width="1392" alt="Screenshot 2022-06-27 at 11 22 33" src="https://user-images.githubusercontent.com/5244595/175909079-f50f78f7-4c77-4251-9d08-7a5cf58230b9.png">

**Comment by Triticum0** [comment]
@nolrinale This Issue been fixed please close the issue

**Comment by nolrinale** [comment]
As of today's build:

Version:      0.7.67
Branch:       master
Commit:       940bee452cc34127ecf3f364c3c5f52e4e6a80a4
Date:         Fri Aug  5 18:21:29 UTC 2022

This issue is fixed, I'm closing this ticket.
