### ISSUE TITLE
Star Wars: Jedi Starfighter - crashing on mission start

### ISSUE THREAD

**Issue by Azurfel** [xemu-project/xemu#954]
### Title

Star Wars: Jedi Starfighter - crashing on mission start due to failed assertion/unimplemented shadow map mode

### Bug Description

Game crashes upon mission load since 0.7.11 due to failed assertion/unimplemented shadow map mode

Created QEMU launch parameters: X:\Emulators\Xbox\Xemu regressiontester\xemu0.7.11.exe -machine xbox,bootrom=X:\Emulators\Xbox\Xemu\bios\mcpx_1.0.bin,kernel-irqchip=off,avpack=hdtv -device smbus-storage,file=C:\Users\XXX\AppData\Roaming\xemu\xemu\eeprom.bin -bios X:\Emulators\Xbox\Xemu\bios\xbox-4627_debug.bin -m 64 -drive index=0,media=disk,file=X:\Emulators\Xbox\Xemu\xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=L:\Xbox\swjsf.iso -display xemu -audiodev none,id=snd0 
xemu_version: 0.7.11
xemu_branch: master
xemu_commit: c33d96127cf3d4bcb0c72482ae875a9ccd0df62b
xemu_date: Wed May 18 00:48:10 UTC 2022
xemu_settings_get_path: config path: C:\Users\XXX\AppData\Roaming\xemu\xemu\xemu.toml
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
OS_Version: Windows
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce RTX 2080/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 452.06
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
audio: Device ac97: audiodev default parameter is deprecated, please specify audiodev=snd0
Shadow map support not implemented for mode 1
**
ERROR:../hw/xbox/nv2a/psh.c:579:get_sampler_type: assertion failed: (!"Shadow map support not implemented for this mode")
Bail out! ERROR:../hw/xbox/nv2a/psh.c:579:get_sampler_type: assertion failed: (!"Shadow map support not implemented for this mode")

### Expected Behavior

Mission loads successfully/assertion succeeds

### xemu Version

0.7.11+

### System Information

OS: Windows 10
CPU: CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
GPU: Nvidia GeForce RTX 2080
GL_VERSION: 4.0.0 NVIDIA 452.06

**Comment by mborgerson** [comment]
Consolidate to #958
