### ISSUE TITLE
Shadow map for PROJECT2D not implemented

### ISSUE THREAD

**Issue by mborgerson** [xemu-project/xemu#958]
### Title

https://xemu.app/titles/4d530005/#Amped-Freestyle-Snowboarding
https://xemu.app/titles/4c410005/#Star-Wars-Jedi-Starfighter

### Bug Description

Shadow mapping was recently introduced, but it is not complete yet, and some games using incomplete parts of this feature now assert, regressing from playable to not playable.

PROJECT2D should be an easy add, and prioritized to bring these games back to playable state.

### Expected Behavior

Implemented

### xemu Version

0.7.17

### System Information

N/A

**Comment by abaire** [comment]
Looking at amped (easier to see the shadow), it's using depth format 0x2E with a 2d rectangular texture. The texture mode is PROJECT2D but it still passes 4 component texture coordinates that have a plausibly valid z coordinate. May just need to treat this as exactly the same case as the PROJECT3D case.
