### ISSUE TITLE
Circus Maximus: Overshadowed Track

### ISSUE THREAD

**Issue by Kohryujin** [xemu-project/xemu#970]
### Title

Circus Maximus: Chariot Wars
EC-001 [45430001]
https://xemu.app/titles/45430001/#Circus-Maximus-Chariot-Wars

### Bug Description

The track appears overly shadowed at a distance, and becomes clear as you approach. 

### Expected Behavior

Going by videos of gameplay on actual hardware, the track should be properly visible without the extra shadow effect. 

### xemu Version

0.7.19

### System Information

<html>
<body>

Field | Value
-- | --
OS | Windows 10 Pro
CPU | AMD FX(tm)-8350 Eight-Core Processor
Graphics Device | Radeon RX 580
Graphics Driver | 4.0.14802 Core Profile Context 22.2.3 30.0.14029.5006

</body>
</html>

### Additional Context

https://user-images.githubusercontent.com/85906547/170162930-27457a4a-88ee-4dd2-a411-71b603979ac7.mp4

A video showing the effect in action.

**Comment by Triticum0** [comment]
@Kohryujin This has been fixed I just tested

**Comment by Kohryujin** [comment]
I will doublecheck when I can and update the compat if correct. A full playthrough for the perfect will take longer but that will be next if no major issues are left.

Edit: Yeah, looks like it's fixed. I'll have to schedule some time to check every track for the perfect, but it looks promising.
