### ISSUE TITLE
Non-latinic filepath

### ISSUE THREAD

**Issue by PaladinChalybs** [xemu-project/xemu#99]
Greetings. I've got a question.

Is there a way to add support for non-latinic (cyrillic namely) support in the file path? 

Or is there a workaround for it that doesn't involve adding the new user for Windows system, for example changing the eeprom.bin and setting file location to local folder instead of "C:\Users\%Username%/Appdata/Roaming/Xemu" to local folder (i.e. the Xemuw.exe folder)?

Currently xemu displays an error message of being unable to generate eeprom file. And when i've tried to use eeprom generated  on my workplace PC, placed in local xemu folder, when I press "save" - it crahes with the following message:

```
Assertion failed!
Program: D:\Games\xemu-win-release\xemuw.exe
File: ui/xemu-settings.c
Line: 383

Expression: fd != NULL
```

**Comment by dracc** [comment]
Adding utf-8 support is probably a pretty daunting task.
As for putting the configuration and EEPROM files in the same folder as the executable, https://github.com/dracc/xemu/commit/e0f4c867fd2abd1f3fcad541104542d639685f59 is one way to do it.

**Comment by PaladinChalybs** [comment]
I need to download the binaries and compile them by myself, correct?
What sort of software should I use?
(Sorry, never done anything like this before).

**Comment by dracc** [comment]
https://github.com/mborgerson/xemu/wiki#windows probably gives you enough information to get going. :)

**Comment by SilentHolmes** [comment]
> I need to download the binaries and compile them by myself, correct?
> What sort of software should I use?
> (Sorry, never done anything like this before).

I've got the same problem, just renamed my profile. That's a quite common issue in different spheres and I have to do that sooner or later.

**Comment by mborgerson** [comment]
Should be fixed. Let me know if it's still broken for you.
